{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_date_fiscal_DateKey\",\"dim_date_fiscal_MonthKey\",\"dim_date_fiscal_TTMKey\",\"dim_date_Holiday\",\"dim_snow_AssignmentGroup\",\"dim_gbs_mor_Goals\",\"dim_gbs_ProfitCenter\",\"SNow_MORMetrics (GBS_Metrics)\",\"ServiceNow_CatalogTask_Closed\",\"ServiceNow_IncidentPS_Resolved\",\"ServiceNow_TaskSLA_Ended\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.141.1558.0 (25.03)+75b5f06a991f8f8a8a4d6b6fcd0f66e1ec2d6fdc"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"CalcGroup\",\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "relationships": [
      {
        "name": "38e61474-9256-420a-b8af-b917163de6f4",
        "fromColumn": "DateID",
        "fromTable": "dim_date_fiscal_DateKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_85f61c1d-c101-4656-afa2-8b2ed3b11878"
      },
      {
        "name": "0a211ae5-32ad-4d51-bee1-6358fb55235f",
        "fromColumn": "DateID",
        "fromTable": "dim_date_fiscal_MonthKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_336abc93-57dc-46da-acaa-273f0a494a3a"
      },
      {
        "name": "ae769ad1-81d4-4e58-bbe0-51b8ee55cd03",
        "fromColumn": "DateID - Mmm",
        "fromTable": "dim_date_fiscal_MonthKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d7c77918-59e0-47ad-bc6e-76d5c4af2469"
      },
      {
        "name": "b1be2d67-588b-4b82-8b30-a2a33d486f49",
        "fromColumn": "DateID",
        "fromTable": "dim_date_fiscal_TTMKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_07d4074b-6db8-4afb-a27b-ef3a916e6b94"
      },
      {
        "name": "4fd538ef-949f-43d6-83d4-76550ae1739f",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "PeriodID",
        "fromTable": "dim_date_fiscal_MonthKey",
        "toColumn": "Period-ID",
        "toTable": "dim_gbs_mor_Goals"
      },
      {
        "name": "97a209d9-29b4-4ead-9b95-37131971c422",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "PeriodID",
        "fromTable": "dim_date_fiscal_DateKey",
        "toColumn": "PeriodID",
        "toTable": "dim_date_fiscal_MonthKey"
      },
      {
        "name": "90370a7b-ebc9-43f3-a6fb-f9fc49a8c69c",
        "fromColumn": "Holiday-Date",
        "fromTable": "dim_date_Holiday",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ea96c6d0-1e78-4218-9ae5-7a7b60ec3fbf"
      },
      {
        "name": "0578dbee-12fe-4ee2-a177-44694d973a85",
        "fromColumn": "ProfitCenter-ID",
        "fromTable": "dim_snow_AssignmentGroup",
        "toColumn": "ProfitCenter-Code",
        "toTable": "dim_gbs_ProfitCenter"
      },
      {
        "name": "bfbe23b7-7a80-41c3-bf97-211f8cdf5024",
        "fromColumn": "closed_at",
        "fromTable": "SNow_MORMetrics (GBS_Metrics)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7e85e738-c3ce-4f35-9f3c-90fe517b2269"
      },
      {
        "name": "23239339-9bb7-4cd9-bcd3-b1652f87a70b",
        "fromColumn": "sys_updated_on",
        "fromTable": "SNow_MORMetrics (GBS_Metrics)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2029faa6-6e12-4a5e-a44f-a3edddda7017"
      },
      {
        "name": "e7375050-13f5-4019-86e7-63d2b4726a24",
        "fromColumn": "loaded_date",
        "fromTable": "SNow_MORMetrics (GBS_Metrics)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a76c3aee-dc91-4a10-ad63-b57a83e59b30"
      },
      {
        "name": "1ff00602-2d7f-4c78-a1d6-d1ce61743a38",
        "fromColumn": "sys_created_on",
        "fromTable": "SNow_MORMetrics (GBS_Metrics)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_99dbaa64-4fec-438e-bd6b-8ae2b551d6b0"
      },
      {
        "name": "10424e78-6de7-4408-ad17-b580bee85634",
        "fromColumn": "sys_created_on - DATE",
        "fromTable": "SNow_MORMetrics (GBS_Metrics)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8105c884-ea8b-45e5-825e-8fedc9957f1a"
      },
      {
        "name": "2be92250-57a6-4bc4-ae33-1469700859ca",
        "fromColumn": "u_resolved_at",
        "fromTable": "SNow_MORMetrics (GBS_Metrics)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_583ceac0-cf2b-40b0-a4a2-16794b1274fe"
      },
      {
        "name": "5ac71257-8db8-1ff2-1f46-6fc05f1ab045",
        "fromColumn": "resolved_date",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "toColumn": "DateID",
        "toTable": "dim_date_fiscal_DateKey"
      },
      {
        "name": "c2ae597d-35bc-2fb7-14f8-86c346b2464b",
        "fromColumn": "closed_date",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "toColumn": "DateID",
        "toTable": "dim_date_fiscal_DateKey"
      },
      {
        "name": "a1e69c02-9f55-6e02-aba9-87083fbdcdc1",
        "fromColumn": "assignment_group",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "toColumn": "Assignment-Group",
        "toTable": "dim_snow_AssignmentGroup"
      },
      {
        "name": "f2bc1e89-486d-0038-fe2a-08bfaf1fe09b",
        "fromColumn": "assignment_group",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "toColumn": "Assignment-Group",
        "toTable": "dim_snow_AssignmentGroup"
      },
      {
        "name": "fb0dda62-29f4-9cee-a6f2-49936aa24e51",
        "fromColumn": "u_resolved_at - DATE",
        "fromTable": "SNow_MORMetrics (GBS_Metrics)",
        "toColumn": "DateID",
        "toTable": "dim_date_fiscal_DateKey"
      },
      {
        "name": "3b1eefb9-2fa0-9c26-213e-70ae287c76ba",
        "fromColumn": "assignment_group",
        "fromTable": "SNow_MORMetrics (GBS_Metrics)",
        "toColumn": "Assignment-Group",
        "toTable": "dim_snow_AssignmentGroup"
      },
      {
        "name": "1c4e5ce1-bc93-4224-8abb-359265754e05",
        "fromColumn": "work_start",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_402dca95-443e-40da-b75a-2a8ed29691c4"
      },
      {
        "name": "514f9e9c-4730-4d90-a864-7ab7af5f25ed",
        "fromColumn": "sys_updated_on",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_85354851-cc60-47ab-9e2e-103d7ab9325b"
      },
      {
        "name": "690d9c93-906e-40b3-ac4f-fd1281b94c20",
        "fromColumn": "sys_created_on",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_96e8bb0c-2634-4282-99c9-399968701ac8"
      },
      {
        "name": "6d262267-dde3-4072-9470-6547bb7046d2",
        "fromColumn": "closed_at",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ee5d4ae4-26d4-4760-9653-e56405084fd1"
      },
      {
        "name": "6ce63d28-dc19-4565-8604-4376953537e5",
        "fromColumn": "opened_at",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a80b2a60-5415-4437-abc9-ab2a8f9f7a8e"
      },
      {
        "name": "108e0f75-27a6-47e6-bc2b-bad05498db12",
        "fromColumn": "work_end",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5471fa6b-68dc-4d3e-963e-e54f0cb79ebc"
      },
      {
        "name": "4e00003d-54b4-480c-b1ed-ad4444ebd788",
        "fromColumn": "loaded_date",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4b1bd8a3-fd4c-424d-aff9-6dff80757ce3"
      },
      {
        "name": "cabd3116-067a-4df0-bf15-df040e83f988",
        "fromColumn": "opened_date",
        "fromTable": "ServiceNow_CatalogTask_Closed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c97d5bc8-6fd4-479b-acc6-54d377087482"
      },
      {
        "name": "c6bbee44-bc3a-4816-95ff-50a302ea3e67",
        "fromColumn": "work_start",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_24be776b-6100-496f-b233-6d6753e29e23"
      },
      {
        "name": "32df03c0-a78a-4139-8a93-42c9d1f6406f",
        "fromColumn": "sys_updated_on",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e9080415-8e4d-42e5-b538-5b9e4de47a75"
      },
      {
        "name": "01316265-b45a-41cd-9682-0d12592dfc3a",
        "fromColumn": "sys_created_on",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a08aaeb3-46aa-472b-acf6-6300499699d2"
      },
      {
        "name": "34fa2708-f808-4b8f-9250-76956ac5ff90",
        "fromColumn": "closed_at",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e194ffee-a7af-4866-9148-8658a61c784f"
      },
      {
        "name": "01b354c8-99f8-4fd0-9879-c8f46338536d",
        "fromColumn": "u_resolved_at",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e9bc2933-4a23-4ed4-8d43-55191bfdd1cd"
      },
      {
        "name": "af769244-2912-4a21-b538-5acb0bd37b4d",
        "fromColumn": "opened_at",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8ef3d604-35f0-4e7a-bb23-b1c244ca912c"
      },
      {
        "name": "b2a2f640-c947-4eee-a5a9-64b42b164300",
        "fromColumn": "work_end",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_11470753-ee0b-4b08-bedf-bb0744528636"
      },
      {
        "name": "3227e651-d2b4-4400-bd13-6049a779c0b1",
        "fromColumn": "loaded_date",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_17802431-26e1-4200-8372-8d1f03ec99e5"
      },
      {
        "name": "f6475805-2731-4068-a13d-e1fedfd4e879",
        "fromColumn": "opened_date",
        "fromTable": "ServiceNow_IncidentPS_Resolved",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7bcea297-3553-4e52-baef-555fccb78005"
      },
      {
        "name": "6e231ae1-7c6d-429a-95a5-b9ad582def77",
        "fromColumn": "sys_updated_on",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_96a8c92d-9228-4b41-bc35-565c9ec6d141"
      },
      {
        "name": "7b4e69fa-184b-4f0b-a416-bfc6e2a9e312",
        "fromColumn": "sys_created_on",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_04432eee-33a0-4736-bc17-50c2e9efafe3"
      },
      {
        "name": "8fb4a068-2b15-4005-b996-d5997e403ac5",
        "fromColumn": "original_breach_time",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_595d1031-8e5b-4cc9-b880-f1571dba9a92"
      },
      {
        "name": "09d6fe59-96a6-4418-9001-3c93f88c2c61",
        "fromColumn": "end_time",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1ff12552-f399-4f86-8b85-1a3731aa9b5f"
      },
      {
        "name": "1d7b687b-9477-4892-8e74-f70a41d4d184",
        "fromColumn": "start_time",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c7f48084-4f56-4408-ace7-47fc3f3cd920"
      },
      {
        "name": "f7494852-d000-4821-93e2-202157caf5e0",
        "fromColumn": "planned_end_time",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f62a5b83-858d-4848-8344-86676f7373f3"
      },
      {
        "name": "9799433b-df38-481f-bfed-213500cdcebf",
        "fromColumn": "start_date",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e9550141-3ad8-4e0a-9a87-9e8bf6e4ff5c"
      },
      {
        "name": "07c7c27e-dab3-4b9b-b5f6-d5e56251567e",
        "fromColumn": "loaded_date",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_47507799-2dd1-4692-a68d-6512e0d54d5d"
      },
      {
        "name": "418d8b3c-0c06-37eb-9575-4fec89621ace",
        "fromColumn": "end_date",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "toColumn": "DateID",
        "toTable": "dim_date_fiscal_DateKey"
      },
      {
        "name": "58767447-8afd-454f-25ff-70376e6b931e",
        "fromColumn": "task_assignment_group",
        "fromTable": "ServiceNow_TaskSLA_Ended",
        "toColumn": "Assignment-Group",
        "toTable": "dim_snow_AssignmentGroup"
      },
      {
        "name": "4e7ca926-ab1d-48d6-947e-29ef72dd6b45",
        "fromColumn": "Start of week",
        "fromTable": "dim_date_fiscal_MonthKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_24e0f6f7-8920-4fe8-a945-0db3b5d482ba"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_dca4052d-aff4-404f-874c-a1f4d0e63d60",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b9cbf0fe-e0c0-4bb8-895d-cefaf6e70b6e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "db879203-3de4-4ad5-ab30-5e56febccefe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5c707b52-fc4d-4ead-afa3-256439174284",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "60c70586-dc33-4a67-8e88-d867afd76452",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "87c486f0-ba38-445b-a22e-f76eac3dcbfb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1049da36-ba96-4705-9739-214fcd095d48",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "331f8aaa-26fe-4838-8655-2664d5f99396",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fa5d7f91-c94e-4faf-85b1-f822993deb91",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6aad10b9-8ef4-45c3-b658-e637511e977e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "17a3c838-b639-4c7d-a942-858ada4d1b3e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b03cf8a3-1d10-4f33-a2e0-635e4599b43d",
                "ordinal": 3
              }
            ],
            "lineageTag": "078f0a67-d305-4d64-819f-aa449cdce262"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "d0f6d403-e8ad-4cf5-a063-38427dba342a",
        "partitions": [
          {
            "name": "DateTableTemplate_dca4052d-aff4-404f-874c-a1f4d0e63d60",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": ".Measures",
        "calculationGroup": {},
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fa159de8-74ac-4579-b081-e3c0c50378e7",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "7942fe90-46a3-411e-bf53-8ac5477598f1",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4a13359a-294c-41ce-90aa-75afee8f7e30",
        "measures": [
          {
            "name": "Total Ticket Count (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "COUNTROWS( ServiceNow_IncidentPS_Resolved )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "58878ce6-18ee-4a82-a685-ecc2f4c10f4c"
          },
          {
            "name": "Working Days Elapsed (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _openedDate = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[opened_date] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[resolved_date] )",
              "",
              "RETURN",
              "    NETWORKDAYS( _openedDate, _resolvedDate, 1, dim_date_Holiday )"
            ],
            "formatString": "0",
            "lineageTag": "9239d5cd-a23d-41f7-bd2e-6919bb4e72aa"
          },
          {
            "name": "Failed SLA (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved, ",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] > ",
              "            CALCULATE(",
              "                MAX(dim_snow_AssignmentGroup[SLA-NetworkDays]),",
              "                FILTER(",
              "                    dim_snow_AssignmentGroup,",
              "                    dim_snow_AssignmentGroup[Assignment-Group] = ",
              "                    ServiceNow_IncidentPS_Resolved[assignment_group]",
              "                )",
              "            )",
              "        )",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "c46c257e-6244-415d-ab1c-4673b2f6452d"
          },
          {
            "name": "SLA Business Days",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures",
            "expression": "SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-BusinessDays] )",
            "lineageTag": "55eeed9a-05a5-4901-8d7d-0f8f7db84255"
          },
          {
            "name": "Passed SLA (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved, ",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] <= ",
              "            CALCULATE(",
              "                MAX(dim_snow_AssignmentGroup[SLA-NetworkDays]),",
              "                FILTER(",
              "                    dim_snow_AssignmentGroup,",
              "                    dim_snow_AssignmentGroup[Assignment-Group] = ",
              "                    ServiceNow_IncidentPS_Resolved[assignment_group]",
              "                )",
              "            )",
              "        )",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "529af6ec-2227-4803-b093-e42f8fbf27ac"
          },
          {
            "name": "SLA % (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "ROUNDDOWN( DIVIDE( [Passed SLA (ServiceNow_IncidentPS_Resolved)] , [Total Ticket Count (ServiceNow_IncidentPS_Resolved)] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "9a4fde66-6f11-4e90-a00b-4cd2035eb542"
          },
          {
            "name": "Status-Closed (SNow_MORMetrics)",
            "displayFolder": ".Counts by Status",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_QA_Metrics)', ",
              "        'SNow_MORMetrics (GBS_QA_Metrics)'[u_incident_state] == \"Closed\" ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "ebd0037a-9d6a-4e2a-b9da-864fcc8ad1b9"
          },
          {
            "name": "Status-New (SNow_MORMetrics)",
            "displayFolder": ".Counts by Status",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_QA_Metrics)', ",
              "        'SNow_MORMetrics (GBS_QA_Metrics)'[u_incident_state] == \"New\" ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "8d91f2f7-1abc-4707-94c3-980642b22d8f"
          },
          {
            "name": "Status-Active (SNow_MORMetrics)",
            "displayFolder": ".Counts by Status",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_QA_Metrics)', ",
              "        'SNow_MORMetrics (GBS_QA_Metrics)'[u_incident_state] == \"Active\" ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "6b37ba0d-7e24-4736-8b3d-5e923d1971bb"
          },
          {
            "name": "Status-Awaiting Email (SNow_MORMetrics)",
            "displayFolder": ".Counts by Status",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_QA_Metrics)', ",
              "        'SNow_MORMetrics (GBS_QA_Metrics)'[u_incident_state] == \"Awaiting Email\" ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "325a60ff-e15b-40f7-9ae3-d962fb9d9b9a"
          },
          {
            "name": "Status-Awaiting Fax (SNow_MORMetrics)",
            "displayFolder": ".Counts by Status",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_QA_Metrics)', ",
              "        'SNow_MORMetrics (GBS_QA_Metrics)'[u_incident_state] == \"Awaiting Fax\" ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "88de68d3-1325-4fcf-8708-ba2cef792421"
          },
          {
            "name": "Status-Awaiting User Info (SNow_MORMetrics)",
            "displayFolder": ".Counts by Status",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_QA_Metrics)', ",
              "        'SNow_MORMetrics (GBS_QA_Metrics)'[u_incident_state] == \"Awaiting User Info\" ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "32e00454-321b-4f74-80fc-7e010f9b7c36"
          },
          {
            "name": "Status-Resolved (SNow_MORMetrics)",
            "displayFolder": ".Counts by Status",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_QA_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_QA_Metrics)', ",
              "        'SNow_MORMetrics (GBS_QA_Metrics)'[u_incident_state] == \"Resolved\" ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "5134f4ae-b457-4adb-8a95-4538ea1f669f"
          },
          {
            "name": "Goal (Payroll)",
            "displayFolder": ".Goals",
            "expression": "VALUES( dim_gbs_mor_Goals[PR_Incident-Resolution] ) ",
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "2ca2b900-6fff-48e9-b8e4-89ff6ae30fa0"
          },
          {
            "name": "Fiscal Period",
            "displayFolder": ".Base Measures",
            "expression": "VALUES( dim_date_fiscal_MonthKey[Month FY-YY] ) ",
            "lineageTag": "88889f33-4ec4-410c-a821-a84e79bb0ba7"
          },
          {
            "name": "Goal (AP InvoiceMRPO)",
            "displayFolder": ".Goals",
            "expression": "VALUES( dim_gbs_mor_Goals[AP_Incident-Resolution-Invoice-Entry] ) ",
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "9e6c7b89-f3e4-4580-9a8a-8f3a0aaa88e0"
          },
          {
            "name": "Goal (AP Banking)",
            "displayFolder": ".Goals",
            "expression": "VALUES( dim_gbs_mor_Goals[AP_Incident-Resolution-Banking] )",
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "ce3755ea-6b9c-434a-bda3-4eb9acd673be"
          },
          {
            "name": "Goal (AP Vendor Control)",
            "displayFolder": ".Goals",
            "expression": "VALUES( dim_gbs_mor_Goals[AP_Incident-Resolution-Vendor-Control] )",
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "0fa32fa1-e487-4726-91c4-1ebb714fe629"
          },
          {
            "name": "Goal (AR)",
            "displayFolder": ".Goals",
            "expression": "VALUES( dim_gbs_mor_Goals[AR_Incident-Resolution] )",
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "0dc1cd11-6d05-4752-a2b0-77e4861900d5"
          },
          {
            "name": "SLA - Payroll_Operations - Font",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % Payroll_Operations (ServiceNow_IncidentPS_Resolved)] >= [Goal (Payroll)], \"#FFFFFF\",",
              "        [SLA % Payroll_Operations (ServiceNow_IncidentPS_Resolved)] < ( [Goal (Payroll)] * 0.9 ), \"#FFFFFF\", ",
              "        \"#000000\" ) "
            ],
            "lineageTag": "a7c8f64f-412b-4d0d-a68d-cdb7f1b8107d"
          },
          {
            "name": "SLA - Payroll_Operations - Background",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % Payroll_Operations (ServiceNow_IncidentPS_Resolved)] >= [Goal (Payroll)], \"#009900\",",
              "        [SLA % Payroll_Operations (ServiceNow_IncidentPS_Resolved)] < ( [Goal (Payroll)] * 0.9 ), \"#CC0000\", ",
              "        \"#FFFF00\" ) "
            ],
            "lineageTag": "e0b61ed0-1043-4069-a51b-aa16bcbff0ab"
          },
          {
            "name": "SLA - AP Banking - Font",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % (ServiceNow_IncidentPS_Resolved)] >= [Goal (AP Banking)], \"#FFFFFF\",",
              "        [SLA % (ServiceNow_IncidentPS_Resolved)] < ( [Goal (AP Banking)] * 0.9 ), \"#FFFFFF\", ",
              "        \"#000000\" ) "
            ],
            "lineageTag": "d77711bf-7535-4e7f-9a02-fc21db37dbb7"
          },
          {
            "name": "SLA - AP InvoiceMRPO - Font",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [AP_InvoiceMRPO SLA % (Incidents + Exceptions)] >= [Goal (AP InvoiceMRPO)], \"#FFFFFF\",",
              "        [AP_InvoiceMRPO SLA % (Incidents + Exceptions)] < ( [Goal (AP InvoiceMRPO)] * 0.9 ), \"#FFFFFF\", ",
              "        \"#000000\" ) "
            ],
            "lineageTag": "46ee3afa-ea75-48b3-b706-22b11ab71094"
          },
          {
            "name": "SLA - AP Vendor Control - Font",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % (ServiceNow_IncidentPS_Resolved)] >= [Goal (AP Vendor Control)], \"#FFFFFF\",",
              "        [SLA % (ServiceNow_IncidentPS_Resolved)] < ( [Goal (AP Vendor Control)] * 0.9 ), \"#FFFFFF\", ",
              "        \"#000000\" ) "
            ],
            "lineageTag": "b1dd668e-5490-491a-818d-54da3807b41b"
          },
          {
            "name": "SLA - AP Banking - Background",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % (ServiceNow_IncidentPS_Resolved)] >= [Goal (AP Banking)], \"#009900\",",
              "        [SLA % (ServiceNow_IncidentPS_Resolved)] < ( [Goal (AP Banking)] * 0.9 ), \"#CC0000\", ",
              "        \"#FFFF00\" ) "
            ],
            "lineageTag": "ca8c3052-eb2e-4a01-97ed-a9b11266e98f"
          },
          {
            "name": "SLA - AP InvoiceMRPO - Background",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [AP_InvoiceMRPO SLA % (Incidents + Exceptions)] >= [Goal (AP InvoiceMRPO)], \"#009900\",",
              "        [AP_InvoiceMRPO SLA % (Incidents + Exceptions)] < ( [Goal (AP InvoiceMRPO)] * 0.9 ), \"#CC0000\", ",
              "        \"#FFFF00\" ) "
            ],
            "lineageTag": "2edf9485-3448-4bee-b516-ae5d7e1668c7"
          },
          {
            "name": "SLA - AP Vendor Control - Background",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % (ServiceNow_IncidentPS_Resolved)] >= [Goal (AP Vendor Control)], \"#009900\",",
              "        [SLA % (ServiceNow_IncidentPS_Resolved)] < ( [Goal (AP Vendor Control)] * 0.9 ), \"#CC0000\", ",
              "        \"#FFFF00\" ) "
            ],
            "lineageTag": "25376e6c-a813-47c2-a9ed-781ca9dd9144"
          },
          {
            "name": "Goal (Payment Services)",
            "displayFolder": ".Goals",
            "expression": "VALUES( dim_gbs_mor_Goals[PS_Inbound-Email-Efficiency] ) ",
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "2147c5c1-6307-4c60-b2f0-f01a000f443c"
          },
          {
            "name": "Passed SLA (PS Email Efficiency) (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[opened_date] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[u_resolved_at] )",
              "",
              "VAR _emails = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[contact_type] )",
              "",
              "VAR _emailCount = ",
              "CALCULATE( ",
              "    COUNTROWS( ServiceNow_IncidentPS_Resolved) ,",
              "        ServiceNow_IncidentPS_Resolved[contact_type] = \"Email\")",
              "",
              "VAR _ticketCount = ",
              "    COUNTROWS(",
              "        FILTER( ServiceNow_IncidentPS_Resolved, ",
              "        ServiceNow_IncidentPS_Resolved[contact_type] = \"Phone\") )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ServiceNow_IncidentPS_Resolved ,",
              "        ServiceNow_IncidentPS_Resolved[contact_type] = \"Email\" &&",
              "        [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] <= [SLA Network Days] ) ) ",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "de084b35-7110-419f-b3c0-525f1da37b67"
          },
          {
            "name": "Total Ticket Count (PS Email Efficiency) (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "        COUNTROWS(",
              "         FILTER( ServiceNow_IncidentPS_Resolved, ",
              "         ServiceNow_IncidentPS_Resolved[contact_type] = \"Email\") )"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "a9395847-cae1-4efe-a223-2a07814765dc"
          },
          {
            "name": "Failed SLA - PS Email Efficiency (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[opened_date] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[u_resolved_at] )",
              "",
              "VAR _emails = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[contact_type] )",
              "",
              "VAR _emailCount = ",
              "CALCULATE( ",
              "    COUNTROWS( ServiceNow_IncidentPS_Resolved ) ,",
              "        ServiceNow_IncidentPS_Resolved[contact_type] = \"Email\"",
              "        )",
              "",
              "VAR _ticketCount = ",
              "    COUNTROWS(",
              "        FILTER( ServiceNow_IncidentPS_Resolved , ",
              "        ServiceNow_IncidentPS_Resolved[contact_type] = \"Phone\"",
              "        ) ",
              "    )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved ,",
              "            ServiceNow_IncidentPS_Resolved[contact_type] = \"Email\" &&",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] > [SLA Network Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "49e698d1-8f8c-4b27-817d-d04c5a04343b"
          },
          {
            "name": "SLA % (PS Email Efficiency) (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "ROUNDDOWN( DIVIDE( [Passed SLA (PS Email Efficiency) (ServiceNow_IncidentPS_Resolved)] , [Total Ticket Count (PS Email Efficiency) (ServiceNow_IncidentPS_Resolved)] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "f5661feb-fa67-446f-a6b7-317bd4783537"
          },
          {
            "name": "SLA - PS Emails - Background",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % (PS Email Efficiency) (ServiceNow_IncidentPS_Resolved)] >= [Goal (Payment Services)], \"#009900\",",
              "        [SLA % (PS Email Efficiency) (ServiceNow_IncidentPS_Resolved)] < ( [Goal (Payment Services)] * 0.9 ), \"#CC0000\", ",
              "        \"#FFFF00\" ) "
            ],
            "lineageTag": "969f3c32-7984-4298-a268-14087d750825"
          },
          {
            "name": "SLA - PS Emails - Font",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % (PS Email Efficiency) (ServiceNow_IncidentPS_Resolved)] >= [Goal (Payment Services)], \"#FFFFFF\",",
              "        [SLA % (PS Email Efficiency) (ServiceNow_IncidentPS_Resolved)] < ( [Goal (Payment Services)] * 0.9 ), \"#FFFFFF\", ",
              "        \"#000000\" ) "
            ],
            "lineageTag": "4edf25ee-fe10-4bbe-8555-3cf8d39b12a6"
          },
          {
            "name": "Critical - Total Ticket Count (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Ticket Count (ServiceNow_IncidentPS_Resolved)] , ",
              "        ServiceNow_IncidentPS_Resolved[priority] = \"1 - Critical\"",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "29cfe57a-7813-4c16-b2d7-f346d15a9e7f"
          },
          {
            "name": "Critical - SLA % (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "ROUNDDOWN( DIVIDE( [Critical - Passed SLA (Network Days) (ServiceNow_IncidentPS_Resolved)] , [Critical - Total Ticket Count (ServiceNow_IncidentPS_Resolved)] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "eddcd75f-1f7f-4dc9-b389-af6c9ec6536d"
          },
          {
            "name": "Low - Failed SLA (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved , ",
              "            ServiceNow_IncidentPS_Resolved[priority] = \"4 - Low\" ",
              "            && ",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] > [SLA Network Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "3bc10e82-f399-48a7-8eca-57d854bd19bb"
          },
          {
            "name": "Low - Passed SLA (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved , ",
              "            ServiceNow_IncidentPS_Resolved[priority] = \"4 - Low\" ",
              "            &&",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] <= [SLA Network Days] ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "434759ad-a0fc-40d7-a62a-09a0a5b1ded1"
          },
          {
            "name": "Low - Total Ticket Count (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "    COUNTROWS(",
              "        FILTER(",
              "        ServiceNow_IncidentPS_Resolved , ",
              "            ServiceNow_IncidentPS_Resolved[priority] = \"4 - Low\"",
              "    )    )"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "4644290e-9ffd-426c-8486-f4e2be9cc5d5"
          },
          {
            "name": "Low - SLA % (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "ROUNDDOWN( DIVIDE( [Low - Passed SLA (ServiceNow_IncidentPS_Resolved)] , [Low - Total Ticket Count (ServiceNow_IncidentPS_Resolved)] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "c195fce9-1e8d-4d41-903c-6865055a91d8"
          },
          {
            "name": "Passed SLA (SNow_MORMetrics) (SLA Business Days) (Measure)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_Metrics)', ",
              "        [Working Days Elapsed (SNow_MORMetrics)] <= [SLA Business Days] ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "f7733cb8-f856-472e-b0a9-26534ad259ee"
          },
          {
            "name": "Working Days Elapsed (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on - DATE] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at - DATE] )",
              "",
              "RETURN",
              "    NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )"
            ],
            "formatString": "0",
            "lineageTag": "c0b0888d-e720-4607-b569-7994dfec81c2"
          },
          {
            "name": "Total Ticket Count (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "COUNTROWS( 'SNow_MORMetrics (GBS_Metrics)' )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "5fb7c054-4575-40d7-8509-6000634f8f49"
          },
          {
            "name": "SLA % (SNow_MORMetrics) (SLA Business Days)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "[Passed SLA (SNow_MORMetrics) (SLA Business Days) (Measure)] / [Total Ticket Count (SNow_MORMetrics)]",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "65187f30-b95f-49aa-8657-4cf21d318125"
          },
          {
            "name": "Failed SLA (Business Days) (SNow_MORMetrics) (Measure)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)', ",
              "            [Working Days Elapsed (SNow_MORMetrics)] > [SLA Business Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "53a47bb8-703a-44ae-bf98-c313b68ec447"
          },
          {
            "name": "Days Elasped - Failed SLA (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _currentDate = SELECTEDVALUE( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR(_currentDate), MONTH(_currentDate) - 1, DAY(_currentDate) )",
              "",
              "VAR _submittedDate = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[opened_date] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[u_resolved_at] )",
              "",
              "VAR _submitted = DATE( YEAR(_submittedDate), MONTH(_submittedDate), DAY(_submittedDate) )",
              "",
              "VAR _resolved = DATE( YEAR(_resolvedDate), MONTH(_resolvedDate), DAY(_resolvedDate) )",
              "",
              "VAR _workingDays = NETWORKDAYS( _submittedDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _failed = ",
              "    CALCULATE( _workingDays, ",
              "        FILTER( dim_date_fiscal_DateKey, ",
              "        dim_date_fiscal_DateKey[DateID] == _currentDate ) ) ",
              "",
              "RETURN",
              "    _failed"
            ],
            "formatString": "0",
            "lineageTag": "ca98e32f-889f-48b5-b288-449c297bab51"
          },
          {
            "name": "Submitted Date (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "DATEVALUE( SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[opened_date] ) ) ",
            "formatString": "Short Date",
            "lineageTag": "39a0c277-aaa0-4a1f-9e27-235e026eb3d5"
          },
          {
            "name": "Resolved Date (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[resolved_date] )",
            "formatString": "Short Date",
            "lineageTag": "a151393a-ea08-4119-ba5f-8dc14308d08b"
          },
          {
            "name": "Assigned To (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[assigned_to] )",
            "lineageTag": "7ea38d99-2dcb-4359-a29f-898ba7ed840e"
          },
          {
            "name": "Category (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[u_category] )",
            "lineageTag": "78f8bcb6-1e93-47eb-ab89-9fc587268646"
          },
          {
            "name": "Subcategory (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": "SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[u_subcategory] )",
            "lineageTag": "d10b7bb7-71a4-4bf9-8b48-54727a14ce67"
          },
          {
            "name": "SLA % (PS Email Efficiency) (Business Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "[Passed SLA (PS Email Efficiency) (Business Days) (SNow_MORMetrics)] / [Total Ticket Count (PS Email Efficiency) (SNow_MORMetrics)]",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "3522ad95-84b4-427b-8053-747f927a211e"
          },
          {
            "name": "Passed SLA (PS Email Efficiency) (Business Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_Metrics)' ,",
              "        'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Email\" &&",
              "        [Working Days Elapsed (SNow_MORMetrics)] <= [SLA Business Days] ) ) ",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "588454e5-6250-4ce8-b64a-a28ad16f647e"
          },
          {
            "name": "Failed SLA - PS Email Efficiency (SLA Business Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _emails = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[contact_type] )",
              "",
              "VAR _emailCount = ",
              "CALCULATE( ",
              "    COUNTROWS( 'SNow_MORMetrics (GBS_Metrics)') ,",
              "        'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Email\"",
              "        )",
              "",
              "VAR _ticketCount = ",
              "    COUNTROWS(",
              "        FILTER( 'SNow_MORMetrics (GBS_Metrics)', ",
              "        'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Phone\"",
              "        ) ",
              "    )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)' ,",
              "            'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Email\" &&",
              "            [Working Days Elapsed (SNow_MORMetrics)] > [SLA Business Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "5f4a9803-226e-474a-a87c-c4404bc9abbb"
          },
          {
            "name": "Total Ticket Count (PS Email Efficiency) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "        COUNTROWS(",
              "         FILTER( 'SNow_MORMetrics (GBS_Metrics)', ",
              "         'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Email\") )"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "cb29ebb3-c563-4da2-8984-975e2ff93819"
          },
          {
            "name": "Assigned To (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[assigned_to] )",
            "lineageTag": "a7f242a4-71fd-48c8-a130-508fd4fa74c7"
          },
          {
            "name": "Category (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_category] )",
            "lineageTag": "f742490d-065b-4df0-b068-52b840ef700b"
          },
          {
            "name": "Critical - Failed SLA (Business Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)', ",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"1 - Critical\" ",
              "            && ",
              "            [Working Days Elapsed (SNow_MORMetrics)] > [SLA Business Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "c321c326-5e30-4cde-84e2-a0b4adf72efa"
          },
          {
            "name": "Critical - Passed SLA (Business Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)',",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"1 - Critical\" ",
              "            &&",
              "            [Working Days Elapsed (SNow_MORMetrics)] <= [SLA Business Days] ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "8846d59c-051a-4fff-aff0-78f45ee781a2"
          },
          {
            "name": "Critical - SLA % (Business Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "[Critical - Passed SLA (Business Days) (SNow_MORMetrics)] / [Critical - Total Ticket Count (SNow_MORMetrics)]",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "c8bf93e9-d3b3-42b1-b418-f53a41b41f7b"
          },
          {
            "name": "Critical - Total Ticket Count (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "    COUNTROWS(",
              "        FILTER(",
              "        'SNow_MORMetrics (GBS_Metrics)' , ",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"1 - Critical\"",
              "    )    )"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "9de3cda2-a00b-4025-9a7e-4b50b5cdb2eb"
          },
          {
            "name": "Low - Failed SLA (Business Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)', ",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"4 - Low\" ",
              "            && ",
              "            [Working Days Elapsed (SNow_MORMetrics)] > [SLA Business Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "85728f25-d953-4bba-8f7d-8bf1d796eb06"
          },
          {
            "name": "Low - Passed SLA (Business Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)',",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"4 - Low\" ",
              "            &&",
              "            [Working Days Elapsed (SNow_MORMetrics)] <= [SLA Business Days] ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "6790cfd8-d12c-4c37-9e6a-3dc76ff1afb7"
          },
          {
            "name": "Low - SLA % (Business Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "[Low - Passed SLA (Business Days) (SNow_MORMetrics)] / [Low - Total Ticket Count (SNow_MORMetrics)]",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "f867a9b5-c9a8-4577-9471-ac13917d0676"
          },
          {
            "name": "Low - Total Ticket Count (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "    COUNTROWS(",
              "        FILTER(",
              "        'SNow_MORMetrics (GBS_Metrics)' , ",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"4 - Low\"",
              "    )    )"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "21de84b0-4387-440e-a87c-3894cc69685e"
          },
          {
            "name": "Days Elasped -Failed SLA (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _currentDate = SELECTEDVALUE( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR(_currentDate), MONTH(_currentDate) - 1, DAY(_currentDate) )",
              "",
              "VAR _submittedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on - DATE] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at - DATE] )",
              "",
              "VAR _submitted = DATE( YEAR(_submittedDate), MONTH(_submittedDate), DAY(_submittedDate) )",
              "",
              "VAR _resolved = DATE( YEAR(_resolvedDate), MONTH(_resolvedDate), DAY(_resolvedDate) )",
              "",
              "VAR _workingDays = NETWORKDAYS( _submittedDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _failed = ",
              "    CALCULATE( _workingDays, ",
              "        FILTER( dim_date_fiscal_DateKey, ",
              "        dim_date_fiscal_DateKey[DateID] == _currentDate ) ) ",
              "",
              "RETURN",
              "    _failed"
            ],
            "formatString": "0",
            "lineageTag": "9ba364c1-21ff-49a4-a5a8-209db4bcc4a9"
          },
          {
            "name": "Resolved Date (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
            "formatString": "Short Date",
            "lineageTag": "b594464e-cc97-4f87-9b91-8a3c68a8ecd9"
          },
          {
            "name": "Subcategory (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_subcategory] )",
            "lineageTag": "cd9fbc0a-bfaf-4c40-a498-570db81df0a0"
          },
          {
            "name": "Submitted Date (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "DATEVALUE( SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] ) ) ",
            "formatString": "Short Date",
            "lineageTag": "231a2ea4-d792-45e4-bfa8-fed51d3cb483"
          },
          {
            "name": "SLA Network Days",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures",
            "expression": "SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
            "lineageTag": "9f5f1d2f-dee4-4a73-afd5-a77a8f65c255"
          },
          {
            "name": "Failed SLA (Network Days) (SNow_MORMetrics) (Measure)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)', ",
              "            [Working Days Elapsed (SNow_MORMetrics)] > [SLA Network Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "768796f5-d762-4d35-bee4-2457d2bdbfc4"
          },
          {
            "name": "Failed SLA - PS Email Efficiency (SLA Network Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on - DATE] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at - DATE] )",
              "",
              "VAR _emails = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[contact_type] )",
              "",
              "VAR _emailCount = ",
              "CALCULATE( ",
              "    COUNTROWS( 'SNow_MORMetrics (GBS_Metrics)') ,",
              "        'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Email\"",
              "        )",
              "",
              "VAR _ticketCount = ",
              "    COUNTROWS(",
              "        FILTER( 'SNow_MORMetrics (GBS_Metrics)', ",
              "        'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Phone\"",
              "        ) ",
              "    )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)' ,",
              "            'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Email\" &&",
              "            [Working Days Elapsed (SNow_MORMetrics)] > [SLA Network Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "00245bfc-12c5-486e-bfd2-03f6dc8ba01d"
          },
          {
            "name": "Passed SLA (SNow_MORMetrics) (SLA Network Days) (Measure)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)', ",
              "            [Working Days Elapsed (SNow_MORMetrics)] <= [SLA Network Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "645683c3-30d9-47ae-8a70-38539b969b35"
          },
          {
            "name": "SLA % (SNow_MORMetrics) (SLA Network Days)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "[Passed SLA (SNow_MORMetrics) (SLA Network Days) (Measure)] / [Total Ticket Count (SNow_MORMetrics)]",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "362f06d8-638c-4265-80f0-3e40e0d8d256"
          },
          {
            "name": "Critical - Failed SLA (Network Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)', ",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"1 - Critical\" ",
              "            && ",
              "            [Working Days Elapsed (SNow_MORMetrics)] > [SLA Network Days]",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "669837bd-3ae1-4bb7-b547-955cce664908"
          },
          {
            "name": "Critical - Passed SLA (Network Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)',",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"1 - Critical\" ",
              "            &&",
              "            [Working Days Elapsed (SNow_MORMetrics)] <= [SLA Network Days] ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "ab34ab2a-f741-4cc8-9844-13b9e34a25e5"
          },
          {
            "name": "Critical - SLA % (Network Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "[Critical - Passed SLA (Network Days) (SNow_MORMetrics)] / [Critical - Total Ticket Count (SNow_MORMetrics)]",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "a9ffd14b-8750-4d8d-b265-d0322ec8d70c"
          },
          {
            "name": "Low - Failed SLA (Network Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)', ",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"4 - Low\" ",
              "            && ",
              "            [Working Days Elapsed (SNow_MORMetrics)] > [SLA Network Days]",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "66cc1444-1c08-4f12-8fc8-b17c2d737c94"
          },
          {
            "name": "Low - Passed SLA (Network Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            'SNow_MORMetrics (GBS_Metrics)',",
              "            'SNow_MORMetrics (GBS_Metrics)'[priority] = \"4 - Low\" ",
              "            &&",
              "            [Working Days Elapsed (SNow_MORMetrics)] <= [SLA Network Days] ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "12f9f076-ada8-4de3-83a5-2391955ef5fb"
          },
          {
            "name": "Low - SLA % (Network Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "[Low - Passed SLA (Network Days) (SNow_MORMetrics)] / [Low - Total Ticket Count (SNow_MORMetrics)]",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "59634cb1-71c2-4981-a20d-c71173cce453"
          },
          {
            "name": "Passed SLA (PS Email Efficiency) (Network Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": [
              "",
              "",
              "VAR _createdDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[sys_created_on] )",
              "",
              "VAR _resolvedDate = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[u_resolved_at] )",
              "",
              "VAR _emails = SELECTEDVALUE( 'SNow_MORMetrics (GBS_Metrics)'[contact_type] )",
              "",
              "VAR _emailCount = ",
              "CALCULATE( ",
              "    COUNTROWS( 'SNow_MORMetrics (GBS_Metrics)') ,",
              "        'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Email\")",
              "",
              "VAR _ticketCount = ",
              "    COUNTROWS(",
              "        FILTER( 'SNow_MORMetrics (GBS_Metrics)', ",
              "        'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Phone\") )",
              "",
              "VAR _workingDays = NETWORKDAYS( _createdDate, _resolvedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( 'SNow_MORMetrics (GBS_Metrics)' ,",
              "        'SNow_MORMetrics (GBS_Metrics)'[contact_type] = \"Email\" &&",
              "        [Working Days Elapsed (SNow_MORMetrics)] <= [SLA Network Days] ) ) ",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "6b34b4d9-fe3a-4032-96c6-35c784254148"
          },
          {
            "name": "SLA % (PS Email Efficiency) (Network Days) (SNow_MORMetrics)",
            "displayFolder": "SNow_MORMetrics",
            "expression": "[Passed SLA (PS Email Efficiency) (Network Days) (SNow_MORMetrics)] / [Total Ticket Count (PS Email Efficiency) (SNow_MORMetrics)]",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "9ea43231-cfaa-42f5-96f3-5875f117ad71"
          },
          {
            "name": "Failed SLA (ServiceNow_CatalogTask_Closed)",
            "displayFolder": "ServiceNow_CatalogTask_Closed",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_CatalogTask_Closed , ",
              "            [Working Days Elapsed (ServiceNow_CatalogTask_Closed)] > [SLA Network Days] ",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "ade5e387-8744-492a-9234-51506d11cc86"
          },
          {
            "name": "Working Days Elapsed (ServiceNow_CatalogTask_Closed)",
            "displayFolder": "ServiceNow_CatalogTask_Closed",
            "expression": [
              "",
              "",
              "VAR _openedDate = SELECTEDVALUE( ServiceNow_CatalogTask_Closed[opened_date] )",
              "",
              "VAR _closedDate = SELECTEDVALUE( ServiceNow_CatalogTask_Closed[closed_date] )",
              "",
              "RETURN",
              "    NETWORKDAYS( _openedDate , _closedDate , 1, dim_date_Holiday )"
            ],
            "formatString": "0",
            "lineageTag": "f45981d0-325a-4cde-abe1-def76013e4de"
          },
          {
            "name": "Total Ticket Count (ServiceNow_CatalogTask_Closed)",
            "displayFolder": "ServiceNow_CatalogTask_Closed",
            "expression": "COUNTROWS( ServiceNow_CatalogTask_Closed )",
            "formatString": "0",
            "lineageTag": "65033941-0940-45a4-be10-9c4d594d3aa7"
          },
          {
            "name": "Passed SLA (ServiceNow_CatalogTask_Closed)",
            "displayFolder": "ServiceNow_CatalogTask_Closed",
            "expression": [
              "",
              "",
              "VAR _openedDate = SELECTEDVALUE( ServiceNow_CatalogTask_Closed[opened_date] )",
              "",
              "VAR _closedDate = SELECTEDVALUE( ServiceNow_CatalogTask_Closed[closed_date] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _openedDate , _closedDate, 1, dim_date_Holiday )",
              "",
              "VAR _slaNetworkdays = SELECTEDVALUE( dim_snow_AssignmentGroup[SLA-NetworkDays] )",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ServiceNow_CatalogTask_Closed , ",
              "        [Working Days Elapsed (ServiceNow_CatalogTask_Closed)] <= [SLA Network Days] ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "0ed2a7c2-d565-4ac4-82be-dee789ea6f7c"
          },
          {
            "name": "SLA % (ServiceNow_CatalogTask_Closed)",
            "displayFolder": "ServiceNow_CatalogTask_Closed",
            "expression": "ROUNDDOWN( DIVIDE( [Passed SLA (ServiceNow_CatalogTask_Closed)] , [Total Ticket Count (ServiceNow_CatalogTask_Closed)] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "51a460e3-4b62-4664-b5e9-55d92f79e12e"
          },
          {
            "name": "AP_InvoiceMRPO Total Ticket Count (Incidents+Exceptions)",
            "displayFolder": "AP_InvoiceMRPO",
            "expression": [
              "",
              "",
              "VAR _exceptions = CALCULATE( COUNTROWS( ServiceNow_CatalogTask_Closed ), ",
              "                    FILTER( ServiceNow_CatalogTask_Closed , ",
              "                    ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\"",
              "                    ) )  ",
              "",
              "VAR _incidentsResolved = COUNTROWS( ServiceNow_IncidentPS_Resolved )",
              "",
              "RETURN ",
              "_exceptions + _incidentsResolved"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "5b4ef420-e691-495c-b103-54f8e9191a9c"
          },
          {
            "name": "Distinct Total Ticket Count-TASK# (ServiceNow_CatalogTask_Closed)",
            "displayFolder": "ServiceNow_CatalogTask_Closed",
            "expression": "COUNTROWS( DISTINCT(ServiceNow_CatalogTask_Closed[number] ))",
            "formatString": "0",
            "lineageTag": "dfc4abec-9c56-493c-b61e-35ff2fd0d61b"
          },
          {
            "name": "Distinct Total Ticket Count-RITM# (ServiceNow_CatalogTask_Closed)",
            "displayFolder": "ServiceNow_CatalogTask_Closed",
            "expression": "COUNTROWS( DISTINCT(ServiceNow_CatalogTask_Closed[request_item] ))",
            "formatString": "0",
            "lineageTag": "7dc9514a-4aac-44d3-938c-4e5ca151f9d6"
          },
          {
            "name": "Distinct Total Ticket Count-REQ# (ServiceNow_CatalogTask_Closed)",
            "displayFolder": "ServiceNow_CatalogTask_Closed",
            "expression": "COUNTROWS( DISTINCT(ServiceNow_CatalogTask_Closed[request] ))",
            "formatString": "0",
            "lineageTag": "c26c8bfc-f4d0-4ea0-ab9e-50a9abbe046a"
          },
          {
            "name": "AP_InvoiceMRPO Passed SLA (Incidents + Exceptions)",
            "displayFolder": "AP_InvoiceMRPO",
            "expression": [
              "",
              "",
              "VAR _exceptionClosed = ",
              "    COUNTROWS( ",
              "        FILTER( ServiceNow_CatalogTask_Closed , ",
              "        ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\" &&",
              "        [Working Days Elapsed (ServiceNow_CatalogTask_Closed)] <= ",
              "        IF( ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\" , 10 , [SLA Network Days] )",
              "        ) ",
              "    ) ",
              "",
              "VAR _incidentResolved = ",
              "    COUNTROWS( ",
              "        FILTER( ServiceNow_IncidentPS_Resolved, ",
              "        [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] <= [SLA Network Days] ) ) ",
              "",
              "RETURN",
              "_exceptionClosed + _incidentResolved"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "e4ba2f15-5175-4973-a574-44ab3607c85d"
          },
          {
            "name": "AP_InvoiceMRPO SLA % (Incidents + Exceptions)",
            "displayFolder": "AP_InvoiceMRPO",
            "expression": "ROUNDDOWN( DIVIDE( [AP_InvoiceMRPO Passed SLA (Incidents + Exceptions)] , [AP_InvoiceMRPO Total Ticket Count (Incidents+Exceptions)] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "e8c11824-4a4f-45e4-9790-51c9a7370189"
          },
          {
            "name": "AP_InvoiceMRPO Failed SLA (Incidents + Exceptions)",
            "displayFolder": "AP_InvoiceMRPO",
            "expression": [
              "",
              "",
              "VAR _exceptionClosed = ",
              "    COUNTROWS( ",
              "        FILTER( ServiceNow_CatalogTask_Closed , ",
              "        ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\" &&",
              "        [Working Days Elapsed (ServiceNow_CatalogTask_Closed)] > ",
              "        IF( ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\" , 10 , [SLA Network Days] )",
              "        ) ",
              "    ) ",
              "",
              "VAR _incidentResolved = ",
              "    COUNTROWS( ",
              "        FILTER( ServiceNow_IncidentPS_Resolved, ",
              "        [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] > [SLA Network Days] ) ) ",
              "",
              "RETURN",
              "_exceptionClosed + _incidentResolved"
            ],
            "formatString": "0",
            "lineageTag": "2c863de5-296d-41f1-8e4b-04a14a9a1461"
          },
          {
            "name": "Critical - Failed SLA (Network Days) (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved , ",
              "            ServiceNow_IncidentPS_Resolved[priority] = \"1 - Critical\" ",
              "            && ",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] > [SLA Network Days]",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "7399f1b9-ae45-4aaa-889b-611f3142df7a"
          },
          {
            "name": "Critical - Passed SLA (Network Days) (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved ,",
              "            ServiceNow_IncidentPS_Resolved[priority] = \"1 - Critical\" ",
              "            &&",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] <= [SLA Network Days] ) ) ",
              "",
              "RETURN",
              "_result"
            ],
            "formatString": "0",
            "lineageTag": "99511708-b947-445f-a486-715ae9bf80c2"
          },
          {
            "name": "Payroll-Tax_Passed SLA (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "Payroll Tax",
            "expression": [
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved, ",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] <= ",
              "            CALCULATE(",
              "                MAX(dim_snow_AssignmentGroup[SLA-NetworkDays]),",
              "                FILTER(",
              "                    dim_snow_AssignmentGroup,",
              "                    dim_snow_AssignmentGroup[Assignment-Group] = ",
              "                    ServiceNow_IncidentPS_Resolved[assignment_group]",
              "                )",
              "            )",
              "        )",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "be8aff1f-792f-4e29-9e12-ad804a3ad65f"
          },
          {
            "name": "OTHERtoReturnBlank_Working Days Elapsed (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "ServiceNow_IncidentPS_Resolved",
            "expression": [
              "",
              "VAR _openedDate = SELECTEDVALUE(ServiceNow_IncidentPS_Resolved[opened_date])",
              "VAR _resolvedDate = SELECTEDVALUE(ServiceNow_IncidentPS_Resolved[resolved_date])",
              "RETURN",
              "    IF(",
              "        ISBLANK(_openedDate) || ISBLANK(_resolvedDate),",
              "        BLANK(),",
              "        NETWORKDAYS(_openedDate, _resolvedDate, 1, dim_date_Holiday)",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "fab15bc8-e208-438e-aa75-6a3031f80c00"
          },
          {
            "name": "Payroll-Tax_Failed SLA (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "Payroll Tax",
            "expression": [
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved, ",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] > ",
              "            CALCULATE(",
              "                MAX(dim_snow_AssignmentGroup[SLA-NetworkDays]),",
              "                FILTER(",
              "                    dim_snow_AssignmentGroup,",
              "                    dim_snow_AssignmentGroup[Assignment-Group] = ",
              "                    ServiceNow_IncidentPS_Resolved[assignment_group]",
              "                ) ",
              "            )",
              "        )",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "2ce7f57b-022f-43cc-b166-b1ca018baa5e"
          },
          {
            "name": "Payroll-Tax_SLA % (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "Payroll Tax",
            "expression": "ROUNDDOWN( DIVIDE( [Payroll-Tax_Passed SLA (ServiceNow_IncidentPS_Resolved)] , [Total Ticket Count (ServiceNow_IncidentPS_Resolved)] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "1549c717-5575-4759-82dd-1eaaefc1177c"
          },
          {
            "name": "Passed SLA Payroll_Operations (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "Payroll Operations",
            "expression": [
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved, ",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] <= ",
              "            CALCULATE(",
              "                IF(",
              "                    SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[assignment_group] ) = \"GBS Payroll Earnings\" &&",
              "                    SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[u_subcategory] ) = \"Retro Pay-greater than 50 employees\",",
              "                    16,",
              "                    IF( ",
              "                        SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[assignment_group] ) = \"GBS Payroll Earnings\" &&",
              "                        SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[u_subcategory] ) = \"Retro Pay-less than 50 employees\",",
              "                        11,",
              "                        IF( ",
              "                            SELECTEDVALUE(ServiceNow_IncidentPS_Resolved[assignment_group]) = \"GBS Payroll Earnings\" &&",
              "                            SELECTEDVALUE(ServiceNow_IncidentPS_Resolved[u_subcategory]) = \"overpayment\",",
              "                            11,",
              "                            MAX(dim_snow_AssignmentGroup[SLA-NetworkDays])",
              "                        )",
              "                    )",
              "                ),",
              "                FILTER(",
              "                    dim_snow_AssignmentGroup,",
              "                    dim_snow_AssignmentGroup[Assignment-Group] = ",
              "                    ServiceNow_IncidentPS_Resolved[assignment_group]",
              "                )",
              "            )",
              "        )",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "82ccb87a-0839-4401-8d83-b66bc8b2d6d4"
          },
          {
            "name": "Failed SLA Payroll_Operations (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "Payroll Operations",
            "expression": [
              "",
              "VAR _result = ",
              "    COUNTROWS( ",
              "        FILTER( ",
              "            ServiceNow_IncidentPS_Resolved, ",
              "            [Working Days Elapsed (ServiceNow_IncidentPS_Resolved)] > ",
              "            CALCULATE(",
              "                IF(",
              "                    SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[assignment_group] ) = \"GBS Payroll Earnings\" &&",
              "                    SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[u_subcategory] ) = \"Retro Pay-greater than 50 employees\",",
              "                    15,",
              "                    IF( ",
              "                        SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[assignment_group] ) = \"GBS Payroll Earnings\" &&",
              "                        SELECTEDVALUE( ServiceNow_IncidentPS_Resolved[u_subcategory] ) = \"Retro Pay-less than 50 employees\",",
              "                        10,",
              "                        IF( ",
              "                            SELECTEDVALUE(ServiceNow_IncidentPS_Resolved[assignment_group]) = \"GBS Payroll Earnings\" &&",
              "                            SELECTEDVALUE(ServiceNow_IncidentPS_Resolved[u_subcategory]) = \"overpayment\",",
              "                            10,",
              "                            MAX(dim_snow_AssignmentGroup[SLA-NetworkDays])",
              "                        )",
              "                    )",
              "                ),",
              "                FILTER(",
              "                    dim_snow_AssignmentGroup,",
              "                    dim_snow_AssignmentGroup[Assignment-Group] = ",
              "                    ServiceNow_IncidentPS_Resolved[assignment_group]",
              "                )",
              "            )",
              "        )",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "4e5d195d-b4bb-4861-a1ea-8d0787ea5db6"
          },
          {
            "name": "SLA % Payroll_Operations (ServiceNow_IncidentPS_Resolved)",
            "displayFolder": "Payroll Operations",
            "expression": "ROUNDDOWN( DIVIDE( [Passed SLA Payroll_Operations (ServiceNow_IncidentPS_Resolved)] , [Total Ticket Count (ServiceNow_IncidentPS_Resolved)] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "84105b4c-440d-471b-9852-1ae549ff3c94"
          },
          {
            "name": "Passed SLA (TaskSLA)",
            "displayFolder": "ServiceNow_TaskSLA_Ended",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    CALCULATE(",
              "         [Distinct Total Ticket Count (TaskSLA)] , ",
              "            ServiceNow_TaskSLA_Ended[has_breached] = \"false\" &&",
              "            ServiceNow_TaskSLA_Ended[task_type] = \"Incident - PS\" ||",
              "            ServiceNow_TaskSLA_Ended[has_breached] = \"false\" &&",
              "            ServiceNow_TaskSLA_Ended[task_type] = \"Catalog Task\"",
              "        )",
              "    ",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "3ce306d5-aa6b-4d83-b174-8f1ee431fbbc"
          },
          {
            "name": "Total Ticket Count (TaskSLA)",
            "displayFolder": "ServiceNow_TaskSLA_Ended",
            "expression": "COUNTROWS( ServiceNow_TaskSLA_Ended )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "387f5b56-918f-46cc-bc78-bec6a72aa61d"
          },
          {
            "name": "AP_InvoiceMRPO Total Ticket Count (Exceptions)",
            "displayFolder": "AP_InvoiceMRPO",
            "expression": [
              "",
              "",
              "VAR _exceptions = CALCULATE( COUNTROWS( ServiceNow_CatalogTask_Closed ), ",
              "                    FILTER( ServiceNow_CatalogTask_Closed , ",
              "                    ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\"",
              "                    ) )  ",
              "",
              "RETURN ",
              "_exceptions"
            ],
            "formatString": "0",
            "lineageTag": "a5110a9f-2c3c-4b29-b940-0750108819a3"
          },
          {
            "name": "AP_InvoiceMRPO Passed SLA (Exceptions)",
            "displayFolder": "AP_InvoiceMRPO",
            "expression": [
              "",
              "",
              "VAR _exceptionClosed = ",
              "    COUNTROWS( ",
              "        FILTER( ServiceNow_CatalogTask_Closed , ",
              "        ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\" &&",
              "        [Working Days Elapsed (ServiceNow_CatalogTask_Closed)] <= ",
              "        IF( ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\" , 10 , [SLA Network Days] )",
              "        ) ",
              "    ) ",
              "",
              "RETURN",
              "_exceptionClosed"
            ],
            "formatString": "0",
            "lineageTag": "7af4c1fa-68a9-456a-8a6c-a4a8856a07ac"
          },
          {
            "name": "AP_InvoiceMRPO Failed SLA (Exceptions)",
            "displayFolder": "AP_InvoiceMRPO",
            "expression": [
              "",
              "",
              "VAR _exceptionClosed = ",
              "    COUNTROWS( ",
              "        FILTER( ServiceNow_CatalogTask_Closed , ",
              "        ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\" &&",
              "        [Working Days Elapsed (ServiceNow_CatalogTask_Closed)] > ",
              "        IF( ServiceNow_CatalogTask_Closed[issue_type] = \"Exception Status\" , 10 , [SLA Network Days] )",
              "        )",
              "    )  ",
              "",
              "RETURN",
              "_exceptionClosed"
            ],
            "formatString": "0",
            "lineageTag": "49150ae2-7506-47f6-99aa-6f221222892c"
          },
          {
            "name": "AP_InvoiceMRPO SLA % (Exceptions)",
            "displayFolder": "AP_InvoiceMRPO",
            "expression": "ROUNDDOWN( DIVIDE( [AP_InvoiceMRPO Passed SLA (Exceptions)] , [AP_InvoiceMRPO Total Ticket Count (Exceptions)] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "521d3d66-6a9e-4aae-9e2d-58d022a175b3"
          },
          {
            "name": "SLA - Payroll_Tax - Background",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % Payroll_Operations (ServiceNow_IncidentPS_Resolved)] >= [Goal (Payroll)], \"#009900\",",
              "        [SLA % Payroll_Operations (ServiceNow_IncidentPS_Resolved)] < ( [Goal (Payroll)] * 0.9 ), \"#CC0000\", ",
              "        \"#FFFF00\" ) "
            ],
            "lineageTag": "bbb50f7d-7861-4abe-92cc-7577266d6dd2"
          },
          {
            "name": "SLA - Payroll_Tax - Font",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % Payroll_Operations (ServiceNow_IncidentPS_Resolved)] >= [Goal (Payroll)], \"#FFFFFF\",",
              "        [SLA % Payroll_Operations (ServiceNow_IncidentPS_Resolved)] < ( [Goal (Payroll)] * 0.9 ), \"#FFFFFF\", ",
              "        \"#000000\" ) "
            ],
            "lineageTag": "ceed97f7-e4d2-442c-ac99-78dfb75366bd"
          },
          {
            "name": "Distinct Total Ticket Count (TaskSLA)",
            "displayFolder": "ServiceNow_TaskSLA_Ended",
            "expression": "COUNTROWS( DISTINCT( ServiceNow_TaskSLA_Ended[task] ) )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "b34b4fc9-7b63-461d-af2c-668ab17b6b08"
          },
          {
            "name": "Failed SLA ALT (TaskSLA)",
            "displayFolder": "ServiceNow_TaskSLA_Ended",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "CALCULATE(",
              "    DISTINCTCOUNT(ServiceNow_TaskSLA_Ended[task]),",
              "    ServiceNow_TaskSLA_Ended[has_breached] = \"true\"",
              ")",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "4429809d-4891-4953-a0b9-c6befb8ec379"
          },
          {
            "name": "Passed SLA ALT (TaskSLA)",
            "displayFolder": "ServiceNow_TaskSLA_Ended",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "CALCULATE(",
              "    DISTINCTCOUNT( ServiceNow_TaskSLA_Ended[task] ) ",
              "    ,",
              "    FILTER(ServiceNow_TaskSLA_Ended ",
              "    , ",
              "    ServiceNow_TaskSLA_Ended[has_breached] = \"false\"",
              "    ) ",
              ") ",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "fa32bdc5-fe87-4ac6-8b42-6be36b1812c4"
          },
          {
            "name": "Distinct Total Ticket Count 2 (TaskSLA)",
            "displayFolder": "ServiceNow_TaskSLA_Ended",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "CALCULATE(",
              "    DISTINCTCOUNT(ServiceNow_TaskSLA_Ended[task])",
              ")",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "a61198be-293f-4446-b8a9-3a78c883425b"
          },
          {
            "name": "Failed SLA (TaskSLA)",
            "displayFolder": "ServiceNow_TaskSLA_Ended",
            "expression": [
              "",
              "",
              "VAR _result = ",
              "    CALCULATE(",
              "         [Distinct Total Ticket Count (TaskSLA)] , ",
              "            ServiceNow_TaskSLA_Ended[has_breached] = \"true\" &&",
              "            ServiceNow_TaskSLA_Ended[task_type] = \"Incident - PS\" ||",
              "            ServiceNow_TaskSLA_Ended[has_breached] = \"true\" &&",
              "            ServiceNow_TaskSLA_Ended[task_type] = \"Catalog Task\"",
              "        )",
              "    ",
              "",
              "RETURN",
              "    _result"
            ],
            "formatString": "0",
            "lineageTag": "dbc5dc6e-73c0-4c76-bc9f-efb5758031aa"
          },
          {
            "name": "Overlapping Tickets",
            "displayFolder": "Accounts Receivable",
            "expression": [
              "",
              "CALCULATE(",
              "    [Distinct Total Ticket Count (TaskSLA)],",
              "    ServiceNow_TaskSLA_Ended[has_breached] = \"false\" &&",
              "    (",
              "        ServiceNow_TaskSLA_Ended[task_type] = \"Incident - PS\" ||",
              "        ServiceNow_TaskSLA_Ended[task_type] = \"Catalog Task\"",
              "    ) &&",
              "    ServiceNow_TaskSLA_Ended[has_breached] = \"true\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b003b743-cf80-4e37-8c15-4a63a88f4e43"
          },
          {
            "name": "AR_TotalTicket_Count",
            "displayFolder": "Accounts Receivable",
            "expression": [
              "",
              "CALCULATE(",
              "        DISTINCTCOUNT( ServiceNow_TaskSLA_Ended[task] ),",
              "        FILTER(",
              "            ServiceNow_TaskSLA_Ended,",
              "            ServiceNow_TaskSLA_Ended[end_time] = ",
              "                CALCULATE(",
              "                    MAX(ServiceNow_TaskSLA_Ended[end_time]),",
              "                    ALLEXCEPT(ServiceNow_TaskSLA_Ended, ServiceNow_TaskSLA_Ended[task])",
              "                ) ",
              "        )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "1388b7fc-2476-486b-aadb-c14fd244e206"
          },
          {
            "name": "AR_PassedSLA_Count",
            "displayFolder": "Accounts Receivable",
            "expression": [
              "",
              "    CALCULATE(",
              "        DISTINCTCOUNT( ServiceNow_TaskSLA_Ended[task] ),",
              "        FILTER(",
              "            ServiceNow_TaskSLA_Ended,",
              "            ServiceNow_TaskSLA_Ended[end_time] = ",
              "                CALCULATE(",
              "                    MAX(ServiceNow_TaskSLA_Ended[end_time]),",
              "                    ALLEXCEPT(ServiceNow_TaskSLA_Ended, ServiceNow_TaskSLA_Ended[task])",
              "                ) &&",
              "            ServiceNow_TaskSLA_Ended[has_breached] == \"False\"",
              "        )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "372f9a8c-cf71-4a65-9bee-ac5c28a394e1"
          },
          {
            "name": "AR_FailedSLA_Count",
            "displayFolder": "Accounts Receivable",
            "expression": [
              "",
              "    CALCULATE(",
              "        DISTINCTCOUNT( ServiceNow_TaskSLA_Ended[task] ),",
              "        FILTER(",
              "            ServiceNow_TaskSLA_Ended,",
              "            ServiceNow_TaskSLA_Ended[end_time] = ",
              "                CALCULATE(",
              "                    MAX(ServiceNow_TaskSLA_Ended[end_time]),",
              "                    ALLEXCEPT(ServiceNow_TaskSLA_Ended, ServiceNow_TaskSLA_Ended[task])",
              "                ) &&",
              "            ServiceNow_TaskSLA_Ended[has_breached] == \"True\"",
              "        )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "02416b2f-8064-4556-8416-48539ec7a3a3"
          },
          {
            "name": "AR_SLA%",
            "displayFolder": "Accounts Receivable",
            "expression": "ROUNDDOWN( DIVIDE( [AR_PassedSLA_Count] , [AR_TotalTicket_Count] ) , 4 )",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "63552430-662d-4148-8295-5bf194cae087"
          },
          {
            "name": "SLA - Accounts Receivable - Background",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [AR_SLA%] >= [Goal (AR)], \"#009900\",",
              "        [AR_SLA%] < ( [Goal (AR)] * 0.9 ), \"#CC0000\", ",
              "        \"#FFFF00\" ) "
            ],
            "lineageTag": "97143a94-6360-45f6-b937-95c0fb353e13"
          },
          {
            "name": "SLA - Accounts Receivable - Font",
            "displayFolder": ".Conditional Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [AR_SLA%] >= [Goal (AR)], \"#FFFFFF\",",
              "        [AR_SLA%] < ( [Goal (AR)] * 0.9 ), \"#FFFFFF\", ",
              "        \"#000000\" ) "
            ],
            "lineageTag": "d102b15e-0727-409a-bb45-b7d4f376e6f6"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "dim_date_fiscal_DateKey",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DayIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "09f81d28-78b1-4bd4-bf8d-1d42a2e53fa7",
            "sourceColumn": "DayIndex",
            "summarizeBy": "sum"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f6146718-4bdf-41f9-874b-862c34261c0e",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_85f61c1d-c101-4656-afa2-8b2ed3b11878"
                },
                "isDefault": true,
                "relationship": "38e61474-9256-420a-b8af-b917163de6f4"
              }
            ]
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27aa782c-bd10-4e4b-8fe8-2142ba56da31",
            "sourceColumn": "Fiscal Period",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekInFM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f4aecb6-f017-4478-9e4b-5e3e4d76d2b0",
            "sourceColumn": "WeekInFM",
            "summarizeBy": "sum"
          },
          {
            "name": "FWeek_Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "55e6f43e-36b8-4019-9d55-843e2973bd2b",
            "sourceColumn": "FWeek_Index",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a693aa1-fd60-4346-92a5-cfe64ea664a8",
            "sourceColumn": "Fiscal-Year",
            "summarizeBy": "none"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3218cc33-731e-4fc3-b65a-8936a00f09f6",
            "sourceColumn": "FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal-Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61939cc3-eff8-45b8-8a4d-e953388fc011",
            "sourceColumn": "Fiscal-Period",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a2c8c85-4abe-4052-9686-cef2cbcd5422",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b098402e-684b-4b7e-aee7-0f880fe7d372",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "MMM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34a066d5-9fd3-4175-8960-94fde0904fde",
            "sourceColumn": "MMM",
            "summarizeBy": "none"
          },
          {
            "name": "MMM_FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "053f06bd-d150-45c1-9013-fe6de5336831",
            "sourceColumn": "MMM_FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e813c75c-fa76-4aa8-a218-e9a0f26389be",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "WeekDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "775174bc-78e9-48e1-a974-e090fde97e94",
            "sourceColumn": "WeekDay",
            "summarizeBy": "sum"
          },
          {
            "name": "Day name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9dc16051-249b-4da3-a089-428e96159c5a",
            "sourceColumn": "Day name",
            "summarizeBy": "none"
          },
          {
            "name": "IsWeekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3a314c00-b575-409a-b898-5ce7702bf5b5",
            "sourceColumn": "IsWeekend",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8c566ff8-7d66-441f-a997-34273850b481",
        "partitions": [
          {
            "name": "dim_date_fiscal_DateKey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_fiscal_DateKey_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_fiscal_DateKey\",version=\"\"]}[Data]",
                "in",
                "    dim_date_fiscal_DateKey_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_85f61c1d-c101-4656-afa2-8b2ed3b11878",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "77466c81-0551-4ab3-98e8-a9be01e5724a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "82ee2f36-ba34-4538-be48-94c8615538f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5dfee182-b6cc-47bd-bc00-5571414a679a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9c9e0358-ac68-4e31-95c2-9e9d9461ca9a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "59e7a2b8-26d5-453a-8d26-824ca49c9f3e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "56694622-b8b2-4d44-bcf1-23ab022f0bae",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f8ffa950-8211-4870-a3bd-d47859119214",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "510b32c1-e189-4f0d-982e-3b366a9bbadc",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d0092733-9997-4b56-8431-6981600b8535",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ab1b9270-70ea-4ef9-93a1-fc1b90180eb3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3c6c992c-be1d-42d7-b6e2-ce22eb448e32",
                "ordinal": 3
              }
            ],
            "lineageTag": "0ca99b6e-e462-4060-bc24-b91f7d76dde9"
          }
        ],
        "isHidden": true,
        "lineageTag": "995feb1a-b8ca-4f52-bc86-8f6bbc830441",
        "partitions": [
          {
            "name": "LocalDateTable_85f61c1d-c101-4656-afa2-8b2ed3b11878",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_DateKey'[DateID])), 1, 1), Date(Year(MAX('dim_date_fiscal_DateKey'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_date_fiscal_MonthKey",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c7b485b0-97f9-4918-ba0c-5fd5ce4b0a46",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_336abc93-57dc-46da-acaa-273f0a494a3a"
                },
                "isDefault": true,
                "relationship": "0a211ae5-32ad-4d51-bee1-6358fb55235f"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d565a291-ccfd-4225-919a-aac7c7c8aa21",
            "sortByColumn": "DateID",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a5bcb79-2dae-4557-ba90-42cade595eff",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29e7a347-fb0d-4c47-8b45-f961f16ad565",
            "sourceColumn": "Fiscal Period",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a75efdca-2e1a-4ebc-8d24-f29416950c9f",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad473a79-71ef-459f-826a-9f02df1e7dc5",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cd7b832-54e8-4f91-b0ef-efa06cac412b",
            "sourceColumn": "FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3837db52-a6f7-4529-b058-3735cccec021",
            "sortByColumn": "DateID",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "MMM_FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5044b06-e1d5-4907-94ba-129db02dc96e",
            "sortByColumn": "DateID",
            "sourceColumn": "MMM_FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50df5129-52c3-4455-ab8b-118c49250963",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month YYYY - Calendar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cee996ad-22e2-486e-877b-ba88cd2fd127",
            "sourceColumn": "Month YYYY - Calendar",
            "summarizeBy": "none"
          },
          {
            "name": "DateID - Mmm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Mmm",
            "lineageTag": "3f8f7424-bafe-454e-a9b1-367fbd54ed3b",
            "sourceColumn": "DateID - Mmm",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d7c77918-59e0-47ad-bc6e-76d5c4af2469"
                },
                "isDefault": true,
                "relationship": "ae769ad1-81d4-4e58-bbe0-51b8ee55cd03"
              }
            ]
          },
          {
            "name": "Calendar-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "502e29a0-542c-413a-be9f-f3a02a9a161f",
            "sourceColumn": "Calendar-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Start of week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "44295c97-6f5d-4300-965a-b391c53cef7d",
            "sourceColumn": "Start of week",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_24e0f6f7-8920-4fe8-a945-0db3b5d482ba"
                },
                "isDefault": true,
                "relationship": "4e7ca926-ab1d-48d6-947e-29ef72dd6b45"
              }
            ]
          }
        ],
        "lineageTag": "7ec0e8e7-a81a-455d-b52f-ac5347932ea2",
        "partitions": [
          {
            "name": "dim_date_fiscal_MonthKey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_fiscal_MonthKey_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_fiscal_MonthKey\",version=\"\"]}[Data]",
                "in",
                "    dim_date_fiscal_MonthKey_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_336abc93-57dc-46da-acaa-273f0a494a3a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d9045f6e-2be9-45ea-9947-91524fc8e32f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9c4967c1-ba46-47a8-976e-9a982d7e9653",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "26cd980f-5db9-43b0-9819-aaa8a4b69d3f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "451948fa-9af1-4b1c-a2da-86f2f1868c38",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0ddcef0a-933e-4bf5-9843-0bd7e2182a13",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5bc7dd1f-03db-4de3-a8fe-7f2d1868890b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "38044c0a-60c4-446d-9336-cf38345e2ed9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f46f0ac6-c1c4-472f-9a76-760c2699c34f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4111ca61-0d11-4c89-9849-024b32897b13",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fa778180-6808-4139-b439-1de1faa5dc5e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d88a1e92-e6a7-4c67-8423-81516372bdc9",
                "ordinal": 3
              }
            ],
            "lineageTag": "7cdfb764-6375-4494-9326-2808a4a88e7d"
          }
        ],
        "isHidden": true,
        "lineageTag": "6bb69474-c412-40f2-9185-dba58f29475b",
        "partitions": [
          {
            "name": "LocalDateTable_336abc93-57dc-46da-acaa-273f0a494a3a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_MonthKey'[DateID])), 1, 1), Date(Year(MAX('dim_date_fiscal_MonthKey'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d7c77918-59e0-47ad-bc6e-76d5c4af2469",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "86b9deb2-9d02-40d2-83ac-13d224b4b893",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d1e4c04a-05dc-4191-b821-00d50332642b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b4b32ce3-0c31-4acc-aaec-2ff44da374b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3e6994bf-b9c0-4056-94c6-bb5aef334f8d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8dd6e35b-eea3-4fb6-a167-627208193e35",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1b0b5564-ad25-42e1-9e61-3d62131b54eb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8735a346-51c6-4875-a3ca-b71a9094985e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f67934b3-e5fb-4c59-b13f-3b57b31b2065",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "045c11fb-31e6-4b19-93ee-fb613177cf28",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d2510868-6992-47a6-96e7-3a7d9014df0b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7885d56c-bc08-4c2a-b24a-a11b49ee6cb7",
                "ordinal": 3
              }
            ],
            "lineageTag": "daad184f-c3c3-4d0a-b536-c2d8f767222f"
          }
        ],
        "isHidden": true,
        "lineageTag": "2a1ef0d6-147b-4258-9014-770d9487af15",
        "partitions": [
          {
            "name": "LocalDateTable_d7c77918-59e0-47ad-bc6e-76d5c4af2469",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_MonthKey'[DateID - Mmm])), 1, 1), Date(Year(MAX('dim_date_fiscal_MonthKey'[DateID - Mmm])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_date_fiscal_TTMKey",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5c0cba55-7a29-4ae7-ad3a-7736ac2ef799",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_07d4074b-6db8-4afb-a27b-ef3a916e6b94"
                },
                "isDefault": true,
                "relationship": "b1be2d67-588b-4b82-8b30-a2a33d486f49"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87cd16f9-3bbd-417d-a701-372bd5beaa78",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a97ff5d-6c5f-4e96-802f-5a0030b2ac7e",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "08e96709-395e-41a0-bc31-c7ffd6772c4c",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ffe26467-c987-45c6-a15e-5eec4b9ce88c",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e567abb-530f-40e7-b59e-a1e0ceacbeee",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a49da269-0841-4a6d-bfb6-aecf949ae08f",
            "sourceColumn": "YY",
            "summarizeBy": "none"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a70d43dc-d007-4320-9e7e-cfc4681b740f",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92125efd-b666-4102-b17f-2152ad8ac217",
            "sourceColumn": "FY-YY",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f09306d5-6901-415b-b6c4-ac7f6f4bbfc4",
        "partitions": [
          {
            "name": "dim_date_fiscal_TTMKey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_fiscal_TTMKey_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_fiscal_TTMKey\",version=\"\"]}[Data]",
                "in",
                "    dim_date_fiscal_TTMKey_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_07d4074b-6db8-4afb-a27b-ef3a916e6b94",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ae10b04e-db8d-4c67-8d59-c66ed00703b4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5f60e2dc-5ed1-479f-9a45-32cd09db8e5c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6772a882-a5a5-4d68-9468-d577b2a88f27",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8d065ffd-b182-4788-9883-e1682f9b0951",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "af9ffe01-efae-474d-98f8-b6d68d177254",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "25adc1d8-c738-4bee-8c0c-54406759880d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "2b463de9-1c81-4611-8ee3-45e5b502bc80",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "dfb47835-0cc2-4bd4-934d-3bad02524107",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a16f5c1b-f04a-49ff-974b-fc4ae137d3e2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "49318173-0bf1-486f-aac7-193892c17d80",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b1b5082d-c811-47c1-955b-10015ad0b63a",
                "ordinal": 3
              }
            ],
            "lineageTag": "4d75ae74-1eec-47e9-be55-f02ec82af357"
          }
        ],
        "isHidden": true,
        "lineageTag": "7d01126c-308b-4e08-8154-56acf11b4e68",
        "partitions": [
          {
            "name": "LocalDateTable_07d4074b-6db8-4afb-a27b-ef3a916e6b94",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_TTMKey'[DateID])), 1, 1), Date(Year(MAX('dim_date_fiscal_TTMKey'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_snow_AssignmentGroup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a81165e-6509-4b14-9c01-e446ee94ede4",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Assignment-Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53c1b05c-f97d-4fca-8c4c-1839a18cd8b9",
            "sourceColumn": "Assignment-Group",
            "summarizeBy": "none"
          },
          {
            "name": "Functional-Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0a4cc9c-8d2b-4b1d-b161-ce91069797c1",
            "sourceColumn": "Functional-Area",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Function",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6909e012-3cc8-4aca-b325-3de5a2502cb4",
            "sourceColumn": "Sub-Function",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09270978-c63e-4044-8021-ef33e168d690",
            "sourceColumn": "ProfitCenter-ID",
            "summarizeBy": "none"
          },
          {
            "name": "SLA-BusinessDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4f295926-d2c7-4985-a474-8ef457d323e3",
            "sourceColumn": "SLA-BusinessDays",
            "summarizeBy": "sum"
          },
          {
            "name": "SLA-NetworkDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cde76201-7879-4642-ac79-e475b5f62a32",
            "sourceColumn": "SLA-NetworkDays",
            "summarizeBy": "sum"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a05a273-1ddf-4e41-b410-828437b9e6dc",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Function-Alt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5448f569-a110-4eae-99e8-c15da854583d",
            "sourceColumn": "Sub-Function-Alt",
            "summarizeBy": "none"
          },
          {
            "name": "Queue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fadb6749-fdd8-4358-9d77-ea1f27ef0a60",
            "sourceColumn": "Queue",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "66beda21-384a-4fb3-a6f7-3b2b979d8fc3",
        "partitions": [
          {
            "name": "dim_snow_AssignmentGroup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"2976903809263492\" = Source{[Key=\"2976903809263492\"]}[Data],",
                "    #\"3485167733657476\" = #\"2976903809263492\"{[Key=\"3485167733657476\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"3485167733657476\",{{\"ProfitCenter-ID\", type text}, {\"SLA-BusinessDays\", type number}, {\"SLA-NetworkDays\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_gbs_mor_Goals",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2512972-653d-45b9-ae21-3ef0ce3f2bf0",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Period-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "488363a9-267d-42cd-8eed-bff056cd9e26",
            "sourceColumn": "Period-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal-Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a195ea7c-093c-4fae-8389-4554ea482e6d",
            "sourceColumn": "Fiscal-Period",
            "summarizeBy": "none"
          },
          {
            "name": "AR_Incident-Resolution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "adae1884-5461-4daa-a4b3-1bef4b77309f",
            "sourceColumn": "AR_Incident-Resolution",
            "summarizeBy": "sum"
          },
          {
            "name": "AR_Unapplied-Cash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b32dfc64-8c11-4367-bb07-12fa06e1c71c",
            "sourceColumn": "AR_Unapplied-Cash",
            "summarizeBy": "none"
          },
          {
            "name": "AR_Cost-Per-Manual-Receipt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "013c2f49-5fdf-4a0a-8e8d-9908fda73ef8",
            "sourceColumn": "AR_Cost-Per-Manual-Receipt",
            "summarizeBy": "none"
          },
          {
            "name": "AR_Cost-Per-SNow-Request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9dd7b20c-e3ca-4bff-b77a-659f8e615dd7",
            "sourceColumn": "AR_Cost-Per-SNow-Request",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Debit-Pending-Items-US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b78755c-367d-4615-9723-00da2aa35c5c",
            "sourceColumn": "CB_Debit-Pending-Items-US",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Bank-Account-Reconciliation-US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bde99ad3-065d-4630-a7b6-99d78ac1d876",
            "sourceColumn": "CB_Bank-Account-Reconciliation-US",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Cost-Per-Manually-Reconcilied-Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0dbd56a5-2320-43c8-895a-68cc5f147651",
            "sourceColumn": "CB_Cost-Per-Manually-Reconcilied-Item",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Debit-Pending-Items-CAN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67449cab-1dde-4041-87c2-aef031cd27c5",
            "sourceColumn": "CB_Debit-Pending-Items-CAN",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Bank-Account-Reconciliation-CAN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e3f686a-92a4-4489-9505-19c13f6fd878",
            "sourceColumn": "CB_Bank-Account-Reconciliation-CAN",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CIP-Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a1d58d1-71cd-4fab-9b47-c485249a5cd5",
            "sourceColumn": "FA_CIP-Balance",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CIP-Balance-Stale",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43ae03dd-d28a-4ce0-bb85-8973c15a6804",
            "sourceColumn": "FA_CIP-Balance-Stale",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CERs-Closed-Timely",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77730545-548f-48e8-b329-765c9f2c356d",
            "sourceColumn": "FA_CERs-Closed-Timely",
            "summarizeBy": "none"
          },
          {
            "name": "FA_Cost-Per-Transaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a76fca32-fb51-4823-b390-74aa23ee23f1",
            "sourceColumn": "FA_Cost-Per-Transaction",
            "summarizeBy": "none"
          },
          {
            "name": "FA_Reconciliations-Prepared-And-Reviewed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c662297-abfe-4f78-bbf6-3f10c93b935b",
            "sourceColumn": "FA_Reconciliations-Prepared-And-Reviewed",
            "summarizeBy": "none"
          },
          {
            "name": "GL_Accurate-Journal-Entries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2213159f-062f-4818-b80d-67cb7a28eaa2",
            "sourceColumn": "GL_Accurate-Journal-Entries",
            "summarizeBy": "none"
          },
          {
            "name": "GL_Cost-Per-Manual-Journal-Entries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6836dd9-805e-467c-b637-b04a8dff2b07",
            "sourceColumn": "GL_Cost-Per-Manual-Journal-Entries",
            "summarizeBy": "none"
          },
          {
            "name": "GL_Reconciliations-Prepared-And-Reviewed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f17d278-37c3-4310-a5dd-42119b2ec41a",
            "sourceColumn": "GL_Reconciliations-Prepared-And-Reviewed",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Cost-Per-Invoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d7985a2-f3f1-41f3-b9e5-9cc0b6819a36",
            "sourceColumn": "AP_Cost-Per-Invoice",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Incident-Resolution-Invoice-Entry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "481a5c35-43c1-4dbf-b239-0d152c69f9ab",
            "sourceColumn": "AP_Incident-Resolution-Invoice-Entry",
            "summarizeBy": "sum"
          },
          {
            "name": "AP_Cost-Per-Payment-Processed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35c1154d-12a3-454e-b32c-ed1362826bba",
            "sourceColumn": "AP_Cost-Per-Payment-Processed",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Incident-Resolution-Banking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c553f72-21ac-4641-9944-3213f3fe4e10",
            "sourceColumn": "AP_Incident-Resolution-Banking",
            "summarizeBy": "sum"
          },
          {
            "name": "AP_Cost-Per-Vendor-Setup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f38cb6b4-7eea-448d-825c-bb15044150c6",
            "sourceColumn": "AP_Cost-Per-Vendor-Setup",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Incident-Resolution-Vendor-Control",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "74e84a6b-8c06-44ee-847e-ef5d6635a0f5",
            "sourceColumn": "AP_Incident-Resolution-Vendor-Control",
            "summarizeBy": "sum"
          },
          {
            "name": "AP_Audit-Recovery-Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e93e4b2d-6347-4974-903a-2bca387a1f94",
            "sourceColumn": "AP_Audit-Recovery-Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "AP_Audit-Recovery-Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e1e1e6f4-a872-4bd3-b810-3c5a893b9072",
            "sourceColumn": "AP_Audit-Recovery-Volume",
            "summarizeBy": "sum"
          },
          {
            "name": "PR_Cost-Per-Payment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b44c6dc9-27d0-44d4-8b48-774541813d2b",
            "sourceColumn": "PR_Cost-Per-Payment",
            "summarizeBy": "none"
          },
          {
            "name": "PR_eForm-Resolution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50a890e6-2438-4b02-840e-747dad0ffb13",
            "sourceColumn": "PR_eForm-Resolution",
            "summarizeBy": "none"
          },
          {
            "name": "PR_Incident-Resolution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0d18ccb0-3065-485d-966d-622cf2587f86",
            "sourceColumn": "PR_Incident-Resolution",
            "summarizeBy": "sum"
          },
          {
            "name": "CC_Customer-Satisfaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "393d7336-853c-4d33-9417-6846911464e7",
            "sourceColumn": "CC_Customer-Satisfaction",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Survey-Participation-Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04807c57-77ac-4672-add1-65d70327356f",
            "sourceColumn": "CC_Survey-Participation-Rate",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Average-Answer-Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3417c3a-d7fc-4722-b729-7c0e19cc0384",
            "sourceColumn": "CC_Average-Answer-Time",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Abandonment-Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc01f0c7-54b0-438a-8939-8a0cf71a4646",
            "sourceColumn": "CC_Abandonment-Rate",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Calls-Answered-Within-SLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd19005b-b78f-4af2-af7f-659343eef82b",
            "sourceColumn": "CC_Calls-Answered-Within-SLA",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Callbacks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "641a73a6-644b-467f-992b-9cb151f97299",
            "sourceColumn": "CC_Callbacks",
            "summarizeBy": "none"
          },
          {
            "name": "PS_Average-Answer-Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12ac2266-51cc-445f-9611-6a88dea164b6",
            "sourceColumn": "PS_Average-Answer-Time",
            "summarizeBy": "none"
          },
          {
            "name": "PS_Abandonment-Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf68227d-f196-40c2-99a8-eb80ab3dc405",
            "sourceColumn": "PS_Abandonment-Rate",
            "summarizeBy": "none"
          },
          {
            "name": "PS_Inbound-Email-Efficiency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb215d4f-3439-4f8b-8c06-8c641aec6dd1",
            "sourceColumn": "PS_Inbound-Email-Efficiency",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "127b1f71-59c3-4712-a012-5b54d8e6c95e",
        "partitions": [
          {
            "name": "dim_gbs_mor_Goals",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"2976903809263492\" = Source{[Key=\"2976903809263492\"]}[Data],",
                "    #\"8860436996771716\" = #\"2976903809263492\"{[Key=\"8860436996771716\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"8860436996771716\",{{\"Period-ID\", type text}, {\"AP_Incident-Resolution-Vendor-Control\", type number}, {\"AP_Audit-Recovery-Rate\", type number}, {\"AP_Audit-Recovery-Volume\", type number}, {\"PR_Incident-Resolution\", type number}, {\"AP_Incident-Resolution-Banking\", type number}, {\"AP_Incident-Resolution-Invoice-Entry\", type number}, {\"AR_Incident-Resolution\", type number}, {\"PS_Inbound-Email-Efficiency\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_date_Holiday",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Holiday-Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ffcc9b11-ef32-4677-93f7-9e0032ec9d38",
            "sourceColumn": "Holiday-Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ea96c6d0-1e78-4218-9ae5-7a7b60ec3fbf"
                },
                "isDefault": true,
                "relationship": "90370a7b-ebc9-43f3-a6fb-f9fc49a8c69c"
              }
            ]
          }
        ],
        "lineageTag": "d6573e35-20f9-4a70-861f-8a0bd8a063e7",
        "partitions": [
          {
            "name": "dim_date_Holiday",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_Holiday_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_Holiday\",version=\"\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dim_date_Holiday_,{\"RowNumber\", \"Holiday-Name\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ea96c6d0-1e78-4218-9ae5-7a7b60ec3fbf",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a6767f31-f7a9-44d1-a766-7692bdb9265b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "92cd246a-502a-4bf7-a585-f4a2628e7bb4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "fb82d771-3ebf-44e8-a78d-ec6931f0b071",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6c5422de-2911-4ea0-83b5-89c47dcca242",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2913b38e-731a-420f-9687-c60f84d77082",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c882ad32-4137-4e68-88a8-fcb6fe7ac867",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "723bd0af-8783-4777-8305-16d36f6e2c20",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3f5725a8-3431-416e-b0a8-9513f5fb63fd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "26c3dafd-350b-4b1f-b15d-6901273c81ef",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d4a105b8-3713-4240-b090-4b0fae2a93f5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3d7259c0-da89-461f-a17a-768fe1bbfd22",
                "ordinal": 3
              }
            ],
            "lineageTag": "71cf463d-fb7d-4779-b0c7-061237154ef6"
          }
        ],
        "isHidden": true,
        "lineageTag": "4b8540c4-f3ad-427b-a6da-caa3401d5af1",
        "partitions": [
          {
            "name": "LocalDateTable_ea96c6d0-1e78-4218-9ae5-7a7b60ec3fbf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_Holiday'[Holiday-Date])), 1, 1), Date(Year(MAX('dim_date_Holiday'[Holiday-Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_gbs_ProfitCenter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "135a18c3-1d4f-4420-9198-e73409f492f5",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter-Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98370e5f-731d-435b-b282-500cf324363e",
            "sourceColumn": "ProfitCenter-Code",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter -ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20528dd9-90b6-486f-bd04-68ea42286479",
            "sourceColumn": "ProfitCenter -ID",
            "summarizeBy": "none"
          },
          {
            "name": "Department-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7e6ae0a-4258-4560-aaed-ba4568f997a5",
            "sourceColumn": "Department-Name",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db447db2-978d-4bfb-9487-797e2ce746f3",
            "sourceColumn": "ProfitCenter-Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55cc8b75-3311-4090-92a2-d8b2223f8233",
        "partitions": [
          {
            "name": "dim_gbs_ProfitCenter",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"2976903809263492\" = Source{[Key=\"2976903809263492\"]}[Data],",
                "    #\"7899457811074948\" = #\"2976903809263492\"{[Key=\"7899457811074948\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"7899457811074948\",{{\"ProfitCenter-Code\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SNow_MORMetrics (GBS_Metrics)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "closed_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f6ef22e7-af35-4fa2-8704-7b2734800b29",
            "sourceColumn": "closed_at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7e85e738-c3ce-4f35-9f3c-90fe517b2269"
                },
                "isDefault": true,
                "relationship": "bfbe23b7-7a80-41c3-bf97-211f8cdf5024"
              }
            ]
          },
          {
            "name": "assignment_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41f9bdec-d932-4e4e-a3fc-f94cad072a06",
            "sourceColumn": "assignment_group",
            "summarizeBy": "none"
          },
          {
            "name": "u_subcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25b37112-daca-47ab-add6-d6dbc574b8f2",
            "sourceColumn": "u_subcategory",
            "summarizeBy": "none"
          },
          {
            "name": "u_incident_state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ff2a33b-708e-49ef-b2dc-dbdd89d57811",
            "sourceColumn": "u_incident_state",
            "summarizeBy": "none"
          },
          {
            "name": "u_opened_by_profit_center",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0c975e5-8643-44d4-9471-970384c7625a",
            "sourceColumn": "u_opened_by_profit_center",
            "summarizeBy": "none"
          },
          {
            "name": "u_resolved_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9fc5ce04-cc52-455d-936e-6c3d75b95ffa",
            "sourceColumn": "u_resolved_at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_583ceac0-cf2b-40b0-a4a2-16794b1274fe"
                },
                "isDefault": true,
                "relationship": "2be92250-57a6-4bc4-ae33-1469700859ca"
              }
            ]
          },
          {
            "name": "sys_updated_on",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "70eaad29-aac9-4d0a-a19b-4523fd833e9a",
            "sourceColumn": "sys_updated_on",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2029faa6-6e12-4a5e-a44f-a3edddda7017"
                },
                "isDefault": true,
                "relationship": "23239339-9bb7-4cd9-bcd3-b1652f87a70b"
              }
            ]
          },
          {
            "name": "u_resolved_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4bcd3bd-2fb2-43cf-898d-118ce71bc469",
            "sourceColumn": "u_resolved_by",
            "summarizeBy": "none"
          },
          {
            "name": "closed_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a571a740-2bbc-4a10-827f-c0fe6228e4ca",
            "sourceColumn": "closed_by",
            "summarizeBy": "none"
          },
          {
            "name": "u_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9eff0231-6558-4034-aaaa-7d99185f7c92",
            "sourceColumn": "u_category",
            "summarizeBy": "none"
          },
          {
            "name": "number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2db166aa-1061-45d2-87b0-c7c396cbe754",
            "sourceColumn": "number",
            "summarizeBy": "none"
          },
          {
            "name": "sys_updated_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54a9127b-b37e-4453-8ba6-1a921312f3bf",
            "sourceColumn": "sys_updated_by",
            "summarizeBy": "none"
          },
          {
            "name": "u_payroll_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45dc9c9d-f62b-422d-9b88-e0c4d0e8658a",
            "sourceColumn": "u_payroll_group",
            "summarizeBy": "none"
          },
          {
            "name": "sys_created_on",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "81df70f7-d718-47c9-af38-94d234862e82",
            "sourceColumn": "sys_created_on",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_99dbaa64-4fec-438e-bd6b-8ae2b551d6b0"
                },
                "isDefault": true,
                "relationship": "1ff00602-2d7f-4c78-a1d6-d1ce61743a38"
              }
            ]
          },
          {
            "name": "state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fd30729-7bec-47e3-8513-170305cfa94c",
            "sourceColumn": "state",
            "summarizeBy": "none"
          },
          {
            "name": "sys_created_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2eea1179-b01a-4d31-9a50-583e222ba33e",
            "sourceColumn": "sys_created_by",
            "summarizeBy": "none"
          },
          {
            "name": "assigned_to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06e974dc-b343-485e-9962-a2cb2880191b",
            "sourceColumn": "assigned_to",
            "summarizeBy": "none"
          },
          {
            "name": "loaded_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3740cd49-3c14-44cf-922b-5e2249f43616",
            "sourceColumn": "loaded_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a76c3aee-dc91-4a10-ad63-b57a83e59b30"
                },
                "isDefault": true,
                "relationship": "e7375050-13f5-4019-86e7-63d2b4726a24"
              }
            ]
          },
          {
            "name": "contact_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bdb3f4b-31b1-4d82-b6cd-343c168d7549",
            "sourceColumn": "contact_type",
            "summarizeBy": "none"
          },
          {
            "name": "priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1ac4006-c5d6-458e-93e8-d08508c801d9",
            "sourceColumn": "priority",
            "summarizeBy": "none"
          },
          {
            "name": "u_resolved_at - DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7285787a-1428-4c52-be31-6ad5b591bed2",
            "sourceColumn": "u_resolved_at - DATE",
            "summarizeBy": "none"
          },
          {
            "name": "sys_created_on - DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "eb7caf1e-e154-4d8b-8ab4-dd8eb02ca753",
            "sourceColumn": "sys_created_on - DATE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8105c884-ea8b-45e5-825e-8fedc9957f1a"
                },
                "isDefault": true,
                "relationship": "10424e78-6de7-4408-ad17-b580bee85634"
              }
            ]
          }
        ],
        "lineageTag": "3a049e81-db14-4c41-803a-7fc9875af035",
        "partitions": [
          {
            "name": "SNow_MORMetrics (GBS_Metrics)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"USPHL0PRPADBA1\", \"GBS_Metrics\"),",
                "    dbo_SNow_MORMetrics = Source{[Schema=\"dbo\",Item=\"SNow_MORMetrics\"]}[Data],",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(dbo_SNow_MORMetrics, \"u_resolved_at\", \"u_resolved_at - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"u_resolved_at - Copy\", \"u_resolved_at - DATE\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"u_resolved_at - DATE\", type date}}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Changed Type\", \"sys_created_on\", \"sys_created_on - Copy\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column1\",{{\"sys_created_on - Copy\", \"sys_created_on - DATE\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"sys_created_on - DATE\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7e85e738-c3ce-4f35-9f3c-90fe517b2269",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c39116d9-4c66-4ee9-b4b6-ac49632ba82c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "112ab9c0-1395-495b-90af-3185a9d68d8b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c98438ac-02c3-46fb-8d2c-968a2f5d705f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "728f402d-17d9-4b51-a61b-78876f232f98",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "1629be87-1794-454d-95a7-ab04f8e85581",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "158a7025-06af-4687-be87-b24a39976242",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "19f940a0-d7ab-40d1-9364-f6375d114af5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "398dfd39-032c-4281-b677-66c44bca4c0c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "98dfebaf-effd-4696-8868-f2b6d954206f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0919d5da-e573-424f-a7b3-ae0e840f0eca",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "709821fd-2595-4131-a9a0-fe1dea00c436",
                "ordinal": 3
              }
            ],
            "lineageTag": "96d95b65-cfb2-42d1-9034-9345b15dd49b"
          }
        ],
        "isHidden": true,
        "lineageTag": "4ee6ed36-6b17-4589-a6d8-6e012485b737",
        "partitions": [
          {
            "name": "LocalDateTable_7e85e738-c3ce-4f35-9f3c-90fe517b2269",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SNow_MORMetrics (GBS_Metrics)'[closed_at])), 1, 1), Date(Year(MAX('SNow_MORMetrics (GBS_Metrics)'[closed_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2029faa6-6e12-4a5e-a44f-a3edddda7017",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "23c28350-7275-4567-9c6e-1222ab0e9e7a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f7eee3b2-146a-4846-b7da-3fbe74eb5793",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b46eaf95-59ff-4e79-aeb7-f934a0e9a20d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d441880a-1d04-4008-a14b-0ca8295873db",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "34bd0e3a-31aa-4f18-b681-23e42d39ff6a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ef89cc78-19fb-4696-b182-6db7b85d0cfb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "6f701634-799d-4545-ace8-9cb65e3e9d90",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5b1e602d-1487-46fb-a38f-82f566e1b76c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e29acdd9-2b0f-4234-bfad-c3d6e306aa6b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9afe513c-44db-45ef-8981-28a612c5fa0a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1af6d5f3-e5c1-4203-83af-c6fbb5abba3c",
                "ordinal": 3
              }
            ],
            "lineageTag": "0c0d19be-e4ea-46d9-b5a9-24d7795c9de1"
          }
        ],
        "isHidden": true,
        "lineageTag": "87e09521-54ff-452e-ad32-c2ed57f21dea",
        "partitions": [
          {
            "name": "LocalDateTable_2029faa6-6e12-4a5e-a44f-a3edddda7017",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SNow_MORMetrics (GBS_Metrics)'[sys_updated_on])), 1, 1), Date(Year(MAX('SNow_MORMetrics (GBS_Metrics)'[sys_updated_on])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a76c3aee-dc91-4a10-ad63-b57a83e59b30",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5121a264-de17-40ad-829a-79a5e7cc6c57",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5c2f3130-5b77-4a69-9232-d7ec7e86676d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a49184ce-56d7-4224-ad54-3d7f65c1ec91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "80e6fb67-f86d-479c-b7cf-dc2b2bf442dd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e8ea04b2-0550-4f29-b62b-db7d4c6b3a38",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "66b11a24-e421-4967-831b-129a122ab7cb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "76fdcd39-7ec9-4e08-bd2f-0d34aae929eb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "90e01f01-6b98-4022-a427-514be7d11378",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fa5ebd92-301d-4e68-8c7b-03445a1b7ee6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e1308309-f3fb-4280-b45e-3a26f0907c9e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "72fdb92a-0908-4dc9-aa49-fb22bb293462",
                "ordinal": 3
              }
            ],
            "lineageTag": "eba32605-08ce-4b63-a385-4a83150c70f5"
          }
        ],
        "isHidden": true,
        "lineageTag": "84f7ff2a-2d7d-464b-8cfd-a30c99301f10",
        "partitions": [
          {
            "name": "LocalDateTable_a76c3aee-dc91-4a10-ad63-b57a83e59b30",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SNow_MORMetrics (GBS_Metrics)'[loaded_date])), 1, 1), Date(Year(MAX('SNow_MORMetrics (GBS_Metrics)'[loaded_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_99dbaa64-4fec-438e-bd6b-8ae2b551d6b0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ae8f6085-cfac-4ce0-8401-ad9412ef437d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7c7de330-9d84-42d3-a565-8a489919768a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "863f6cf8-5ebd-458e-b50d-23d73f9070cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4ca53cd0-963e-4175-b59d-e5dd2f85fa12",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "093acf67-daf1-4100-9082-c9a6e7984845",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "423b90ff-4f53-4302-b85e-68dfea183b5b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "91254401-5048-40cf-97f1-5679de072c5e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ea214eac-234a-429a-a094-4366a74cd2dc",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b1728b75-f939-4808-a4c8-f91d173a61ab",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bb74efd3-9d58-4437-8ac9-867ffb6cb289",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a45ad15a-18e2-4768-9735-cc5f72556811",
                "ordinal": 3
              }
            ],
            "lineageTag": "f9ae0bd7-c1a2-4728-8578-769cc7a910af"
          }
        ],
        "isHidden": true,
        "lineageTag": "fab83944-ea44-4bf2-9d21-1ca1f34b5283",
        "partitions": [
          {
            "name": "LocalDateTable_99dbaa64-4fec-438e-bd6b-8ae2b551d6b0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SNow_MORMetrics (GBS_Metrics)'[sys_created_on])), 1, 1), Date(Year(MAX('SNow_MORMetrics (GBS_Metrics)'[sys_created_on])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8105c884-ea8b-45e5-825e-8fedc9957f1a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5562f5f8-da63-4bf8-aafa-45fd26cc1825",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "bc34bdb6-3b06-41ce-8321-c1a5d932af46",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "aed88f8c-bf17-4be2-aa15-35a9a73b0037",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "81f95e0c-3523-4ac3-bb3a-1cfd544a2973",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d1a2e0b1-5f2b-4fa4-b90b-88bc2f34e403",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "aef3ef99-c702-4920-a000-d92c3183cfc4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "fd77cc5c-fc97-45e8-a9f7-ef132da60906",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0e2ceba1-08de-4b28-887d-ad8f22ec4a4f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "039f56bd-8f24-4468-9bae-d0eacd7610ec",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "88101fd8-2755-4437-b582-2874d39a1602",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "bca9f91c-fb71-4106-800c-a6e6fea6c037",
                "ordinal": 3
              }
            ],
            "lineageTag": "a04be632-be47-4eb2-ae62-b2c2853a4c74"
          }
        ],
        "isHidden": true,
        "lineageTag": "eba45140-a7f2-4725-ae01-0f4411067027",
        "partitions": [
          {
            "name": "LocalDateTable_8105c884-ea8b-45e5-825e-8fedc9957f1a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SNow_MORMetrics (GBS_Metrics)'[sys_created_on - DATE])), 1, 1), Date(Year(MAX('SNow_MORMetrics (GBS_Metrics)'[sys_created_on - DATE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_583ceac0-cf2b-40b0-a4a2-16794b1274fe",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "46a9df68-05a5-4365-95df-d4e391ebd146",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "623b6b19-3eb8-44fb-afdc-412f1411c5f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ede5ce4d-03c8-449c-8316-dea2224ca979",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2bdee5f3-958f-4eac-992e-6e15e0cb85bb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a55fd86a-c812-4e80-8835-b1bdd1f33f1b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ac218173-236b-4d82-9248-3618e89f5c0b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "dfc54819-f641-4592-86d0-0ba58e96021e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e866100a-2bf1-4e12-85c7-7a0c6b76417f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9f1d383c-477c-4c47-ab57-28d4fc44a107",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a58654c7-0954-4cfd-81d8-279e48d9560a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c40fa907-7a68-4a6a-a531-6f73643bb528",
                "ordinal": 3
              }
            ],
            "lineageTag": "9f48bebf-47bc-410a-9dd3-68937d695f43"
          }
        ],
        "isHidden": true,
        "lineageTag": "cdd8d329-ef3e-4959-afb6-4a7dfa45d3a1",
        "partitions": [
          {
            "name": "LocalDateTable_583ceac0-cf2b-40b0-a4a2-16794b1274fe",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SNow_MORMetrics (GBS_Metrics)'[u_resolved_at])), 1, 1), Date(Year(MAX('SNow_MORMetrics (GBS_Metrics)'[u_resolved_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "ServiceNow_CatalogTask_Closed",
        "columns": [
          {
            "name": "parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff086e80-2d15-4d42-b4dd-dc2cad956d99",
            "sourceColumn": "parent",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e87ec8b5-dbb8-47f9-a05f-96c65cf7874a",
            "sourceColumn": "request",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "work_start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d607f1da-7aaf-4c8b-a7d4-fb0dbd0f70d2",
            "sourceColumn": "work_start",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_402dca95-443e-40da-b75a-2a8ed29691c4"
                },
                "isDefault": true,
                "relationship": "1c4e5ce1-bc93-4224-8abb-359265754e05"
              }
            ]
          },
          {
            "name": "made_sla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae38a731-fc08-40e4-a5cd-2a8db198ee15",
            "sourceColumn": "made_sla",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "assignment_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91aa5001-7409-4e02-9c38-9c7809f4a9dd",
            "sourceColumn": "assignment_group",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sc_catalog",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddf03014-1756-4212-a1c9-4de463d557c2",
            "sourceColumn": "sc_catalog",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "calendar_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ce0cb6d-5e00-4f1a-b006-328c9d23d990",
            "sourceColumn": "calendar_duration",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "u_profit_center",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61afd138-8161-41c3-864e-c63a6f725f29",
            "sourceColumn": "u_profit_center",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sys_updated_on",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5cd9e59c-bd1e-4eab-984c-86f7e22cbebd",
            "sourceColumn": "sys_updated_on",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_85354851-cc60-47ab-9e2e-103d7ab9325b"
                },
                "isDefault": true,
                "relationship": "514f9e9c-4730-4d90-a864-7ab7af5f25ed"
              }
            ]
          },
          {
            "name": "sys_class_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f143331-bc2b-4274-8187-7683c5effc09",
            "sourceColumn": "sys_class_name",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "closed_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8ecc109-507d-4243-bd86-1ffc04c5fd52",
            "sourceColumn": "closed_by",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a30ea02-2bf2-4b6c-9512-2681be0b2b47",
            "sourceColumn": "number",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "contact_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08194ace-1029-4425-8491-a3bdba8f809d",
            "sourceColumn": "contact_type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sys_updated_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91b656d7-9100-4ebe-b7f4-14232670f630",
            "sourceColumn": "sys_updated_by",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "opened_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe6e4428-8482-493f-9cb9-17accca998b8",
            "sourceColumn": "opened_by",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sys_created_on",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4a85a2d7-96dc-4298-acc8-cbb3fefadd02",
            "sourceColumn": "sys_created_on",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_96e8bb0c-2634-4282-99c9-399968701ac8"
                },
                "isDefault": true,
                "relationship": "690d9c93-906e-40b3-ac4f-fd1281b94c20"
              }
            ]
          },
          {
            "name": "state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7528fc3a-b647-4fcc-9c0f-321309df3cab",
            "sourceColumn": "state",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sys_created_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b05d2480-d6e8-466b-8ffc-17f62c7c11e8",
            "sourceColumn": "sys_created_by",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "assigned_to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d81bc7f-a988-490f-b816-22b0345d6da0",
            "sourceColumn": "assigned_to",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "calendar_stc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2079b225-c996-460d-862a-6a42d18cfcb2",
            "sourceColumn": "calendar_stc",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "closed_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ddf0ba58-1691-403f-a42b-10144edcfc27",
            "sourceColumn": "closed_at",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ee5d4ae4-26d4-4760-9653-e56405084fd1"
                },
                "isDefault": true,
                "relationship": "6d262267-dde3-4072-9470-6547bb7046d2"
              }
            ]
          },
          {
            "name": "sla_due",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1571718-c183-45fb-9130-c8567c4e62db",
            "sourceColumn": "sla_due",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "u_opened_by_profit_center",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea5bae1f-e803-4a41-a6d4-f5a584b4c075",
            "sourceColumn": "u_opened_by_profit_center",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "request_item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0cc07f7-a435-444e-93dd-2e5008091f21",
            "sourceColumn": "request_item",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "741816c2-c886-4c6f-a16f-1e3ca5a04ae3",
            "sourceColumn": "priority",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "time_worked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "523f0258-9e45-4985-89d7-e8a54b1ec96e",
            "sourceColumn": "time_worked",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "opened_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5cf53002-7009-416f-af03-969764660138",
            "sourceColumn": "opened_at",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a80b2a60-5415-4437-abc9-ab2a8f9f7a8e"
                },
                "isDefault": true,
                "relationship": "6ce63d28-dc19-4565-8604-4376953537e5"
              }
            ]
          },
          {
            "name": "business_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f80e61b-d7a4-4289-a19f-78064ec0eb0a",
            "sourceColumn": "business_duration",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "work_end",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "75677d8c-2f84-4324-9856-ffc6d9c995ba",
            "sourceColumn": "work_end",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5471fa6b-68dc-4d3e-963e-e54f0cb79ebc"
                },
                "isDefault": true,
                "relationship": "108e0f75-27a6-47e6-bc2b-bad05498db12"
              }
            ]
          },
          {
            "name": "loaded_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "fc34b7df-c481-409a-985b-7487929b5c3e",
            "sourceColumn": "loaded_date",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4b1bd8a3-fd4c-424d-aff9-6dff80757ce3"
                },
                "isDefault": true,
                "relationship": "4e00003d-54b4-480c-b1ed-ad4444ebd788"
              }
            ]
          },
          {
            "name": "closed_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "77a38ebc-7c6e-40da-8c29-89245f99495b",
            "sourceColumn": "closed_date",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "opened_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5d9df3b5-4e11-42c4-8721-55dca94a125a",
            "sourceColumn": "opened_date",
            "sourceProviderType": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c97d5bc8-6fd4-479b-acc6-54d377087482"
                },
                "isDefault": true,
                "relationship": "cabd3116-067a-4df0-bf15-df040e83f988"
              }
            ]
          },
          {
            "name": "issue_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25acf956-7641-42b5-bdb9-8b184b3b015e",
            "sourceColumn": "issue_type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3cdadc5d-8a41-455c-bac5-9446797d9c1f",
        "partitions": [
          {
            "name": "ServiceNow_CatalogTask_Closed",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"USPHL0PRPADBA1\", \"Graham_Workspace\"),",
                "    dbo_ServiceNow_CatalogTask_Closed = Source{[Schema=\"dbo\",Item=\"ServiceNow_CatalogTask_Closed\"]}[Data]",
                "in",
                "    dbo_ServiceNow_CatalogTask_Closed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ServiceNow_IncidentPS_Resolved",
        "columns": [
          {
            "name": "parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07372cb8-d6a8-484a-99f9-ab736ac37a9f",
            "sourceColumn": "parent",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "work_start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "718d17e1-5e1e-4b29-9f84-fe38f97ff51a",
            "sourceColumn": "work_start",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_24be776b-6100-496f-b233-6d6753e29e23"
                },
                "isDefault": true,
                "relationship": "c6bbee44-bc3a-4816-95ff-50a302ea3e67"
              }
            ]
          },
          {
            "name": "made_sla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae511e2b-93ae-4e69-84d9-9f25419a6418",
            "sourceColumn": "made_sla",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "assignment_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c905b558-4364-4eba-81ab-b424f74497f3",
            "sourceColumn": "assignment_group",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "calendar_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39592c8e-147a-4c3f-b872-e937b70f7235",
            "sourceColumn": "calendar_duration",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "u_profit_center",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f067be28-5637-488a-8587-8eb377ec2d81",
            "sourceColumn": "u_profit_center",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sys_updated_on",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "200735a0-656d-48dd-81ed-e90839493979",
            "sourceColumn": "sys_updated_on",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e9080415-8e4d-42e5-b538-5b9e4de47a75"
                },
                "isDefault": true,
                "relationship": "32df03c0-a78a-4139-8a93-42c9d1f6406f"
              }
            ]
          },
          {
            "name": "u_resolved_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55bb4bd2-3bd9-41bf-8baf-8732bfe44da6",
            "sourceColumn": "u_resolved_by",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sys_class_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c760172f-c0e6-437e-aaf5-8f787235c120",
            "sourceColumn": "sys_class_name",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "closed_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00e2abba-850f-402d-8e95-b81363285e9b",
            "sourceColumn": "closed_by",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "779ca1e3-49ab-45d2-9f7d-c3d3d66158b4",
            "sourceColumn": "number",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "contact_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66126cb7-b76b-413d-9512-3ae7c0ae694c",
            "sourceColumn": "contact_type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sys_updated_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfdb1550-5266-4e5d-84b0-ef10ef211a35",
            "sourceColumn": "sys_updated_by",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "opened_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfcb690b-afab-4b26-8ea4-559ed16b47e7",
            "sourceColumn": "opened_by",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "u_payroll_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7bf4e42-7821-45f7-81cc-4134f352b2f4",
            "sourceColumn": "u_payroll_group",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sys_created_on",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "eb44bdcc-6358-4fc8-b6ad-7a86647353f3",
            "sourceColumn": "sys_created_on",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a08aaeb3-46aa-472b-acf6-6300499699d2"
                },
                "isDefault": true,
                "relationship": "01316265-b45a-41cd-9682-0d12592dfc3a"
              }
            ]
          },
          {
            "name": "state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "063b4662-159d-4d1e-b6cb-c0a9fd30bb7f",
            "sourceColumn": "state",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "reassignment_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "add3873a-9bb5-4caf-b523-a1470307f294",
            "sourceColumn": "reassignment_count",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sys_created_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26043d41-cba8-49f6-b1b8-9785fc3792d2",
            "sourceColumn": "sys_created_by",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "assigned_to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a495ea6e-16ff-4d89-927b-1ea68ab9bc4e",
            "sourceColumn": "assigned_to",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "closed_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c02adc24-5ef9-4dba-9490-5ac9e7254173",
            "sourceColumn": "closed_at",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e194ffee-a7af-4866-9148-8658a61c784f"
                },
                "isDefault": true,
                "relationship": "34fa2708-f808-4b8f-9250-76956ac5ff90"
              }
            ]
          },
          {
            "name": "u_subcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "159a68a7-8739-4f85-a000-bed72a6f3369",
            "sourceColumn": "u_subcategory",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sla_due",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d20f2204-525b-4198-ba5e-4973640f7b36",
            "sourceColumn": "sla_due",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "u_incident_state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8858ef60-4492-46b7-939d-4ce4b574454c",
            "sourceColumn": "u_incident_state",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "u_opened_by_profit_center",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d44c01bc-d8ed-4cba-b8ab-86183025153a",
            "sourceColumn": "u_opened_by_profit_center",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7ade5a2-3d76-46eb-9798-ec837f4bc693",
            "sourceColumn": "active",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "u_resolved_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6d12a6c8-67db-46dc-adf8-ed7f1ffe7a4c",
            "sourceColumn": "u_resolved_at",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e9bc2933-4a23-4ed4-8d43-55191bfdd1cd"
                },
                "isDefault": true,
                "relationship": "01b354c8-99f8-4fd0-9879-c8f46338536d"
              }
            ]
          },
          {
            "name": "priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a373df72-dee0-4d3e-9936-03b33a49b63f",
            "sourceColumn": "priority",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "time_worked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4cff5b2-3c3c-4f2c-8097-e7413b97a102",
            "sourceColumn": "time_worked",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "u_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df0532c1-b9cb-4dbc-b02c-fe2b8f8fe719",
            "sourceColumn": "u_category",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "opened_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2098dee3-a73c-49dd-ac93-fb2b6707deba",
            "sourceColumn": "opened_at",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8ef3d604-35f0-4e7a-bb23-b1c244ca912c"
                },
                "isDefault": true,
                "relationship": "af769244-2912-4a21-b538-5acb0bd37b4d"
              }
            ]
          },
          {
            "name": "business_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "764cd92a-3cbf-4d0f-a4ee-6cad442f2979",
            "sourceColumn": "business_duration",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "work_end",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "200ec984-4b99-4169-9903-c5597d91da69",
            "sourceColumn": "work_end",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_11470753-ee0b-4b08-bedf-bb0744528636"
                },
                "isDefault": true,
                "relationship": "b2a2f640-c947-4eee-a5a9-64b42b164300"
              }
            ]
          },
          {
            "name": "loaded_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7fcafc2f-e37c-4143-88d5-8f81a4e44264",
            "sourceColumn": "loaded_date",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_17802431-26e1-4200-8372-8d1f03ec99e5"
                },
                "isDefault": true,
                "relationship": "3227e651-d2b4-4400-bd13-6049a779c0b1"
              }
            ]
          },
          {
            "name": "opened_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1c3f9286-d981-49ff-bbfa-ab2867f42699",
            "sourceColumn": "opened_date",
            "sourceProviderType": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7bcea297-3553-4e52-baef-555fccb78005"
                },
                "isDefault": true,
                "relationship": "f6475805-2731-4068-a13d-e1fedfd4e879"
              }
            ]
          },
          {
            "name": "resolved_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c0671678-55ee-48f9-a7d5-13f8be0e1403",
            "sourceColumn": "resolved_date",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c1a44f78-513b-4bd2-af88-a0986886b7b4",
        "partitions": [
          {
            "name": "ServiceNow_IncidentPS_Resolved",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"USPHL0PRPADBA1\", \"Graham_Workspace\"),",
                "    dbo_ServiceNow_IncidentPS_Resolved = Source{[Schema=\"dbo\",Item=\"ServiceNow_IncidentPS_Resolved\"]}[Data]",
                "in",
                "    dbo_ServiceNow_IncidentPS_Resolved"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_402dca95-443e-40da-b75a-2a8ed29691c4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "75810850-45b4-4415-ae8a-1621dc8768cd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2646b550-4713-433a-b086-ce050942f1ec",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "64821ad3-02f6-48e9-902c-377856f2fa37",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "188b27bf-2428-4789-817d-7f3105bda5b7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "89072245-adb0-4735-8aec-d2420c5065a7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a795b712-6593-4c13-9773-327d5088f352",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f6805d7a-1c82-482c-a016-f1f09332be5a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cf4daab3-2087-40b0-a327-d775583aea80",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "601d7468-0b75-4908-9e40-c01992df2291",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0d9ed1b0-e81b-4744-b77b-166f5cda6bb6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f481248b-cf86-49ad-a558-b3ab970c82d6",
                "ordinal": 3
              }
            ],
            "lineageTag": "f36ccd57-f3b2-4ed6-bae6-daf440d19b11"
          }
        ],
        "isHidden": true,
        "lineageTag": "7897a5d5-5299-4055-8112-701c8ecc2383",
        "partitions": [
          {
            "name": "LocalDateTable_402dca95-443e-40da-b75a-2a8ed29691c4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_CatalogTask_Closed'[work_start])), 1, 1), Date(Year(MAX('ServiceNow_CatalogTask_Closed'[work_start])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_85354851-cc60-47ab-9e2e-103d7ab9325b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d80d8e18-a63d-4f55-8445-b3202db0d330",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c02faf31-a257-43ef-8eb0-5fa05de4b1ac",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "23f77e59-a5ea-4488-a07f-26574ca538e1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dbe5d4a8-972b-493e-af39-45323b68339c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "86b09706-28d6-4e2e-b6ad-22ab20cc4dcf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "afd328a3-60c6-4e03-a701-f3407d1e3837",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "22ce986e-cae9-40b7-a441-14a377d055a9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cf8f982d-f4b3-4fc6-838f-e3462bc66c4a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2eb73057-6c0a-433c-9a64-dce3a6fe6665",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6b58962e-f7e1-4748-933f-b355b06b17bc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e5b60809-f5a7-4da4-8eec-4c5e87e739fc",
                "ordinal": 3
              }
            ],
            "lineageTag": "9632c955-13cb-4ccc-be60-3ed9623d1a85"
          }
        ],
        "isHidden": true,
        "lineageTag": "19a4097b-af5f-4eaa-abec-c69c528a8535",
        "partitions": [
          {
            "name": "LocalDateTable_85354851-cc60-47ab-9e2e-103d7ab9325b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_CatalogTask_Closed'[sys_updated_on])), 1, 1), Date(Year(MAX('ServiceNow_CatalogTask_Closed'[sys_updated_on])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_96e8bb0c-2634-4282-99c9-399968701ac8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bffd4a5d-38f5-4dd7-9f61-37d918f21fb7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "62e2eed5-aefc-418b-b412-c1783708ad61",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4675c2a5-3b44-416c-96f1-3274c726ff49",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a1c21469-12eb-4cb3-87ae-1b31833990e1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2e66c162-b607-471e-a4f7-f2f1cf199f70",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9b8ef925-d593-4391-9088-70111b57cfbe",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1590a32a-0a72-4042-89dc-814a57594b18",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "585e3c02-aa3b-4fc5-ab0d-b6b383ba26ae",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "806664e2-dad9-4766-aa0a-7225f26e5bbf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6d85fde4-5268-4a84-b5fd-f8d9268c2121",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fdd8489a-23b4-4278-81ef-a3e27cb505e1",
                "ordinal": 3
              }
            ],
            "lineageTag": "5f024f49-95b0-4ccf-8fe8-434363775aec"
          }
        ],
        "isHidden": true,
        "lineageTag": "0c1f1668-4751-458f-b570-1d4cb0f12ea7",
        "partitions": [
          {
            "name": "LocalDateTable_96e8bb0c-2634-4282-99c9-399968701ac8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_CatalogTask_Closed'[sys_created_on])), 1, 1), Date(Year(MAX('ServiceNow_CatalogTask_Closed'[sys_created_on])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ee5d4ae4-26d4-4760-9653-e56405084fd1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cfdcccbe-a9a0-4907-ac63-5ba581b89204",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7f92fb21-9d48-4574-a590-1bca6a236f8a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a9371625-d0a8-4d24-a856-db007e846ea0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0292abc2-0194-4808-95fd-2f2f2a81f0c8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5bd27d3d-2fad-4e47-bd55-f9cbfc4733ce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "12c00f2c-3b2f-4c1d-af74-a6d717d3e8f5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4d4a4df6-d2e6-4584-a762-249fd5cda847",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "62675397-8146-4944-a265-c711e9c8a16f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "75b5e347-3b65-4249-94e5-1ad290364d03",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7c25e41a-b277-45bf-99d8-db2b7f8b36cb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "06c6869c-7f0f-47ec-b6c1-7116bda16e50",
                "ordinal": 3
              }
            ],
            "lineageTag": "fbdca314-b24f-4fc2-93d8-9825f2b526ed"
          }
        ],
        "isHidden": true,
        "lineageTag": "c6b21548-36f5-4af9-a97b-d6096345d7d0",
        "partitions": [
          {
            "name": "LocalDateTable_ee5d4ae4-26d4-4760-9653-e56405084fd1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_CatalogTask_Closed'[closed_at])), 1, 1), Date(Year(MAX('ServiceNow_CatalogTask_Closed'[closed_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a80b2a60-5415-4437-abc9-ab2a8f9f7a8e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8234bb52-fbf4-4fb7-8944-8523ca8e0916",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3556b453-f9a7-4606-a7ed-d4aaa0b975e7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "289337da-492e-4b37-bfc4-b4f53ccdf901",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0ea83e55-8712-4f5f-af7b-a49b2767b66d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e855d16a-3055-4ec9-9662-f41ec4b36375",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "94301bc8-4930-459d-b4ff-f504204158a4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5aec10c2-c1e0-4de0-ae3f-40584c634b39",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "baa34605-2b45-4305-ade8-45258dce1916",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b4ec8206-a92e-41dc-9ebb-9d210c535c9b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "cb9271a3-dbe1-4fbf-bbd9-751cdba75b09",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "516de4ae-2e40-4eec-b9bc-a87ca1da0df2",
                "ordinal": 3
              }
            ],
            "lineageTag": "a5f8ea65-8b74-4a04-9724-a2292398c8fc"
          }
        ],
        "isHidden": true,
        "lineageTag": "1aac22f8-6150-4956-9b46-dfe2967242f7",
        "partitions": [
          {
            "name": "LocalDateTable_a80b2a60-5415-4437-abc9-ab2a8f9f7a8e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_CatalogTask_Closed'[opened_at])), 1, 1), Date(Year(MAX('ServiceNow_CatalogTask_Closed'[opened_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_5471fa6b-68dc-4d3e-963e-e54f0cb79ebc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "491b5ec9-1f64-4440-a2de-1feefd5d36ee",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "57471f29-4c01-4158-8121-5288481b699d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "742364b8-86f7-432a-865a-6efec2620f1e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6998c4f1-b3f3-4043-ac19-d36318500043",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "cea4cf24-c05a-4ac1-8869-c32d64782471",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "23c29b9a-650c-4507-b188-bcc68973a1c4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4d6c18b9-cdfb-4faf-ac36-cc2e1b5f503e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fe9537df-6533-4782-8625-8f0ff08048a7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5a28868e-e831-421d-862a-a3a460f92363",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e91d02b7-e50f-4ac3-8033-9a6f2b02b686",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "23915540-f72f-4015-96a8-9fc64b443871",
                "ordinal": 3
              }
            ],
            "lineageTag": "d1cf6e5d-302b-4d38-a9ef-6646182f14c3"
          }
        ],
        "isHidden": true,
        "lineageTag": "c58e52bc-993d-44df-a71d-eaa7de51f582",
        "partitions": [
          {
            "name": "LocalDateTable_5471fa6b-68dc-4d3e-963e-e54f0cb79ebc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_CatalogTask_Closed'[work_end])), 1, 1), Date(Year(MAX('ServiceNow_CatalogTask_Closed'[work_end])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4b1bd8a3-fd4c-424d-aff9-6dff80757ce3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "102d2532-f255-44a8-af1f-9e4dbfc6c390",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "6300fb4c-6a73-487a-87b7-7e9545b5b5a5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "81f11eb8-cc16-4f77-9ad3-e1256a690b6a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "978c08e2-5d4b-40b6-b73c-65c518741ba6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "cc84c5c3-4468-4cea-9bf8-4a071edc08cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d7bc7543-b732-46de-be7e-d74a5bd8de27",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "eb355b0b-e110-4990-9fee-1bc845b6938b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "34999b55-e466-4426-94cb-7f9225c17c59",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8755ae23-12b3-47a9-9bd8-0220dd89d5d4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b5ecd689-b405-48b3-bd92-bfeea82a0f08",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "33b12888-cb97-4de6-959a-b63e0fd05da2",
                "ordinal": 3
              }
            ],
            "lineageTag": "fa2815a2-3e27-4de0-a13a-5aca48f0e313"
          }
        ],
        "isHidden": true,
        "lineageTag": "5c77c170-3571-45ad-8d4a-78bbea9afe2c",
        "partitions": [
          {
            "name": "LocalDateTable_4b1bd8a3-fd4c-424d-aff9-6dff80757ce3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_CatalogTask_Closed'[loaded_date])), 1, 1), Date(Year(MAX('ServiceNow_CatalogTask_Closed'[loaded_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c97d5bc8-6fd4-479b-acc6-54d377087482",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7255246f-9326-40ed-80b5-1f9cf22b5efb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c784fc7e-2f99-4c01-88c9-e9921c864af8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "26796894-5e9c-4494-a2ba-13449e653442",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "35e1a365-655a-42bf-8fa5-500c9a146703",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3f9ad52a-8ac7-4084-8e05-482ef1ba8e2f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f5d33e36-abb0-41f8-80e6-d2858ef68066",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "83bda8a3-86a2-4fc1-971c-1a435e7e6ea8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7c348028-d118-4c2b-b3e9-e475097053ed",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4b4b816a-8025-4a76-bca0-7e267bb06972",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ae1ab67c-e0a0-46bf-af0b-ba38f6b79cb4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d6c02e6b-9710-46b7-8832-56b481152e20",
                "ordinal": 3
              }
            ],
            "lineageTag": "d964c8c4-04e9-4941-8b36-c749c54aab57"
          }
        ],
        "isHidden": true,
        "lineageTag": "7a66d702-99eb-4913-8a17-68905d809909",
        "partitions": [
          {
            "name": "LocalDateTable_c97d5bc8-6fd4-479b-acc6-54d377087482",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_CatalogTask_Closed'[opened_date])), 1, 1), Date(Year(MAX('ServiceNow_CatalogTask_Closed'[opened_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_24be776b-6100-496f-b233-6d6753e29e23",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fd2ba487-f73e-40a2-bfe6-0452b3c05957",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f954ceb7-5163-4e87-b5fb-11e1c975077f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "d84ecef5-84f7-4c4b-b12a-da48de5fd2a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a3af38fa-0c50-436d-bc0e-e3cb75c180bb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2e24ca41-f4a5-40f4-9ba6-d0a481afa72e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e9299647-34ac-4467-b941-9c320d718a25",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4764e651-8b37-42f6-894d-363b9004b94f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4534b2f5-a019-4ed5-afb3-9ccbfaeb982a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b71913b1-ad9d-475d-8dbb-87b09e7503be",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "116d8ba4-4495-434e-a936-241d9cd86882",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f46e720c-5eeb-4b28-9ebc-a09f280720ff",
                "ordinal": 3
              }
            ],
            "lineageTag": "6d241553-481c-49e4-88c5-b3544d2a5aa3"
          }
        ],
        "isHidden": true,
        "lineageTag": "8d471852-6e86-47a1-95be-7dca3876f1ea",
        "partitions": [
          {
            "name": "LocalDateTable_24be776b-6100-496f-b233-6d6753e29e23",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_IncidentPS_Resolved'[work_start])), 1, 1), Date(Year(MAX('ServiceNow_IncidentPS_Resolved'[work_start])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e9080415-8e4d-42e5-b538-5b9e4de47a75",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "28810f14-3207-422e-bdb2-326c0f4e99b3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "74cd71a4-ec78-4a16-ae36-66076996df61",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0305fa14-805d-418b-9d49-33159f086773",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c1b89b79-f368-4d3e-b736-9fd6c0ea6398",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "cd090b68-1e51-4d4a-8cb5-8acb7a87e79f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d291d4a7-cf53-4bdb-99d7-eb645291e49e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "31437bcf-82e2-409e-8230-976b0aab958f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "88339461-d9df-49a1-93f8-0ab5fff0cb03",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1224e33c-ff7c-4bf6-88dd-44d07ac32695",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bd876ebc-062a-4b1e-99b3-baa5f719e235",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "35352ab9-3c1f-46e9-9511-eeeb46607361",
                "ordinal": 3
              }
            ],
            "lineageTag": "c4c6f15d-ce57-4f6d-a53b-ce77c3048134"
          }
        ],
        "isHidden": true,
        "lineageTag": "f3ca8b62-fa68-4968-8969-05b8aab819b1",
        "partitions": [
          {
            "name": "LocalDateTable_e9080415-8e4d-42e5-b538-5b9e4de47a75",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_IncidentPS_Resolved'[sys_updated_on])), 1, 1), Date(Year(MAX('ServiceNow_IncidentPS_Resolved'[sys_updated_on])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a08aaeb3-46aa-472b-acf6-6300499699d2",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f401c7e2-2062-4ca9-97d3-d1052a5d9e90",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "bb9f1288-e07b-4e0e-b9b0-9197f6a0d851",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "153f2502-8e5a-4fce-981c-ffefabd7add8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "639116de-a84e-4ea5-b0b2-d993a071d803",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c8270a56-9600-4541-bde5-88f3e383f50c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b6183afb-f9a8-4983-804d-dbe9c651f2c9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5d21a13a-2849-4043-a21d-9280d66a1094",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cf79a4ae-df70-40c0-974d-d63372933c49",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4c80c1b4-4586-45a9-a8d1-d15c3eaac8a9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bd643dea-89cc-41f9-9efc-aee3b303048c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a65a123e-3d3f-4c0f-af6b-215993d544ba",
                "ordinal": 3
              }
            ],
            "lineageTag": "66d9d2d4-6da5-4d24-84ee-370de5366e82"
          }
        ],
        "isHidden": true,
        "lineageTag": "ba9984bf-2a2e-4d80-93ac-a2c5208b49f5",
        "partitions": [
          {
            "name": "LocalDateTable_a08aaeb3-46aa-472b-acf6-6300499699d2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_IncidentPS_Resolved'[sys_created_on])), 1, 1), Date(Year(MAX('ServiceNow_IncidentPS_Resolved'[sys_created_on])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e194ffee-a7af-4866-9148-8658a61c784f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "193f0425-efe0-46c5-9b87-a88d420eafce",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0dac6f4f-88a6-4819-9361-15e94d67f2f2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b8daa92f-f0cf-4c43-9d6e-0e9f0b1c4cd0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "777ad5c7-7d5c-4cfc-8ada-5ac58ca7230b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "310bc54f-e1cc-4c2e-9e57-07580b44357b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "17d6c0c6-a482-4eed-988d-b61249729e48",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "0a296bc9-a8db-4e27-9f0e-f502f5c89c53",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a0569b38-8a2e-4142-8eae-1dbd6c7d444a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b4f46710-180d-404c-9b7b-3d02e7be1a57",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e6c167ac-bd6a-4c66-9672-5f27e5dfd8be",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "17a21da0-1088-4f83-a0e8-d88a3f22bff3",
                "ordinal": 3
              }
            ],
            "lineageTag": "0abc4b97-e81c-486c-ac94-619416903c9e"
          }
        ],
        "isHidden": true,
        "lineageTag": "62917bf3-0e36-47ef-8a63-2e5ffe925948",
        "partitions": [
          {
            "name": "LocalDateTable_e194ffee-a7af-4866-9148-8658a61c784f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_IncidentPS_Resolved'[closed_at])), 1, 1), Date(Year(MAX('ServiceNow_IncidentPS_Resolved'[closed_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e9bc2933-4a23-4ed4-8d43-55191bfdd1cd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "646f0b4c-4864-4f32-a2d2-78acb55e65e3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f79ad627-c42b-413e-8aca-905287071068",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8ab50d5d-db1a-4565-a0c2-bf16a56087dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8f715820-b30e-4e83-8ace-24df1bf4678a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "73bfdba3-44ab-4d15-b300-8b4d684085fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "455e9e00-74a3-4433-bbf3-a2e80e91355c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5939b0f4-cd08-4ee1-aa32-92b6163514d9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "41099a9d-11bc-47cf-a2e0-bb2eade9e522",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7bb6e97f-6099-4201-ba7b-3a93e0683d0b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0825dca5-ec1d-4f6c-87f5-73ca09e066c9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2990e7ed-2af9-4ded-9ec4-6c99518c0668",
                "ordinal": 3
              }
            ],
            "lineageTag": "01d1ff76-146b-463f-8986-2a43d0665d2d"
          }
        ],
        "isHidden": true,
        "lineageTag": "4f1e03ba-e969-4924-acda-0cbbbdaa8b8f",
        "partitions": [
          {
            "name": "LocalDateTable_e9bc2933-4a23-4ed4-8d43-55191bfdd1cd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_IncidentPS_Resolved'[u_resolved_at])), 1, 1), Date(Year(MAX('ServiceNow_IncidentPS_Resolved'[u_resolved_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8ef3d604-35f0-4e7a-bb23-b1c244ca912c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "52fc16dd-b81b-4599-babb-263624892765",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c17f68f3-672a-4d0f-b9d0-11edd2608107",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "09c98aba-b437-4d9b-8b91-b5a6c1179880",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8df76a28-6b85-4683-aa05-bd008ba29ef6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "00122b7b-8a19-4dd4-8b24-02669172e5e0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a21448f2-83d1-4bc5-8a8a-d8558eda5dbd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d2615f13-20d3-4178-a5e3-e3c220a1f3d1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "57bf17b8-8705-4c40-b7b7-1e219030446d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c8bb0974-2063-46b4-9cb2-dacee8d8ac3d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e6eca5f0-dd6e-49e2-a75f-0c4b1f56ca3a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7273a017-7cb1-4fa4-a8b5-4ef66d70941d",
                "ordinal": 3
              }
            ],
            "lineageTag": "fdf7b275-d019-4239-b65b-2d28a8cbd7fe"
          }
        ],
        "isHidden": true,
        "lineageTag": "a9590fb1-c2f5-4ad8-836a-d1e27aca86ba",
        "partitions": [
          {
            "name": "LocalDateTable_8ef3d604-35f0-4e7a-bb23-b1c244ca912c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_IncidentPS_Resolved'[opened_at])), 1, 1), Date(Year(MAX('ServiceNow_IncidentPS_Resolved'[opened_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_11470753-ee0b-4b08-bedf-bb0744528636",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ee18fb83-3e71-4e00-9c6a-fe599f6a09f8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0162069a-8282-4fbf-99e3-f82e342f8ac8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e0292349-d8bf-45f0-ae93-b20461a00892",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "710f1ca6-78ee-4497-a0d5-dc5cb7fa172c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "df3c24f3-32e7-48a5-b62c-d98cb7f39b02",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "38670db2-a1e4-4c04-83b0-f830bd52a18a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9a4097ef-cc4b-4126-8835-966e39e8ee58",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0f698a6f-9dd6-40cd-8674-e2fb47456198",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "25ce3bc3-bd25-4e37-b3d2-cdef6a25b999",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7713a56d-4483-44a0-875d-abfcbe78a966",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f5ec98ae-afaf-42be-803e-5832846ed4a4",
                "ordinal": 3
              }
            ],
            "lineageTag": "44ae6ca7-f2df-4a6f-989b-59b28aed0b53"
          }
        ],
        "isHidden": true,
        "lineageTag": "2e93de54-7f44-4911-94d6-8af7014e2037",
        "partitions": [
          {
            "name": "LocalDateTable_11470753-ee0b-4b08-bedf-bb0744528636",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_IncidentPS_Resolved'[work_end])), 1, 1), Date(Year(MAX('ServiceNow_IncidentPS_Resolved'[work_end])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_17802431-26e1-4200-8372-8d1f03ec99e5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1a02eea6-7f20-477f-9901-4649e891271a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "69d673ce-00fe-46f0-b49d-81d9d4da3e7a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "733a6d8e-f16b-4c67-9b0a-8c4c60f50bf6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f3d64745-a365-4207-9e7e-4b99c3255e72",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "347d5b40-b6a2-4e13-b071-2f4485da220b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "bc475b82-f4cd-48ad-aac1-0839fbe651f0",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "548b6b7f-3482-433d-9b21-030be677c075",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8438c741-9a8c-4a00-a437-7c7c3b52af32",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9f0cdb61-10af-487c-8bbe-cf4c263ea283",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7be7f069-e031-4402-a3ba-df6713b310da",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b8105d63-6064-4a3f-9fda-a494124aa407",
                "ordinal": 3
              }
            ],
            "lineageTag": "bd3f86b3-d3a4-458d-a04a-24ce44615874"
          }
        ],
        "isHidden": true,
        "lineageTag": "2dbb42f7-9bc0-4941-843f-695f30d02abf",
        "partitions": [
          {
            "name": "LocalDateTable_17802431-26e1-4200-8372-8d1f03ec99e5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_IncidentPS_Resolved'[loaded_date])), 1, 1), Date(Year(MAX('ServiceNow_IncidentPS_Resolved'[loaded_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7bcea297-3553-4e52-baef-555fccb78005",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "21105a68-8535-4e7a-8b91-ff6f49251842",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3b9eabd3-50db-4363-bd4b-b4b0922e4df4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b9a534f8-3dc5-4038-af85-fdb00f7d88a2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "cb5ee5c3-8dcd-4194-afb5-6c91545fe58e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "18d57c92-ff6b-45a8-940c-35384be6e2e6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d5b192eb-d200-4d18-8025-1ea3584f0098",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7a86cd9f-8ad2-4b27-a72b-58305f7874fa",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c7cc9a81-6791-47b1-993c-4878fc9d6cef",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e6362787-7616-48f6-b923-a386b1f5d576",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9665c675-8c74-4181-9cf4-2aa894c2a73e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "742af7be-7a61-4795-a47a-e6ad184bf3dd",
                "ordinal": 3
              }
            ],
            "lineageTag": "18254385-ae67-4fef-9672-9d31a4b1f9b1"
          }
        ],
        "isHidden": true,
        "lineageTag": "360060e9-3acd-41a3-bd4c-db7dece49f75",
        "partitions": [
          {
            "name": "LocalDateTable_7bcea297-3553-4e52-baef-555fccb78005",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_IncidentPS_Resolved'[opened_date])), 1, 1), Date(Year(MAX('ServiceNow_IncidentPS_Resolved'[opened_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "ServiceNow_TaskSLA_Ended",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "pause_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f08c7816-faaf-4b51-97bb-57cf0d3efc76",
            "sourceColumn": "pause_duration",
            "summarizeBy": "none"
          },
          {
            "name": "task_assigned_to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fcd65ab-4970-4cca-8156-d676dfef88a6",
            "sourceColumn": "task_assigned_to",
            "summarizeBy": "none"
          },
          {
            "name": "pause_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbd39c1b-5b8b-4077-a1c1-35e78ecd2938",
            "sourceColumn": "pause_time",
            "summarizeBy": "none"
          },
          {
            "name": "timezone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8373fda5-4046-44d4-a5ff-1ba76f3563a0",
            "sourceColumn": "timezone",
            "summarizeBy": "none"
          },
          {
            "name": "sys_updated_on",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "54394e53-8659-4c75-a00f-e74ca537c201",
            "sourceColumn": "sys_updated_on",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_96a8c92d-9228-4b41-bc35-565c9ec6d141"
                },
                "isDefault": true,
                "relationship": "6e231ae1-7c6d-429a-95a5-b9ad582def77"
              }
            ]
          },
          {
            "name": "business_time_left",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f175f9b0-cf33-47d3-84b8-30e02ed955dd",
            "sourceColumn": "business_time_left",
            "summarizeBy": "none"
          },
          {
            "name": "duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f3410a1-18da-425f-81b9-9b02589e1c1f",
            "sourceColumn": "duration",
            "summarizeBy": "none"
          },
          {
            "name": "sys_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4ff5219-1c78-416d-87dd-365d6c931159",
            "sourceColumn": "sys_id",
            "summarizeBy": "none"
          },
          {
            "name": "time_left",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ad3d9db-9b0f-4e5d-b6a6-0a003fa9383e",
            "sourceColumn": "time_left",
            "summarizeBy": "none"
          },
          {
            "name": "sys_updated_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b5c96ef-96a7-4805-888c-fb759e78ed61",
            "sourceColumn": "sys_updated_by",
            "summarizeBy": "none"
          },
          {
            "name": "sys_created_on",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "21bf3fde-fde7-450f-911e-09a32a86331f",
            "sourceColumn": "sys_created_on",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_04432eee-33a0-4736-bc17-50c2e9efafe3"
                },
                "isDefault": true,
                "relationship": "7b4e69fa-184b-4f0b-a416-bfc6e2a9e312"
              }
            ]
          },
          {
            "name": "percentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00b9e505-c39a-4537-a1be-1c37dc32fbd4",
            "sourceColumn": "percentage",
            "summarizeBy": "none"
          },
          {
            "name": "original_breach_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a28fc3f6-ca06-4486-a7f0-682321d87e87",
            "sourceColumn": "original_breach_time",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_595d1031-8e5b-4cc9-b880-f1571dba9a92"
                },
                "isDefault": true,
                "relationship": "8fb4a068-2b15-4005-b996-d5997e403ac5"
              }
            ]
          },
          {
            "name": "sys_created_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49b61d0f-9cef-440a-9bee-ffb5ad2002de",
            "sourceColumn": "sys_created_by",
            "summarizeBy": "none"
          },
          {
            "name": "business_percentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb3e1316-b304-48a6-a527-59acf9276665",
            "sourceColumn": "business_percentage",
            "summarizeBy": "none"
          },
          {
            "name": "task_assignment_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c549cab-10ed-488a-8ba3-d2df20aedd13",
            "sourceColumn": "task_assignment_group",
            "summarizeBy": "none"
          },
          {
            "name": "end_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4c307da2-e480-48cb-87ce-06abdc850344",
            "sourceColumn": "end_time",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1ff12552-f399-4f86-8b85-1a3731aa9b5f"
                },
                "isDefault": true,
                "relationship": "09d6fe59-96a6-4418-9001-3c93f88c2c61"
              }
            ]
          },
          {
            "name": "sys_mod_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f6f27cf-019e-4836-9f75-dbb025fcac16",
            "sourceColumn": "sys_mod_count",
            "summarizeBy": "none"
          },
          {
            "name": "active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79c61dd8-bcda-4608-ade7-fe9cd2c49615",
            "sourceColumn": "active",
            "summarizeBy": "none"
          },
          {
            "name": "business_pause_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72ceb7a2-0b50-4d8b-b28a-8abc2ac910ac",
            "sourceColumn": "business_pause_duration",
            "summarizeBy": "none"
          },
          {
            "name": "sys_tags",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "828be02e-7d0a-4d7c-bff7-dd6e8f33973b",
            "sourceColumn": "sys_tags",
            "summarizeBy": "none"
          },
          {
            "name": "schedule",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5b3a40e-de5c-4f3e-85c6-ab8b0a5acd0f",
            "sourceColumn": "schedule",
            "summarizeBy": "none"
          },
          {
            "name": "start_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6b621629-bc78-453e-a0bb-d6d1a6843682",
            "sourceColumn": "start_time",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c7f48084-4f56-4408-ace7-47fc3f3cd920"
                },
                "isDefault": true,
                "relationship": "1d7b687b-9477-4892-8e74-f70a41d4d184"
              }
            ]
          },
          {
            "name": "business_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "672aadcb-5015-4a92-8445-4ed6a8be86a8",
            "sourceColumn": "business_duration",
            "summarizeBy": "none"
          },
          {
            "name": "task",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b07ce0e-410a-43fc-92f7-444645761091",
            "sourceColumn": "task",
            "summarizeBy": "none"
          },
          {
            "name": "task_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2083c545-f8a7-4aa1-ac39-15e817a87a41",
            "sourceColumn": "task_type",
            "summarizeBy": "none"
          },
          {
            "name": "stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb2ce324-f85e-41b3-93cd-2762d0442afd",
            "sourceColumn": "stage",
            "summarizeBy": "none"
          },
          {
            "name": "planned_end_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "86ee50bc-166a-4a85-b302-eb108f3209c5",
            "sourceColumn": "planned_end_time",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f62a5b83-858d-4848-8344-86676f7373f3"
                },
                "isDefault": true,
                "relationship": "f7494852-d000-4821-93e2-202157caf5e0"
              }
            ]
          },
          {
            "name": "has_breached",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac081a2c-c6c6-40dc-a607-38d9c25053ad",
            "sourceColumn": "has_breached",
            "summarizeBy": "none"
          },
          {
            "name": "start_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8f2a913b-5de0-4980-b8be-a134d8bc8682",
            "sourceColumn": "start_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e9550141-3ad8-4e0a-9a87-9e8bf6e4ff5c"
                },
                "isDefault": true,
                "relationship": "9799433b-df38-481f-bfed-213500cdcebf"
              }
            ]
          },
          {
            "name": "end_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "084a9edc-155b-402a-8975-10ec1986726d",
            "sourceColumn": "end_date",
            "summarizeBy": "none"
          },
          {
            "name": "loaded_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4b81fe95-14a3-48f0-83ac-40e410978fca",
            "sourceColumn": "loaded_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_47507799-2dd1-4692-a68d-6512e0d54d5d"
                },
                "isDefault": true,
                "relationship": "07c7c27e-dab3-4b9b-b5f6-d5e56251567e"
              }
            ]
          }
        ],
        "lineageTag": "69c09bc6-d8b0-43cd-ba05-46b256b10e80",
        "partitions": [
          {
            "name": "ServiceNow_TaskSLA_Ended",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"USPHL0PRPADBA1\", \"Graham_Workspace\"),",
                "    dbo_ServiceNow_TaskSLA_Ended = Source{[Schema=\"dbo\",Item=\"ServiceNow_TaskSLA_Ended\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_ServiceNow_TaskSLA_Ended,{{\"sys_updated_on\", type datetime}, {\"sys_created_on\", type datetime}, {\"original_breach_time\", type datetime}, {\"end_time\", type datetime}, {\"start_time\", type datetime}, {\"planned_end_time\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_96a8c92d-9228-4b41-bc35-565c9ec6d141",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4367a1d1-42a4-4b42-82e6-5b9aa7c9a71f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1cbdaf09-b2db-40a4-9409-3da2716c74f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "54af2797-3a00-4917-99bc-dbd887c0b50d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c88b06f6-7749-4025-84c4-ab284b82c3ae",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "052eadbb-1057-4da7-976f-8cfc02e195d6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cb6dc90c-f5de-450e-b365-5617cf4afdb9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "93ea917c-81bd-4794-8fb8-d710fafbd446",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "67c52a3a-010f-4e70-8af6-c71723eae264",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "127dc603-f26d-4b41-a386-6903eecfc7d3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "084a2b4d-f687-41a8-be85-537f535de225",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f607c9b7-a376-4ffa-b6a1-364176993491",
                "ordinal": 3
              }
            ],
            "lineageTag": "acfb9279-6793-4850-988a-cd33d7aa127c"
          }
        ],
        "isHidden": true,
        "lineageTag": "90cd8ed6-8a29-4185-9a90-fa3681319c62",
        "partitions": [
          {
            "name": "LocalDateTable_96a8c92d-9228-4b41-bc35-565c9ec6d141",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_TaskSLA_Ended'[sys_updated_on])), 1, 1), Date(Year(MAX('ServiceNow_TaskSLA_Ended'[sys_updated_on])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_04432eee-33a0-4736-bc17-50c2e9efafe3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8835395f-005a-443f-b6eb-6747985cd08e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7d07a6b2-a515-43d5-934c-a84dc6d354cf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "594a704b-903b-4a8a-b604-e27b9a3d610b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e99c365e-67fb-4644-9735-8db813600193",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "44656e66-1aa0-4e56-a40f-5964bce55ea5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "540ee999-5c44-4854-8932-eb782ddeb430",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "57faefb1-4620-4217-a71a-a17ab19c498c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2d94b739-c808-45f9-9c4c-86b6963e7011",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "59cad464-facb-4c61-a8c7-fe4b28e2f74c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9d14760f-c56f-45c7-8915-8238e9b5fab2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "188ce549-c9a0-4ad6-96f6-031daa1b1bf0",
                "ordinal": 3
              }
            ],
            "lineageTag": "b53a11a2-8191-4641-b90d-6973f3cbb29f"
          }
        ],
        "isHidden": true,
        "lineageTag": "ab8c6ae3-3da1-4790-8961-96a946f4520f",
        "partitions": [
          {
            "name": "LocalDateTable_04432eee-33a0-4736-bc17-50c2e9efafe3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_TaskSLA_Ended'[sys_created_on])), 1, 1), Date(Year(MAX('ServiceNow_TaskSLA_Ended'[sys_created_on])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_595d1031-8e5b-4cc9-b880-f1571dba9a92",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bfc3787e-24f5-4504-b162-d1abdf202eec",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "475eb993-8edb-4017-9853-b00d3ea7faa0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4dc17161-f444-4887-a88e-eea6860301f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1d548e61-c081-4a46-82ad-d53466c5e318",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "baa97b18-4a0c-4f98-a2cf-798e8f1410a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "37e415d6-bf21-4c5a-a865-2c6d00a53f40",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "2f662dba-733a-4c4d-804e-ae85b2f0fe98",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c15be8a7-eba4-4e32-a16e-01730dd8485c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "77d377b1-3991-4da1-b9b8-1926469c1da3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "780580c2-8888-427e-85e8-3ca4dbf2a85a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e313a615-8c9f-4937-9d59-b417f496db7d",
                "ordinal": 3
              }
            ],
            "lineageTag": "84219258-9f98-4552-9a3f-01e3a522fe38"
          }
        ],
        "isHidden": true,
        "lineageTag": "feb7a5af-f6bc-4cf5-9952-99c49ac25759",
        "partitions": [
          {
            "name": "LocalDateTable_595d1031-8e5b-4cc9-b880-f1571dba9a92",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_TaskSLA_Ended'[original_breach_time])), 1, 1), Date(Year(MAX('ServiceNow_TaskSLA_Ended'[original_breach_time])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_1ff12552-f399-4f86-8b85-1a3731aa9b5f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c508c055-2859-4d3c-a026-04652e037e45",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "70501e7e-44ff-45a2-88fa-dca2607976a8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "360dc678-6c60-4500-be62-eb4f9f16a556",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6600ba5f-6eca-4b78-b9b3-4b3a723bcfa4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0033275b-c846-4a76-9d60-44bcd84d00db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ddd14c2e-9373-42d7-8bdd-b25148aef553",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "47388a93-aca1-49e1-84c7-c8dd340fda48",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7a3c0134-de92-4dd9-b4aa-c8c7951f8e25",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "67930790-e350-4259-824d-2086028fdd19",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a7c5f0b8-6f5c-428c-9e23-7ff92a92f273",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7963902a-b54b-4513-ab86-1b8c64d6a706",
                "ordinal": 3
              }
            ],
            "lineageTag": "0b5dc248-010c-435b-a0e1-e91359e44256"
          }
        ],
        "isHidden": true,
        "lineageTag": "d8118c87-1500-4e32-b4c8-2c1b0e3a078c",
        "partitions": [
          {
            "name": "LocalDateTable_1ff12552-f399-4f86-8b85-1a3731aa9b5f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_TaskSLA_Ended'[end_time])), 1, 1), Date(Year(MAX('ServiceNow_TaskSLA_Ended'[end_time])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c7f48084-4f56-4408-ace7-47fc3f3cd920",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ee956260-a087-4549-89dd-960650873421",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c7af3433-53a9-4de4-a819-901bb11c7611",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "281f8d53-5a54-408b-8245-f9c50340f31b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b1e710a5-4887-4811-94ec-4f541981075e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "527effb7-da63-462c-b8f5-32e1a44d1c40",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cf8fb678-89c6-4764-bc5c-42c7b6d1179c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "12870b34-4bfa-408f-ac2b-f4db83e10a5f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2032df9e-55cd-4560-ae6f-83be6f400713",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f477c427-9ea0-42a9-a521-00e6317b376d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6ae0461d-05f3-4b62-8c48-b55faf89fff6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "832e21ae-e06c-42a9-ae63-06273aeac97b",
                "ordinal": 3
              }
            ],
            "lineageTag": "6bf5149a-d30d-4d18-80a2-66d25ee35d18"
          }
        ],
        "isHidden": true,
        "lineageTag": "1d83bf16-85ca-4695-bee6-eec93f13f0f0",
        "partitions": [
          {
            "name": "LocalDateTable_c7f48084-4f56-4408-ace7-47fc3f3cd920",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_TaskSLA_Ended'[start_time])), 1, 1), Date(Year(MAX('ServiceNow_TaskSLA_Ended'[start_time])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f62a5b83-858d-4848-8344-86676f7373f3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3afbab44-0266-41ad-959e-cee2eba565a6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "874a4b1c-fde9-4d0e-b387-7cb8fcee5a43",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "71ee617a-df9e-4dc5-8fdd-43360f696ab5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3e28bd6f-085b-498f-a25e-27ed4d225c5b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7843b52f-ec2d-43c1-a93a-79744c38bad5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6a2a37ab-da7f-4c20-a790-6e3456eff5ce",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f4a3d229-f0e1-4943-8370-15c01aeb2e2e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6d6c7d9a-eb5e-4caa-ad0c-f7ababe00b72",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3d4f5c28-b858-4d4d-a143-61bd704becea",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "631fa67d-e352-4afc-af1b-49fb4f958024",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "faa29b23-b8ad-4e65-bc90-3ed91371170d",
                "ordinal": 3
              }
            ],
            "lineageTag": "b204f84f-5973-4911-a0ed-7b4559600776"
          }
        ],
        "isHidden": true,
        "lineageTag": "7a6e2a0c-dd33-4dbe-8764-49deba914b20",
        "partitions": [
          {
            "name": "LocalDateTable_f62a5b83-858d-4848-8344-86676f7373f3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_TaskSLA_Ended'[planned_end_time])), 1, 1), Date(Year(MAX('ServiceNow_TaskSLA_Ended'[planned_end_time])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e9550141-3ad8-4e0a-9a87-9e8bf6e4ff5c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4a4ec008-fd89-4419-9de6-fb3d35e28421",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f147adbb-e3ef-4b6e-aa2d-4b713f96d408",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "85a57337-8177-4c6c-b476-e4258d87b9f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d26ae0a8-6f0f-42af-a236-182591254217",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d0cc801a-7d2a-451a-8aad-95df41bdc463",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e24b6473-c688-4e85-a0fc-f0c9e8f306f6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3104515f-a98b-49af-b9fd-6e3edff11370",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "74545050-992b-4e0a-a8f9-96cbe0425835",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8c09d94c-8e6d-4e07-9b4c-9198991a867b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4812a3e9-0b41-4da9-a271-0e5493947fca",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6658d10a-b504-4a2a-88a5-b07af2cf3ebc",
                "ordinal": 3
              }
            ],
            "lineageTag": "8f0c509c-9d03-4cb0-87fb-26dd792c2d85"
          }
        ],
        "isHidden": true,
        "lineageTag": "af845c6a-fc2b-4300-b2eb-e754bf7f7642",
        "partitions": [
          {
            "name": "LocalDateTable_e9550141-3ad8-4e0a-9a87-9e8bf6e4ff5c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_TaskSLA_Ended'[start_date])), 1, 1), Date(Year(MAX('ServiceNow_TaskSLA_Ended'[start_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_47507799-2dd1-4692-a68d-6512e0d54d5d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "60dd354d-3050-4a09-a044-6c0347759732",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "43b5fdd2-db0a-4544-82cd-9c3f5a171371",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4a53ad58-620a-456a-8352-5bb432cdb3fa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4cf2cd09-2b58-4724-a2fc-86829d086e87",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2b85ca9e-d824-4a3a-9a20-36900c8d82e6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "46bf741c-af10-46d8-b2d3-a7f075174bcc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b34acc4c-4712-4418-9874-a4c1602a5e76",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c9cec711-289e-4827-ad38-bda74cdffdd3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c194eec7-6212-47b2-b199-907fd39f6e07",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "40b2de31-44b0-4cd0-9b93-e587a3461ae9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8692f91f-2a20-4d11-8b56-5f6ebf442486",
                "ordinal": 3
              }
            ],
            "lineageTag": "0fb75203-231f-4db2-945f-e0e524c7d97b"
          }
        ],
        "isHidden": true,
        "lineageTag": "a0778057-aaad-4973-bfc7-4414e9b33738",
        "partitions": [
          {
            "name": "LocalDateTable_47507799-2dd1-4692-a68d-6512e0d54d5d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceNow_TaskSLA_Ended'[loaded_date])), 1, 1), Date(Year(MAX('ServiceNow_TaskSLA_Ended'[loaded_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_24e0f6f7-8920-4fe8-a945-0db3b5d482ba",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a842b8e6-8cd9-4bd7-b313-8335eda3b1ab",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ddc9dfe9-391b-4899-b3c4-6b9316dbe7c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c91e930f-089e-41f7-b390-03d775ee2d4e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9500eb4e-a328-44c6-91c5-dd0dd91b38bc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d94176d1-21be-4a6a-bfd8-e2f98536bed7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6aceaa53-f863-403b-9a15-edeaa6a3d340",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "fef0a81c-1998-46ff-be99-49af099021bd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "113f713f-2d56-46e0-87a1-d98d519f814a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "25842abe-a23a-4185-92a4-b753ea3b780d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d423165e-35e3-4812-aa6d-7df3694d9c05",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "da8f330e-01fc-4d9b-bb1b-f4579994722f",
                "ordinal": 3
              }
            ],
            "lineageTag": "cbf4280b-9e28-4827-90ba-98c630b3cac0"
          }
        ],
        "isHidden": true,
        "lineageTag": "2ab6d2a0-babc-40bc-9dde-c23932f39c4e",
        "partitions": [
          {
            "name": "LocalDateTable_24e0f6f7-8920-4fe8-a945-0db3b5d482ba",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_MonthKey'[Start of week])), 1, 1), Date(Year(MAX('dim_date_fiscal_MonthKey'[Start of week])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}