{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"HR_Metrics\",\"HR_ActiveEmployee_BeginCount\",\"HR_ActiveEmployee\",\"Account_Hierarchy_Linking\",\"Dashboard_Account_Hierarchy\",\"dim_Date\",\"metricData_GBS\",\"metricEmailVolume_CC\",\"metricDuplicateInvoices_AP\",\"metricData_AP\",\"DirectQuery to AS - GBSMetrics_V2.2.1\",\"dim_mor_KpiSortOrder\",\"dim_mor_s&bSortOrder\",\"dim_ProfitCenters_hr_tbls\",\"dim_mor_ProfitCenters\",\"dim_mor_KPIs\",\"fact_mor_Comments-GBS\",\"dim_ac_MetricList\",\"dim_ac_SortList\",\"dim_ac_TeamSort\",\"dim_mor_ccTeams\",\"fact_mor_HeadcountPlan\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "DirectQuery to AS - GBSMetrics_V2.2.1",
        "annotations": [
          {
            "name": "PBI_IncludeFutureArtifacts",
            "value": "True"
          },
          {
            "name": "PBI_RemovedChildren",
            "value": "[{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"8ca937c2-b1f2-4424-ab81-bf9e49a23317\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"4276fdc1-6b51-4d2a-b7e6-911f1d21e6fb\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"caa192b8-4b83-433a-8407-a346b5cc3675\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"a561230e-6b03-4478-8afc-b0c63f0b10d1\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"60a39339-c066-414c-8d32-135eba17d799\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"af514192-d833-44d3-a7d5-8b34eab8abf7\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"a975f8a3-7f65-4116-a7b8-fa1571a0e81c\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"84294d71-859a-4776-afd4-7788f1c82bf1\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"e6d70fe7-51fc-4b4a-9363-20414b8dbb25\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"844d1de2-cf02-4f11-96dd-d4bb6e00586c\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"65820e64-793f-4557-b6bf-77c5bcb66a6f\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"e4ee11fd-702c-463b-a84b-bf3a19380b7d\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"1e6160db-1488-4fff-ac5f-b378e3e8e79d\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"4a37a81c-0931-4707-bd58-098b4710d1e1\"}},\"objectType\":\"Table\"}]"
          }
        ],
        "expression": [
          "let",
          "    Source = AnalysisServices.Database(\"powerbi://api.powerbi.com/v1.0/myorg/GBS%20Metrics\", \"GBSMetrics_V2.2.1\"),",
          "    Cubes = Table.Combine(Source[Data]),",
          "    Cube = Cubes{[Id=\"Model\", Kind=\"Cube\"]}[Data]",
          "in",
          "    Cube"
        ],
        "kind": "m",
        "lineageTag": "51d11c79-6ea9-4a86-8d70-1772cba93981"
      }
    ],
    "relationships": [
      {
        "name": "70da1c4b-c0eb-4b60-bd8d-9f568f0ef144",
        "fromColumn": "AdjustedServiceDate",
        "fromTable": "HR_Metrics",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_35c6a38b-34af-4a62-8b42-24de6c2bae44"
      },
      {
        "name": "65372733-0f8f-4434-870d-ec5ed6ef77f2",
        "fromColumn": "Tx_EventDate",
        "fromTable": "HR_Metrics",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2723ee2f-7827-4b3c-87ec-98ac492ab03d"
      },
      {
        "name": "4334272f-c608-409a-a8c7-ca28fea451b1",
        "fromColumn": "Tx_EndDate",
        "fromTable": "HR_Metrics",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_80933ec3-5ea1-4d0c-9c2e-ad3e6b282ce1"
      },
      {
        "name": "39411978-1ba5-4110-af8d-a5d0d562d7fc",
        "fromColumn": "AdjustedServiceDate",
        "fromTable": "HR_ActiveEmployee_BeginCount",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_70a8b74c-6067-45da-b9cc-40f602e08e63"
      },
      {
        "name": "18b4a8be-2086-496d-ad4c-e3cd170ee9aa",
        "fromColumn": "AdjustedServiceDate",
        "fromTable": "HR_ActiveEmployee",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_82de534e-3204-47f1-a2cb-4298f579053b"
      },
      {
        "name": "be63b63c-4dea-40f6-a564-fd36b9ae824e",
        "fromColumn": "DateID",
        "fromTable": "dim_Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c4fc22ff-ebbe-4a6e-a408-32c5a26b168e"
      },
      {
        "name": "2ab234f7-b894-44fa-af52-1945def0f4b0",
        "fromColumn": "Lvl_2",
        "fromTable": "Account_Hierarchy_Linking",
        "toColumn": "Lvl_2",
        "toTable": "Dashboard_Account_Hierarchy"
      },
      {
        "name": "8684c478-edfc-4ff3-bae3-fbbdaabbb184",
        "fromColumn": "DateID-Mmm",
        "fromTable": "dim_Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1dac8d8a-06c8-441d-ba5d-d42a7a4e2b9c"
      },
      {
        "name": "b06198b0-06a8-40cf-8ff0-b6208f90602b",
        "fromColumn": "DateID",
        "fromTable": "DateKey_TTM",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7b19b701-86ef-44e9-9665-e940f58fb3eb"
      },
      {
        "name": "10645d02-87a1-420c-adb8-03eda3908051",
        "fromColumn": "CalendarID",
        "fromTable": "HR_Metrics",
        "toColumn": "CalendarID",
        "toTable": "dim_Date"
      },
      {
        "name": "ec5d1ac7-447c-4901-ade5-dbc74cfaa277",
        "fromColumn": "CalendarID",
        "fromTable": "HR_ActiveEmployee",
        "toColumn": "CalendarID",
        "toTable": "dim_Date"
      },
      {
        "name": "b065a9b8-bb50-4c99-9102-ea8a287def50",
        "fromColumn": "LoadDate",
        "fromTable": "HR_ActiveEmployee",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7036a8fb-8bd0-421b-b386-95cd900365f9"
      },
      {
        "name": "2a651874-9609-43ee-be44-66006faedccb",
        "fromColumn": "LoadDate",
        "fromTable": "HR_ActiveEmployee_BeginCount",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_699afe88-c003-4400-a522-89941ff6ae1b"
      },
      {
        "name": "53396364-69d8-4ebe-8ba3-8888e89d936d",
        "fromColumn": "CalendarID",
        "fromTable": "HR_ActiveEmployee_BeginCount",
        "toColumn": "CalendarID",
        "toTable": "dim_Date"
      },
      {
        "name": "f4d066d2-aafe-4e7b-9652-459bd5863c9e",
        "fromColumn": "PeriodID",
        "fromTable": "metricData_GBS",
        "toColumn": "PeriodID",
        "toTable": "dim_Date"
      },
      {
        "name": "c1e8e295-4a06-4272-8d6c-df757257282b",
        "fromColumn": "DateID",
        "fromTable": "metricData_GBS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_16744950-94c0-4703-ba7a-a062cf6fadd2"
      },
      {
        "name": "a8a56556-fd9a-43dc-8c5a-8c3725dab1fb",
        "fromColumn": "DateID",
        "fromTable": "metricEmailVolume_CC",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e22548d0-4ed9-4c99-9040-b992316b46c3"
      },
      {
        "name": "9eaa1a67-9ccc-4fad-8ccf-8e36048518f7",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "PeriodID",
        "fromTable": "metricEmailVolume_CC",
        "toColumn": "PeriodID",
        "toTable": "dim_Date"
      },
      {
        "name": "a150d6c1-573e-475f-826b-08fac43915a2",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "PeriodID",
        "fromTable": "metricDuplicateInvoices_AP",
        "toColumn": "PeriodID",
        "toTable": "dim_Date"
      },
      {
        "name": "519ddaf5-2c3a-4494-9063-6e4f29caa4d5",
        "fromColumn": "DateID",
        "fromTable": "metricData_AP",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ab6b19d9-8dcd-426c-9c07-cbcc889ba4e5"
      },
      {
        "name": "45230dee-4f25-4a5a-987e-cd2f1268d760",
        "fromColumn": "PeriodID",
        "fromTable": "metricData_AP",
        "toColumn": "PeriodID",
        "toTable": "dim_Date"
      },
      {
        "name": "3f4893b4-2b8d-4d4b-b61e-20005fc61756",
        "fromColumn": "DateID",
        "fromTable": "metricDuplicateInvoices_AP",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_02f597d7-8fd6-415a-8ffe-05149d46ed5f"
      },
      {
        "name": "91c5414f-aa87-4230-b190-fbc112014fd8",
        "fromColumn": "CREATE_DATE",
        "fromTable": "UFR GL_L2_SUMMARY_F (EDWRPRD)",
        "toColumn": "Date",
        "toTable": "LocalDateTable_cf36d641-663a-4643-b10b-9305a2dbabe0"
      },
      {
        "name": "c78822be-df0d-480e-b5c2-3d57f4af86e5",
        "fromColumn": "ACCOUNT_KEY",
        "fromTable": "UFR GL_L2_SUMMARY_F (EDWRPRD)",
        "securityFilteringBehavior": "none",
        "toColumn": "LVL1",
        "toTable": "Account_Hierarchy_Linking"
      },
      {
        "name": "2b0dd531-758c-42c3-a238-c627b1b3d475",
        "fromColumn": "Fiscal Period",
        "fromTable": "UFR GL_L2_SUMMARY_F (EDWRPRD)",
        "securityFilteringBehavior": "none",
        "toColumn": "Mmm_FY-YY",
        "toTable": "dim_Date"
      },
      {
        "name": "0d240eaf-ea36-4b7b-bdba-85abb9bb2100",
        "fromColumn": "ProfitCenterCode",
        "fromTable": "HR_ActiveEmployee",
        "toColumn": "ProfitCenter Code",
        "toTable": "dim_ProfitCenters_hr_tbls"
      },
      {
        "name": "dc18373c-b00c-4bf0-9f4e-caa8f35a9e1a",
        "fromColumn": "ProfitCenterCode",
        "fromTable": "HR_ActiveEmployee_BeginCount",
        "toColumn": "ProfitCenter Code",
        "toTable": "dim_ProfitCenters_hr_tbls"
      },
      {
        "name": "b733598e-fa18-4a34-a2a8-08d77d525ced",
        "fromColumn": "ProfitCenterCode",
        "fromTable": "HR_Metrics",
        "toColumn": "ProfitCenter Code",
        "toTable": "dim_ProfitCenters_hr_tbls"
      },
      {
        "name": "59ced300-dbd0-49cf-917f-4342bfdc9c69",
        "fromColumn": "ORG_VALUE",
        "fromTable": "UFR GL_L2_SUMMARY_F (EDWRPRD)",
        "securityFilteringBehavior": "none",
        "toColumn": "ProfitCenter Code",
        "toTable": "dim_ProfitCenters_hr_tbls"
      },
      {
        "name": "43f5dee6-357e-46fa-b2c0-40e2adec3570",
        "fromColumn": "Dept",
        "fromTable": "metricData_GBS",
        "toCardinality": "many",
        "toColumn": "Department-Name",
        "toTable": "dim_mor_ProfitCenters"
      },
      {
        "name": "5b96e5c8-ccfe-4881-87cf-1a92525235b7",
        "fromColumn": "Dept",
        "fromTable": "metricData_AP",
        "toCardinality": "many",
        "toColumn": "Department-Name",
        "toTable": "dim_mor_ProfitCenters"
      },
      {
        "name": "f95bf71a-8f42-4a04-b0d6-2d1a99322879",
        "fromColumn": "Department",
        "fromTable": "fact_mor_Comments-GBS",
        "toCardinality": "many",
        "toColumn": "Department-Name",
        "toTable": "dim_mor_ProfitCenters"
      },
      {
        "name": "d3ee0cad-8b11-40b1-a7c7-87b884913202",
        "fromColumn": "Kpi-Name",
        "fromTable": "dim_mor_KPIs",
        "toColumn": "Kpi-Name",
        "toTable": "dim_mor_KpiSortOrder"
      },
      {
        "name": "73a3f8d6-b02f-437f-91b3-b493d4561544",
        "fromColumn": "Kpi-Name",
        "fromTable": "metricData_GBS",
        "toCardinality": "many",
        "toColumn": "Kpi-Name",
        "toTable": "dim_mor_KPIs"
      },
      {
        "name": "5efe0b0d-636f-4d6c-a4b9-d90ecb43acb7",
        "fromColumn": "Kpi-Name",
        "fromTable": "metricData_AP",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "Kpi-Name",
        "toTable": "dim_mor_KPIs"
      },
      {
        "name": "6bbe8d81-70a3-4cac-ab21-d440e8232fdb",
        "fromColumn": "Org",
        "fromTable": "dim_ProfitCenters_hr_tbls",
        "toColumn": "Department-Name",
        "toTable": "dim_mor_s&bSortOrder"
      },
      {
        "name": "3721d7bf-4658-4af2-ab67-c3e9dbc8a8de",
        "fromColumn": "AC-Metric-Name",
        "fromTable": "dim_ac_MetricList",
        "toColumn": "AC-Metric-Name",
        "toTable": "dim_ac_SortList"
      },
      {
        "name": "fe6fddff-0ee0-4849-aeec-e54eab271958",
        "fromColumn": "Team",
        "fromTable": "dim_ac_MetricList",
        "toColumn": "Team",
        "toTable": "dim_ac_TeamSort"
      },
      {
        "name": "0874b20a-2f5c-4bf0-924e-952e072edfa0",
        "fromColumn": "Kpi-Name",
        "fromTable": "metricData_GBS",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "Kpi-Name",
        "toTable": "dim_ac_MetricList"
      },
      {
        "name": "bd7a96ed-ec42-4e42-a8ef-5f3fdcb39e93",
        "fromColumn": "Fiscal-Period",
        "fromTable": "fact_mor_Comments-GBS",
        "toColumn": "Month FY-YY",
        "toTable": "dim_Date"
      },
      {
        "name": "cb7fc850-d361-4e88-bb31-8562822d05b9",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Department-Name",
        "fromTable": "dim_mor_ccTeams",
        "toCardinality": "many",
        "toColumn": "Dept",
        "toTable": "metricEmailVolume_CC"
      },
      {
        "name": "8430eada-e7ee-4ba3-937f-9dc9d840336b",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Kpi-ID",
        "fromTable": "dim_ac_MetricList",
        "toColumn": "Kpi-ID",
        "toTable": "dim_mor_KPIs"
      },
      {
        "name": "7873c1d6-3256-4b7c-8b30-9739a5b71824",
        "fromColumn": "ProfitCenter Code",
        "fromTable": "fact_mor_HeadcountPlan",
        "toColumn": "ProfitCenter Code",
        "toTable": "dim_ProfitCenters_hr_tbls"
      },
      {
        "name": "4eed2dd8-366d-423d-8654-1247437cf9c6",
        "fromColumn": "PeriodID",
        "fromTable": "fact_mor_HeadcountPlan",
        "toColumn": "PeriodID",
        "toTable": "dim_Date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_fbbb093b-b0f1-4762-9ae6-e321b080224a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "87911110-24fa-41b2-a64c-e36ebb6a3ab3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "24caf06d-a1c0-446c-82db-d952c8f4380a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8c7f6d51-75e5-429f-9805-2a79ed4d28c4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "62058c97-75c1-4834-bb58-626fd4ba299f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "444cc002-b4a3-465e-8b5e-892375ef8576",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "559cf52a-7172-401c-8399-5d25a5a087fa",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1909645e-79d7-4dc1-9e6c-207a7d5bbedf",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4f278ebc-9693-4636-bf24-1cf4fbcad3ec",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e2d7088e-95fd-43a4-a62e-cd823dedc668",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "21b22c85-4be8-4673-9486-e03ea3353354",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "10ca0c4c-e579-421c-90ff-315a181db62e",
                "ordinal": 3
              }
            ],
            "lineageTag": "82bc94e0-c47a-46f3-a9b0-7c1306d250d3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "38313f9f-d682-473a-bf32-946e8ba752d3",
        "partitions": [
          {
            "name": "DateTableTemplate_fbbb093b-b0f1-4762-9ae6-e321b080224a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "HR_Metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "762c34d3-8b02-497a-8dcf-d120af0e9fb6",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "735ac696-7cad-4c70-a142-8d720bdc553f",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "count"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f4f1030-178d-4c1b-a5c9-9cc82ab9e7e2",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "MiddleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "366af5b0-03fc-4dfc-8deb-391ab882dc96",
            "sourceColumn": "MiddleName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4d6ea96-7b17-429a-a26b-078f00fbaa55",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "AdjustedServiceDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1bef54c7-a8a4-4a2f-9a38-005df0f1735d",
            "sourceColumn": "AdjustedServiceDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_35c6a38b-34af-4a62-8b42-24de6c2bae44"
                },
                "isDefault": true,
                "relationship": "70da1c4b-c0eb-4b60-bd8d-9f568f0ef144"
              }
            ]
          },
          {
            "name": "EmployeeStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "107f6d4c-8286-45da-ad06-d4e1a2ad2b70",
            "sourceColumn": "EmployeeStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42052f97-3404-41ac-b022-6ab3b04eaf78",
            "sourceColumn": "ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "183c768c-11ca-40aa-a10b-1fe099491ae4",
            "sourceColumn": "ProfitCenterCode",
            "summarizeBy": "none"
          },
          {
            "name": "Tx_Event",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc793bcb-a926-45d7-948a-3da2c9b3128c",
            "sourceColumn": "Tx_Event",
            "summarizeBy": "none"
          },
          {
            "name": "Tx_EventDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ec8cca7f-e609-4304-99c1-897fe927c280",
            "sourceColumn": "Tx_EventDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2723ee2f-7827-4b3c-87ec-98ac492ab03d"
                },
                "isDefault": true,
                "relationship": "65372733-0f8f-4434-870d-ec5ed6ef77f2"
              }
            ]
          },
          {
            "name": "Tx_EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fa49d525-db0d-463c-a812-fbbeb2924fec",
            "sourceColumn": "Tx_EndDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_80933ec3-5ea1-4d0c-9c2e-ad3e6b282ce1"
                },
                "isDefault": true,
                "relationship": "4334272f-c608-409a-a8c7-ca28fea451b1"
              }
            ]
          },
          {
            "name": "ActualEvent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aae41269-22bf-45f8-9f6f-7055829e5007",
            "sourceColumn": "ActualEvent",
            "summarizeBy": "none"
          },
          {
            "name": "ReportMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aabc92be-18a0-4a5a-92b9-82e94e1ce29c",
            "sourceColumn": "ReportMonth",
            "summarizeBy": "none"
          },
          {
            "name": "ReportYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e64f59f-93b9-44a2-891e-aebcc97fbbbd",
            "sourceColumn": "ReportYear",
            "summarizeBy": "none"
          },
          {
            "name": "EmployeeName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb11ed1d-ccdf-41ad-bda0-0444bb46b7b6",
            "sourceColumn": "EmployeeName",
            "summarizeBy": "none"
          },
          {
            "name": "BeginCountMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1af9d14e-bc72-42fb-9bc2-c590e5c398b4",
            "sourceColumn": "BeginCountMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b444687d-1205-45fd-bc3d-ce6ed4823bb8",
            "sourceColumn": "CalendarID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c566d87d-8047-40af-9c16-e42f3b492551",
        "measures": [
          {
            "name": "ReplaceBlank",
            "expression": [
              "",
              "",
              "VAR Distcount = CALCULATE ( DISTINCTCOUNT(HR_Metrics[EmployeeID] ))",
              "",
              "RETURN",
              "    IF ( ISBLANK(Distcount) = TRUE(),0,Distcount)"
            ],
            "formatString": "0",
            "lineageTag": "53f6c3c3-12be-475c-b928-e327e354e9cc"
          }
        ],
        "partitions": [
          {
            "name": "HR_Metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"USPHL0PRPADBA1\"),",
                "    GBS_Metrics = Source{[Name=\"GBS_Metrics\"]}[Data],",
                "    dbo_HR_Metrics = GBS_Metrics{[Schema=\"dbo\",Item=\"HR_Metrics\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_HR_Metrics,{{\"ReportYear\", type text}, {\"ReportMonth\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"PeriodID\", each [ReportYear] & [ReportMonth]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"PeriodID\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"PeriodID\", \"CalendarID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_35c6a38b-34af-4a62-8b42-24de6c2bae44",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "63b9ae3f-7917-4adc-927b-cd7069095757",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e3772f7e-cb1c-4c4e-9793-281b7d6d254d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4c38f3ab-d07a-46b7-a290-4cdb890d2df2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e421431b-e80e-4e9d-bd79-9e6dacf0d268",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b26fcbf4-1bd8-412c-8bb3-fa33c3ec448f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8ac6fb38-2f67-40db-b59a-ba98c9aed1a4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "694cc824-4eac-48f7-9963-4108043439b4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c0a9ae28-0223-4202-befd-225e18843b89",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "58f53597-2cb5-4043-a41e-c503ee66f1da",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1c6bf42e-e853-4ae2-a721-defff779df36",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "682c3b86-340d-40f8-a8f0-a3b9de9c5d51",
                "ordinal": 3
              }
            ],
            "lineageTag": "3e7e3606-8ca6-4d8d-a58f-5b4de5ffc562"
          }
        ],
        "isHidden": true,
        "lineageTag": "3a0bb1c6-b948-4fd7-aca7-859c159a3ae8",
        "partitions": [
          {
            "name": "LocalDateTable_35c6a38b-34af-4a62-8b42-24de6c2bae44",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('HR_Metrics'[AdjustedServiceDate])), 1, 1), Date(Year(MAX('HR_Metrics'[AdjustedServiceDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2723ee2f-7827-4b3c-87ec-98ac492ab03d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "deea8e6f-4dde-4089-8229-87ed90f58e57",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "208436e3-8ba6-4b71-8cb1-7c1ea0f7913c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8f7be7a5-08e4-45ee-9002-a6d25a9ed80f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "27539402-187f-4d8f-911a-cd010ca2c615",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c325a476-0512-4f3f-9681-b8c69054d339",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "81cd93c1-0abe-470b-b31d-42e2e9c57437",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "31d90c0a-b1f5-422c-b2d9-d3385ce9ca40",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c49cbab8-8846-4219-9ad1-06ac2965490e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c5c1f975-3608-4c65-82df-78ee21cee908",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6ad1df06-6f2e-4d0c-86fa-32c8a115e874",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b07abdb2-4a3d-4643-939b-9d2ba5340e43",
                "ordinal": 3
              }
            ],
            "lineageTag": "a3333a62-ebb6-4dbc-801e-63081ef38146"
          }
        ],
        "isHidden": true,
        "lineageTag": "e438b264-15e3-4cfd-995c-bb3265c7cd75",
        "partitions": [
          {
            "name": "LocalDateTable_2723ee2f-7827-4b3c-87ec-98ac492ab03d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('HR_Metrics'[Tx_EventDate])), 1, 1), Date(Year(MAX('HR_Metrics'[Tx_EventDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_80933ec3-5ea1-4d0c-9c2e-ad3e6b282ce1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5f99ff15-6dd1-48a2-8368-849556915d4d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9aee7815-c9d9-42e2-871c-f3d297c72257",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d488441c-ad0e-4673-8c9f-9b4841fed594",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2a25cd15-350f-408e-830d-12f14d617637",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0f3f8e2b-d97a-483a-81bd-52ba0af44acc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a3f3bb15-811b-4d23-9739-c473e96afef8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fe0a49cb-50a8-4d3c-85cd-5f00ed3c0d21",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "71374851-e2b2-4d8f-9d17-c77b01c690d6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9943039a-8be0-4bc5-927d-53bd3f0f1e37",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ce396125-af1e-4c73-9a0b-6e364ba709e4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "cf6d8428-6100-4a46-a103-ca80f4ac2e64",
                "ordinal": 3
              }
            ],
            "lineageTag": "c9dd9473-d2ba-4295-859e-9cbfce5b133f"
          }
        ],
        "isHidden": true,
        "lineageTag": "965c40bb-2df6-4537-9ff6-d9e2e4106f1e",
        "partitions": [
          {
            "name": "LocalDateTable_80933ec3-5ea1-4d0c-9c2e-ad3e6b282ce1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('HR_Metrics'[Tx_EndDate])), 1, 1), Date(Year(MAX('HR_Metrics'[Tx_EndDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "HR_ActiveEmployee_BeginCount",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "81683afa-3432-4dae-a2ca-dfcd57115378",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c0207e8-0a4e-432c-ad75-5fec4a93fae0",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "count"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce1ce2be-51c8-46ff-97dc-06c3cc7db3e7",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "MiddleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82fb5cb9-d3bb-4782-a261-8e24dad42afc",
            "sourceColumn": "MiddleName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07b21e5e-1b54-4fa5-9964-5745994093c1",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "AdjustedServiceDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "43431a8d-299b-4740-953a-ff408b975817",
            "sourceColumn": "AdjustedServiceDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_70a8b74c-6067-45da-b9cc-40f602e08e63"
                },
                "isDefault": true,
                "relationship": "39411978-1ba5-4110-af8d-a5d0d562d7fc"
              }
            ]
          },
          {
            "name": "EmployeeStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3447418-8993-4a8d-9eca-9d689067d539",
            "sourceColumn": "EmployeeStatus",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "606e546a-ed57-4263-919c-8df239c2c738",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "LineofBusiness",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5457313-725a-462b-9169-b8be3da1dc6e",
            "sourceColumn": "LineofBusiness",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f77493b5-c917-4b5c-8a77-55466a54c061",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "DistrictCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81c95dc9-351f-4f1d-8223-487cfada53ac",
            "sourceColumn": "DistrictCode",
            "summarizeBy": "none"
          },
          {
            "name": "District",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16da1675-2256-4eef-a25c-26161c1cab05",
            "sourceColumn": "District",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "291ac388-6a47-49a8-a634-148f9ca5358c",
            "sourceColumn": "ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33af7757-5301-48b2-93a8-859024b06bc2",
            "sourceColumn": "ProfitCenterCode",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "793fee18-597b-4a02-83da-6404ba9cc471",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "236e8605-6f37-4e3a-bf3b-877be2546edc",
            "sourceColumn": "MonthNo",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "505de4ed-3445-433b-aca1-1706dde7c8ac",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "ActualEvent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffa181ff-d829-46a7-b7b0-92adebb653b0",
            "sourceColumn": "ActualEvent",
            "summarizeBy": "none"
          },
          {
            "name": "BeginCountMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efd76503-5979-4bd5-be91-bdbfbf282c1d",
            "sourceColumn": "BeginCountMonth",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentCountMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b09d042-c717-4479-b302-372942aa3cb0",
            "sourceColumn": "CurrentCountMonth",
            "summarizeBy": "none"
          },
          {
            "name": "LoadDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "76fb12a5-61d4-45f8-bafe-a9df7ddbef45",
            "sourceColumn": "LoadDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_699afe88-c003-4400-a522-89941ff6ae1b"
                },
                "isDefault": true,
                "relationship": "2a651874-9609-43ee-be44-66006faedccb"
              }
            ]
          },
          {
            "name": "CalendarID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee3f1fa5-c888-45ef-ac5f-7820846d3231",
            "sourceColumn": "CalendarID",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "HR_ActiveEmployee_BeginCount[FirstName] & \" \" & HR_ActiveEmployee_BeginCount[LastName]",
            "isDataTypeInferred": true,
            "lineageTag": "1e4f4122-8cec-4f42-8e70-79f5e1cb30cc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "d59d9039-f44a-4508-9967-89e67611482a",
        "measures": [
          {
            "name": "ReplaceBlank (Starting)",
            "expression": [
              "",
              "",
              "VAR BeginCOUNT = CALCULATE ( COUNT(HR_ActiveEmployee_BeginCount[BeginCountMonth] ))",
              "",
              "RETURN",
              "    IF ( ISBLANK(BeginCOUNT) = TRUE(),0,BeginCOUNT)"
            ],
            "formatString": "0",
            "lineageTag": "27b83d3b-05fc-45c2-baf2-5c3a4623a5b2"
          }
        ],
        "partitions": [
          {
            "name": "HR_ActiveEmployee_BeginCount",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"USPHL0PRPADBA1\"),",
                "    GBS_Metrics = Source{[Name=\"GBS_Metrics\"]}[Data],",
                "    dbo_HR_ActiveEmployee_BeginCount = GBS_Metrics{[Schema=\"dbo\",Item=\"HR_ActiveEmployee_BeginCount\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_HR_ActiveEmployee_BeginCount,{{\"MonthNo\", type text}, {\"Year\", type text}, {\"BeginCountMonth\", type text}, {\"CurrentCountMonth\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"CalendarID\", each [Year] & [BeginCountMonth])",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_70a8b74c-6067-45da-b9cc-40f602e08e63",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2aaa20bf-fd7d-4bd4-a5b0-b3eefb8a49f4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e5d7bffc-fbab-4f92-99ba-b7a97b8469d0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8312d01d-f705-4185-babd-25b5ec7b56c3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "66fbdf9f-e779-4bcf-a45d-680291689eb5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e0fa4af6-62cb-435e-a97e-3dc23f269d3b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2706113b-b795-4eb5-b210-cd4791fe9364",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "beaccc60-417a-4ef3-aa43-21c712cf636a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5bdd5349-673e-4290-867f-59961aa80df2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "62de305e-7169-4fba-a4f1-8f31d7faac37",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "85adbb63-61a6-42ac-be02-6fac57e7c577",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5f24c592-47ac-4f98-9757-ebc8c1033aa4",
                "ordinal": 3
              }
            ],
            "lineageTag": "9e7f3842-cebc-461b-a4e3-f429181cde10"
          }
        ],
        "isHidden": true,
        "lineageTag": "50b0844c-8465-4cd5-9e3e-68db72a13c2d",
        "partitions": [
          {
            "name": "LocalDateTable_70a8b74c-6067-45da-b9cc-40f602e08e63",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('HR_ActiveEmployee_BeginCount'[AdjustedServiceDate])), 1, 1), Date(Year(MAX('HR_ActiveEmployee_BeginCount'[AdjustedServiceDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "HR_ActiveEmployee",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7780390c-ff51-4e4d-8279-3bad0e1d84ed",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "82593124-261e-4111-86d3-7ecb6e867f19",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "count"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6bd5de5-7893-42e8-89a1-acd47911f0ac",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "MiddleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ae68098-d418-4a5f-a459-19b04d2c669b",
            "sourceColumn": "MiddleName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a16525eb-30b0-4f8e-8c06-a973c663c6f8",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "AdjustedServiceDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "96e60e2f-1b98-43d0-b08c-21007fc9f0bd",
            "sourceColumn": "AdjustedServiceDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_82de534e-3204-47f1-a2cb-4298f579053b"
                },
                "isDefault": true,
                "relationship": "18b4a8be-2086-496d-ad4c-e3cd170ee9aa"
              }
            ]
          },
          {
            "name": "EmployeeStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "518b4246-3737-48ec-9eaf-ef046f8e883a",
            "sourceColumn": "EmployeeStatus",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42a2c82f-f4be-4f5f-9061-3ff2cf5140f4",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "LineofBusiness",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6973fd85-b5be-4b4c-849f-27cf15f4646d",
            "sourceColumn": "LineofBusiness",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5adcff2a-71e4-4a05-a7a9-c8cb3455b1ff",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "DistrictCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54924a98-b571-4f49-9b76-c2ee456f3d72",
            "sourceColumn": "DistrictCode",
            "summarizeBy": "none"
          },
          {
            "name": "District",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "354fe061-2462-402d-ad30-888f5f70c022",
            "sourceColumn": "District",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "befb815d-8223-45d8-b8f7-2a18c066d23e",
            "sourceColumn": "ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e24d0d3-139d-48a0-8c21-450428c60774",
            "sourceColumn": "ProfitCenterCode",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdca7a71-a9ba-49f2-a5aa-8c154df9d96c",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad4389e1-2ee5-4e63-8154-774731620d0a",
            "sourceColumn": "MonthNo",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b25a27fc-4d25-458b-8a05-997d6d6e68a5",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "ActualEvent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "564cff85-2bbd-49bb-9081-d4167b58ed94",
            "sourceColumn": "ActualEvent",
            "summarizeBy": "none"
          },
          {
            "name": "BeginCountMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c614cbb1-5a37-4871-8ac7-6dcbaf06f33b",
            "sourceColumn": "BeginCountMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "CurrentCountMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "20ebb6b8-5eda-4f60-8025-6f22a6696a96",
            "sourceColumn": "CurrentCountMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "LoadDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c212d87b-4f1e-4d12-bf58-24c4ba7b2280",
            "sourceColumn": "LoadDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7036a8fb-8bd0-421b-b386-95cd900365f9"
                },
                "isDefault": true,
                "relationship": "b065a9b8-bb50-4c99-9102-ea8a287def50"
              }
            ]
          },
          {
            "name": "CalendarID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b16faa7-d184-4cb2-8fc0-fd173aa1032c",
            "sourceColumn": "CalendarID",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "HR_ActiveEmployee[FirstName] & \" \" & HR_ActiveEmployee[LastName]",
            "isDataTypeInferred": true,
            "lineageTag": "7afd582e-ee1d-4e34-a526-fd5cc1a4bde6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "3f9b520e-fd0c-4a04-a828-fc3a71cfa5f0",
        "measures": [
          {
            "name": "ReplaceBlank (Current)",
            "expression": [
              "",
              "",
              "VAR CurrentCount = CALCULATE ( COUNT (HR_ActiveEmployee[CurrentCountMonth] ))",
              "",
              "RETURN",
              "    IF ( ISBLANK(CurrentCount) = TRUE(),0,CurrentCount)"
            ],
            "formatString": "0",
            "lineageTag": "92cb5a40-3b34-4121-87a8-b6f0058498aa"
          }
        ],
        "partitions": [
          {
            "name": "HR_ActiveEmployee",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"USPHL0PRPADBA1\"),",
                "    GBS_Metrics = Source{[Name=\"GBS_Metrics\"]}[Data],",
                "    dbo_HR_ActiveEmployee = GBS_Metrics{[Schema=\"dbo\",Item=\"HR_ActiveEmployee\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_HR_ActiveEmployee,{{\"MonthNo\", type text}, {\"Year\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"CalendarID\", each [Year] & [MonthNo]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"CalendarID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_82de534e-3204-47f1-a2cb-4298f579053b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f5a8189b-75eb-445f-bed1-ab309af12cca",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8d06564e-100f-4d61-82f1-da598c881781",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7a7c1f5e-507b-41a5-a051-f25efdc8f934",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "563095b7-7fdb-4b58-9903-d783be1259f3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b6b9477b-8ee7-40b1-aef5-2dddc470adb2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a44b5db2-a1db-46b0-9036-5f40bbdbcda8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "60c30aab-1ad5-435e-bc2c-e3c434b3b9f5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5e6e964e-064f-41eb-b5ab-ef3f32d32a72",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e6ba6f9d-0cbd-47a5-ae64-91dcbb04e164",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8d6848bd-2e90-4c39-90cb-db1208e1278b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "35b7f8c0-53d9-4720-82ee-d3a2287d79a3",
                "ordinal": 3
              }
            ],
            "lineageTag": "dff7e4bc-cc63-4898-b47a-a57bb31f519c"
          }
        ],
        "isHidden": true,
        "lineageTag": "b4f076c2-5614-45f6-ab7e-7a48bdb37366",
        "partitions": [
          {
            "name": "LocalDateTable_82de534e-3204-47f1-a2cb-4298f579053b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('HR_ActiveEmployee'[AdjustedServiceDate])), 1, 1), Date(Year(MAX('HR_ActiveEmployee'[AdjustedServiceDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Account_Hierarchy_Linking",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LVL1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f4c13a0-cb3f-41b7-ae71-87524a54c29c",
            "sourceColumn": "LVL1",
            "summarizeBy": "none"
          },
          {
            "name": "LVL1_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8003769-b21e-449e-b04a-82ea9f381b89",
            "sourceColumn": "LVL1_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "Lvl1_Name_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68082458-e4e4-4365-b080-23f876b3b43c",
            "sourceColumn": "Lvl1_Name_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Lvl_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "140b91e9-8c21-46a0-89a3-8bb47edd8963",
            "sourceColumn": "Lvl_2",
            "summarizeBy": "none"
          },
          {
            "name": "Lvl_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f27e1ebc-7f62-4808-8c55-d443db66b690",
            "sourceColumn": "Lvl_3",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "aebaa71b-865d-48cb-b3bf-5bb3b5272089",
        "partitions": [
          {
            "name": "Account_Hierarchy_Linking",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4169f96c-3615-44a9-b663-2a44c9927df8\" = Workspaces{[workspaceId=\"4169f96c-3615-44a9-b663-2a44c9927df8\"]}[Data],",
                "    #\"5a515e39-9d14-42ea-acb4-adaa48f362a6\" = #\"4169f96c-3615-44a9-b663-2a44c9927df8\"{[dataflowId=\"5a515e39-9d14-42ea-acb4-adaa48f362a6\"]}[Data],",
                "    Account_Hierarchy_Linking_ = #\"5a515e39-9d14-42ea-acb4-adaa48f362a6\"{[entity=\"Account_Hierarchy_Linking\",version=\"\"]}[Data]",
                "in",
                "    Account_Hierarchy_Linking_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dashboard_Account_Hierarchy",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sort_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7908afc8-9049-4cd0-b601-23ce72610f45",
            "sourceColumn": "Sort_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Lvl_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "af0e1161-6c08-482c-94e2-5d161c76bb73",
            "sortByColumn": "Sort_ID",
            "sourceColumn": "Lvl_2",
            "summarizeBy": "none"
          },
          {
            "name": "Lvl_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94e65a26-3da8-47a7-ac54-ba13d7d06c3f",
            "sourceColumn": "Lvl_3",
            "summarizeBy": "none"
          },
          {
            "name": "Lvl_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3deb8025-8d21-4ddb-8f87-0fd3cc6422e2",
            "sourceColumn": "Lvl_4",
            "summarizeBy": "none"
          },
          {
            "name": "Lvl_5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7efe734f-bfc6-46ee-80db-aa7cc8be8087",
            "sourceColumn": "Lvl_5",
            "summarizeBy": "none"
          },
          {
            "name": "Account_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87055611-87a2-42d2-90e0-c68c494ca3d5",
            "sourceColumn": "Account_Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6bb89d3d-a33c-4beb-b15e-4dfeedc1a0fc",
        "partitions": [
          {
            "name": "Dashboard_Account_Hierarchy",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4169f96c-3615-44a9-b663-2a44c9927df8\" = Workspaces{[workspaceId=\"4169f96c-3615-44a9-b663-2a44c9927df8\"]}[Data],",
                "    #\"5a515e39-9d14-42ea-acb4-adaa48f362a6\" = #\"4169f96c-3615-44a9-b663-2a44c9927df8\"{[dataflowId=\"5a515e39-9d14-42ea-acb4-adaa48f362a6\"]}[Data],",
                "    Dashboard_Account_Hierarchy_ = #\"5a515e39-9d14-42ea-acb4-adaa48f362a6\"{[entity=\"Dashboard_Account_Hierarchy\",version=\"\"]}[Data]",
                "in",
                "    Dashboard_Account_Hierarchy_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "b5341085-dd36-4692-9dca-0970e6b9469a",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c4fc22ff-ebbe-4a6e-a408-32c5a26b168e"
                },
                "isDefault": true,
                "relationship": "be63b63c-4dea-40f6-a564-fd36b9ae824e"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ffc26a5-9103-4162-9076-214aa6aa4c45",
            "sortByColumn": "DateID",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "583b9d29-15d6-47d3-a99e-c4586db10a38",
            "sortByColumn": "DateID",
            "sourceColumn": "StartDate",
            "summarizeBy": "none"
          },
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd0a906e-8ef3-43c7-8a46-e5d9ab9ebd71",
            "sortByColumn": "DateID",
            "sourceColumn": "EndDate",
            "summarizeBy": "none"
          },
          {
            "name": "Month name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e008a90-86e5-4d14-9db6-97a64161681f",
            "sourceColumn": "Month name",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6994eacc-3788-4b4e-aae8-2a4f84c0c13a",
            "sourceColumn": "Fiscal Period",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f0032d0-98ab-4450-b4a3-2d927684eef2",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c34f203-0470-4b5c-84db-38de6980bd43",
            "sourceColumn": "FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Mmm_FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a61ba2a-a72f-441e-8060-fd347cac92a7",
            "sortByColumn": "DateID",
            "sourceColumn": "Mmm_FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "DateID-Mmm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Mmm",
            "lineageTag": "f0a668f5-35e3-43f1-b533-d8e3b074517b",
            "sortByColumn": "DateID",
            "sourceColumn": "DateID-Mmm",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1dac8d8a-06c8-441d-ba5d-d42a7a4e2b9c"
                },
                "isDefault": true,
                "relationship": "8684c478-edfc-4ff3-bae3-fbbdaabbb184"
              }
            ]
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d3e7fd8-b2e3-47ea-98ea-ec375f7a47fd",
            "sortByColumn": "DateID",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6aa852f8-2f34-4fbe-bff1-6c94e0f10264",
            "sourceColumn": "Calendar Month",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a0f85c6-064a-498f-b65c-8e170e59f570",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f126161-476e-4f5c-8fdb-fa109158dc07",
            "sortByColumn": "DateID",
            "sourceColumn": "CalendarID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ebe95eeb-676e-411d-b7c7-9d846d77fe02",
        "partitions": [
          {
            "name": "dim_Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4169f96c-3615-44a9-b663-2a44c9927df8\" = Workspaces{[workspaceId=\"4169f96c-3615-44a9-b663-2a44c9927df8\"]}[Data],",
                "    #\"51917be9-2c04-4aec-ab16-811902d1b7ed\" = #\"4169f96c-3615-44a9-b663-2a44c9927df8\"{[dataflowId=\"51917be9-2c04-4aec-ab16-811902d1b7ed\"]}[Data],",
                "    dim_Date_ = #\"51917be9-2c04-4aec-ab16-811902d1b7ed\"{[entity=\"dim_Date\",version=\"\"]}[Data],",
                "    #\"Inserted Month\" = Table.AddColumn(dim_Date_, \"Month\", each Date.Month([DateID]), Int64.Type),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Inserted Month\", \"Year\", each Date.Year([DateID]), Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Year\",{{\"Month\", \"Calendar Month\"}, {\"Year\", \"Calendar Year\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Calendar Month\", type text}, {\"Calendar Year\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type1\", \"CalendarID\", each [Fiscal Year] & [Calendar Month]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"CalendarID\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c4fc22ff-ebbe-4a6e-a408-32c5a26b168e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c989194c-4553-46cd-b12e-981ebd30e55e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b0a97b4c-f7bb-40d9-a7db-9019910ab9f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e91ea6a6-17c2-47bb-8a5c-42968a8d0b31",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7c818be8-cb52-4105-b31f-4ce73ee609bb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "45e5f1bd-3b80-4c97-bec2-ce167e4b879b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "325b9e73-dd7c-41e0-a605-884290319d8e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0be2ffa6-51e1-4d96-abe3-6552b1074050",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "babb4a0a-dff6-450e-a6f6-b89670978f19",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3af923bb-3bb2-4f18-9e07-2de49422b4ca",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3bc7a057-a3bd-4310-9671-fce126293c9b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d08ab68a-2db1-4875-a601-baea8d75bdae",
                "ordinal": 3
              }
            ],
            "lineageTag": "6c387e5e-a4e7-436f-bcbb-e189578159bb"
          }
        ],
        "isHidden": true,
        "lineageTag": "079f65a2-1c98-4c39-aeb4-f9b231065ed3",
        "partitions": [
          {
            "name": "LocalDateTable_c4fc22ff-ebbe-4a6e-a408-32c5a26b168e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_Date'[DateID])), 1, 1), Date(Year(MAX('dim_Date'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "metricData_GBS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dept",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f764228-13d0-4207-9db5-eb9b4c21be63",
            "sourceColumn": "Dept",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82b523bf-2b48-4a9c-83d5-0ec32c57e625",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1acbb3c6-e068-4ef7-8f0e-6fc2cd8368b3",
            "sourceColumn": "Kpi-Name",
            "summarizeBy": "none"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "11333bd1-6210-45ea-92ce-ca36a76225a2",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_16744950-94c0-4703-ba7a-a062cf6fadd2"
                },
                "isDefault": true,
                "relationship": "c1e8e295-4a06-4272-8d6c-df757257282b"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e3806d3-b2fa-4eae-ad59-cc128f3e5ea2",
            "sortByColumn": "DateID",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "29f604e6-b86e-41b8-a9ca-64220d671fc3",
            "sourceColumn": "Goal",
            "summarizeBy": "sum"
          },
          {
            "name": "mor-Numerator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8874a730-0a6f-420d-b2db-5850f71b70f2",
            "sourceColumn": "mor-Numerator",
            "summarizeBy": "sum"
          },
          {
            "name": "mor-TotalQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56ce56b6-d897-429e-9cf8-ddffbfd70ee3",
            "sourceColumn": "mor-TotalQty",
            "summarizeBy": "sum"
          },
          {
            "name": "Kpi-Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f6e2dc05-2479-4410-907a-337dbff17846",
            "sourceColumn": "Kpi-Total",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "552ec7f9-43b6-4303-92ee-5eba03315d1a",
        "partitions": [
          {
            "name": "metricData_GBS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4169f96c-3615-44a9-b663-2a44c9927df8\" = Workspaces{[workspaceId=\"4169f96c-3615-44a9-b663-2a44c9927df8\"]}[Data],",
                "    #\"51917be9-2c04-4aec-ab16-811902d1b7ed\" = #\"4169f96c-3615-44a9-b663-2a44c9927df8\"{[dataflowId=\"51917be9-2c04-4aec-ab16-811902d1b7ed\"]}[Data],",
                "    metricData_GBS_ = #\"51917be9-2c04-4aec-ab16-811902d1b7ed\"{[entity=\"metricData_GBS\",version=\"\"]}[Data]",
                "in",
                "    metricData_GBS_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_1dac8d8a-06c8-441d-ba5d-d42a7a4e2b9c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9b4878ae-fb24-42bb-81dc-56972e40002b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e79b2929-d338-4c1b-a28f-7624ea0763c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "73db713d-cb34-4686-991f-435baf20c9b0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "76098e1b-c1d0-49cf-881f-2db502376c95",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c9174345-71a7-4c4c-a164-ffcae32441fd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "540490d4-72d2-46e7-bc24-63098737c5b0",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "41ca7e36-ae28-4103-b6a5-eb1b3b13911a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cf034716-a1cc-4c50-b3cf-5ecb5d054ccf",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9654c985-1808-4e14-9d8a-9d5484a1ee7e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ec6f22fa-9504-4336-b1ad-cec910f02824",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e694a8fd-fe79-428b-baa3-b62bdeb2d13a",
                "ordinal": 3
              }
            ],
            "lineageTag": "84581e19-23cb-4e03-ae56-a99622ca0201"
          }
        ],
        "isHidden": true,
        "lineageTag": "ad1ce85e-149e-48ba-bd53-94a2a498e9da",
        "partitions": [
          {
            "name": "LocalDateTable_1dac8d8a-06c8-441d-ba5d-d42a7a4e2b9c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_Date'[DateID-Mmm])), 1, 1), Date(Year(MAX('dim_Date'[DateID-Mmm])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": ".Measures",
        "calculationGroup": {},
        "columns": [
          {
            "name": "Name",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "76618d25-aaea-4c6b-b134-089248eac895",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "eca40a09-6b2a-4132-9a6e-055093147b35",
            "sourceColumn": "Ordinal"
          }
        ],
        "lineageTag": "8c2f4ad0-a580-4c6e-9380-f7a9ca31b15d",
        "measures": [
          {
            "name": "Actual",
            "displayFolder": "Budget",
            "expression": "SUM ( 'UFR GL_L2_SUMMARY_F (EDWRPRD)'[PTD_ACTUAL] )",
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "2ec916c5-3d0a-4992-b07e-e713b236e05a"
          },
          {
            "name": "Plan",
            "displayFolder": "Budget",
            "expression": "SUM ( 'UFR GL_L2_SUMMARY_F (EDWRPRD)'[PTD_BUDGET] ) ",
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "4187808f-dced-4609-87d1-13db915b88be"
          },
          {
            "name": "Prior Year",
            "displayFolder": "Budget",
            "expression": "SUM ( 'UFR GL_L2_SUMMARY_F (EDWRPRD)'[PY_PTD_ACTUAL] ) ",
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "2319b572-6b63-442f-b5dd-4edcfd929ab7"
          },
          {
            "name": "Actual (YTD)",
            "displayFolder": "Budget",
            "expression": "SUM ( 'UFR GL_L2_SUMMARY_F (EDWRPRD)'[YTD_ACTUAL] ) ",
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "c897b590-3874-4f96-ac99-e1848ff4b281"
          },
          {
            "name": "Plan (YTD)",
            "displayFolder": "Budget",
            "expression": "SUM ( 'UFR GL_L2_SUMMARY_F (EDWRPRD)'[YTD_BUDGET] ) ",
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "dd469210-1371-40e5-bdfd-c54a2c4530b6"
          },
          {
            "name": "Prior Year (YTD)",
            "displayFolder": "Budget",
            "expression": "SUM ( 'UFR GL_L2_SUMMARY_F (EDWRPRD)'[PY_YTD_ACTUAL] ) ",
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "d6f21698-860a-4e9b-b90d-beb537c6c28f"
          },
          {
            "name": "Actual vs Plan",
            "displayFolder": "Budget",
            "expression": [
              "",
              "    [Actual] - [Plan]"
            ],
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "c349038e-b2f1-4dec-8d55-f5abf9571347"
          },
          {
            "name": "Actual vs Prior Year",
            "displayFolder": "Budget",
            "expression": [
              "",
              "    [Actual] - [Prior Year]"
            ],
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "c6e33c8f-97b2-418e-a2c7-c0ae241930f5"
          },
          {
            "name": "Actual (YTD) vs Plan (YTD)",
            "displayFolder": "Budget",
            "expression": [
              "",
              "    [Actual (YTD)] - [Plan (YTD)]"
            ],
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "1be070dc-33a3-4134-a9b6-5595ee2e8243"
          },
          {
            "name": "Actual (YTD) vs Prior Year (YTD)",
            "displayFolder": "Budget",
            "expression": [
              "",
              "    [Actual (YTD)] - [Prior Year (YTD)]"
            ],
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            },
            "lineageTag": "67a8c20f-e8eb-4159-ab42-e397155a5b41"
          },
          {
            "name": "Goal (GBS)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (GBS)",
            "expression": "SELECTEDVALUE ( metricData_GBS[Goal] ) ",
            "lineageTag": "9290d7ee-45f9-437e-9a6f-4d8bcf161fcf"
          },
          {
            "name": "mor-Numerator (GBS)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (GBS)",
            "expression": "SUM ( metricData_GBS[mor-Numerator] ) ",
            "lineageTag": "fc553d14-7588-4580-8777-bf7b6f6dd6ed"
          },
          {
            "name": "mor-TotalQty (GBS)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (GBS)",
            "expression": "SUM ( metricData_GBS[mor-TotalQty] ) ",
            "lineageTag": "6fdfe83a-9d5d-455b-b8bb-ecbd2b442478"
          },
          {
            "name": "KPI (GBS)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (GBS)",
            "expression": [
              "",
              "    [mor-Numerator (GBS)] / [mor-TotalQty (GBS)]"
            ],
            "lineageTag": "9fce7ba4-313d-4e04-b7c0-daa2967ec264"
          },
          {
            "name": "LOA End - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "    COALESCE( COUNTROWS( FILTER( HR_Metrics, HR_Metrics[ActualEvent] = \"LOA End\" ) ), 0 )"
            ],
            "formatString": "0",
            "lineageTag": "1bfa0fa6-4ef5-4d0d-b070-bc0f05e002b1"
          },
          {
            "name": "LOA Start - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "    COALESCE( COUNTROWS( FILTER( HR_Metrics, HR_Metrics[ActualEvent] = \"LOA Start\" ) ), 0 )"
            ],
            "formatString": "0",
            "lineageTag": "f64f704e-9175-4816-abd9-c5e6ed9ecb68"
          },
          {
            "name": "New Hires - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "    COALESCE( COUNTROWS( FILTER( HR_Metrics, HR_Metrics[ActualEvent] = \"New Hire\" ) ), 0 )"
            ],
            "formatString": "0",
            "lineageTag": "24c4cbcb-cb16-49cd-8fcd-8a2d6355f88e"
          },
          {
            "name": "Termination - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "    COALESCE( COUNTROWS( FILTER( HR_Metrics, HR_Metrics[ActualEvent] = \"Termination\" ) ), 0 )"
            ],
            "formatString": "0",
            "lineageTag": "4152c0e6-c258-4552-a617-47a384caa327"
          },
          {
            "name": "Transfer In - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "    COALESCE( COUNTROWS( FILTER( HR_Metrics, HR_Metrics[ActualEvent] = \"Transfer In\" ) ), 0 )"
            ],
            "formatString": "0",
            "lineageTag": "40db977c-6148-4987-93ef-2de8f3bd5538"
          },
          {
            "name": "Transfer Out - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "    COALESCE( COUNTROWS( FILTER( HR_Metrics, HR_Metrics[ActualEvent] = \"Transfer Out\" ) ), 0 )"
            ],
            "formatString": "0",
            "lineageTag": "47b34f8c-2d19-47d3-9dc3-d05b6d47549a"
          },
          {
            "name": "Goal - ComboTTM (GBS)",
            "displayFolder": ".ComboTTM (GBS)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Goal (GBS)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Goal (GBS)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Goal (GBS)] * 86400, ",
              "        [Goal (GBS)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Invoice Entry\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Banking\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Setup\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Vendor Control\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Audit Recovery Rate\", ",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "eb187035-fd6b-45bc-b9ce-9e1f71596e5f"
          },
          {
            "name": "KPI - ComboTTM (GBS)",
            "displayFolder": ".ComboTTM (GBS)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [KPI (GBS)] * 86400, ",
              "        [KPI (GBS)] ))),",
              "            FILTER (",
              "                'dim_Date',",
              "                'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                    && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Invoice Entry\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Banking\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Setup\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Vendor Control\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Audit Recovery Rate\", ",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.0%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.0%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "5c8f0e88-f377-40e8-b0da-f9ba1a904ef6"
          },
          {
            "name": "Qty - ComboTTM (GBS)",
            "displayFolder": ".ComboTTM (GBS)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF (",
              "            _KpiSelect = \"Unapplied Cash\",",
              "            [mor-TotalQty (GBS)],",
              "            IF (",
              "                _KpiSelect = \"CIP Balance\",",
              "                [mor-TotalQty (GBS)],",
              "                IF ( ",
              "                    _KpiSelect = \"CIP Balance (Stale)\", ",
              "                    [mor-TotalQty (GBS)], ",
              "                    IF ( ",
              "                        _KpiSelect = \"Audit Recovery Rate\", ",
              "                        [mor-TotalQty (GBS)], ",
              "                        IF ( ",
              "                            _KpiSelect = \"Duplicate Invoices\", ",
              "                            [mor-TotalQty (GBS)], ",
              "                            [mor-TotalQty (GBS)] * 1000 ",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        ),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"$0.0 M\",",
                "        IF (",
                "            KpiSelection = \"CIP Balance\",",
                "            \"$0.0 M\",",
                "            IF ( KpiSelection = \"CIP Balance (Stale)\", \"$0.0 M\", \"#,0\" )",
                "        )",
                "    )",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "418f0325-c159-4726-ba58-1a8e253f642e"
          },
          {
            "name": "DeptName (Lvl 1)",
            "displayFolder": "Misc",
            "expression": [
              "",
              "    SELECTEDVALUE( GBS_Department_Hierarchy[Level 1] )"
            ],
            "lineageTag": "33c99659-f578-4bf1-b90f-0436a05b842f"
          },
          {
            "name": "DeptName (Lvl 2)",
            "displayFolder": "Misc",
            "expression": [
              "",
              "    SELECTEDVALUE( GBS_Department_Hierarchy[Level 2] )"
            ],
            "lineageTag": "20cb778b-a12b-4308-9fdd-4e761dd712d5"
          },
          {
            "name": "ColWidth",
            "displayFolder": "Misc",
            "expression": [
              "\"*********\"",
              "// Adjust desired width by adding/removing \"*\" above (One * = One Character).",
              "// Make sure column \"Auto-size width\" is turned to \"ON\". ",
              "// Drag this measure to the \"Values\" field of the matrix.",
              "// Ensure width is as needed, can add or remove * to change width.",
              "// Change \"Auto-size width\" to \"OFF\".",
              "// Remove this measure from the \"Values\" field.",
              "// Columns will remain same width as when measure applied. ",
              "// If using in TTM visuals, visual will remove extra columns once this measure removed."
            ],
            "lineageTag": "27eaaa07-c47a-4f60-bb9a-709997c81644"
          },
          {
            "name": "KpiName - TitleFormatting",
            "displayFolder": "MIsc",
            "expression": [
              "",
              "    SELECTEDVALUE( 'dim_mor_KPIs'[Kpi-Name] )"
            ],
            "lineageTag": "1a12f0ff-4fca-49a4-9a17-e968883bc3e4"
          },
          {
            "name": "Current Period",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] ) ",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24,  ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _CurrentDate ",
              "        )",
              "    ",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.00\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Current Period], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Current Period], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Current Period], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "461611ac-379f-4c9b-abc8-45b94fce2f5b"
          },
          {
            "name": "Current Period - Background",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Current Period] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                    [Current Period] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#FFC7CE\",",
              "                    \"#FFEB9C\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Current Period] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                [Current Period] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#FFC7CE\",",
              "                \"#FFEB9C\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "d35b3276-1dfd-46fd-8d72-ce52f1910ae3"
          },
          {
            "name": "Current QTD",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtr =",
              "IF ( _FyMonth = 1, _CurrentMonth,",
              "IF ( _FyMonth = 4, _CurrentMonth,",
              "IF ( _FyMonth = 7, _CurrentMonth,",
              "IF ( _FyMonth = 10, _CurrentMonth,",
              "IF ( _FyMonth = 2, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 5, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 8, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 11, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 3, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 6, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 9, _CurrentMonthPlus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthPlus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] >= _FyQtr",
              "                && dim_Date[DateID-Mmm] <= _CurrentDate",
              "        )",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Current QTD], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Current QTD], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Current QTD], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "39209261-3b84-407c-8276-3223d1be484c"
          },
          {
            "name": "Goal-Comparison Matrix (GBS)",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "-- This Measure changes the Goal of Average Answer Time && Abandonment Rate, when Payment Services is the selected Team.",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] ) ",
              "",
              "VAR _kpi =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _dept = ",
              "    SELECTEDVALUE ( metricData_GBS[Dept] )",
              "",
              "VAR _team = ",
              "    SELECTEDVALUE ( metricData_GBS[Team] )",
              "",
              "VAR _goal = [Goal (GBS)]",
              "",
              "",
              "VAR _goalValidate = ",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time - PS\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Abandonment Rate\" ), ",
              "        0.1,",
              "    _goal )))",
              "",
              " ",
              "",
              "VAR _result =",
              "    CALCULATE(",
              "    IF ( _kpi = \"Average Answer Time\", [Goal (GBS)] * 86400 / 60 / 60 / 24,",
              "    IF ( _kpi = \"Average Answer Time - PS\", [Goal (GBS)] * 86400 / 60 / 60 / 24, ",
              "    [Goal (GBS)] )),",
              "                 dim_Date[DateID-Mmm] == _CurrentDate ",
              "    )",
              "",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0%\",",
                "        \"Bank Account Reconciliation - US\", \"0%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0%\",",
                "        \"Incident Resolution - AR\", \"0%\",",
                "        \"Unapplied Cash\", \"0%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.0%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0%\",",
                "        \"CIP Balance\", \"0%\",",
                "        \"CIP Balance (Stale)\", \"0%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0%\",",
                "        \"Audit Recovery Rate\", \"0%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0%\",",
                "        \"Incident Resolution - PR\", \"0%\",",
                "        \"Customer Satisfaction\", \"0%\",",
                "        \"Survey Participation Rate\", \"0%\",",
                "        \"Average Answer Time\", FORMAT( [Goal-Comparison Matrix (GBS)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0%\",",
                "        \"Calls Answered within Service Level\", \"0%\",",
                "        \"Callbacks\", FORMAT( [Goal-Comparison Matrix (GBS)], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Goal-Comparison Matrix (GBS)], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0%\",",
                "        \"Inbound Email Efficiency\", \"0%\")"
              ]
            },
            "lineageTag": "763c0038-5702-4ae0-b195-96b2f8456e45"
          },
          {
            "name": "Prior Period",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _PreviousDate ",
              "            )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Prior Period], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Prior Period], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Prior Period], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "41b058dc-b249-4cf7-ac10-523155cec686"
          },
          {
            "name": "Prior Year (Period)",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _PreviousDate ",
              "            )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Prior Year (Period)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", \"0\",",
                "        \"Average Answer Time - PS\", \"0\",",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "b9619293-e7b0-41bf-b185-c3c2822bef7d"
          },
          {
            "name": "Prior Year (Quarter)",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( 'DateKey_TTM'[DateID] )",
              "",
              "VAR _PriorFiscalMonth =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) + 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) + 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtrStartDate =",
              "IF ( _FyMonth = 1, _PriorFiscalMonth,",
              "IF ( _FyMonth = 4, _PriorFiscalMonth,",
              "IF ( _FyMonth = 7, _PriorFiscalMonth,",
              "IF ( _FyMonth = 10, _PriorFiscalMonth,",
              "IF ( _FyMonth = 2, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 5, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 8, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 11, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 3, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 6, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 9, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 12, _PriorFiscalMonthMinus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtrEndDate =",
              "IF ( _FyMonth = 1, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 4, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 7, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 10, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 2, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 5, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 8, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 11, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 3, _PriorFiscalMonth,",
              "IF ( _FyMonth = 6, _PriorFiscalMonth,",
              "IF ( _FyMonth = 9, _PriorFiscalMonth, ",
              "IF ( _FyMonth = 12, _PriorFiscalMonth ) ) ) ) ) ) ) ) ) ) ) ) ",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            'dim_Date'[DateID-Mmm] >= _FyQtrStartDate",
              "                && 'dim_Date'[DateID-Mmm] <= _FyQtrEndDate",
              "        )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "4f3e3fef-505d-4ec4-a508-7d51fac8912c"
          },
          {
            "name": "Current Period - Font",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Current Period] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                    [Current Period] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#9C0006\",",
              "                    \"#9C6500\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Current Period] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                [Current Period] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#9C0006\",",
              "                \"#9C6500\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "cfe2dfcf-c47a-48a8-8d12-4f852bab363f"
          },
          {
            "name": "Current QTD - Background",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Current QTD] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                    [Current QTD] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#FFC7CE\",",
              "                    \"#FFEB9C\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Current QTD] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                [Current QTD] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#FFC7CE\",",
              "                \"#FFEB9C\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "56da726d-1dc1-41b1-b211-7adbda2d5ff9"
          },
          {
            "name": "Current QTD - Font",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Current QTD] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                    [Current QTD] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#9C0006\",",
              "                    \"#9C6500\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Current QTD] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                [Current QTD] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#9C0006\",",
              "                \"#9C6500\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "ccc820bd-ee8f-4632-b22e-9ffafffee72a"
          },
          {
            "name": "Prior Period - Background",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Prior Period] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                    [Prior Period] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#FFC7CE\",",
              "                    \"#FFEB9C\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Prior Period] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                [Prior Period] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#FFC7CE\",",
              "                \"#FFEB9C\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "d61ef7d1-d617-4342-9940-d84b4bceb598"
          },
          {
            "name": "Prior Period - Font",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Prior Period] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                    [Prior Period] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#9C0006\",",
              "                    \"#9C6500\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Prior Period] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                [Prior Period] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#9C0006\",",
              "                \"#9C6500\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "a5649149-fd53-40f3-969e-559ce38085d3"
          },
          {
            "name": "Prior Year (Period) - Background",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Prior Year (Period)] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                    [Prior Year (Period)] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#FFC7CE\",",
              "                    \"#FFEB9C\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Prior Year (Period)] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                [Prior Year (Period)] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#FFC7CE\",",
              "                \"#FFEB9C\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "02814526-f797-4e86-a516-369232d92243"
          },
          {
            "name": "Prior Year (Period) - Font",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Prior Year (Period)] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                    [Prior Year (Period)] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#9C0006\",",
              "                    \"#9C6500\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Prior Year (Period)] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                [Prior Year (Period)] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#9C0006\",",
              "                \"#9C6500\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "93549848-f62f-4b30-936c-0e9f5a255c91"
          },
          {
            "name": "Prior Year (Quarter) - Background",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Prior Year (Quarter)] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                    [Prior Year (Quarter)] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#FFC7CE\",",
              "                    \"#FFEB9C\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Prior Year (Quarter)] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                [Prior Year (Quarter)] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#FFC7CE\",",
              "                \"#FFEB9C\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "f2ea4274-e613-4973-b9f8-0ecee9a17797"
          },
          {
            "name": "Prior Year (Quarter) - Font",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Prior Year (Quarter)] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                    [Prior Year (Quarter)] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#9C0006\",",
              "                    \"#9C6500\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Prior Year (Quarter)] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#006100\",",
              "                [Prior Year (Quarter)] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#9C0006\",",
              "                \"#9C6500\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "31173641-1376-4eaf-9f46-b4337b7de456"
          },
          {
            "name": "ColWidth1",
            "displayFolder": "Misc",
            "expression": [
              "\"($000,000,000.00)\"",
              "// Adjust desired width by adding/removing \"*\" above (One * = One Character).",
              "// Make sure column \"Auto-size width\" is turned to \"ON\". ",
              "// Drag this measure to the \"Values\" field of the matrix.",
              "// Ensure width is as needed, can add or remove * to change width.",
              "// Change \"Auto-size width\" to \"OFF\".",
              "// Remove this measure from the \"Values\" field.",
              "// Columns will remain same width as when measure applied. ",
              "// If using in TTM visuals, visual will remove extra columns once this measure removed."
            ],
            "lineageTag": "478ad47d-cb98-4c80-8c5d-3fa76cb8de1a"
          },
          {
            "name": "DeptName (Lvl 3)",
            "displayFolder": "Misc",
            "expression": [
              "",
              "    SELECTEDVALUE( GBS_Department_Hierarchy[Level 3] )"
            ],
            "lineageTag": "9473cd72-21cb-48e3-aa62-ce2caa718a1f"
          },
          {
            "name": "mor-Numerator (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (AP)",
            "expression": "SUM ( metricData_AP[mor-Numerator] )",
            "lineageTag": "4485b446-0a8c-414c-a280-57fd98414865"
          },
          {
            "name": "Goal (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (AP)",
            "expression": "SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Goal] ) ",
            "lineageTag": "e53a18c1-3426-4290-8afe-0146849b87b3"
          },
          {
            "name": "Prevented (AP-DupInv)",
            "displayFolder": ".Duplicate Invoices (AP)",
            "expression": "VALUES ( metricDuplicateInvoices_AP[Prevented] )",
            "lineageTag": "06386fd8-47b7-45ec-b3cb-d88148e0bc5b"
          },
          {
            "name": "Recovered (AP-DupInv)",
            "displayFolder": ".Duplicate Invoices (AP)",
            "expression": "SUM ( metricDuplicateInvoices_AP[Recovered] ) ",
            "formatString": "0",
            "lineageTag": "9819773a-86dc-4884-abeb-7984200f1b34"
          },
          {
            "name": "Total-Dollars (AP-DupInv)",
            "displayFolder": ".Duplicate Invoices (AP)",
            "expression": "SUM ( metricDuplicateInvoices_AP[Total-Dollars] )",
            "formatString": "0",
            "lineageTag": "253255d5-c3ca-470e-b1a8-9fc93f1e9d58"
          },
          {
            "name": "Total-Volume (AP-DupInv)",
            "displayFolder": ".Duplicate Invoices (AP)",
            "expression": "SUM ( metricDuplicateInvoices_AP[Total-Volume] )",
            "formatString": "0",
            "lineageTag": "563daf3a-9055-4079-9d35-ae32f32baf64"
          },
          {
            "name": "Labor-Cost (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[Labor Cost] )",
            "lineageTag": "2a02c34e-595c-4f0e-a328-59f2a8d467b4"
          },
          {
            "name": "SNOW-withinSLA (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[SNOW-withinSLA] )",
            "lineageTag": "e1e7f3d2-1afa-45b1-99d2-b591d924af6c"
          },
          {
            "name": "Recovered-Audit (AP)",
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[Recovered-Audit] )",
            "formatString": "0",
            "lineageTag": "b883f05b-f751-46bb-a5e8-1aa89e5bd9cd"
          },
          {
            "name": "marketPRO-Invoices (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[marketPRO-Invoices] )",
            "lineageTag": "ad84350d-7110-449b-b866-e0644fb1db7f"
          },
          {
            "name": "m4a-Invoices (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[M4A-Invoices] )",
            "lineageTag": "c89c9e5c-d0b2-40fb-97b8-736fa5a7a6a0"
          },
          {
            "name": "Manual-Invoices (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[Manual-Invoices] )",
            "lineageTag": "f14b864c-8c50-4abf-bcf9-63a2789caaa4"
          },
          {
            "name": "SNOW-TotalQty (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[SNow-TotalQty] )",
            "lineageTag": "fdab2578-7547-4e96-8213-fd222b9780d4"
          },
          {
            "name": "PaymentsProcessed-TotalQty (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[PaymentsProcessed-Total] )",
            "lineageTag": "d5fc5900-58fe-42b5-bdee-fd5f1dc21b04"
          },
          {
            "name": "Active-VendorSetups (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[Active-Setups] )",
            "lineageTag": "d72bfb5d-5aff-4a8e-a173-fbfad1aabeda"
          },
          {
            "name": "AP_Approvals-VendorSetups (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[AP_Approvals-Setups] )",
            "lineageTag": "4fd82daf-bb09-417c-b8c8-ed02a6c08861"
          },
          {
            "name": "Manual-VendorSetups (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[Manual-Setups] )",
            "lineageTag": "2c729e5a-edd9-4234-a815-a47b8efe8ab9"
          },
          {
            "name": "TotalDollars-Audit (AP)",
            "displayFolder": ".AP Table Measures",
            "expression": "SUM ( metricData_AP[TotalDollars-Audit] )",
            "formatString": "0",
            "lineageTag": "64add105-7343-4eda-9a61-1022ef010c5c"
          },
          {
            "name": "mor-TotalQty (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (AP)",
            "expression": "SUM ( metricData_AP[mor-TotalQty] )",
            "lineageTag": "80880041-2b88-409d-a131-5172684950c1"
          },
          {
            "name": "iCare-Email (CC)",
            "displayFolder": ".Email Volume (CC)",
            "expression": "SUM ( metricEmailVolume_CC[iCare] )",
            "formatString": "0",
            "lineageTag": "74c85d6e-570a-4183-8db5-4fc6b5a5a9f5"
          },
          {
            "name": "MunchMail-Email (CC)",
            "displayFolder": ".Email Volume (CC)",
            "expression": "SUM ( metricEmailVolume_CC[MunchMail] )",
            "formatString": "0",
            "lineageTag": "e22e9f04-c916-4196-a6ca-d34d7fe3cbed"
          },
          {
            "name": "US_Open-Email (CC)",
            "displayFolder": ".Email Volume (CC)",
            "expression": "SUM ( metricEmailVolume_CC[UsOpen] ) ",
            "formatString": "0",
            "lineageTag": "cfca15d4-57c8-4b79-a3db-aa569d8036a0"
          },
          {
            "name": "Spurs-Email (CC)",
            "displayFolder": ".Email Volume (CC)",
            "expression": "SUM ( metricEmailVolume_CC[Spurs] ) ",
            "formatString": "0",
            "lineageTag": "c3ff3766-3225-4649-ae47-0eb533ab0bdf"
          },
          {
            "name": "Sharks-Email (CC)",
            "displayFolder": ".Email Volume (CC)",
            "expression": "SUM ( metricEmailVolume_CC[Sharks] )",
            "formatString": "0",
            "lineageTag": "dbfc5519-1b06-415b-9342-9b7414a48a10"
          },
          {
            "name": "ContactUs-Email (CC)",
            "displayFolder": ".Email Volume (CC)",
            "expression": "SUM ( metricEmailVolume_CC[ContactUs] )",
            "formatString": "0",
            "lineageTag": "51c98a77-f2a5-439c-9fe5-23c118e44b06"
          },
          {
            "name": "Facilities-Email (CC)",
            "displayFolder": ".Email Volume (CC)",
            "expression": "SUM ( metricEmailVolume_CC[Facilities] ) ",
            "formatString": "0",
            "lineageTag": "23742c34-e0b1-41b2-ac27-f32c98b412f2"
          },
          {
            "name": "TotalVolume-Email (CC)",
            "displayFolder": ".Email Volume (CC)",
            "expression": "SUM ( metricEmailVolume_CC[Total-Volume] )",
            "formatString": "0",
            "lineageTag": "cf9aed08-e92f-4956-8c7c-ab23efde62b2"
          },
          {
            "name": "ServiceNow-KPI (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (AP)",
            "expression": [
              "",
              "    [SNOW-withinSLA (AP)] / [SNOW-TotalQty (AP)]"
            ],
            "lineageTag": "5e443450-ae13-4af0-aaf0-e2621f458570"
          },
          {
            "name": "SNOW-KPI - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [ServiceNow-KPI (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [ServiceNow-KPI (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [ServiceNow-KPI (AP)] * 86400, ",
              "        [ServiceNow-KPI (AP)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_KpiList'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Invoice Entry\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Banking\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Setup\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Vendor Control\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Audit Recovery Rate\", ",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0#%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.00%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.00%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "c2291697-3c67-4d17-89fb-076df93881cd"
          },
          {
            "name": "CostPer-KPI (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (AP)",
            "expression": [
              "",
              "    [Labor-Cost (AP)] / [mor-TotalQty (AP)]"
            ],
            "lineageTag": "2aaae909-62d1-4fa7-80b5-712c41e7b587"
          },
          {
            "name": "AuditRecovery-KPI (AP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (AP)",
            "expression": [
              "",
              "    [Recovered (AP-DupInv)] / [Total-Dollars (AP-DupInv)]"
            ],
            "lineageTag": "1f5e2b09-6645-41de-89dd-e910fd2c65bd"
          },
          {
            "name": "CostPer-KPI - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [CostPer-KPI (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [CostPer-KPI (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [CostPer-KPI (AP)] * 86400, ",
              "        [CostPer-KPI (AP)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_KpiList'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Invoice Entry\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Banking\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Setup\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Vendor Control\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Audit Recovery Rate\", ",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0#%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.00%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.00%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "0c35eeb0-8f15-408b-a63d-7e7fd9fe6365"
          },
          {
            "name": "AuditRecovery-KPI - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [AuditRecovery-KPI (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [AuditRecovery-KPI (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [AuditRecovery-KPI (AP)] * 86400, ",
              "        [AuditRecovery-KPI (AP)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_KpiList'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Invoice Entry\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Banking\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Setup\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Vendor Control\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Audit Recovery Rate\", ",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0#%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.00%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.00%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "c982e0ca-974d-477a-ab8d-f816a3415c72"
          },
          {
            "name": "Prevented-DupInv - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Prevented (AP-DupInv)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Prevented (AP-DupInv)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Prevented (AP-DupInv)] * 86400, ",
              "        [Prevented (AP-DupInv)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$0.0\""
            },
            "lineageTag": "0e8ab550-b7d5-46ff-8954-939ade9a2aba"
          },
          {
            "name": "Recovered-DupInv - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Recovered (AP-DupInv)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Recovered (AP-DupInv)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Recovered (AP-DupInv)] * 86400, ",
              "        [Recovered (AP-DupInv)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$0.0\" "
            },
            "lineageTag": "92e49c81-0ec9-46b9-809a-634654af4c3d"
          },
          {
            "name": "TotalDollars-DupInv - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Total-Dollars (AP-DupInv)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Total-Dollars (AP-DupInv)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Total-Dollars (AP-DupInv)] * 86400, ",
              "        [Total-Dollars (AP-DupInv)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0 M\""
            },
            "lineageTag": "bc7b2171-e6ce-44fa-b47e-f94308ab9c55"
          },
          {
            "name": "TotalVolume-DupInv - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricDuplicateInvoices_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Total-Volume (AP-DupInv)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Total-Volume (AP-DupInv)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Total-Volume (AP-DupInv)] * 86400, ",
              "        [Total-Volume (AP-DupInv)] * 1000))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "88effa31-7161-4f1e-a678-87b1bc47a84e"
          },
          {
            "name": "Qty - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        [mor-TotalQty (AP)] * 1000,",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate",
              "        ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_KpiList'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"$0.0 M\",",
                "        IF (",
                "            KpiSelection = \"CIP Balance\",",
                "            \"$0.0 M\",",
                "            IF ( KpiSelection = \"CIP Balance (Stale)\", \"$0.0 M\", \"0,0\" )",
                "        )",
                "    )",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "42ba7942-c556-4245-a2c6-f141430b7eab"
          },
          {
            "name": "Goal - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    SELECTEDVALUE ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Goal (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Goal (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Goal (AP)] * 86400, ",
              "        [Goal (AP)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_KpiList'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Invoice Entry\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Banking\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Setup\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Vendor Control\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Audit Recovery Rate\", ",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                " RETURN",
                "     KpiFormat"
              ]
            },
            "lineageTag": "71cb2091-099e-45ce-af16-9ed258263de3"
          },
          {
            "name": "ColWidth2",
            "displayFolder": "Misc",
            "expression": [
              "\"0000.00%\"",
              "// Adjust desired width by adding/removing \"*\" above (One * = One Character).",
              "// Make sure column \"Auto-size width\" is turned to \"ON\". ",
              "// Drag this measure to the \"Values\" field of the matrix.",
              "// Ensure width is as needed, can add or remove * to change width.",
              "// Change \"Auto-size width\" to \"OFF\".",
              "// Remove this measure from the \"Values\" field.",
              "// Columns will remain same width as when measure applied. ",
              "// If using in TTM visuals, visual will remove extra columns once this measure removed."
            ],
            "lineageTag": "50ef2cf2-2fe5-4670-aa74-29d63fa039aa"
          },
          {
            "name": "marketPRO-Invoices - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [marketPRO-Invoices (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [marketPRO-Invoices (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [marketPRO-Invoices (AP)] * 86400, ",
              "        [marketPRO-Invoices (AP)] * 1000 ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "bf45d0cd-d374-4de0-b17c-c1ece3453347"
          },
          {
            "name": "Manual-Invoices - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Manual-Invoices (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Manual-Invoices (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Manual-Invoices (AP)] * 86400, ",
              "        [Manual-Invoices (AP)] * 1000))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "d7a7818e-9944-44f7-a7e6-9957909d5d39"
          },
          {
            "name": "m4a-Invoices - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [m4a-Invoices (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [m4a-Invoices (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [m4a-Invoices (AP)] * 86400, ",
              "        [m4a-Invoices (AP)] * 1000))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "e0b108d3-dada-431b-8875-358f47abda7d"
          },
          {
            "name": "Manual-VendorSetups - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Manual-VendorSetups (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Manual-VendorSetups (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Manual-VendorSetups (AP)] * 86400, ",
              "        [Manual-VendorSetups (AP)] * 1000))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "bb6723f5-639c-4925-aab7-24fe3fb0084d"
          },
          {
            "name": "AP_Approvals-VendorSetups - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [AP_Approvals-VendorSetups (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [AP_Approvals-VendorSetups (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [AP_Approvals-VendorSetups (AP)] * 86400, ",
              "        [AP_Approvals-VendorSetups (AP)] * 1000))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "1c6282b0-7cb3-4480-ba37-6b81dd10efe2"
          },
          {
            "name": "Active-VendorSetups - ComboTTM (AP)",
            "displayFolder": ".ComboTTM (AP)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_AP[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Active-VendorSetups (AP)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Active-VendorSetups (AP)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Active-VendorSetups (AP)] * 86400, ",
              "        [Active-VendorSetups (AP)] * 1000))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "7629d55a-bd82-43de-8571-c635d11568ec"
          },
          {
            "name": "KPI2_PS/BSS-TEST_ - ComboTTM (GBS)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".NOODLES",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _TeamSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Team] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [KPI (GBS)] * 86400, ",
              "        [KPI (GBS)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "lineageTag": "7512eef5-ade4-4a33-b9c0-3436fc242100"
          },
          {
            "name": "Goal-Comparison Matrix1 (GBS)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".NOODLES",
            "expression": [
              "",
              "",
              "-- This Measure changes the Goal of Average Answer Time && Abandonment Rate, when Payment Services is the selected Team.",
              "",
              "VAR _kpi =",
              "    SELECTEDVALUE ( 'dim_KpiList'[Kpi-Name] )",
              "",
              "VAR _dept = ",
              "    SELECTEDVALUE ( metricData_GBS[Dept] )",
              "",
              "VAR _team = ",
              "    SELECTEDVALUE ( metricData_GBS[Team] )",
              "",
              "VAR _goal = [Goal (GBS)]",
              "",
              "",
              "VAR _result =",
              "    IF ( _kpi = \"Average Answer Time\", _goal * 86400, ",
              "    IF ( _kpi = \"Average Answer Time - PS\", _goal * 86400, ",
              "    _goal ))",
              "",
              "",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "775ae4dd-7d24-4510-9577-78c6eddadfa8"
          },
          {
            "name": "Current Period1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".NOODLES",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] ) ",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400,  ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _CurrentDate ",
              "        )",
              "    ",
              "RETURN",
              "    _Result"
            ],
            "lineageTag": "1e56bd3e-cdca-410b-9e7b-263127d685c7"
          },
          {
            "name": "ContactUs - ComboTTM (CC_EmailVolume)",
            "displayFolder": ".ComboTTM (CC_EmailVolume)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        [ContactUs-Email (CC)] , ",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate",
              "        ) ) ",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "2e1dab49-0b6f-412a-a060-7adfa8ef15a4"
          },
          {
            "name": "iCare - ComboTTM (CC_EmailVolume)",
            "displayFolder": ".ComboTTM (CC_EmailVolume)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        [iCare-Email (CC)] , ",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate",
              "        ) ) ",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "61b4293e-adef-43c6-aed6-a6862619c5e8"
          },
          {
            "name": "Facilities - ComboTTM (CC_EmailVolume)",
            "displayFolder": ".ComboTTM (CC_EmailVolume)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Facilities-Email (CC)] , ",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate",
              "        ) ) ",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "950e5e17-ccc2-430d-9062-cbb1f8738106"
          },
          {
            "name": "MunchMail - ComboTTM (CC_EmailVolume)",
            "displayFolder": ".ComboTTM (CC_EmailVolume)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        [MunchMail-Email (CC)] , ",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate",
              "        ) ) ",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "6d11c14b-c93c-4c5e-8869-1affffeba1ac"
          },
          {
            "name": "Sharks - ComboTTM (CC_EmailVolume)",
            "displayFolder": ".ComboTTM (CC_EmailVolume)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Sharks-Email (CC)] , ",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate",
              "        ) ) ",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "1713443a-e52f-4a64-8a24-b5d2fc1ee02d"
          },
          {
            "name": "Spurs - ComboTTM (CC_EmailVolume)",
            "displayFolder": ".ComboTTM (CC_EmailVolume)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Spurs-Email (CC)] , ",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate",
              "        ) ) ",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "0fd33aa0-c3d0-4b95-b93f-f33dc56ab63c"
          },
          {
            "name": "US Open - ComboTTM (CC_EmailVolume)",
            "displayFolder": ".ComboTTM (CC_EmailVolume)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        [US_Open-Email (CC)] , ",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate",
              "        ) ) ",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "cc16e3a2-922a-4257-a8ef-2244edfebd33"
          },
          {
            "name": "KPI - ComboTTM_Matrix (CC)",
            "displayFolder": ".MatrixTTM (CC)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Callbacks\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ))),",
              "            FILTER (",
              "                'dim_Date',",
              "                'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                    && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [KPI - ComboTTM_Matrix (CC)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [KPI - ComboTTM_Matrix (CC)], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [KPI - ComboTTM_Matrix (CC)], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "a01c9e98-3291-4873-9d5c-94f67b2d5033"
          },
          {
            "name": "KPI2 - ComboTTM_Matrix (CC)",
            "displayFolder": ".NOODLES",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400, ",
              "        IF ( _KpiSelect = \"Callbacks\", [KPI (GBS)] * 86400, ",
              "        [KPI (GBS)] ))),",
              "            FILTER (",
              "                'dim_Date',",
              "                'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                    && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_KpiList'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Invoice Entry\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Banking\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Setup\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - Vendor Control\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Audit Recovery Rate\", ",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.0%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.0%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.0%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "f64c1b7a-c453-4953-b3b8-a5a2228162e5"
          },
          {
            "name": "Goal-Comparison Matrix (CC)",
            "displayFolder": ".KPI Comparison Matrix (GBS)",
            "expression": [
              "",
              "",
              "-- This Measure changes the Goal of Average Answer Time && Abandonment Rate, when Payment Services is the selected Team.",
              "",
              "VAR _kpi =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _dept = ",
              "    SELECTEDVALUE ( metricData_GBS[Dept] )",
              "",
              "VAR _team = ",
              "    SELECTEDVALUE ( metricData_GBS[Team] )",
              "",
              "VAR _goal = [Goal (CC)]",
              "",
              "",
              "VAR _goalValidate = ",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time - PS\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Abandonment Rate\" ), ",
              "        0.1,",
              "    _goal )))",
              "",
              "",
              "VAR _result =",
              "    IF ( _kpi = \"Average Answer Time\", _goalValidate * 86400 / 60 / 60 / 24, ",
              "    IF ( _kpi = \"Average Answer Time - PS\", _goalValidate * 86400 / 60 / 60 / 24, ",
              "    _goalValidate ))",
              "",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0%\",",
                "        \"Bank Account Reconciliation - US\", \"0%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0%\",",
                "        \"Incident Resolution - AR\", \"0%\",",
                "        \"Unapplied Cash\", \"0%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0%\",",
                "        \"CIP Balance\", \"0%\",",
                "        \"CIP Balance (Stale)\", \"0%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0%\",",
                "        \"Audit Recovery Rate\", \"0%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0%\",",
                "        \"Incident Resolution - PR\", \"0%\",",
                "        \"Customer Satisfaction\", \"0%\",",
                "        \"Survey Participation Rate\", \"0%\",",
                "        \"Average Answer Time\", FORMAT( [Goal-Comparison Matrix (CC)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0%\",",
                "        \"Calls Answered within Service Level\", \"0%\",",
                "        \"Callbacks\", FORMAT( [Goal-Comparison Matrix (CC)], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Goal-Comparison Matrix (CC)], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0%\",",
                "        \"Inbound Email Efficiency\", \"0%\")"
              ]
            },
            "lineageTag": "2e9988e4-b61c-4ba7-81ed-b0d11fad0da1"
          },
          {
            "name": "Goal (CC)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".Base Measures (CC)",
            "expression": "SELECTEDVALUE ( metricData_GBS[Goal] ) ",
            "lineageTag": "72db42d2-64b8-48c6-8e23-75c4703ba07a"
          },
          {
            "name": "Goal - ComboTTM (CC)",
            "displayFolder": ".MatrixTTM (CC)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Goal (CC)] * 86400 / 60 / 60 / 24,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Goal (CC)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Goal (CC)] * 86400 / 60 / 60 / 24, ",
              "        [Goal (CC)] ))),",
              "        FILTER (",
              "            'dim_Date',",
              "            'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0%\",",
                "        \"Bank Account Reconciliation - US\", \"0%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0%\",",
                "        \"Incident Resolution - AR\", \"0%\",",
                "        \"Unapplied Cash\", \"0%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0%\",",
                "        \"CIP Balance\", \"0%\",",
                "        \"CIP Balance (Stale)\", \"0%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0%\",",
                "        \"Audit Recovery Rate\", \"0%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0%\",",
                "        \"Incident Resolution - PR\", \"0%\",",
                "        \"Customer Satisfaction\", \"0%\",",
                "        \"Survey Participation Rate\", \"0%\",",
                "        \"Average Answer Time\", FORMAT( [Goal - ComboTTM (CC)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0%\",",
                "        \"Calls Answered within Service Level\", \"0%\",",
                "        \"Callbacks\", FORMAT( [Goal - ComboTTM (CC)], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Goal - ComboTTM (CC)], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0%\",",
                "        \"Inbound Email Efficiency\", \"0%\")"
              ]
            },
            "lineageTag": "d8a16a0f-f30d-4574-aeac-7aa4a98c91df"
          },
          {
            "name": "KPI1 - ComboTTM_Matrix (CC)",
            "displayFolder": ".MatrixTTM (CC)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( dim_KpiList[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Callbacks\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ))),",
              "            FILTER (",
              "                'dim_Date',",
              "                'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                    && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_KpiList'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        FORMAT( [KPI1 - ComboTTM_Matrix (CC)] / 100 , \"Percent\" ) ,",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        FORMAT( [KPI1 - ComboTTM_Matrix (CC)] , \"0.0%\" ) ,",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        FORMAT( [KPI1 - ComboTTM_Matrix (CC)] , \"nn:ss\" )",
                "--    IF (",
                "--        KpiSelection = \"Abandonment Rate\",",
                "--        \"0.0%\",",
                "--    IF (",
                "--        KpiSelection = \"Calls Answered within Service Level\",",
                "--        \"0.0%\",",
                "--    IF (",
                "--        KpiSelection = \"Callbacks\",",
                "--        \"0\",",
                "--    IF (",
                "--        KpiSelection = \"Average Answer Time - PS\",",
                "--        \"0\",",
                "--    IF (",
                "--        KpiSelection = \"Abandonment Rate - PS\",",
                "--       \"0.0%\",",
                "--    IF ( ",
                "--        KpiSelection = \"Inbound Email Efficiency\", ",
                "--        \"0.0%\" )",
                ")))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "6437d995-d16d-4ca5-ac3f-617378679896"
          },
          {
            "name": "Goal1 - ComboTTM_Matrix (CC)",
            "displayFolder": ".MatrixTTM (CC)",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _KpiSelect = ",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [Goal (CC)] * 86400 / 60 / 60 / 24,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [Goal (CC)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Callbacks\", [Goal (CC)] * 86400 / 60 / 60 / 24, ",
              "        [Goal (CC)] ))),",
              "            FILTER (",
              "                'dim_Date',",
              "                'dim_Date'[DateID-Mmm] >= _PreviousDate",
              "                    && 'dim_Date'[DateID-Mmm] <= _CurrentDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( 'dim_KpiList'[Kpi-Name] )",
                "VAR KpiFormat =",
                "    FORMAT( ",
                "        SELECTEDMEASURE(),",
                "        SWITCH ( ",
                "        TRUE (), ",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.0%\",",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.0%\",",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.0%\",",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "        KpiSelection = \"Incident Resolution - Invoice Entry\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "        KpiSelection = \"Incident Resolution - Banking\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Cost Per Vendor Setup\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "        KpiSelection = \"Incident Resolution - Vendor Control\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Audit Recovery Rate\", ",
                "        \"0.0%\",",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,##0.00;(\\$#,##0.00);\\$#,##0.00\",",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0%\",",
                "        KpiSelection = \"Average Answer Time\",",
                "        \"nn:ss\",",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0%\",",
                "        KpiSelection = \"Callbacks\",",
                "        \"nn:ss\",",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"nn:ss\",",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.0%\",",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0%\" ))",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "d4ed24aa-e3d2-4fb6-b172-66668004e406"
          },
          {
            "name": "Current Period (CC)",
            "displayFolder": ".KPI Comparison Matrix (CC)-NOT USED",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( dim_KpiList[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] ) ",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24,  ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _CurrentDate ",
              "        )",
              "    ",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        TRUE(),",
                "        _KpiSelection = \"Customer Satisfaction\", \"0.00%\" , ",
                "        _KpiSelection = \"Survey Participation Rate\", \"0.00%\" , ",
                "        _KpiSelection = \"Average Answer Time\", FORMAT( [Current Period (CC)], \"nn:ss\"), ",
                "        _KpiSelection = \"Abandonment Rate\", \"0.00%\" ,",
                "        _KpiSelection = \"Calls Answered within Service Level\", \"0.00%\" ,",
                "        _KpiSelection = \"Callbacks\", \"0\" ,",
                "        _KpiSelection = \"Average Answer Time - PS\", \"0\" ,",
                "        _KpiSelection = \"Abandonment Rate - PS\", \"0.00%\" ,",
                "        _KpiSelection = \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "9fa75563-71c4-491e-a616-c13d60490049"
          },
          {
            "name": "Current QTD (CC)",
            "displayFolder": ".KPI Comparison Matrix (CC)-NOT USED",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( dim_KpiList[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 4,",
              "IF ( MONTH ( _CurrentDate ) == 8, 5, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 6 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtr =",
              "IF ( _FyMonth = 1, _CurrentMonth,",
              "IF ( _FyMonth = 4, _CurrentMonth,",
              "IF ( _FyMonth = 7, _CurrentMonth,",
              "IF ( _FyMonth = 10, _CurrentMonth,",
              "IF ( _FyMonth = 2, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 5, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 8, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 11, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 3, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 6, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 9, _CurrentMonthPlus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthPlus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] >= _FyQtr",
              "                && dim_Date[DateID-Mmm] <= _CurrentDate",
              "        )",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        TRUE(),",
                "        _KpiSelection = \"Customer Satisfaction\", \"0.00%\" , ",
                "        _KpiSelection = \"Survey Participation Rate\", \"0.00%\" , ",
                "        _KpiSelection = \"Average Answer Time\", FORMAT( [Current QTD (CC)], \"nn:ss\"), ",
                "        _KpiSelection = \"Abandonment Rate\", \"0.00%\" ,",
                "        _KpiSelection = \"Calls Answered within Service Level\", \"0.00%\" ,",
                "        _KpiSelection = \"Callbacks\", FORMAT( [Current QTD (CC)], \"nn:ss\"),",
                "        _KpiSelection = \"Average Answer Time - PS\", \"0\" ,",
                "        _KpiSelection = \"Abandonment Rate - PS\", \"0.00%\" ,",
                "        _KpiSelection = \"Inbound Email Efficiency\", \"0.00%\")\t"
              ]
            },
            "lineageTag": "261f57c2-517f-43c6-9b08-597f49358aeb"
          },
          {
            "name": "Prior Period (CC)",
            "displayFolder": ".KPI Comparison Matrix (CC)-NOT USED",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( dim_KpiList[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _PreviousDate ",
              "            )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        TRUE(),",
                "        _KpiSelection = \"Customer Satisfaction\", \"0.00%\" , ",
                "        _KpiSelection = \"Survey Participation Rate\", \"0.00%\" , ",
                "        _KpiSelection = \"Average Answer Time\", FORMAT( [Prior Period (CC)], \"nn:ss\"), ",
                "        _KpiSelection = \"Abandonment Rate\", \"0.00%\" ,",
                "        _KpiSelection = \"Calls Answered within Service Level\", \"0.00%\" ,",
                "        _KpiSelection = \"Callbacks\", FORMAT( [Prior Period (CC)], \"nn:ss\"),",
                "        _KpiSelection = \"Average Answer Time - PS\", \"0\" ,",
                "        _KpiSelection = \"Abandonment Rate - PS\", \"0.00%\" ,",
                "        _KpiSelection = \"Inbound Email Efficiency\", \"0.00%\")\t"
              ]
            },
            "lineageTag": "ec834da2-9fb7-4137-9e8f-5b598df53e35"
          },
          {
            "name": "Prior Year (Period) (CC)",
            "displayFolder": ".KPI Comparison Matrix (CC)-NOT USED",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _PreviousDate ",
              "            )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        TRUE(),",
                "        _KpiSelection = \"Customer Satisfaction\", \"0.00%\" , ",
                "        _KpiSelection = \"Survey Participation Rate\", \"0.00%\" , ",
                "        _KpiSelection = \"Average Answer Time\", FORMAT( [Prior Year (Period) (CC)], \"nn:ss\"), ",
                "        _KpiSelection = \"Abandonment Rate\", \"0.00%\" ,",
                "        _KpiSelection = \"Calls Answered within Service Level\", \"0.00%\" ,",
                "        _KpiSelection = \"Callbacks\", FORMAT( [Prior Year (Period) (CC)], \"nn:ss\"),",
                "        _KpiSelection = \"Average Answer Time - PS\", \"0\" ,",
                "        _KpiSelection = \"Abandonment Rate - PS\", \"0.00%\" ,",
                "        _KpiSelection = \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "83946959-9921-40b8-ac5f-6427f8910a37"
          },
          {
            "name": "StartingTotal - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "",
              "VAR BeginCOUNT = CALCULATE ( COUNT(HR_ActiveEmployee_BeginCount[BeginCountMonth] ))",
              "",
              "RETURN",
              "    IF ( ISBLANK(BeginCOUNT) = TRUE(),0,BeginCOUNT)"
            ],
            "formatString": "0",
            "lineageTag": "394ece30-8a6d-4619-a34b-b844dbb24942"
          },
          {
            "name": "EndingTotal - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "",
              "VAR CurrentCount = CALCULATE ( COUNT (HR_ActiveEmployee[CurrentCountMonth] ))",
              "",
              "RETURN",
              "    IF ( ISBLANK(CurrentCount) = TRUE(),0,CurrentCount)"
            ],
            "formatString": "0",
            "lineageTag": "ea99efa0-e316-458d-b25b-f3cc5ab060bd"
          },
          {
            "name": "PlannedHC - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "    SUM ( fact_mor_HeadcountPlan[Plan-Headcount] )"
            ],
            "formatStringDefinition": {
              "expression": "\"0.#\""
            },
            "lineageTag": "e03eebef-67ac-42b7-82ff-95701f8a2868"
          },
          {
            "name": "OpenRoles - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "    [PlannedHC - Count] - [EndingTotal - Count]"
            ],
            "formatStringDefinition": {
              "expression": "\"0.#\""
            },
            "lineageTag": "3122ff7c-d62a-402f-97db-2267b13a9778"
          },
          {
            "name": "PLANvACTUAL-HC(NoBlank) - Count",
            "displayFolder": "Headcount",
            "expression": [
              "",
              "",
              "VAR _SumPlan = SUM( fact_mor_HeadcountPlan[Plan-Headcount] )",
              "",
              "RETURN",
              "    IF( _SumPlan = 0, 0, _SumPlan )"
            ],
            "formatStringDefinition": {
              "expression": "\"0.#\""
            },
            "lineageTag": "31203310-83f1-45b7-ab66-9f29dae6b362"
          },
          {
            "name": "TeamName - TitleFormatting",
            "displayFolder": "Misc",
            "expression": [
              "",
              "    SELECTEDVALUE( metricData_GBS[Team] )"
            ],
            "lineageTag": "d58f825b-5cc8-4ac7-9701-2fd7ba6282ce"
          },
          {
            "name": "Operational Highlights",
            "displayFolder": ".NOODLES",
            "expression": [
              "",
              "",
              "VAR _currentDate = ",
              "    MAX ( dim_Date[Month FY-YY] )",
              "",
              "VAR _commentSelect =  SELECTEDVALUE( 'mor_Comments-AP'[Op-Highlight] )",
              "",
              "RETURN",
              "    _commentSelect"
            ],
            "lineageTag": "9305c333-9fca-4393-80a2-433fbfb8f7c7"
          },
          {
            "name": "AP - Audit Recovery Rate - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AP - Audit Recovery Rate],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "5556e8da-76f4-4cd2-a91c-f048203296ad"
          },
          {
            "name": "AP - Audit Recovery Rate",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AP-AuditRecoveryRate] )",
            "lineageTag": "79416a9a-43be-4e59-8122-69fa54fb524f"
          },
          {
            "name": "AP - Audit Recovery Volume",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AP-AuditRecoveryVolume] )",
            "lineageTag": "56a8d4d7-8542-45b6-a910-e0f73ada638b"
          },
          {
            "name": "AP - Cost Per Payment",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AP-CostPerPayment] )",
            "lineageTag": "c531db1f-8476-499c-9ca9-48a2e717cf68"
          },
          {
            "name": "AP - Cost Per Invoice",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AP-CostPerInvoice] )",
            "lineageTag": "d72b8788-02ee-487b-95a5-a96b50d1bb76"
          },
          {
            "name": "AP - VendorControlSLA",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AP-VendorControlSLA] )",
            "lineageTag": "5e880a9b-8e48-49f2-9eeb-9f47f261c8fd"
          },
          {
            "name": "AP - Cost Per Vendor",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AP-CostPerVendor] )",
            "lineageTag": "eb5d298b-3945-4aef-86f8-af88d21c90ac"
          },
          {
            "name": "AP - InvoiceSLA",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AP-InvoiceSLA] )",
            "lineageTag": "e7c5ec90-7308-4f7a-a92a-3ceafb6e5734"
          },
          {
            "name": "AP - BankingSLA",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AP-BankingSLA] )",
            "lineageTag": "90ba80b1-03b1-4e56-aa38-3845c91dd139"
          },
          {
            "name": ".Operational Highlights - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [.Operational Highlights],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "8155d7ae-cea8-476a-8416-c21f14d838e2"
          },
          {
            "name": "AP - Audit Recovery Volume - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AP - Audit Recovery Volume],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "431aeb76-7c40-4034-a7f3-c0a7cf0b836a"
          },
          {
            "name": ".Headcount - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "VAR _headcount = SELECTEDVALUE( 'fact_mor_Comments-GBS'[Headcount] ) ",
              "",
              "VAR _department = SELECTEDVALUE( 'fact_mor_Comments-GBS'[Department] )",
              "",
              "VAR _team = SELECTEDVALUE( 'fact_mor_Comments-GBS'[Team] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        _headcount,",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "3e83e8b9-0924-4b73-9345-b1c6a3743827"
          },
          {
            "name": "AP - Cost Per Invoice - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AP - Cost Per Invoice],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "617e4edc-69b4-47ae-bbb1-414a75e60530"
          },
          {
            "name": "AP - SLA-Invoice - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AP - InvoiceSLA],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "65175687-5503-448e-811b-a73d6c7564cc"
          },
          {
            "name": ".Budget - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "VAR _budgetComment = SELECTEDVALUE( 'fact_mor_Comments-GBS'[Budget] ) ",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        _budgetComment,",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "e448e66a-0874-4b35-8975-6efdc83a5057"
          },
          {
            "name": "AP - Cost Per Payment - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AP - Cost Per Payment],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "9d9ec388-c1fd-4e10-8b9b-7c50f58f0e37"
          },
          {
            "name": "AP - Cost Per Vendor - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AP - Cost Per Vendor],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "33b91a26-1b37-4147-84c2-cb6b4d9540e3"
          },
          {
            "name": "AP - SLA-Banking - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AP - BankingSLA],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "a952c5b3-874f-488c-9370-5f2c8ef3606f"
          },
          {
            "name": "AP - SLA-VendorControl - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AP - VendorControlSLA],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "08c07d23-b395-4e3b-b450-c477bfcdba94"
          },
          {
            "name": "AR - IncidentResolutionSLA",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AR_IncidentResolution-SLA] )",
            "lineageTag": "3d86ae82-fb8e-445f-b678-5197ac1041e7"
          },
          {
            "name": "AR - IncidentResolutionSLA - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AR - IncidentResolutionSLA],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "f88fdd9c-fe42-4ca5-a5bb-8893802e6b33"
          },
          {
            "name": "AR - UnappliedCash",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AR_UnappliedCash] )",
            "lineageTag": "a2350cec-7788-46ca-a0fd-9b0f48801e34"
          },
          {
            "name": "AR - CostPerManualReceipt",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AR_CostPerManualReceipt] )",
            "lineageTag": "2f479e6c-2b5f-4f1e-bb08-24acc7cf2778"
          },
          {
            "name": "AR - CostPerSnowRequest",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[AR_CostPerSnowRequest] )",
            "lineageTag": "2ae3276c-70c0-476a-ba9d-f5cd6af86f7a"
          },
          {
            "name": "AR - UnappliedCash - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AR - UnappliedCash],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "1fd1f6c6-1d3a-405e-b008-529ed7fdc40c"
          },
          {
            "name": "AR - CostPerManualReceipt - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AR - CostPerManualReceipt],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "5938cf84-9030-427e-a820-2c9b4265df3e"
          },
          {
            "name": "AR - CostPerSnowRequest - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [AR - CostPerSnowRequest],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "1bb935c4-4f60-44ef-87b8-10f1cce99573"
          },
          {
            "name": ".Operational Highlights",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[Op-Highlights] )",
            "lineageTag": "1ba7f947-70ad-4e8f-bff3-1f6fce8004fe"
          },
          {
            "name": ".Budget",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[Budget] )",
            "lineageTag": "db554035-1925-4a24-a4f3-9667a6fddb87"
          },
          {
            "name": ".Headcount",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[Headcount] )",
            "lineageTag": "40dc4766-0e00-4ed3-a6d5-0e428c04eea2"
          },
          {
            "name": "Goal1 (CC)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".NOODLES",
            "expression": "SUM ( dim_mor_KPIs[Kpi-Goal] )",
            "lineageTag": "872c1cb3-9216-46de-9b21-98f9e34a5c8b"
          },
          {
            "name": "CB - DebitPendingItemsUS",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[CB_DebitPendingItems-US] )",
            "lineageTag": "6e44ea82-0156-4e3f-88c5-4f5b8bf46a2d"
          },
          {
            "name": "CB - DebitPendingItemsCAN",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[CB_DebitPendingItems-CAN] )",
            "lineageTag": "775c84c7-898a-49f1-adb3-5855dcd341c2"
          },
          {
            "name": "CB - CostPerManuallyReconciledItem",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[CB_CostPerManualReconItem] )",
            "lineageTag": "b39d4d6a-0b5f-494c-8345-4c11721b43d4"
          },
          {
            "name": "CB - BankAccountReconciliationUS",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[CB_BankAccountRecon-US] )",
            "lineageTag": "d721745b-9c5b-41b8-937c-ac70d09101a0"
          },
          {
            "name": "CB - BankAccountReconciliationCAN",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[CB_BankAccountRecon-CAN] )",
            "lineageTag": "86d27075-16e2-4ba5-967a-5f27c903cfb6"
          },
          {
            "name": "FA - CIPBalance",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[FA_CIP-Balance] )",
            "lineageTag": "feab5560-87a0-4e34-987f-b50e7703e64f"
          },
          {
            "name": "FA - CIPBalanceStale",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[FA_CIP-Balance-Stale] )",
            "lineageTag": "a96c5610-f909-4e9c-a932-be9a9deaeebf"
          },
          {
            "name": "FA - CERsClosedTimely",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[FA_CERsClosedTimely] )",
            "lineageTag": "592f9a20-b9f0-430d-abf6-6a58ef4c1c87"
          },
          {
            "name": "FA - CostPerTransaction",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[FA_CostPerTransaction] )",
            "lineageTag": "f42ce505-9c39-413c-b0f3-dd1605fc3d1a"
          },
          {
            "name": "FA - ReconciliationsPrepared&Reviewed",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[FA_ReconciliationsPrepared&Reviewed] )",
            "lineageTag": "56dee3f4-a2f1-4b90-b8e2-21a47fc19350"
          },
          {
            "name": "GL - AccurateJournalEntries",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[GL_AccurateJournalEntries] )",
            "lineageTag": "d38c413d-c40b-48a5-98d2-3b1f03214044"
          },
          {
            "name": "GL - CostPerManualJournalEntry",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[GL_CostPerManualJournalEntries] )",
            "lineageTag": "90a111f9-8465-4edc-af25-53f3c8bb43bf"
          },
          {
            "name": "GL - ReconciliationsPrepared&Reviewed",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[GL_ReconciliationsPrepared&Reviewed] )",
            "lineageTag": "b532dfe6-38ab-483a-85c3-e9e7a8803329"
          },
          {
            "name": "PR - CostPerPayment",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[PR_CostPerPayment] )",
            "lineageTag": "2447a010-bcd0-4e92-bd9e-27f211aa8779"
          },
          {
            "name": "PR - eFormResolution",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[PR_eFormResolution] )",
            "lineageTag": "150fc52f-8dd6-496d-9510-899d0f0d027a"
          },
          {
            "name": "PR - IncidentResolutionSLA",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[PR_IncidentResolution-SLA] )",
            "lineageTag": "163ef85f-d24b-4254-960c-5cbc43375064"
          },
          {
            "name": "BSS - CustomerSatisfaction",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[BSS_CustomerSatisfaction] )",
            "lineageTag": "15ed15ee-0a4a-4171-8a8f-6262bdb6bbc0"
          },
          {
            "name": "BSS - SurveyParticipationRate",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[BSS_SurveyParticipationRate] )",
            "lineageTag": "b43d5f36-99c5-4b96-b594-3a93d4d93a9e"
          },
          {
            "name": "BSS - AverageAnswerTime",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[BSS_AverageAnswerTime] )",
            "lineageTag": "1dad27d1-2b18-4613-a1c5-fef473daafd2"
          },
          {
            "name": "BSS - AbandonmentRate",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[BSS_AbandonmentRate] )",
            "lineageTag": "5142a984-f086-435c-bfca-26a8c6327662"
          },
          {
            "name": "BSS - CallsWithinSLA",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[BSS_CallsAnsweredWithinSLA] )",
            "lineageTag": "fbae7379-e83b-4980-81fd-da8249f288ee"
          },
          {
            "name": "BSS - Callbacks",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[BSS_Callbacks] )",
            "lineageTag": "54b8aa45-4ca0-40e2-8997-3d1e08d57c3e"
          },
          {
            "name": "BSS - EmailVolume",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[BSS_EmailVolume] )",
            "lineageTag": "792c4de8-d650-47ed-b193-d4a53a5c8dc3"
          },
          {
            "name": "PS - CustomerSatisfaction",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[PS_CustomerSatisfaction] )",
            "lineageTag": "ecf7505c-17c3-462c-ab88-8bdf035f7de7"
          },
          {
            "name": "PS - AverageAnswerTime",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[PS_AverageAnswerTime] )",
            "lineageTag": "f39e85e2-9109-4554-82ce-b4ccc17b0241"
          },
          {
            "name": "PS - AbandonmentRate",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[PS_AbandonmentRate] )",
            "lineageTag": "12387479-83eb-4ca2-979a-abcbfd5f1b7c"
          },
          {
            "name": "PS - InboundEmailEfficiency",
            "displayFolder": ".Comment SELECTVALUES",
            "expression": "SELECTEDVALUE( 'fact_mor_Comments-GBS'[PS_InboundEmailEfficiency] )",
            "lineageTag": "92fc4678-b481-4ad1-b833-4bc2c9c88957"
          },
          {
            "name": "CB - BankAccountReconciliationUS - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [CB - BankAccountReconciliationUS],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "2e116cf4-1a01-41bc-aa54-3fec02e55df8"
          },
          {
            "name": "CB - BankAccountReconciliationCAN - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [CB - BankAccountReconciliationCAN],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "183e7828-7b07-456a-a531-5a55ed817355"
          },
          {
            "name": "CB - CostPerManuallyReconciledItem - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [CB - CostPerManuallyReconciledItem],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "76596393-db06-4dd0-89b3-41db868450ce"
          },
          {
            "name": "CB - DebitPendingItemsUS - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [CB - DebitPendingItemsUS],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "5ec71015-0edd-4f80-8a9d-d35cb48e7afe"
          },
          {
            "name": "CB - DebitPendingItemsCAN - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [CB - DebitPendingItemsCAN],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "ffbfbefa-8391-420d-96b2-4f2546d42c51"
          },
          {
            "name": "FA - CIPBalance - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [FA - CIPBalance],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "d1c1239d-5f93-4368-84b6-daddc0cdfc53"
          },
          {
            "name": "FA - CIPBalanceStale - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [FA - CIPBalanceStale],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "45dc8bc9-918b-4ae5-94ec-1dd49dabfabb"
          },
          {
            "name": "FA - CERsClosedTimely - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [FA - CERsClosedTimely],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "be34350e-ceaa-4264-bc1d-ce4db466884e"
          },
          {
            "name": "FA - CostPerTransaction - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [FA - CostPerTransaction],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "2aaf5c42-309b-4fae-bbc2-2778ef1bf0ac"
          },
          {
            "name": "FA - ReconciliationsPrepared&Reviewed - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [FA - ReconciliationsPrepared&Reviewed],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "983e8e2b-a853-4408-bbf2-829fb2ffa18f"
          },
          {
            "name": "GL - ReconciliationsPrepared&Reviewed - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [GL - ReconciliationsPrepared&Reviewed],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "41545119-dc0c-4c6a-b02e-cd1fd4071ff7"
          },
          {
            "name": "GL - AccurateJournalEntries - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [GL - AccurateJournalEntries],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "f877de45-f3e2-4bda-a394-798000bdab2c"
          },
          {
            "name": "GL - CostPerManualJournalEntry - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [GL - CostPerManualJournalEntry],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "307c940c-5389-492c-bf22-0cf01805c256"
          },
          {
            "name": "PR - CostPerPayment - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [PR - CostPerPayment],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "04ce0df4-89df-4e01-9da3-773c780bbf21"
          },
          {
            "name": "PR - eFormResolution - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [PR - eFormResolution],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "72f2199a-753b-4ab0-8ed2-dcc931ae412a"
          },
          {
            "name": "PR - IncidentResolutionSLA - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [PR - IncidentResolutionSLA],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "6940ab9a-ed2d-47cf-bd9a-ce687fd10852"
          },
          {
            "name": "AC Current QTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "AC Noodles",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 4,",
              "IF ( MONTH ( _CurrentDate ) == 8, 5, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 6 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtr =",
              "IF ( _FyMonth = 1, _CurrentMonth,",
              "IF ( _FyMonth = 4, _CurrentMonth,",
              "IF ( _FyMonth = 7, _CurrentMonth,",
              "IF ( _FyMonth = 10, _CurrentMonth,",
              "IF ( _FyMonth = 2, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 5, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 8, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 11, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 3, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 6, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 9, _CurrentMonthPlus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthPlus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] >= _FyQtr",
              "                && dim_Date[DateID-Mmm] <= _CurrentDate",
              "        )",
              "RETURN",
              "    _Result"
            ],
            "lineageTag": "b09e634f-2281-4896-9226-70b8b470a173"
          },
          {
            "name": "AC - Goal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "AC Noodles",
            "expression": [
              "",
              "",
              "-- This Measure changes the Goal of Average Answer Time && Abandonment Rate, when Payment Services is the selected Team.",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] ) ",
              "",
              "VAR _kpi =",
              "    SELECTEDVALUE ( dim_ac_MetricList[Kpi-Name] )",
              "",
              "VAR _dept = ",
              "    SELECTEDVALUE ( dim_ac_MetricList[Department] )",
              "",
              "VAR _team = ",
              "    SELECTEDVALUE ( dim_ac_MetricList[Team] )",
              "",
              "VAR _goal = [Goal (AC)]",
              "",
              "",
              "VAR _result =",
              "    CALCULATE(",
              "    IF ( _kpi = \"Average Answer Time\", [Goal (AC)] * 86400 / 60 / 60 / 24,",
              "    IF ( _kpi = \"Average Answer Time - PS\", [Goal (AC)] * 86400 / 60 / 60 / 24, ",
              "    _goal )),",
              "                 dim_Date[DateID-Mmm] == _CurrentDate ",
              "    )",
              "",
              "",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "4f356698-1d93-4aca-b2db-a17b2f1fca75"
          },
          {
            "name": "Goal (AC)",
            "displayFolder": "AC Noodles",
            "expression": "SELECTEDVALUE ( dim_mor_KPIs[Kpi-Goal] ) ",
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0%\",",
                "        \"Bank Account Reconciliation - US\", \"0%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0%\",",
                "        \"Incident Resolution - AR\", \"0%\",",
                "        \"Unapplied Cash\", \"0%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.0%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0%\",",
                "        \"CIP Balance\", \"0%\",",
                "        \"CIP Balance (Stale)\", \"0%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0%\",",
                "        \"Audit Recovery Rate\", \"0%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0%\",",
                "        \"Incident Resolution - PR\", \"0%\",",
                "        \"Customer Satisfaction\", \"0%\",",
                "        \"Survey Participation Rate\", \"0%\",",
                "        \"Average Answer Time\", FORMAT( [Goal-Comparison Matrix (GBS)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0%\",",
                "        \"Calls Answered within Service Level\", \"0%\",",
                "        \"Callbacks\", FORMAT( [Goal-Comparison Matrix (GBS)], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Goal-Comparison Matrix (GBS)], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0%\",",
                "        \"Inbound Email Efficiency\", \"0%\")"
              ]
            },
            "lineageTag": "a57b8a78-2460-439d-8ccb-8056efa2ce76"
          },
          {
            "name": "AC - Current QTD Total Qty",
            "displayFolder": "AC Noodles",
            "expression": [
              "",
              "",
              "VAR _qty = [mor-TotalQty (GBS)]",
              "",
              "VAR _qty1 = SUM ( metricData_GBS[mor-TotalQty] )",
              "",
              "VAR _kpiSelect = SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate = SELECTEDVALUE ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterStart =",
              "IF ( _FyMonth = 1, _CurrentMonth,",
              "IF ( _FyMonth = 4, _CurrentMonth,",
              "IF ( _FyMonth = 7, _CurrentMonth,",
              "IF ( _FyMonth = 10, _CurrentMonth,",
              "IF ( _FyMonth = 2, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 5, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 8, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 11, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 3, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 6, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 9, _CurrentMonthMinus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthMinus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        _qty * 1000 ,  ",
              "            dim_Date[DateID-Mmm] == _quarterStart ",
              "                && dim_Date[DateID-Mmm] == _CurrentDate ) ",
              "",
              "VAR _result1 = ",
              "    CALCULATE( ",
              "        [mor-Numerator (GBS)] , ",
              "        FILTER( dim_Date , ",
              "        dim_Date[DateID] > _quarterStart ",
              "        && dim_Date[DateID] <= _CurrentMonth ) )",
              "",
              "",
              "RETURN",
              "    _result1"
            ],
            "formatStringDefinition": {
              "expression": "\"\""
            },
            "lineageTag": "b87f862f-3077-4d6f-ac18-907ea174beec"
          },
          {
            "name": "AC - Current Qtr TotalQty-OLD",
            "displayFolder": "AC Noodles",
            "expression": [
              "",
              "",
              "VAR _KPI = [mor-TotalQty (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtr =",
              "IF ( _FyMonth = 1, _CurrentMonth,",
              "IF ( _FyMonth = 4, _CurrentMonth,",
              "IF ( _FyMonth = 7, _CurrentMonth,",
              "IF ( _FyMonth = 10, _CurrentMonth,",
              "IF ( _FyMonth = 2, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 5, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 8, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 11, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 3, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 6, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 9, _CurrentMonthPlus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthPlus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        [mor-TotalQty (GBS)] * 1000,",
              "            dim_Date[DateID-Mmm] >= _FyQtr",
              "                && dim_Date[DateID-Mmm] <= _CurrentMonth",
              "        )",
              "        ",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "0e458411-653f-41ea-be47-73b7e866997b"
          },
          {
            "name": "Goal1 (AC)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "AC Noodles",
            "expression": [
              "",
              "",
              "VAR _goal = SELECTEDVALUE ( metricData_GBS[Goal] ) ",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _result = ",
              "    CALCULATE( ",
              "        _goal , ",
              "        dim_Date[DateID] == _currentDate )",
              "",
              "Return ",
              "    _result"
            ],
            "lineageTag": "14fa55fe-fb9a-4bd0-b4a9-8699abe25061"
          },
          {
            "name": "AC - PY Qtr KPI",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect = SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
              "",
              "VAR _CurrentDate = MAX ( 'DateKey_TTM'[DateID] )",
              "",
              "VAR _PriorFiscalMonth =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) + 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) + 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtrStartDate =",
              "IF ( _FyMonth = 1, _PriorFiscalMonth,",
              "IF ( _FyMonth = 4, _PriorFiscalMonth,",
              "IF ( _FyMonth = 7, _PriorFiscalMonth,",
              "IF ( _FyMonth = 10, _PriorFiscalMonth,",
              "IF ( _FyMonth = 2, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 5, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 8, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 11, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 3, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 6, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 9, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 12, _PriorFiscalMonthMinus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtrEndDate =",
              "IF ( _FyMonth = 1, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 4, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 7, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 10, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 2, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 5, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 8, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 11, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 3, _PriorFiscalMonth,",
              "IF ( _FyMonth = 6, _PriorFiscalMonth,",
              "IF ( _FyMonth = 9, _PriorFiscalMonth, ",
              "IF ( _FyMonth = 12, _PriorFiscalMonth ) ) ) ) ) ) ) ) ) ) ) ) ",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "            [mor-Numerator (GBS)] / [mor-TotalQty (GBS)] ) ),",
              "        IF( _KpiSelect = \"Unapplied Cash\", dim_Date[DateID-Mmm] = _PriorFiscalMonth ,",
              "        IF( _KpiSelect = \"CIP Balance\", dim_Date[DateID-Mmm] = _PriorFiscalMonth ,",
              "            'dim_Date'[DateID-Mmm] >= _FyQtrStartDate && 'dim_Date'[DateID-Mmm] <= _FyQtrEndDate ) ) ",
              "        )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( dim_ac_MetricList[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Prior Year (Quarter)], \"h:nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Prior Year (Quarter)], \"h:nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Prior Year (Quarter)], \"h:nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "f1fa202c-8e6b-4dee-9991-35b13c25625e"
          },
          {
            "name": "AC - Current Qtr KPI-OLD",
            "displayFolder": "AC Noodles",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtr =",
              "IF ( _FyMonth = 1, _CurrentMonth,",
              "IF ( _FyMonth = 4, _CurrentMonth,",
              "IF ( _FyMonth = 7, _CurrentMonth,",
              "IF ( _FyMonth = 10, _CurrentMonth,",
              "IF ( _FyMonth = 2, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 5, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 8, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 11, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 3, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 6, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 9, _CurrentMonthPlus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthPlus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] >= _FyQtr",
              "                && dim_Date[DateID-Mmm] <= _CurrentDate",
              "        )",
              "        ",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( dim_ac_MetricList[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "f030de43-cb6b-40c1-97bd-5ac6118b6c5a"
          },
          {
            "name": "AC - Prior QTD1",
            "displayFolder": "AC Noodles",
            "expression": [
              "",
              "",
              "VAR _kpi = [KPI (GBS)]",
              "",
              "VAR _numerator = [mor-Numerator (GBS)]",
              "",
              "VAR _qty = [mor-TotalQty (GBS)]",
              "",
              "VAR _KpiSelect = SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate = MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus3 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 3, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus4 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 4, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus5 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 5 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus6 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 6, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterStart =",
              "IF ( _FyMonth = 1, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 2, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 3, _CurrentMonthMinus6,",
              "IF ( _FyMonth = 4, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 5, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 6, _CurrentMonthMinus6,",
              "IF ( _FyMonth = 7, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 8, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 9, _CurrentMonthMinus6,",
              "IF ( _FyMonth = 10, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 11, _CurrentMonthMinus5, ",
              "IF ( _FyMonth = 12, _CurrentMonthMinus6 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterEnd =",
              "IF ( _FyMonth = 1, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 2, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 3, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 4, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 5, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 6, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 7, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 8, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 9, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 10, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 11, _CurrentMonthMinus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthMinus3 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [mor-Numerator (GBS)] / [mor-TotalQty (GBS)] ) ),",
              "        FILTER(",
              "            dim_Date, ",
              "            dim_Date[DateID-Mmm] >= _quarterStart",
              "                && dim_Date[DateID-Mmm] <= _quarterEnd )",
              "        )",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( dim_ac_MetricList[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "7ca85f91-89c9-45db-897c-7c6ece505ada"
          },
          {
            "name": "AC - Previous Qtr KPI",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _num = SUM (metricData_GBS[mor-Numerator] ) ",
              "",
              "VAR _qty = SUM ( metricData_GBS[mor-TotalQty] )",
              "",
              "VAR _KpiSelect = SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus3 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 3, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus4 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 4, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus5 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 5 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus6 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 6, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterStart =",
              "IF ( _FyMonth = 1, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 2, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 3, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 4, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 5, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 6, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 7, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 8, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 9, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 10, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 11, _CurrentMonthMinus4, ",
              "IF ( _FyMonth = 12, _CurrentMonthMinus5 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterEnd =",
              "IF ( _FyMonth = 1, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 2, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 3, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 4, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 5, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 6, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 7, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 8, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 9, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 10, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 11, _CurrentMonthMinus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthMinus3 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "            [mor-Numerator (GBS)] / [mor-TotalQty (GBS)] ) ),",
              "        IF( _KpiSelect = \"Unapplied Cash\", dim_Date[DateID-Mmm] = _quarterEnd ,",
              "        IF( _KpiSelect = \"CIP Balance\", dim_Date[DateID-Mmm] = _quarterEnd ,",
              "            dim_Date[DateID-Mmm] >= _quarterStart && dim_Date[DateID-Mmm] <= _quarterEnd ) ) ",
              "            )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( dim_ac_MetricList[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.00\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Prior Year (Quarter)], \"h:nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Prior Year (Quarter)], \"h:nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Prior Year (Quarter)], \"h:nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\") "
              ]
            },
            "lineageTag": "b2635eaf-8176-4005-92da-9edf8b72f18d"
          },
          {
            "name": "AC - PY TotalQty",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "",
              "VAR _KPI = [mor-TotalQty (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PriorFiscalMonth =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) + 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) + 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtrStartDate =",
              "IF ( _FyMonth = 1, _PriorFiscalMonth,",
              "IF ( _FyMonth = 4, _PriorFiscalMonth,",
              "IF ( _FyMonth = 7, _PriorFiscalMonth,",
              "IF ( _FyMonth = 10, _PriorFiscalMonth,",
              "IF ( _FyMonth = 2, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 5, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 8, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 11, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 3, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 6, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 9, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 12, _PriorFiscalMonthMinus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtrEndDate =",
              "IF ( _FyMonth = 1, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 4, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 7, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 10, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 2, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 5, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 8, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 11, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 3, _PriorFiscalMonth,",
              "IF ( _FyMonth = 6, _PriorFiscalMonth,",
              "IF ( _FyMonth = 9, _PriorFiscalMonth, ",
              "IF ( _FyMonth = 12, _PriorFiscalMonth ) ) ) ) ) ) ) ) ) ) ) ) ",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF(_KpiSelect = \"Unapplied Cash\", [mor-TotalQty (GBS)] * 1000000 ,",
              "        IF(_KpiSelect = \"CIP Balance\", [mor-TotalQty (GBS)] * 1000000 ,",
              "            [mor-TotalQty (GBS)] * 1000 ) ) ,",
              "        IF( _KpiSelect = \"Debit Pending Items - US\", dim_Date[DateID-Mmm] = _FyQtrEndDate ,",
              "        IF( _KpiSelect = \"Debit Pending Items - Canada\", dim_Date[DateID-Mmm] = _FyQtrEndDate , ",
              "        IF( _KpiSelect = \"Bank Account Reconciliation - US\", dim_Date[DateID-Mmm] = _FyQtrEndDate ,",
              "        IF( _KpiSelect = \"Bank Account Reconciliation - Canada\", dim_Date[DateID-Mmm] = _FyQtrEndDate ,",
              "        IF( _KpiSelect = \"Unapplied Cash\", dim_Date[DateID-Mmm] = _FyQtrEndDate ,",
              "        IF( _KpiSelect = \"CIP Balance\", dim_Date[DateID-Mmm] = _FyQtrEndDate ,",
              "            dim_Date[DateID-Mmm] >= _FyQtrStartDate",
              "                && dim_Date[DateID-Mmm] <= _FyQtrEndDate ) ) ) ) ) )",
              "        )",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "baa926f9-fa87-45ed-82d0-4f23e241181d"
          },
          {
            "name": "AC - Previous Qtr TotalQty",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _KPI = [mor-TotalQty (GBS)]",
              "",
              "VAR _KpiSelect = SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus3 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 3, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus4 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 4, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus5 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 5 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus6 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 6, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterStart =",
              "IF ( _FyMonth = 1, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 2, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 3, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 4, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 5, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 6, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 7, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 8, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 9, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 10, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 11, _CurrentMonthMinus4, ",
              "IF ( _FyMonth = 12, _CurrentMonthMinus5 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterEnd =",
              "IF ( _FyMonth = 1, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 2, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 3, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 4, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 5, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 6, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 7, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 8, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 9, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 10, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 11, _CurrentMonthMinus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthMinus3 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF(_KpiSelect = \"Unapplied Cash\", [mor-TotalQty (GBS)] * 1000000 ,",
              "        IF(_KpiSelect = \"CIP Balance\", [mor-TotalQty (GBS)] * 1000000 ,",
              "            [mor-TotalQty (GBS)] * 1000 ) ) ,",
              "        IF( _KpiSelect = \"Debit Pending Items - US\", dim_Date[DateID-Mmm] = _quarterEnd ,",
              "        IF( _KpiSelect = \"Debit Pending Items - Canada\", dim_Date[DateID-Mmm] = _quarterEnd , ",
              "        IF( _KpiSelect = \"Bank Account Reconciliation - US\", dim_Date[DateID-Mmm] = _quarterEnd ,",
              "        IF( _KpiSelect = \"Bank Account Reconciliation - Canada\", dim_Date[DateID-Mmm] = _quarterEnd ,",
              "        IF( _KpiSelect = \"Unapplied Cash\", dim_Date[DateID-Mmm] = _quarterEnd ,",
              "        IF( _KpiSelect = \"CIP Balance\", dim_Date[DateID-Mmm] = _quarterEnd ,",
              "            dim_Date[DateID-Mmm] >= _quarterStart",
              "                && dim_Date[DateID-Mmm] <= _quarterEnd ) ) ) ) ) )",
              "        )",
              "        ",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "95612a59-0b3b-43db-8cdc-170d1621dc0d"
          },
          {
            "name": "Unapplied Cash",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "AC Noodles",
            "expression": [
              "CALCULATE( [mor-TotalQty (GBS)] * 1000, ",
              "                    metricData_GBS[Kpi-Name] == \"Unapplied Cash\"",
              ")"
            ],
            "lineageTag": "c80e669c-2062-4947-a12b-a4e0395e7762"
          },
          {
            "name": "AC - Prior QTD2",
            "displayFolder": "AC Noodles",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _num = SUM (metricData_GBS[mor-Numerator] ) ",
              "",
              "VAR _qty = SUM ( metricData_GBS[mor-TotalQty] )",
              "",
              "VAR _KpiSelect = SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus3 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 3, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus4 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 4, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus5 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 5 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus6 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 6, DAY ( _CurrentDate ) )",
              "",
              "VAR _quarterStart =",
              "IF ( MONTH ( _CurrentDate ) == 1, _CurrentMonthMinus4,",
              "IF ( MONTH ( _CurrentDate ) == 2, _CurrentMonthMinus5,",
              "IF ( MONTH ( _CurrentDate ) == 3, _CurrentMonthMinus6,",
              "IF ( MONTH ( _CurrentDate ) == 4, _CurrentMonthMinus4,",
              "IF ( MONTH ( _CurrentDate ) == 5, _CurrentMonthMinus5,",
              "IF ( MONTH ( _CurrentDate ) == 6, _CurrentMonthMinus6,",
              "IF ( MONTH ( _CurrentDate ) == 7, _CurrentMonthMinus4,",
              "IF ( MONTH ( _CurrentDate ) == 8, _CurrentMonthMinus5,",
              "IF ( MONTH ( _CurrentDate ) == 9, _CurrentMonthMinus6,",
              "IF ( MONTH ( _CurrentDate ) == 10, _CurrentMonthMinus4,",
              "IF ( MONTH ( _CurrentDate ) == 11,  _CurrentMonthMinus5,",
              "IF ( MONTH ( _CurrentDate ) == 12, _CurrentMonthMinus6 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterEnd =",
              "IF ( MONTH ( _CurrentDate ) == 1, _CurrentMonthMinus1,",
              "IF ( MONTH ( _CurrentDate ) == 2, _CurrentMonthMinus2,",
              "IF ( MONTH ( _CurrentDate ) == 3, _CurrentMonthMinus3,",
              "IF ( MONTH ( _CurrentDate ) == 4, _CurrentMonthMinus1,",
              "IF ( MONTH ( _CurrentDate ) == 5, _CurrentMonthMinus2,",
              "IF ( MONTH ( _CurrentDate ) == 6, _CurrentMonthMinus3,",
              "IF ( MONTH ( _CurrentDate ) == 7, _CurrentMonthMinus1,",
              "IF ( MONTH ( _CurrentDate ) == 8, _CurrentMonthMinus2,",
              "IF ( MONTH ( _CurrentDate ) == 9, _CurrentMonthMinus3,",
              "IF ( MONTH ( _CurrentDate ) == 10, _CurrentMonthMinus1,",
              "IF ( MONTH ( _CurrentDate ) == 11,  _CurrentMonthMinus2,",
              "IF ( MONTH ( _CurrentDate ) == 12, _CurrentMonthMinus3 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _numerator =",
              "    CALCULATE (",
              "        SUM( metricData_GBS[mor-Numerator] ),",
              "            dim_Date[DateID] >= _quarterStart",
              "             && dim_Date[DateID] <= _quarterEnd",
              "        )",
              "",
              "VAR _Quantity =",
              "    CALCULATE (",
              "        SUM( metricData_GBS[mor-TotalQty] ),",
              "            dim_Date[DateID] >= _quarterStart",
              "             && dim_Date[DateID] <= _quarterEnd",
              "        )",
              "",
              "",
              "RETURN",
              "    _numerator / _Quantity"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( dim_ac_MetricList[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Prior Year (Quarter)], \"nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\") "
              ]
            },
            "lineageTag": "65d22fca-5360-4fc8-bf32-bc42a450faf5"
          },
          {
            "name": "BSS - Abandonment Rate - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [BSS - AbandonmentRate],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "69a80add-2e34-4042-be32-0a956aed30f9"
          },
          {
            "name": "BSS - Average Answer Time - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [BSS - AverageAnswerTime],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "8a6c25f6-6623-41c0-9ec8-cbf84ce3fab0"
          },
          {
            "name": "BSS - Callbacks - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [BSS - Callbacks],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "134070b6-2fd3-4e68-9fc4-1a6419bb5805"
          },
          {
            "name": "BSS - Calls Within SLA - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [BSS - CallsWithinSLA],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "ceee68ab-b0f9-4577-b4a2-2664a6cc6160"
          },
          {
            "name": "BSS - Customer Satisfaction - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [BSS - CustomerSatisfaction],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "41a3b3ab-3378-4e9c-beeb-3f28136ce971"
          },
          {
            "name": "BSS - Email Volume - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [BSS - EmailVolume],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "d1f72e20-53d8-4537-8d2c-373fdea91799"
          },
          {
            "name": "BSS - Survey Participation Rate - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [BSS - SurveyParticipationRate],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "4495ee2b-294d-4879-9f5b-eb392d6a9ebd"
          },
          {
            "name": "PS - Inbound Email Efficiency - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [PS - InboundEmailEfficiency],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "c2ab462b-982b-490b-acb1-ff1e907903c7"
          },
          {
            "name": "PS - Abandonment Rate - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [PS - AbandonmentRate],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "c7dcad4c-ca8d-41b8-b96c-6d67015c1e90"
          },
          {
            "name": "PS - Average Answer Time - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [PS - AverageAnswerTime],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "f2412b04-5565-42ea-b1fb-f77196c8523b"
          },
          {
            "name": "PS - Customer Satisfaction - Comment",
            "displayFolder": ".Comment Measures",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [PS - CustomerSatisfaction],",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "lineageTag": "5a0fb3dc-b4ba-49f9-a8a1-b43ed1c77e46"
          },
          {
            "name": ".Headcount2 - Comment",
            "displayFolder": ".NOODLES",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX ( DateKey_TTM[Month FY-YY] )",
              "",
              "VAR _headcount = SELECTEDVALUE( 'fact_mor_Comments-GBS'[Headcount] ) ",
              "",
              "VAR _department = SELECTEDVALUE( 'fact_mor_Comments-GBS'[Department] )",
              "",
              "VAR _team = SELECTEDVALUE( 'fact_mor_Comments-GBS'[Team] )",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        IF( _department = \"Contact Center\", _team = \"Business Support Services\" , ",
              "        [.Headcount] ) ,",
              "        FILTER( dim_Date,",
              "        dim_Date[Month FY-YY] == _currentDate ))"
            ],
            "formatStringDefinition": {
              "expression": "\"\""
            },
            "lineageTag": "cd83d610-946d-43e5-9e57-f62e1f8979df"
          },
          {
            "name": "DateCheck",
            "displayFolder": "Misc",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( DateKey_TTM[DateID] )",
              "",
              "RETURN ",
              "    _currentDate"
            ],
            "formatString": "General Date",
            "lineageTag": "e2828ae5-5f7a-4859-9b6e-d7e73b008afb"
          },
          {
            "name": "Goal-Comparison Matrix2 (CC)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".NOODLES",
            "expression": [
              "",
              "",
              "-- This Measure changes the Goal of Average Answer Time && Abandonment Rate, when Payment Services is the selected Team.",
              "",
              "VAR _kpi =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _dept = ",
              "    SELECTEDVALUE ( metricData_GBS[Dept] )",
              "",
              "VAR _team = ",
              "    SELECTEDVALUE ( metricData_GBS[Team] )",
              "",
              "VAR _goal = [Goal (CC)]",
              "",
              "",
              "VAR _goalValidate = ",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time - PS\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Abandonment Rate\" ), ",
              "        0.1,",
              "    _goal )))",
              "",
              "",
              "VAR _result =",
              "    IF ( _kpi = \"Average Answer Time\", _goal * 86400 / 60 / 60 / 24, ",
              "    IF ( _kpi = \"Average Answer Time - PS\", _goal * 86400 / 60 / 60 / 24, ",
              "    _goal ))",
              "",
              "",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "d5cfd564-030a-425c-8d5a-e49f08d2f7c6"
          },
          {
            "name": "Current Period2",
            "displayFolder": ".KPI Comparison Matrix (GBS) - IF-testing",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] ) ",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24,  ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _CurrentDate ",
              "        )",
              "    ",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
                "",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Invoice Entry\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Banking\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Control Transaction\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Vendor Control\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Statement Review\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0#%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        FORMAT( [Current Period2], \"nn:ss\"),",
                "--       \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.00%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.00%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "9c7151bf-9db0-46f3-85b0-3e6682593528"
          },
          {
            "name": "Current QTD2",
            "displayFolder": ".KPI Comparison Matrix (GBS) - IF-testing",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtr =",
              "IF ( _FyMonth = 1, _CurrentMonth,",
              "IF ( _FyMonth = 4, _CurrentMonth,",
              "IF ( _FyMonth = 7, _CurrentMonth,",
              "IF ( _FyMonth = 10, _CurrentMonth,",
              "IF ( _FyMonth = 2, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 5, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 8, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 11, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 3, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 6, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 9, _CurrentMonthPlus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthPlus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] >= _FyQtr",
              "                && dim_Date[DateID-Mmm] <= _CurrentDate",
              "        )",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
                "",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Invoice Entry\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Banking\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Control Transaction\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Vendor Control\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Statement Review\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0#%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        FORMAT( [Current QTD2], \"nn:ss\"),",
                "--       \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.00%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.00%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "80a1b7ac-7779-4a0b-85bc-0db16b9e43b9"
          },
          {
            "name": "Goal-Comparison Matrix2 (GBS)",
            "displayFolder": ".KPI Comparison Matrix (GBS) - IF-testing",
            "expression": [
              "",
              "",
              "-- This Measure changes the Goal of Average Answer Time && Abandonment Rate, when Payment Services is the selected Team.",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] ) ",
              "",
              "VAR _kpi =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _dept = ",
              "    SELECTEDVALUE ( metricData_GBS[Dept] )",
              "",
              "VAR _team = ",
              "    SELECTEDVALUE ( metricData_GBS[Team] )",
              "",
              "VAR _goal = [Goal (GBS)]",
              "",
              "",
              "VAR _goalValidate = ",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time - PS\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Abandonment Rate\" ), ",
              "        0.1,",
              "    _goal )))",
              "",
              " ",
              "",
              "VAR _result =",
              "    CALCULATE(",
              "    IF ( _kpi = \"Average Answer Time\", [Goal (GBS)] * 86400 / 60 / 60 / 24,",
              "    IF ( _kpi = \"Average Answer Time - PS\", [Goal (GBS)] * 86400 / 60 / 60 / 24, ",
              "    [Goal (GBS)] )),",
              "                 dim_Date[DateID-Mmm] == _CurrentDate ",
              "    )",
              "",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Invoice Entry\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Banking\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Control Transaction\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Vendor Control\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Statement Review\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        FORMAT( [Goal-Comparison Matrix2 (GBS)], \"nn:ss\"),",
                "--        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "726383ee-8e2c-4abb-a0a9-17df953f3ade"
          },
          {
            "name": "Prior Period2",
            "displayFolder": ".KPI Comparison Matrix (GBS) - IF-testing",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24,",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _PreviousDate ",
              "            )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
                "",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Invoice Entry\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Banking\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Control Transaction\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Vendor Control\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Statement Review\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0#%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        FORMAT( [Prior Period2], \"nn:ss\"),",
                "--       \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.00%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.00%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "a9b12949-d1aa-4242-8116-d70ab3a6ad80"
          },
          {
            "name": "Prior Year (Period)2",
            "displayFolder": ".KPI Comparison Matrix (GBS) - IF-testing",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _PreviousDate =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400, ",
              "        [KPI (GBS)] ) ),",
              "            dim_Date[DateID-Mmm] == _PreviousDate ",
              "            )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
                "",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Invoice Entry\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Banking\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Control Transaction\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Vendor Control\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Statement Review\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0#%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        FORMAT( [Prior Year (Period)2], \"nn:ss\"),",
                "--       \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.00%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.00%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "3271b3c9-84e6-4409-9dc6-c8ff3536fa76"
          },
          {
            "name": "Prior Year (Quarter)2",
            "displayFolder": ".KPI Comparison Matrix (GBS) - IF-testing",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentDate =",
              "    MAX ( 'DateKey_TTM'[DateID] )",
              "",
              "VAR _PriorFiscalMonth =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) + 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _PriorFiscalMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1, MONTH ( _CurrentDate ) + 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtrStartDate =",
              "IF ( _FyMonth = 1, _PriorFiscalMonth,",
              "IF ( _FyMonth = 4, _PriorFiscalMonth,",
              "IF ( _FyMonth = 7, _PriorFiscalMonth,",
              "IF ( _FyMonth = 10, _PriorFiscalMonth,",
              "IF ( _FyMonth = 2, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 5, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 8, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 11, _PriorFiscalMonthMinus1,",
              "IF ( _FyMonth = 3, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 6, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 9, _PriorFiscalMonthMinus2,",
              "IF ( _FyMonth = 12, _PriorFiscalMonthMinus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtrEndDate =",
              "IF ( _FyMonth = 1, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 4, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 7, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 10, _PriorFiscalMonthPlus2,",
              "IF ( _FyMonth = 2, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 5, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 8, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 11, _PriorFiscalMonthPlus1,",
              "IF ( _FyMonth = 3, _PriorFiscalMonth,",
              "IF ( _FyMonth = 6, _PriorFiscalMonth,",
              "IF ( _FyMonth = 9, _PriorFiscalMonth, ",
              "IF ( _FyMonth = 12, _PriorFiscalMonth ) ) ) ) ) ) ) ) ) ) ) ) ",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        IF ( _KpiSelect = \"Average Answer Time - PS\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ),",
              "            'dim_Date'[DateID-Mmm] >= _FyQtrStartDate",
              "                && 'dim_Date'[DateID-Mmm] <= _FyQtrEndDate",
              "        )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR KpiSelection =",
                "    SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
                "",
                "VAR KpiFormat =",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - US\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manually Reconciled Item\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Debit Pending Items - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Bank Account Reconciliation - Canada\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AR\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Unapplied Cash\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Receipt\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Snow Request\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Accurate Journal Entries\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Manual Journal Entry\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - GL\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CIP Balance (Stale)\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"CERs Closed Timely\",",
                "        \"0.0#\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Transaction - FA\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Reconciliations Prepared & Reviewed - FA\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Invoice\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Invoice Entry\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment Processed\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Banking\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Vendor Control Transaction\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - AP Vendor Control\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Statement Review\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"Cost Per Payment - PR\",",
                "        \"\\$#,###.00;(\\$#,###.00);\\$#,###.00\",",
                "    IF (",
                "        KpiSelection = \"eForm Resolution\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Incident Resolution - PR\",",
                "        \"0.0#%\",",
                "    IF (",
                "        KpiSelection = \"Customer Satisfaction\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Survey Participation Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time\",",
                "        FORMAT( [Prior Year (Quarter)2], \"nn:ss\"),",
                "--       \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Calls Answered within Service Level\",",
                "        \"0.00%\",",
                "    IF (",
                "        KpiSelection = \"Callbacks\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Average Answer Time - PS\",",
                "        \"0\",",
                "    IF (",
                "        KpiSelection = \"Abandonment Rate - PS\",",
                "        \"0.00%\",",
                "    IF ( ",
                "        KpiSelection = \"Inbound Email Efficiency\", ",
                "        \"0.00%\" )",
                ")))))))))))))))))))))))))))))))))))",
                "",
                "RETURN",
                "    KpiFormat"
              ]
            },
            "lineageTag": "e249c0eb-556a-460d-bdd6-7d9ee624ffc1"
          },
          {
            "name": "Current Period - Background2",
            "displayFolder": ".KPI Comparison Matrix (GBS) - IF-testing",
            "expression": [
              "",
              "",
              "VAR _KpiSelection = ",
              "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
              "",
              "VAR _Color =",
              "    IF ( ",
              "        _KpiSelection = \"Debit Pending Items - US\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - US\" ||",
              "        _KpiSelection = \"Debit Pending Items - Canada\" ||",
              "        _KpiSelection = \"Bank Account Reconciliation - Canada\" ||",
              "        _KpiSelection = \"Incident Resolution - AR\" ||",
              "        _KpiSelection = \"Accurate Journal Entries\" ||",
              "//      _KpiSelection = \"Reconciliations Prepared & Reviewed - GL\" ||       -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Reconciliations Prepared & Reviewed - FA\" ||",
              "        _KpiSelection = \"Incident Resolution - Invoice Entry\" ||",
              "        _KpiSelection = \"Incident Resolution - Banking\" ||",
              "        _KpiSelection = \"Incident Resolution - Vendor Control\" ||",
              "        _KpiSelection = \"Audit Recovery Rate\" ||",
              "        _KpiSelection = \"eForm Resolution\" ||",
              "        _KpiSelection = \"Incident Resolution - PR\" ||",
              "        _KpiSelection = \"Customer Satisfaction\" ||",
              "        _KpiSelection = \"Survey Participation Rate\" ||",
              "        _KpiSelection = \"Calls Answered within Service Level\" ||",
              "        _KpiSelection = \"Inbound Email Efficiency\",",
              "            SWITCH (",
              "                TRUE (),",
              "                    [Current Period] >= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                    [Current Period] < VALUE( [Goal-Comparison Matrix (GBS)] * 0.9 ), \"#FFC7CE\",",
              "                    \"#FFEB9C\" ) ,",
              "",
              "    IF ( ",
              "//      _KpiSelection = \"Cost Per Manually Reconciled Item\" ||              -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Unapplied Cash\" ||",
              "//      _KpiSelection = \"Cost Per Manual Receipt\" ||                        -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per SNow Request\" ||                          -- Remove comment bounds & this comment if goal established",
              "//      _KpiSelection = \"Cost Per Manual Journal Entry\" ||                  -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection =\"CIP Balance\" ||",
              "        _KpiSelection = \"CIP Balance (Stale)\" ||",
              "        _KpiSelection = \"CERs Closed Timely\" ||",
              "//      _KpiSelection = \"Cost Per Transaction - FA\" ||                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Cost Per Invoice\" ||",
              "        _KpiSelection = \"Cost Per Payment Processed\" ||",
              "        _KpiSelection = \"Cost Per Vendor Setup\" ||",
              "        _KpiSelection = \"Cost Per Payment - PR\" ||",
              "        _KpiSelection = \"Average Answer Time\" ||",
              "        _KpiSelection = \"Abandonment Rate\" ||",
              "//      _KpiSelection = \"Callbacks\" ||                                      -- Remove comment bounds & this comment if goal established",
              "        _KpiSelection = \"Average Answer Time - PS\" ||",
              "        _KpiSelection = \"Abandonment Rate - PS\",",
              "        SWITCH (",
              "            TRUE (),",
              "                [Current Period] <= VALUE( [Goal-Comparison Matrix (GBS)] ), \"#C6EFCE\",",
              "                [Current Period] > VALUE( [Goal-Comparison Matrix (GBS)] * 1.1 ), \"#FFC7CE\",",
              "                \"#FFEB9C\" ) ) )",
              "",
              "RETURN ",
              "    _Color"
            ],
            "lineageTag": "4947c14f-2212-4f0d-ab32-682a42eca25c"
          },
          {
            "name": "AC - Current Qtr KPI",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "",
              "VAR _KPI = [KPI (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtr =",
              "IF ( _FyMonth = 1, _CurrentMonth,",
              "IF ( _FyMonth = 4, _CurrentMonth,",
              "IF ( _FyMonth = 7, _CurrentMonth,",
              "IF ( _FyMonth = 10, _CurrentMonth,",
              "IF ( _FyMonth = 2, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 5, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 8, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 11, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 3, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 6, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 9, _CurrentMonthPlus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthPlus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF ( _KpiSelect = \"Average Answer Time\", [KPI (GBS)] * 86400 / 60 / 60 / 24, ",
              "        [KPI (GBS)] ) ,",
              "        IF( _KpiSelect = \"Unapplied Cash\", dim_Date[DateID-Mmm] = _CurrentDate ,",
              "        IF( _KpiSelect = \"CIP Balance\", dim_Date[DateID-Mmm] = _CurrentDate ,",
              "            dim_Date[DateID-Mmm] >= _FyQtr && dim_Date[DateID-Mmm] <= _CurrentDate",
              "        )))",
              "        ",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( dim_ac_MetricList[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0.00%\",",
                "        \"Bank Account Reconciliation - US\", \"0.00%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0.00%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0.00%\",",
                "        \"Incident Resolution - AR\", \"0.00%\",",
                "        \"Unapplied Cash\", \"0.00%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.00%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0.00%\",",
                "        \"CIP Balance\", \"0.00%\",",
                "        \"CIP Balance (Stale)\", \"0.00%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0.00%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0.00%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0.00%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0.00%\",",
                "        \"Audit Recovery Rate\", \"0.00%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0.00%\",",
                "        \"Incident Resolution - PR\", \"0.0#%\",",
                "        \"Customer Satisfaction\", \"0.00%\",",
                "        \"Survey Participation Rate\", \"0.00%\",",
                "        \"Average Answer Time\", FORMAT( [Prior Year (Quarter)], \"h:nn:ss\"),",
                "        \"Abandonment Rate\", \"0.00%\",",
                "        \"Calls Answered within Service Level\", \"0.00%\",",
                "        \"Callbacks\", FORMAT( [Prior Year (Quarter)], \"h:nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [Prior Year (Quarter)], \"h:nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0.00%\",",
                "        \"Inbound Email Efficiency\", \"0.00%\")"
              ]
            },
            "lineageTag": "5faf5169-cc82-48bf-9433-238b3df30920"
          },
          {
            "name": "AC - Current Qtr TotalQty",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "",
              "VAR _KPI = [mor-TotalQty (GBS)]",
              "",
              "VAR _KpiSelect =",
              "    SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthPlus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyQtr =",
              "IF ( _FyMonth = 1, _CurrentMonth,",
              "IF ( _FyMonth = 4, _CurrentMonth,",
              "IF ( _FyMonth = 7, _CurrentMonth,",
              "IF ( _FyMonth = 10, _CurrentMonth,",
              "IF ( _FyMonth = 2, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 5, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 8, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 11, _CurrentMonthPlus1,",
              "IF ( _FyMonth = 3, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 6, _CurrentMonthPlus2,",
              "IF ( _FyMonth = 9, _CurrentMonthPlus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthPlus2 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _Result =",
              "    CALCULATE (",
              "        IF(_KpiSelect = \"Unapplied Cash\", [mor-TotalQty (GBS)] * 1000000 ,",
              "        IF(_KpiSelect = \"CIP Balance\", [mor-TotalQty (GBS)] * 1000000 ,",
              "            [mor-TotalQty (GBS)] * 1000 ) ) ,",
              "        IF( _KpiSelect = \"Debit Pending Items - US\", dim_Date[DateID-Mmm] = _CurrentDate ,",
              "        IF( _KpiSelect = \"Debit Pending Items - Canada\", dim_Date[DateID-Mmm] = _CurrentDate , ",
              "        IF( _KpiSelect = \"Bank Account Reconciliation - US\", dim_Date[DateID-Mmm] = _CurrentDate ,",
              "        IF( _KpiSelect = \"Bank Account Reconciliation - Canada\", dim_Date[DateID-Mmm] = _CurrentDate ,",
              "        IF( _KpiSelect = \"Unapplied Cash\", dim_Date[DateID-Mmm] = _CurrentDate ,",
              "        IF( _KpiSelect = \"CIP Balance\", dim_Date[DateID-Mmm] = _CurrentDate ,",
              "            dim_Date[DateID-Mmm] >= _FyQtr",
              "                && dim_Date[DateID-Mmm] <= _CurrentMonth ) ) ) ) ) ) ",
              "        )",
              "        ",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "cf82e62d-9d4d-4008-a785-cf398e330fdd"
          },
          {
            "name": "AC - Current & PY \"Q#\"",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _result = ",
              "    CALCULATE( ",
              "        IF( _FyMonth == 1 , \"Q1\", ",
              "        IF( _FyMonth == 2 , \"Q1\", ",
              "        IF( _FyMonth == 3 , \"Q1\", ",
              "        IF( _FyMonth == 4 , \"Q2\", ",
              "        IF( _FyMonth == 5 , \"Q2\", ",
              "        IF( _FyMonth == 6 , \"Q2\", ",
              "        IF( _FyMonth == 7 , \"Q3\", ",
              "        IF( _FyMonth == 8 , \"Q3\",        ",
              "        IF( _FyMonth == 9 , \"Q3\", ",
              "        IF( _FyMonth == 10 , \"Q4\", ",
              "        IF( _FyMonth == 11 , \"Q4\", ",
              "        IF( _FyMonth == 12 , \"Q4\" ) ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": "\"\""
            },
            "lineageTag": "82afaf55-49c8-4efb-a9a3-086b7f4fa669"
          },
          {
            "name": "AC - Previous Qtr \"Q#\"",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _KPI = [mor-TotalQty (GBS)]",
              "",
              "VAR _KpiSelect = SELECTEDVALUE ( metricData_GBS[Kpi-Name] )",
              "",
              "VAR _CurrentMonthMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 1, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus2 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 2 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus3 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 3, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus4 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 4, DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus5 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 5 , DAY ( _CurrentDate ) )",
              "",
              "VAR _CurrentMonthMinus6 =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ) - 6, DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterStart =",
              "IF ( _FyMonth = 1, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 2, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 3, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 4, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 5, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 6, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 7, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 8, _CurrentMonthMinus4,",
              "IF ( _FyMonth = 9, _CurrentMonthMinus5,",
              "IF ( _FyMonth = 10, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 11, _CurrentMonthMinus4, ",
              "IF ( _FyMonth = 12, _CurrentMonthMinus5 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _quarterEnd =",
              "IF ( _FyMonth = 1, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 2, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 3, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 4, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 5, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 6, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 7, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 8, _CurrentMonthMinus2,",
              "IF ( _FyMonth = 9, _CurrentMonthMinus3,",
              "IF ( _FyMonth = 10, _CurrentMonthMinus1,",
              "IF ( _FyMonth = 11, _CurrentMonthMinus2, ",
              "IF ( _FyMonth = 12, _CurrentMonthMinus3 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _result = ",
              "    CALCULATE( ",
              "        IF( _FyMonth == 1 , \"Q4\", ",
              "        IF( _FyMonth == 2 , \"Q4\", ",
              "        IF( _FyMonth == 3 , \"Q4\", ",
              "        IF( _FyMonth == 4 , \"Q1\", ",
              "        IF( _FyMonth == 5 , \"Q1\", ",
              "        IF( _FyMonth == 6 , \"Q1\", ",
              "        IF( _FyMonth == 7 , \"Q2\", ",
              "        IF( _FyMonth == 8 , \"Q2\",        ",
              "        IF( _FyMonth == 9 , \"Q2\", ",
              "        IF( _FyMonth == 10 , \"Q3\", ",
              "        IF( _FyMonth == 11 , \"Q3\", ",
              "        IF( _FyMonth == 12 , \"Q3\" ) ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "        ",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "3e1d957b-51f3-4df7-8111-aae78bd92ac8"
          },
          {
            "name": "AC - Current \"FY-YY\"",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _YearPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ) + 1 , MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )    ",
              "",
              "VAR _YearMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1 , MONTH ( _CurrentDate ), DAY ( _CurrentDate ) ) ",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyYear = ",
              "    IF ( _FyMonth == 1 , _YearPlus1 , ",
              "    IF ( _FyMonth == 2 , _YearPlus1 ,",
              "    IF ( _FyMonth == 3 , _YearPlus1 ,",
              "    IF ( _FyMonth == 4 , _CurrentMonth ,",
              "    IF ( _FyMonth == 5 , _CurrentMonth ,",
              "    IF ( _FyMonth == 6 , _CurrentMonth ,",
              "    IF ( _FyMonth == 7 , _CurrentMonth ,",
              "    IF ( _FyMonth == 8 , _CurrentMonth ,",
              "    IF ( _FyMonth == 9 , _CurrentMonth ,",
              "    IF ( _FyMonth == 10 , _CurrentMonth ,",
              "    IF ( _FyMonth == 11 , _CurrentMonth ,",
              "    IF ( _FyMonth == 12 , _CurrentMonth ) ) ) ) ) ) ) ) ) ) ) ) ",
              "",
              "VAR _quarter = ",
              "    CALCULATE( ",
              "        IF( _FyMonth == 1 , \"Q1\", ",
              "        IF( _FyMonth == 2 , \"Q1\", ",
              "        IF( _FyMonth == 3 , \"Q1\", ",
              "        IF( _FyMonth == 4 , \"Q2\", ",
              "        IF( _FyMonth == 5 , \"Q2\", ",
              "        IF( _FyMonth == 6 , \"Q2\", ",
              "        IF( _FyMonth == 7 , \"Q3\", ",
              "        IF( _FyMonth == 8 , \"Q3\",        ",
              "        IF( _FyMonth == 9 , \"Q3\", ",
              "        IF( _FyMonth == 10 , \"Q4\", ",
              "        IF( _FyMonth == 11 , \"Q4\", ",
              "        IF( _FyMonth == 12 , \"Q4\" ) ) ) ) ) ) ) ) ) ) ) ) )       ",
              "",
              "",
              "RETURN",
              "    COMBINEVALUES(\"-\",  \"FY\", ",
              "    FORMAT( _FyYear, \"YY\" ) )"
            ],
            "lineageTag": "babe5f6f-bff6-4f8a-9a2e-e5d6f965eeb5"
          },
          {
            "name": "AC - PY \"FY-YY\"",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _YearPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ) + 1 , MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )    ",
              "",
              "VAR _YearMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1 , MONTH ( _CurrentDate ), DAY ( _CurrentDate ) ) ",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyYear = ",
              "    IF ( _FyMonth == 1 , _CurrentMonth , ",
              "    IF ( _FyMonth == 2 , _CurrentMonth ,",
              "    IF ( _FyMonth == 3 , _CurrentMonth ,",
              "    IF ( _FyMonth == 4 , _YearMinus1 ,",
              "    IF ( _FyMonth == 5 , _YearMinus1 ,",
              "    IF ( _FyMonth == 6 , _YearMinus1 ,",
              "    IF ( _FyMonth == 7 , _YearMinus1 ,",
              "    IF ( _FyMonth == 8 , _YearMinus1 ,",
              "    IF ( _FyMonth == 9 , _YearMinus1 ,",
              "    IF ( _FyMonth == 10 , _YearMinus1 ,",
              "    IF ( _FyMonth == 11 , _YearMinus1 ,",
              "    IF ( _FyMonth == 12 , _YearMinus1 ) ) ) ) ) ) ) ) ) ) ) ) ",
              "",
              "VAR _quarter = ",
              "    CALCULATE( ",
              "        IF( _FyMonth == 1 , \"Q1\", ",
              "        IF( _FyMonth == 2 , \"Q1\", ",
              "        IF( _FyMonth == 3 , \"Q1\", ",
              "        IF( _FyMonth == 4 , \"Q2\", ",
              "        IF( _FyMonth == 5 , \"Q2\", ",
              "        IF( _FyMonth == 6 , \"Q2\", ",
              "        IF( _FyMonth == 7 , \"Q3\", ",
              "        IF( _FyMonth == 8 , \"Q3\",        ",
              "        IF( _FyMonth == 9 , \"Q3\", ",
              "        IF( _FyMonth == 10 , \"Q4\", ",
              "        IF( _FyMonth == 11 , \"Q4\", ",
              "        IF( _FyMonth == 12 , \"Q4\" ) ) ) ) ) ) ) ) ) ) ) ) )       ",
              "",
              "",
              "RETURN",
              "    COMBINEVALUES(\"-\",  \"FY\", ",
              "    FORMAT( _FyYear, \"YY\" ) )"
            ],
            "lineageTag": "81bf73ed-2414-4085-ad85-7bb3b75216b3"
          },
          {
            "name": "AC - Previous \"FY-YY\"",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "    ",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] )",
              "",
              "VAR _CurrentMonth =",
              "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )",
              "",
              "VAR _YearPlus1 =",
              "    DATE ( YEAR ( _CurrentDate ) + 1 , MONTH ( _CurrentDate ), DAY ( _CurrentDate ) )    ",
              "",
              "VAR _YearMinus1 =",
              "    DATE ( YEAR ( _CurrentDate ) - 1 , MONTH ( _CurrentDate ), DAY ( _CurrentDate ) ) ",
              "",
              "VAR _YearMinus3 =",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 3 , DAY ( _CurrentDate ) )",
              "",
              "VAR _FyMonth =",
              "IF ( MONTH ( _CurrentDate ) == 10, 1,",
              "IF ( MONTH ( _CurrentDate ) == 11, 2,",
              "IF ( MONTH ( _CurrentDate ) == 12, 3,",
              "IF ( MONTH ( _CurrentDate ) == 1, 4,",
              "IF ( MONTH ( _CurrentDate ) == 2, 5,",
              "IF ( MONTH ( _CurrentDate ) == 3, 6,",
              "IF ( MONTH ( _CurrentDate ) == 4, 7,",
              "IF ( MONTH ( _CurrentDate ) == 5, 8,",
              "IF ( MONTH ( _CurrentDate ) == 6, 9,",
              "IF ( MONTH ( _CurrentDate ) == 7, 10,",
              "IF ( MONTH ( _CurrentDate ) == 8, 11, ",
              "IF ( MONTH ( _CurrentDate ) == 9, 12 ) ) ) ) ) ) ) ) ) ) ) )",
              "",
              "VAR _FyYear = ",
              "    IF ( _FyMonth == 1 , _YearMinus3 , ",
              "    IF ( _FyMonth == 2 , _YearMinus3 ,",
              "    IF ( _FyMonth == 3 , _YearMinus3 ,",
              "    IF ( _FyMonth == 4 , _CurrentMonth ,",
              "    IF ( _FyMonth == 5 , _CurrentMonth ,",
              "    IF ( _FyMonth == 6 , _CurrentMonth ,",
              "    IF ( _FyMonth == 7 , _CurrentMonth ,",
              "    IF ( _FyMonth == 8 , _CurrentMonth ,",
              "    IF ( _FyMonth == 9 , _CurrentMonth ,",
              "    IF ( _FyMonth == 10 , _CurrentMonth ,",
              "    IF ( _FyMonth == 11 , _CurrentMonth ,",
              "    IF ( _FyMonth == 12 , _CurrentMonth ) ) ) ) ) ) ) ) ) ) ) )     ",
              "",
              "",
              "RETURN",
              "    COMBINEVALUES(\"-\",  \"FY\", ",
              "    FORMAT( _FyYear, \"YY\" ) )"
            ],
            "lineageTag": "8fff846e-2cb6-44b1-8e16-ba5e4061c734"
          },
          {
            "name": "AC - Goal2",
            "displayFolder": "AC Measures",
            "expression": [
              "",
              "",
              "-- This Measure changes the Goal of Average Answer Time && Abandonment Rate, when Payment Services is the selected Team.",
              "",
              "VAR _CurrentDate =",
              "    MAX ( DateKey_TTM[DateID] ) ",
              "",
              "VAR _kpi =",
              "    SELECTEDVALUE ( dim_mor_KPIs[Kpi-Name] )",
              "",
              "VAR _dept = ",
              "    SELECTEDVALUE ( dim_mor_KPIs[Department-Name] )",
              "",
              "VAR _team = ",
              "    SELECTEDVALUE ( dim_mor_KPIs[Team-Name] )",
              "",
              "VAR _goal = SELECTEDVALUE( dim_mor_KPIs[Kpi-Goal] )",
              "",
              "",
              "/* VAR _goalValidate = ",
              "    IF ( AND ( ",
              "        _team  == \"Business Support Services\",",
              "        _kpi == \"Average Answer Time\" ), ",
              "        0.00069,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Average Answer Time - PS\" ), ",
              "        0.00243055555555556,",
              "    IF ( AND ( ",
              "        _team  == \"Payment Services\",",
              "        _kpi == \"Abandonment Rate\" ), ",
              "        0.1,",
              "    _goal ))))",
              "*/ ",
              " ",
              "",
              "VAR _result =",
              "    CALCULATE(",
              "    IF ( _kpi = \"Average Answer Time\", _goal * 86400 / 60 / 60 / 24,",
              "    IF ( _kpi = \"Average Answer Time - PS\", _goal * 86400 / 60 / 60 / 24, ",
              "    _goal ))",
              "--    ,",
              "--                 dim_Date[DateID-Mmm] == _CurrentDate ",
              "    )",
              "",
              "",
              "RETURN",
              "    _result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _KpiSelection =",
                "    SELECTEDVALUE ( 'dim_mor_KPIs'[Kpi-Name] )",
                "",
                "RETURN",
                "    SWITCH( ",
                "        _KpiSelection,",
                "        \"Debit Pending Items - US\", \"0%\",",
                "        \"Bank Account Reconciliation - US\", \"0%\",",
                "        \"Cost Per Manually Reconciled Item\", \"\\$#,##0.00\",",
                "        \"Debit Pending Items - Canada\", \"0%\",",
                "        \"Bank Account Reconciliation - Canada\", \"0%\",",
                "        \"Incident Resolution - AR\", \"0%\",",
                "        \"Unapplied Cash\", \"0%\",",
                "        \"Cost Per Manual Receipt\", \"\\$#,##0.00\",",
                "        \"Cost Per Snow Request\", \"\\$#,##0.00\",",
                "        \"Accurate Journal Entries\", \"0.0%\",",
                "        \"Cost Per Manual Journal Entry\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - GL\", \"0%\",",
                "        \"CIP Balance\", \"0%\",",
                "        \"CIP Balance (Stale)\", \"0%\",",
                "        \"CERs Closed Timely\", \"0.0#\",",
                "        \"Cost Per Transaction - FA\", \"\\$#,##0.00\",",
                "        \"Reconciliations Prepared & Reviewed - FA\", \"0%\",",
                "        \"Cost Per Invoice\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Invoice Entry\", \"0%\",",
                "        \"Cost Per Payment Processed\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Banking\", \"0%\",",
                "        \"Cost Per Vendor Setup\", \"\\$#,##0.00\",",
                "        \"Incident Resolution - Vendor Control\", \"0%\",",
                "        \"Audit Recovery Rate\", \"0%\",",
                "        \"Cost Per Payment - PR\", \"\\$#,##0.00\",",
                "        \"eForm Resolution\", \"0%\",",
                "        \"Incident Resolution - PR\", \"0%\",",
                "        \"Customer Satisfaction\", \"0%\",",
                "        \"Survey Participation Rate\", \"0%\",",
                "        \"Average Answer Time\", FORMAT( [AC - Goal2], \"h:nn:ss\"),",
                "        \"Abandonment Rate\", \"0%\",",
                "        \"Calls Answered within Service Level\", \"0%\",",
                "        \"Callbacks\", FORMAT( [AC - Goal2], \"h:nn:ss\"),",
                "        \"Average Answer Time - PS\", FORMAT( [AC - Goal2], \"h:nn:ss\"),",
                "        \"Abandonment Rate - PS\", \"0%\",",
                "        \"Inbound Email Efficiency\", \"0%\")"
              ]
            },
            "lineageTag": "2bb3389f-a379-4e0c-b2ce-c85752e15042"
          },
          {
            "name": "mor-Numerator (GBS)2",
            "expression": [
              "",
              "",
              "VAR _kpiName = SELECTEDVALUE( dim_mor_KPIs[Kpi-Name] )",
              "",
              "VAR _numSum = ",
              " CALCULATE( ",
              "    IF( _kpiName = \"Cost Per Invoice\" ,  SUM( metricData_AP[Labor Cost] ), ",
              "    IF( _kpiName = \"Incident Resolution - Invoice Entry\" ,  SUM( metricData_AP[SNOW-withinSLA] ),",
              "    IF( _kpiName = \"Cost Per Payment Processed\" ,  SUM(metricData_AP[Labor Cost] ),",
              "    IF( _kpiName = \"Incident Resolution - Banking\" ,  SUM( metricData_AP[SNOW-withinSLA] ),",
              "    IF( _kpiName = \"Cost Per Vendor Setup\" ,  SUM(metricData_AP[Labor Cost] ),",
              "    IF( _kpiName = \"Incident Resolution - Vendor Control\" ,  SUM( metricData_AP[SNOW-withinSLA] ),",
              "    IF( _kpiName = \"Audit Recovery Rate\" ,  SUM(metricData_AP[Labor Cost] ),",
              "    IF( _kpiName = \"Audit Recovery Volume\" ,  SUM(metricData_AP[Labor Cost] ),",
              "   ",
              "    )))))))))"
            ],
            "lineageTag": "74b8819c-a765-4dc3-8044-bd767625a929"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "DateKey_TTM",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ac601961dab6456586ca5649e273c85e"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b1bb5a8f-7cf1-4df2-986f-1db9ca0d675e",
            "sourceColumn": "dim_Date[DateID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7b19b701-86ef-44e9-9665-e940f58fb3eb"
                },
                "isDefault": true,
                "relationship": "b06198b0-06a8-40cf-8ff0-b6208f90602b"
              }
            ]
          },
          {
            "name": "DateID-Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH( DateKey_TTM[DateID] )",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a7e8158e-f0b5-4244-9e10-b816e8ce6dfc",
            "sortByColumn": "DateID",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF( MONTH (DateKey_TTM[DateID]) >= 10, YEAR(DateKey_TTM[DateID]) + 1, YEAR(DateKey_TTM[DateID]))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f9d15d0f-f388-4e7e-90b7-28b0d8f35f73",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"FY-\" & RIGHT([Fiscal Year], 2)",
            "isDataTypeInferred": true,
            "lineageTag": "5e8728aa-391d-4840-8a71-cbc016f8a5fb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "DateKey_TTM[Month] & \" \" & DateKey_TTM[FY-YY]",
            "isDataTypeInferred": true,
            "lineageTag": "33ba3f5f-0dae-442b-90ad-b566c636b604",
            "sortByColumn": "DateID",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "SWITCH( ",
              "    DateKey_TTM[DateID-Month], ",
              "    1, \"January\",",
              "    2, \"February\",",
              "    3, \"March\",",
              "    4, \"April\",",
              "    5, \"May\",",
              "    6, \"June\",",
              "    7, \"July\",",
              "    8, \"August\",",
              "    9, \"September\",",
              "    10, \"October\",",
              "    11, \"November\",",
              "    12, \"December\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ee5a62be-1a37-4db7-a579-d45e0a4cc704",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "076ba418-4adb-48dd-8bf3-45e9859b6fa6",
        "partitions": [
          {
            "name": "DateKey_TTM",
            "mode": "import",
            "source": {
              "expression": "DISTINCT( dim_Date[DateID] )",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7b19b701-86ef-44e9-9665-e940f58fb3eb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "915e2518-1c8f-48ee-a108-2f7f64caadce",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea6e5119-4cf9-4ac0-85df-2f31f08ac436",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5f939d3d-5769-483e-8a7c-7f0f859f1abd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "72c4a280-76a9-4cd1-88f2-b6fcbe83dae8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bb6f0d10-bb2f-4184-863d-7afece3844ab",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "261d0493-fc15-45de-81b2-f3ec7e1052b1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5c59d829-6201-4b8d-8a14-2105262d9252",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d0658a92-e284-4962-8a81-09b1844a1709",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e7650b69-8aa2-4524-a1dc-e8533dae3b09",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8bbf987a-ab46-4d75-b7ee-6eb528fd0e9a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "faed9244-d620-4aa1-90a5-cb72d2c3da67",
                "ordinal": 3
              }
            ],
            "lineageTag": "259d65ec-935e-4eb8-a1b3-88b6ea4c5c04"
          }
        ],
        "isHidden": true,
        "lineageTag": "d553ecea-1855-4833-843a-4f91c06e7aa6",
        "partitions": [
          {
            "name": "LocalDateTable_7b19b701-86ef-44e9-9665-e940f58fb3eb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DateKey_TTM'[DateID])), 1, 1), Date(Year(MAX('DateKey_TTM'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7036a8fb-8bd0-421b-b386-95cd900365f9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a1f294c4-0772-4f33-aee9-4c8d113e08ae",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "88f3026e-4b8b-481b-8b42-792ff9f55a06",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3e5e37d0-0b5c-4d08-9362-9cb288c02aad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f3454628-8a88-4a49-b99f-b477b6039d1d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e318df58-e270-43fc-ba09-8f1ee42c13aa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ae2f489b-7f19-4504-bc44-d01d84db891a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c96ac4d2-2346-400b-8fa8-edaa282bdc51",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2ec40ea6-8d49-401d-9c6a-3dbe72bcebc2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "251532dc-c87c-4c12-9af5-b91da6760ebd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "52823086-d065-4988-8eb2-a9e2c6df87ef",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f829821d-23d3-4ca1-b2ad-e9c715efcca8",
                "ordinal": 3
              }
            ],
            "lineageTag": "036ef3a9-5130-49e2-b7b4-02b555ddf59f"
          }
        ],
        "isHidden": true,
        "lineageTag": "2a9543c2-3c45-4279-8ad0-5f8f4911ddbd",
        "partitions": [
          {
            "name": "LocalDateTable_7036a8fb-8bd0-421b-b386-95cd900365f9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('HR_ActiveEmployee'[LoadDate])), 1, 1), Date(Year(MAX('HR_ActiveEmployee'[LoadDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_699afe88-c003-4400-a522-89941ff6ae1b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bcb9a96c-8ac2-4ec6-aa87-fdc2f895c84f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b1df2179-9ed3-43b6-b8d7-9addde529cc2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "44dbbac8-c70f-4136-bac4-43fa2ef1cd98",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e4e7ee9b-1c30-4b26-9060-92c642900cad",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d51783b7-2112-4df9-adb7-87afe114a765",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c1e28798-7024-443c-b0d6-86acda081509",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1382b682-bf8d-4cee-b7cd-5b6a953103e2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a11925a6-3fde-4e78-878d-749b93866470",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "401d3e9f-1cc9-431d-8c60-240b2b0204bf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3bebd9e2-982d-4842-aa2b-f0887bb39bef",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8fcccd15-8d78-47f3-93a0-9883ac6011cb",
                "ordinal": 3
              }
            ],
            "lineageTag": "0f7a98a4-fcaa-4954-952a-e6d379b28a47"
          }
        ],
        "isHidden": true,
        "lineageTag": "5c4a1d9a-ad6a-406e-a0f0-3bc6d2e038e9",
        "partitions": [
          {
            "name": "LocalDateTable_699afe88-c003-4400-a522-89941ff6ae1b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('HR_ActiveEmployee_BeginCount'[LoadDate])), 1, 1), Date(Year(MAX('HR_ActiveEmployee_BeginCount'[LoadDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_16744950-94c0-4703-ba7a-a062cf6fadd2",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0744831f-d357-44d3-af79-899e08b6f1a1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3568c40a-68ef-4d8c-9f5b-dcf2cca05832",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fe3abd8c-1d15-473d-8312-289c3016ff8a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7dc43d5d-c302-440b-b31a-5ce29fc5743b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "99bf1f8b-1681-4c03-9d6f-c769840a671c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "520b778f-5ff5-49e8-b7fb-64c4afdbdc2a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bbdae4ee-c521-40da-83f9-5ba19ae7d9a5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c7fcccce-de9d-40ee-8563-086069332671",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d97b1f5c-ee8c-4131-b9dc-2d6a51e4a1f8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1cd82923-b682-4eea-a9eb-984b96295165",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f9013100-1d4c-437f-a432-94a496115fd5",
                "ordinal": 3
              }
            ],
            "lineageTag": "f83e153c-04a6-4d48-af3a-67eec417ebb8"
          }
        ],
        "isHidden": true,
        "lineageTag": "7bbaf558-5811-47f3-9d02-674c49f95bc2",
        "partitions": [
          {
            "name": "LocalDateTable_16744950-94c0-4703-ba7a-a062cf6fadd2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('metricData_GBS'[DateID])), 1, 1), Date(Year(MAX('metricData_GBS'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "metricEmailVolume_CC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dept",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16d5168e-e45f-413f-90fa-945cfbdea0bf",
            "sourceColumn": "Dept",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9f8515f-531c-45af-8c2a-825db09c3699",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2db5af40-58f7-4a79-82f7-bd1416261cdc",
            "sourceColumn": "Kpi-Name",
            "summarizeBy": "none"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0aa90519-1e45-4145-bb10-c2a437ad6ce0",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e22548d0-4ed9-4c99-9040-b992316b46c3"
                },
                "isDefault": true,
                "relationship": "a8a56556-fd9a-43dc-8c5a-8c3725dab1fb"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a5b8ef5-4f0f-4f84-8eac-9b167a9489b8",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "iCare",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2281a513-e434-48f2-af9c-229a3f316f0a",
            "sourceColumn": "iCare",
            "summarizeBy": "sum"
          },
          {
            "name": "MunchMail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db4a9a62-fbfa-49b3-b043-d7311fddf5dc",
            "sourceColumn": "MunchMail",
            "summarizeBy": "sum"
          },
          {
            "name": "UsOpen",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92cab6d4-ed9c-42f1-bb2e-df55a1263199",
            "sourceColumn": "UsOpen",
            "summarizeBy": "sum"
          },
          {
            "name": "Spurs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ab595db-462f-474b-84f4-bcaeb0326f67",
            "sourceColumn": "Spurs",
            "summarizeBy": "sum"
          },
          {
            "name": "Sharks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db1034a8-85f7-4df9-8f8e-22a3596dd7b6",
            "sourceColumn": "Sharks",
            "summarizeBy": "sum"
          },
          {
            "name": "ContactUs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "782f1f8f-401a-4c57-ae6b-10ac7d1cab0c",
            "sourceColumn": "ContactUs",
            "summarizeBy": "sum"
          },
          {
            "name": "Facilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ee2ddac-aa8c-40c5-b57c-52ba3ff49b99",
            "sourceColumn": "Facilities",
            "summarizeBy": "sum"
          },
          {
            "name": "Total-Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb9582a0-7a7a-437f-a0d2-43841b486b18",
            "sourceColumn": "Total-Volume",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5019f9b8-aec8-4b29-8827-009690d18058",
        "partitions": [
          {
            "name": "metricEmailVolume_CC",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4169f96c-3615-44a9-b663-2a44c9927df8\" = Workspaces{[workspaceId=\"4169f96c-3615-44a9-b663-2a44c9927df8\"]}[Data],",
                "    #\"51917be9-2c04-4aec-ab16-811902d1b7ed\" = #\"4169f96c-3615-44a9-b663-2a44c9927df8\"{[dataflowId=\"51917be9-2c04-4aec-ab16-811902d1b7ed\"]}[Data],",
                "    metricEmailVolume_CC_ = #\"51917be9-2c04-4aec-ab16-811902d1b7ed\"{[entity=\"metricEmailVolume_CC\",version=\"\"]}[Data]",
                "in",
                "    metricEmailVolume_CC_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e22548d0-4ed9-4c99-9040-b992316b46c3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "453526e8-3b61-49be-93f9-beab70a49b2c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e63a3b92-36a2-42d2-9be1-a4ce3908597c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea513d41-bf46-4cf5-9168-7f7e0472d270",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d84e2874-9cdd-4437-91d3-998923b00bd4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ae74760f-40a7-45ea-8a88-6dee200ce1a9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "40ceb981-a828-42db-bea2-65c66424b79e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6e003915-9a41-4270-bce7-312b11d247da",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c3f7fb54-0242-4926-a79b-cab398803e8f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1161b2e9-4f6a-4a2c-a8a3-76b33f6bd4e0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2b3250e9-392a-4488-ab0b-d74b67e00302",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "664504a1-6dc5-4f06-9977-73e64f9077d7",
                "ordinal": 3
              }
            ],
            "lineageTag": "10f7fea6-ee84-49a5-97e0-2b4f27a669a9"
          }
        ],
        "isHidden": true,
        "lineageTag": "24d51106-a1e4-4dc1-8a67-5e83ee285a9c",
        "partitions": [
          {
            "name": "LocalDateTable_e22548d0-4ed9-4c99-9040-b992316b46c3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('metricEmailVolume_CC'[DateID])), 1, 1), Date(Year(MAX('metricEmailVolume_CC'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "metricDuplicateInvoices_AP",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dept",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f468709-131a-482b-baa6-0da978681f95",
            "sourceColumn": "Dept",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "300a3dff-64b1-4cc4-9d29-0f10316958ce",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8f35ab5-ac1c-420e-97ad-e85353d97312",
            "sourceColumn": "Kpi-Name",
            "summarizeBy": "none"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ccc72f91-af58-42e9-9d5c-0939c1a60d1b",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_02f597d7-8fd6-415a-8ffe-05149d46ed5f"
                },
                "isDefault": true,
                "relationship": "3f4893b4-2b8d-4d4b-b61e-20005fc61756"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01184615-326e-4202-a826-3e3ed1e18152",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Prevented",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "716473a8-7b4c-48b0-8839-f720852e86b7",
            "sourceColumn": "Prevented",
            "summarizeBy": "sum"
          },
          {
            "name": "Recovered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2c5bd2aa-3cfb-4fc6-97b2-0c64bf029602",
            "sourceColumn": "Recovered",
            "summarizeBy": "sum"
          },
          {
            "name": "Total-Dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "798eba2e-ed7a-4a9c-bb9a-ee708776b2b3",
            "sourceColumn": "Total-Dollars",
            "summarizeBy": "sum"
          },
          {
            "name": "Total-Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5a180ec1-138e-49ba-80fa-2f7bf11cd08d",
            "sourceColumn": "Total-Volume",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6269bc88-d995-4477-8d1d-a85e6a592d9d",
        "partitions": [
          {
            "name": "metricDuplicateInvoices_AP",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4169f96c-3615-44a9-b663-2a44c9927df8\" = Workspaces{[workspaceId=\"4169f96c-3615-44a9-b663-2a44c9927df8\"]}[Data],",
                "    #\"51917be9-2c04-4aec-ab16-811902d1b7ed\" = #\"4169f96c-3615-44a9-b663-2a44c9927df8\"{[dataflowId=\"51917be9-2c04-4aec-ab16-811902d1b7ed\"]}[Data],",
                "    metricDuplicateInvoices_AP_ = #\"51917be9-2c04-4aec-ab16-811902d1b7ed\"{[entity=\"metricDuplicateInvoices_AP\",version=\"\"]}[Data]",
                "in",
                "    metricDuplicateInvoices_AP_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "metricData_AP",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dept",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a12b19df-aa3e-42fa-a61a-a6e8d03f734e",
            "sourceColumn": "Dept",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "219df2e0-bb9d-4aaf-a557-341f07d8ef28",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a11b7195-b0d9-4b01-b7cf-226b1b382bed",
            "sourceColumn": "Kpi-Name",
            "summarizeBy": "none"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9486033b-ddbd-4b98-a774-3a9025f4f0f7",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ab6b19d9-8dcd-426c-9c07-cbcc889ba4e5"
                },
                "isDefault": true,
                "relationship": "519ddaf5-2c3a-4494-9063-6e4f29caa4d5"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "392926f4-e743-4cf9-953a-8d66fd1cc87c",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "65881551-a93a-4618-ab47-3ceeb2006269",
            "sourceColumn": "Goal",
            "summarizeBy": "sum"
          },
          {
            "name": "Labor Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "32a226cb-e7cd-450c-8725-8ee128a68221",
            "sourceColumn": "Labor Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "SNOW-withinSLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "77abdb99-88d2-4099-88ed-2c7a02bfda53",
            "sourceColumn": "SNOW-withinSLA",
            "summarizeBy": "sum"
          },
          {
            "name": "Recovered-Audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8ff569df-21ad-4cc7-91ef-846637aa5958",
            "sourceColumn": "Recovered-Audit",
            "summarizeBy": "sum"
          },
          {
            "name": "marketPRO-Invoices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "66175b3a-9bcd-4fed-8bd4-d722ae747941",
            "sourceColumn": "marketPRO-Invoices",
            "summarizeBy": "sum"
          },
          {
            "name": "M4A-Invoices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b69c9529-581f-4fc2-930c-6dc13f750306",
            "sourceColumn": "M4A-Invoices",
            "summarizeBy": "sum"
          },
          {
            "name": "Manual-Invoices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4614ed0f-8479-4872-b4ee-e150eec08c4c",
            "sourceColumn": "Manual-Invoices",
            "summarizeBy": "sum"
          },
          {
            "name": "SNow-TotalQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a3c5b89c-4201-42eb-a837-dd361221e2f0",
            "sourceColumn": "SNow-TotalQty",
            "summarizeBy": "sum"
          },
          {
            "name": "PaymentsProcessed-Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67b3aec5-dfe2-4635-93ad-ee55e674ba91",
            "sourceColumn": "PaymentsProcessed-Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Active-Setups",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8897904e-241e-41d2-b1dc-ff8d81c27d11",
            "sourceColumn": "Active-Setups",
            "summarizeBy": "sum"
          },
          {
            "name": "AP_Approvals-Setups",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1aaf3907-1a86-4bf0-a4a4-3f5dc10e72ae",
            "sourceColumn": "AP_Approvals-Setups",
            "summarizeBy": "sum"
          },
          {
            "name": "Manual-Setups",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "37197b60-27a5-4b6c-8812-253cb972785a",
            "sourceColumn": "Manual-Setups",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalDollars-Audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2f8500ce-5c42-4fc1-bfa5-02f69b9f39f6",
            "sourceColumn": "TotalDollars-Audit",
            "summarizeBy": "sum"
          },
          {
            "name": "mor-Numerator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c9678236-c6f9-4198-9c9e-c1d3f4ef80f2",
            "sourceColumn": "mor-Numerator",
            "summarizeBy": "sum"
          },
          {
            "name": "mor-TotalQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "93b8d690-3d46-4fd0-8fce-a86feb11011a",
            "sourceColumn": "mor-TotalQty",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "669a3399-43fd-48f8-8bd1-c41f24e99b8e",
        "partitions": [
          {
            "name": "metricData_AP",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4169f96c-3615-44a9-b663-2a44c9927df8\" = Workspaces{[workspaceId=\"4169f96c-3615-44a9-b663-2a44c9927df8\"]}[Data],",
                "    #\"51917be9-2c04-4aec-ab16-811902d1b7ed\" = #\"4169f96c-3615-44a9-b663-2a44c9927df8\"{[dataflowId=\"51917be9-2c04-4aec-ab16-811902d1b7ed\"]}[Data],",
                "    metricData_AP_ = #\"51917be9-2c04-4aec-ab16-811902d1b7ed\"{[entity=\"metricData_AP\",version=\"\"]}[Data]",
                "in",
                "    metricData_AP_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ab6b19d9-8dcd-426c-9c07-cbcc889ba4e5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "99d05f03-468f-4954-a2ae-bb73158f9927",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2c0261ab-435c-4206-937e-e6962a7240f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a2e60d6b-ef89-4167-b1ed-e9298c2013f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c3fc66fa-adbe-4c06-8abc-69211cb46623",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "626324b5-f3f7-4470-885e-a6bea46b929e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2e25de20-4f87-4ecc-a962-aa80f7e7785c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "06b9df6a-e9a8-4d02-bec1-0f03b80123ef",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0574b134-1310-4a2b-8eae-ae4e1206c0bb",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1d162055-4002-4d00-aac0-7c3aec6a49d6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b12e907c-8519-4b11-8f2f-72efb60df17e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1f084673-1144-43aa-87e1-2a1dfc1e8d61",
                "ordinal": 3
              }
            ],
            "lineageTag": "d88e5676-5169-4774-8cc2-5b5fa105ad60"
          }
        ],
        "isHidden": true,
        "lineageTag": "2601efae-0ad9-4f1f-b74a-825ae16e1108",
        "partitions": [
          {
            "name": "LocalDateTable_ab6b19d9-8dcd-426c-9c07-cbcc889ba4e5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('metricData_AP'[DateID])), 1, 1), Date(Year(MAX('metricData_AP'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_02f597d7-8fd6-415a-8ffe-05149d46ed5f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "89a12bde-6431-4bdf-8ef0-84cb9164c4ae",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "27a44ac4-1846-44e9-9528-f799c2a16b96",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1c86b463-d751-4fb0-a185-951f3190cbd1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dfaaa329-2890-4c00-b4d2-f26097aa2e5d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "02d5a6a3-ee2d-4ee5-bbd9-3e0f7aad7fd7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e05e970f-83c3-4fcb-a875-4e7b1f382907",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8ec5344c-326b-4e44-bec4-074216573661",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9c0044bf-7d06-474d-b951-878dfca3df34",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "56ec6eb9-d9fc-43a8-b9c2-ef79add5fb0e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ea850e3f-9223-4707-9b1c-cd839e0cc65c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "bd692be8-fdf8-4f4d-ba3d-4a0be5ddec18",
                "ordinal": 3
              }
            ],
            "lineageTag": "28a10ad9-6510-4933-9f1c-ecd1f746e829"
          }
        ],
        "isHidden": true,
        "lineageTag": "82915fde-7972-40b9-9abe-c6f6add4a61a",
        "partitions": [
          {
            "name": "LocalDateTable_02f597d7-8fd6-415a-8ffe-05149d46ed5f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('metricDuplicateInvoices_AP'[DateID])), 1, 1), Date(Year(MAX('metricDuplicateInvoices_AP'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "UFR GL_L2_SUMMARY_F (EDWRPRD)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "ORG_VALUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "cb7ee6ea-6900-456f-b689-67b68be5f056",
            "sourceColumn": "ORG_VALUE",
            "sourceLineageTag": "6888ada4-ab17-467f-b63b-c774892bbbfb",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "7c6d1a22-2c59-4a7f-80e5-ad5532fa9a16",
            "sourceColumn": "ACCOUNT_KEY",
            "sourceLineageTag": "6f244cdc-19df-4f58-b299-b61122f1b02e",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORY_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "29d9e16f-a741-4746-84f3-fd0f1a3af7f7",
            "sourceColumn": "CATEGORY_KEY",
            "sourceLineageTag": "04f9b17d-0807-41d3-9509-5a5d2ac80999",
            "summarizeBy": "none"
          },
          {
            "name": "SERVICE_TYPE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "f5bee121-7f8b-445a-b5d8-a58712ddada9",
            "sourceColumn": "SERVICE_TYPE_KEY",
            "sourceLineageTag": "9edcacfa-3351-4833-8b7c-e31e3342fa5b",
            "summarizeBy": "none"
          },
          {
            "name": "BILL_CODE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "a90afd5b-19d8-4b92-88c0-3164896f0293",
            "sourceColumn": "BILL_CODE_KEY",
            "sourceLineageTag": "b7a52cae-50e4-4d72-bc79-f6c8bbcaa8bd",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENCY_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "2d5b8a87-0b5d-4d61-ab53-d2730139dfb0",
            "sourceColumn": "CURRENCY_KEY",
            "sourceLineageTag": "9189b3b7-72c2-41aa-862b-0e4a058d4257",
            "summarizeBy": "none"
          },
          {
            "name": "FISCAL_MONTH_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4943621d-20a5-4ce4-a89f-099444a52fa3",
            "sourceColumn": "FISCAL_MONTH_ID",
            "sourceLineageTag": "9cf6053d-9d69-4f7a-a208-9d9b9306625e",
            "summarizeBy": "count"
          },
          {
            "name": "PTD_ACTUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "57663d50-ac69-437a-a313-a6c0e78aac1b",
            "sourceColumn": "PTD_ACTUAL",
            "sourceLineageTag": "cf3ddd97-5c8b-468b-8f47-0e13334c9302",
            "summarizeBy": "sum"
          },
          {
            "name": "QTD_ACTUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "f806a78e-efa0-487a-93bc-038cb8b0ee2a",
            "sourceColumn": "QTD_ACTUAL",
            "sourceLineageTag": "860a7727-a587-4b43-a715-9741d07ceb65",
            "summarizeBy": "sum"
          },
          {
            "name": "YTD_ACTUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "a8374ea4-2ff9-4642-b779-9f70c17a94b5",
            "sourceColumn": "YTD_ACTUAL",
            "sourceLineageTag": "25159e06-51c2-4b3c-bc9b-eb096a8111e4",
            "summarizeBy": "sum"
          },
          {
            "name": "PTD_BUDGET",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "a2c3c0bf-5312-4f7b-81b9-107c19992e5c",
            "sourceColumn": "PTD_BUDGET",
            "sourceLineageTag": "895afe13-1d69-4107-936f-344405b26c3d",
            "summarizeBy": "sum"
          },
          {
            "name": "QTD_BUDGET",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "428e776e-a2d8-44c4-b55c-95c3e2f528e1",
            "sourceColumn": "QTD_BUDGET",
            "sourceLineageTag": "49fe0bbf-ee7e-45f3-9572-43cd32b82c03",
            "summarizeBy": "sum"
          },
          {
            "name": "YTD_BUDGET",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "f406a0ec-3907-472a-bb06-836179b0028a",
            "sourceColumn": "YTD_BUDGET",
            "sourceLineageTag": "6ed74ec5-47d0-4596-b345-7af27d33ab2b",
            "summarizeBy": "sum"
          },
          {
            "name": "PTD_PROJECTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "0457a015-3520-4fcb-b2dd-26cba9351cad",
            "sourceColumn": "PTD_PROJECTION",
            "sourceLineageTag": "1f81396e-d218-4aa7-adcb-0850e44fe96a",
            "summarizeBy": "sum"
          },
          {
            "name": "QTD_PROJECTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "2495dd93-2eda-4b00-8356-40a26543588d",
            "sourceColumn": "QTD_PROJECTION",
            "sourceLineageTag": "f2699b1e-74aa-47db-bef9-029b449de1e5",
            "summarizeBy": "sum"
          },
          {
            "name": "YTD_PROJECTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "722e5e08-bb11-497c-8f3c-5c78dcb86287",
            "sourceColumn": "YTD_PROJECTION",
            "sourceLineageTag": "b575c5f2-0e40-4090-bae6-4027a6a4d46b",
            "summarizeBy": "sum"
          },
          {
            "name": "CREATE_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "90c94c8e-a9d6-41eb-9bc5-fcb28fc3a935",
            "sourceColumn": "CREATE_DATE",
            "sourceLineageTag": "73adc103-982f-417d-ab16-18a9a086e9c6",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_cf36d641-663a-4643-b10b-9305a2dbabe0"
                },
                "isDefault": true,
                "relationship": "91c5414f-aa87-4230-b190-fbc112014fd8"
              }
            ]
          },
          {
            "name": "SOURCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "4a5fe8ae-a174-454e-b6a1-12653aab746e",
            "sourceColumn": "SOURCE",
            "sourceLineageTag": "65e490fd-b12d-4e0e-aa8c-f5bf79220ee6",
            "summarizeBy": "none"
          },
          {
            "name": "AUDIT_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "6e3ca937-4ba2-4b3a-8511-9631d68dae3d",
            "sourceColumn": "AUDIT_KEY",
            "sourceLineageTag": "e3e08380-77a6-44cb-82e8-350f76ba2c96",
            "summarizeBy": "sum"
          },
          {
            "name": "CONCEPT_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "40f7f608-204a-489a-aa41-d7641e706c49",
            "sourceColumn": "CONCEPT_KEY",
            "sourceLineageTag": "a5c04b6a-9bd9-4ec6-a7f2-e92846d89e2e",
            "summarizeBy": "none"
          },
          {
            "name": "LEDGER_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0cf8c510-1cb9-4142-961a-76a2d761a5b0",
            "sourceColumn": "LEDGER_KEY",
            "sourceLineageTag": "54ce6f3e-bb84-4f74-84b4-6be29d165f7e",
            "summarizeBy": "sum"
          },
          {
            "name": "PTD_FLASH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "ca74d0fc-7e03-42ac-84fc-6fd8356d1d39",
            "sourceColumn": "PTD_FLASH",
            "sourceLineageTag": "c3fe8317-317c-4c1c-b977-90f05e1259c9",
            "summarizeBy": "sum"
          },
          {
            "name": "PTD_BUDGET_VARIANCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "3692f236-2123-4b65-a142-5d2a92058111",
            "sourceColumn": "PTD_BUDGET_VARIANCE",
            "sourceLineageTag": "8bb0536b-054c-4961-96d1-1bde5022a43f",
            "summarizeBy": "sum"
          },
          {
            "name": "PTD_FLASH_VARIANCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "240eec5a-c16a-4190-9f01-6322345291e7",
            "sourceColumn": "PTD_FLASH_VARIANCE",
            "sourceLineageTag": "da64c53b-2673-4527-886e-72a47b44ddd8",
            "summarizeBy": "sum"
          },
          {
            "name": "PTD_PROJECTION_VARIANCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "e2f899be-2d72-4ecd-a6bb-d44a455856d8",
            "sourceColumn": "PTD_PROJECTION_VARIANCE",
            "sourceLineageTag": "70d5f1d4-0ad2-4929-a78f-3658dfa9f0b4",
            "summarizeBy": "sum"
          },
          {
            "name": "TRAN_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "1af063fc-f5a9-4366-9756-a5b1c3aaa04e",
            "sourceColumn": "TRAN_TYPE",
            "sourceLineageTag": "a1404c14-c0df-432d-bba5-4d9ae87a3414",
            "summarizeBy": "none"
          },
          {
            "name": "PY_PTD_ACTUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "f3b6adac-7736-4a65-9f2e-72b2ea4ff020",
            "sourceColumn": "PY_PTD_ACTUAL",
            "sourceLineageTag": "0e2223b5-4dc9-4abb-83a0-e8ce3dd32e50",
            "summarizeBy": "sum"
          },
          {
            "name": "PY_QTD_ACTUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "932b7f0a-fd59-4e11-a867-f21aa01217e5",
            "sourceColumn": "PY_QTD_ACTUAL",
            "sourceLineageTag": "5798048b-6086-4b92-9996-29a884bdc2aa",
            "summarizeBy": "sum"
          },
          {
            "name": "PY_YTD_ACTUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "68ccbdb9-24e6-462a-9495-690d94bea29f",
            "sourceColumn": "PY_YTD_ACTUAL",
            "sourceLineageTag": "238b8d83-047f-4920-98eb-d9613a4e1354",
            "summarizeBy": "sum"
          },
          {
            "name": "SEGMENTATION_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3aa16a8d-ce64-466a-a4d9-c2889ec31097",
            "sourceColumn": "SEGMENTATION_KEY",
            "sourceLineageTag": "90e2ff73-92ec-42b6-8bed-48b6fe2e963d",
            "summarizeBy": "sum"
          },
          {
            "name": "PTD_ACTUAL_BEGIN_BAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "b68bb72f-644d-40a5-93b9-afece34c4351",
            "sourceColumn": "PTD_ACTUAL_BEGIN_BAL",
            "sourceLineageTag": "8f5cce35-c9bf-4e16-8d92-7600be4e95c6",
            "summarizeBy": "sum"
          },
          {
            "name": "PY_PTD_ACTUAL_BEGIN_BAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "b6bea9b1-e05e-43ca-b2cf-21c7392ef9fd",
            "sourceColumn": "PY_PTD_ACTUAL_BEGIN_BAL",
            "sourceLineageTag": "40d29c0b-fe52-492d-9ec0-169075f562c6",
            "summarizeBy": "sum"
          },
          {
            "name": "CURRENCY_D_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "31ec210e-6c4c-40ec-a08a-bc0a411985fd",
            "sourceColumn": "CURRENCY_D_KEY",
            "sourceLineageTag": "508bfdc1-6b3d-4b7c-a861-9ebc958fed28",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "a68afe43-4b6e-4b70-b99a-74cb3ff075b2",
            "sourceColumn": "Month",
            "sourceLineageTag": "47919b1f-bc20-4372-890c-025221411a74",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "1e687660-e2b9-46fc-a5a6-a204581c5c6a",
            "sourceColumn": "Fiscal Year",
            "sourceLineageTag": "c9d44d05-7f75-47d7-81fa-28b74c300917",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "27d53c82-d2e2-4e7a-aab0-11fadc8fed2a",
            "sourceColumn": "Fiscal Period",
            "sourceLineageTag": "9858e84c-b1e8-4b86-a8e4-efe27ef83563",
            "summarizeBy": "none"
          },
          {
            "name": "Month No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "ca108bbc-e610-42e0-80b0-5b8effd7b649",
            "sourceColumn": "Month No",
            "sourceLineageTag": "815b8597-3e53-413f-bd1d-71b672dc4d0e",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55e889ce-d4cf-4c90-84f0-6f2c4450c0b9",
        "measures": [
          {
            "name": "PTD_ACTUAL_FORM",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"PTD_ACTUAL_FORM\", STRING, \"DirectQuery to AS - GBSMetrics_V2.2.1\")",
            "lineageTag": "f9548b89-352f-46b9-ae6e-54443af41a12",
            "sourceLineageTag": "ef127392-0b17-4240-abb9-7d976509e46a"
          }
        ],
        "partitions": [
          {
            "name": "UFR GL_L2_SUMMARY_F (EDWRPRD)",
            "mode": "directQuery",
            "source": {
              "entityName": "UFR GL_L2_SUMMARY_F",
              "expressionSource": "DirectQuery to AS - GBSMetrics_V2.2.1",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "b426c135-ee71-43be-9cb5-4df403f03e0c"
      },
      {
        "name": "LocalDateTable_cf36d641-663a-4643-b10b-9305a2dbabe0",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "isHidden": true,
            "isNullable": false,
            "lineageTag": "e9f6dabd-0834-4616-bc37-6d8a15f4223c",
            "sourceColumn": "Date",
            "sourceLineageTag": "6b46edf4-4e30-4e4d-8ab5-cf90f6e9013d",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "e369c3f5-66ae-4d70-9016-cc10fdd3b6c2",
            "sourceColumn": "Year",
            "sourceLineageTag": "321a8d18-7924-4fbe-a5cb-73b493f834ae",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "2b9ae292-cfc4-4743-bdf4-158c78fd46aa",
            "sourceColumn": "MonthNo",
            "sourceLineageTag": "a7a7badd-5e7a-446a-a89d-4460fa6e2eb5",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a02e3aed-b11d-4cc0-8936-f53bd751dc8b",
            "sortByColumn": "MonthNo",
            "sourceColumn": "Month",
            "sourceLineageTag": "eb182898-4e63-4b6a-a66b-883e8028c9f9",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "d9457b95-56d1-468e-b7d0-f26fe94fd653",
            "sourceColumn": "QuarterNo",
            "sourceLineageTag": "deebf422-fa39-4fa4-839d-c0b217083db3",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8de39800-48f5-44a7-84f6-53f4f18aba14",
            "sortByColumn": "QuarterNo",
            "sourceColumn": "Quarter",
            "sourceLineageTag": "c3058f89-bad1-4e11-87ef-a1967eea4f62",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "63eb3d4c-7be4-4b23-b488-9fe3a91d0e9a",
            "sourceColumn": "Day",
            "sourceLineageTag": "e941f5c3-eb45-445a-a869-833291b247e2",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "eb24d2f1-ee15-4762-bfcb-4d582e59591b",
                "ordinal": 0,
                "sourceLineageTag": "7c282636-cf9d-4265-b5a2-d2d629761392"
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "00738abd-0488-48bf-883d-596d356026b2",
                "ordinal": 1,
                "sourceLineageTag": "bf2d9d95-dbdb-4680-b736-711fc6fc4723"
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "45ae5dbb-e9fc-4bdd-bcfe-8593d600be94",
                "ordinal": 2,
                "sourceLineageTag": "33851afe-05c1-4da1-ac18-e0772d2e5bef"
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "005bece3-2107-47e4-bd08-1a0155a6bb3f",
                "ordinal": 3,
                "sourceLineageTag": "91d11ff0-f6d0-41c7-8380-7ebf909875b0"
              }
            ],
            "lineageTag": "7a038c20-1864-46ea-b48f-7700bc5fbc97",
            "sourceLineageTag": "112c7cba-25e4-4b7d-84c7-f19e10da277f"
          }
        ],
        "lineageTag": "05241be3-caf1-4c28-b2cd-95d36702dd28",
        "partitions": [
          {
            "name": "LocalDateTable_cf36d641-663a-4643-b10b-9305a2dbabe0",
            "mode": "directQuery",
            "source": {
              "entityName": "LocalDateTable_cf36d641-663a-4643-b10b-9305a2dbabe0",
              "expressionSource": "DirectQuery to AS - GBSMetrics_V2.2.1",
              "type": "entity"
            }
          }
        ],
        "showAsVariationsOnly": true,
        "sourceLineageTag": "43438d4e-3bcb-42de-80ea-4d526b6535f7"
      },
      {
        "name": "dim_mor_KpiSortOrder",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9c427e4-8cb5-4665-83c1-880428822edd",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Sort-Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d07b3a39-c9c3-4a77-8f6a-f7bfec1d4243",
            "sourceColumn": "Sort-Order",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "40e652c2-69b7-49ef-858e-bb21d1bdac1f",
            "sortByColumn": "RowNumber",
            "sourceColumn": "Kpi-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Department-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3c21804-8233-4b4a-91fc-6388a76a9a30",
            "sourceColumn": "Department-Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "462ef01f-de21-462d-9aad-52538ac2d6bb",
        "partitions": [
          {
            "name": "dim_mor_KpiSortOrder",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"5370849032884100\" = #\"6501382963390340\"{[Key=\"5370849032884100\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"5370849032884100\",{{\"RowNumber\", Int64.Type}, {\"Sort-Order\", Int64.Type}, {\"Kpi-Name\", type text}, {\"Department-Name\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_mor_s&bSortOrder",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c32326d2-93ac-408a-96f3-85de7627b140",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Sort-Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae757dcc-7582-4094-b6b6-bc216123a806",
            "sourceColumn": "Sort-Order",
            "summarizeBy": "none"
          },
          {
            "name": "Department-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"dim_mor_s&bSortOrder\",\"TableItemName\":\"Department-Name (groups)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a96ec99-c9a6-4bd2-8f6f-c8b901bde7e0",
            "sortByColumn": "Sort-Order",
            "sourceColumn": "Department-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Grouping",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ad5a118-558e-462c-99c0-4cd0a0ab7635",
            "sourceColumn": "Grouping",
            "summarizeBy": "none"
          },
          {
            "name": "Department-Name (groups)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"d\",\"Entity\":\"dim_mor_s&bSortOrder\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Department-Name\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Total\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Department-Name\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Accounts Receivable'\"}}],[{\"Literal\":{\"Value\":\"'Operational Adjustments'\"}}],[{\"Literal\":{\"Value\":\"'Nashville Overhead'\"}}],[{\"Literal\":{\"Value\":\"'Nashville Overhead - HR'\"}}],[{\"Literal\":{\"Value\":\"'Ultimate Payroll Recovery'\"}}],[{\"Literal\":{\"Value\":\"'Corporate Card & Expense Reporting Services'\"}}],[{\"Literal\":{\"Value\":\"'Business Chargeouts'\"}}],[{\"Literal\":{\"Value\":\"'Payment Services'\"}}],[{\"Literal\":{\"Value\":\"'Payroll Systems'\"}}],[{\"Literal\":{\"Value\":\"'Payroll Projects and System Administration'\"}}],[{\"Literal\":{\"Value\":\"'Cash & Banking'\"}}],[{\"Literal\":{\"Value\":\"'Fixed Assets'\"}}],[{\"Literal\":{\"Value\":\"'General Ledger'\"}}],[{\"Literal\":{\"Value\":\"'PR GL & Business Compliance'\"}}],[{\"Literal\":{\"Value\":\"'Accounts Payable'\"}}],[{\"Literal\":{\"Value\":\"'Payroll'\"}}],[{\"Literal\":{\"Value\":\"'Contact Center'\"}}],[{\"Literal\":{\"Value\":\"'PMO'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('dim_mor_s&bSortOrder'[Department-Name]),",
              "\t\"(Blank)\",",
              "\t'dim_mor_s&bSortOrder'[Department-Name] IN {\"Accounts Receivable\",",
              "\t\t\"Operational Adjustments\",",
              "\t\t\"Nashville Overhead\",",
              "\t\t\"Nashville Overhead - HR\",",
              "\t\t\"Ultimate Payroll Recovery\",",
              "\t\t\"Corporate Card & Expense Reporting Services\",",
              "\t\t\"Business Chargeouts\",",
              "\t\t\"Payment Services\",",
              "\t\t\"Payroll Systems\",",
              "\t\t\"Payroll Projects and System Administration\",",
              "\t\t\"Cash & Banking\",",
              "\t\t\"Fixed Assets\",",
              "\t\t\"General Ledger\",",
              "\t\t\"PR GL & Business Compliance\",",
              "\t\t\"Accounts Payable\",",
              "\t\t\"Payroll\",",
              "\t\t\"Contact Center\",",
              "\t\t\"PMO\"},",
              "\t\"Total\",",
              "\t'dim_mor_s&bSortOrder'[Department-Name]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "dim_mor_s&bSortOrder"
                          }
                        },
                        "Property": "Department-Name"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "31b92b59-ef9e-41a7-a114-fee3a54e4172",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "2fb832fc-3e9b-45d2-92ac-c1bc81664275",
        "partitions": [
          {
            "name": "dim_mor_s&bSortOrder",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"2696364307730308\" = #\"6501382963390340\"{[Key=\"2696364307730308\"]}[Data]",
                "in",
                "    #\"2696364307730308\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_ProfitCenters_hr_tbls",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "015213f9-4331-4680-93e4-1b4288fb04d3",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54b5439d-75aa-4552-8158-b0db0370e8e0",
            "sourceColumn": "ProfitCenter ID",
            "summarizeBy": "none"
          },
          {
            "name": "Parent ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04d19406-9577-4aef-82ef-0020cfef9425",
            "sourceColumn": "Parent ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "Org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfea89fc-a4f8-4cc3-a073-cc2bac923f65",
            "sourceColumn": "Org",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "864aed2a-200a-48b1-b7d5-ffe4fd3e7bdd",
            "sourceColumn": "ProfitCenter Code",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6e70cc0-3e24-4275-a41c-d8e91562b05e",
            "sourceColumn": "ProfitCenter Name",
            "summarizeBy": "none"
          },
          {
            "name": "Is GBS ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce72fdd8-08cc-4705-a22e-d73c26328dfe",
            "sourceColumn": "Is GBS ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "Department ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34028011-500b-4702-abe9-74a28fadf7bf",
            "sourceColumn": "Department ID",
            "summarizeBy": "none"
          },
          {
            "name": "Department Name (Lookup)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8f1c591-ab68-405a-ba70-a4288117e1f2",
            "sourceColumn": "Department Name (Lookup)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e8f17760-1b34-4840-b0f2-a0b9e5f46257",
        "partitions": [
          {
            "name": "dim_ProfitCenters_hr_tbls",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"6701410573832068\" = #\"6501382963390340\"{[Key=\"6701410573832068\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"6701410573832068\",{{\"ProfitCenter Code\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_mor_ProfitCenters",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9949c47-56b2-48d7-9f92-68eb9a8187b8",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "938e6005-1555-40e8-a0c0-1882d0a68ce5",
            "sourceColumn": "ProfitCenter-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Department-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa8c4fc3-9ba5-4832-8a9f-9898ac4da8a7",
            "sourceColumn": "Department-Name",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter-Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9de13461-c10c-4809-8533-e248b726ab86",
            "sourceColumn": "ProfitCenter-Code",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62918b7e-12ea-484a-9d10-457d77d48fb7",
            "sourceColumn": "ProfitCenter-Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7c6b548a-292f-4f94-b7df-009c768aa625",
        "partitions": [
          {
            "name": "dim_mor_ProfitCenters",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"8593446746935172\" = #\"6501382963390340\"{[Key=\"8593446746935172\"]}[Data]",
                "in",
                "    #\"8593446746935172\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_mor_KPIs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b48fd45-4dd0-487b-8b10-6fcf1911713c",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b827d2be-561e-41ce-ba99-a81aa0bdd626",
            "sourceColumn": "Kpi-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d85bf86a-d89d-48ad-8ef7-18ebf2a57299",
            "sourceColumn": "Kpi-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "54bee36b-ca9a-435b-8d01-2d2fd140621e",
            "sourceColumn": "Kpi-Goal",
            "summarizeBy": "sum"
          },
          {
            "name": "Team-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "210018e8-97fc-4dbb-ace8-d23afc885f19",
            "sourceColumn": "Team-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Department-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5e72c5a-e227-4454-af89-24d8fcc36dc4",
            "sourceColumn": "Department-Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "13317097-4822-4d40-a1b3-b9d21634b4cb",
        "partitions": [
          {
            "name": "dim_mor_KPIs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"3032735408934788\" = #\"6501382963390340\"{[Key=\"3032735408934788\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"3032735408934788\",{{\"Kpi-ID\", type text}, {\"Kpi-Goal\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_mor_Comments-GBS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1137420-c86f-46b6-b3ad-39baaf24ee69",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Period-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b6ad769-f4da-4313-a8bf-5144aa1e8c2f",
            "sourceColumn": "Period-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a48c209f-b33e-4a76-a603-40c8351c5ac0",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbd5b9c9-65a6-492f-b043-95e3a21f2c0d",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal-Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c87ef1a-daa3-43cf-94ed-b1917eb04eff",
            "sourceColumn": "Fiscal-Period",
            "summarizeBy": "none"
          },
          {
            "name": "Op-Highlights",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b61fdaa-06f2-4ab5-a589-2f27e07cb519",
            "sourceColumn": "Op-Highlights",
            "summarizeBy": "none"
          },
          {
            "name": "Headcount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb5bc6fe-0710-49f9-b8b6-d20fbda8467e",
            "sourceColumn": "Headcount",
            "summarizeBy": "none"
          },
          {
            "name": "Budget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7e09070-573a-439f-8e2c-314f1f53df3d",
            "sourceColumn": "Budget",
            "summarizeBy": "none"
          },
          {
            "name": "AP-CostPerInvoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aefb8347-258d-4d60-8a79-bcae7b65f0da",
            "sourceColumn": "AP-CostPerInvoice",
            "summarizeBy": "none"
          },
          {
            "name": "AP-InvoiceSLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9deab6e-7b92-4466-b843-29e77b5849b4",
            "sourceColumn": "AP-InvoiceSLA",
            "summarizeBy": "none"
          },
          {
            "name": "AP-CostPerPayment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4abe24d7-17b2-42bc-b7de-c1a078a94770",
            "sourceColumn": "AP-CostPerPayment",
            "summarizeBy": "none"
          },
          {
            "name": "AP-BankingSLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2456d3fd-3523-4a1b-95fd-b2ef3b5f04f5",
            "sourceColumn": "AP-BankingSLA",
            "summarizeBy": "none"
          },
          {
            "name": "AP-CostPerVendor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35314c94-817c-4267-baca-31887a42ab14",
            "sourceColumn": "AP-CostPerVendor",
            "summarizeBy": "none"
          },
          {
            "name": "AP-VendorControlSLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6535192-2c9d-41e4-b23e-6f4daf28b772",
            "sourceColumn": "AP-VendorControlSLA",
            "summarizeBy": "none"
          },
          {
            "name": "AP-AuditRecoveryRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14ca9346-125f-4e96-9691-cab10fb7c9c3",
            "sourceColumn": "AP-AuditRecoveryRate",
            "summarizeBy": "none"
          },
          {
            "name": "AP-AuditRecoveryVolume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd7853a6-2c60-4797-b9af-b98166667896",
            "sourceColumn": "AP-AuditRecoveryVolume",
            "summarizeBy": "none"
          },
          {
            "name": "AR_IncidentResolution-SLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a3e20ba-d1f3-4e72-a2d7-63e03668c3f2",
            "sourceColumn": "AR_IncidentResolution-SLA",
            "summarizeBy": "none"
          },
          {
            "name": "AR_UnappliedCash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "473cfe0f-82aa-42c1-8ffd-c4956bbb66bd",
            "sourceColumn": "AR_UnappliedCash",
            "summarizeBy": "none"
          },
          {
            "name": "AR_CostPerManualReceipt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e64b63c-f3d3-4bf8-b7d5-dfab3d5c036f",
            "sourceColumn": "AR_CostPerManualReceipt",
            "summarizeBy": "none"
          },
          {
            "name": "AR_CostPerSnowRequest",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4edbf940-168a-4577-945f-4ff5bbd5fbf8",
            "sourceColumn": "AR_CostPerSnowRequest",
            "summarizeBy": "none"
          },
          {
            "name": "CB_DebitPendingItems-US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2fed5dd-2051-4303-86b2-5c7196e5dd59",
            "sourceColumn": "CB_DebitPendingItems-US",
            "summarizeBy": "none"
          },
          {
            "name": "CB_BankAccountRecon-US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d89bd33a-a0da-43f1-97d1-78e346193521",
            "sourceColumn": "CB_BankAccountRecon-US",
            "summarizeBy": "none"
          },
          {
            "name": "CB_CostPerManualReconItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25a2a5b0-9dc8-4fb2-8b56-fbcb6b0e3e62",
            "sourceColumn": "CB_CostPerManualReconItem",
            "summarizeBy": "none"
          },
          {
            "name": "CB_DebitPendingItems-CAN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a136f57-0e01-4cc1-b820-d162b4679cd1",
            "sourceColumn": "CB_DebitPendingItems-CAN",
            "summarizeBy": "none"
          },
          {
            "name": "CB_BankAccountRecon-CAN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd4bf6bb-c132-4e32-b683-c485deb4e79f",
            "sourceColumn": "CB_BankAccountRecon-CAN",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CIP-Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0176f9a-da22-40b1-9391-ea8e68a4dcdd",
            "sourceColumn": "FA_CIP-Balance",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CIP-Balance-Stale",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69aa8809-776a-4780-b1e1-0919377ee186",
            "sourceColumn": "FA_CIP-Balance-Stale",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CERsClosedTimely",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d1cf049-b668-4116-9055-d7b7615d2d39",
            "sourceColumn": "FA_CERsClosedTimely",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CostPerTransaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9368606f-5a36-484d-bb53-70eba83fc7fd",
            "sourceColumn": "FA_CostPerTransaction",
            "summarizeBy": "none"
          },
          {
            "name": "FA_ReconciliationsPrepared&Reviewed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc942e14-097e-499e-8fdb-fc9a492a5a25",
            "sourceColumn": "FA_ReconciliationsPrepared&Reviewed",
            "summarizeBy": "none"
          },
          {
            "name": "GL_AccurateJournalEntries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73baaa43-74eb-4dfd-a2f7-938b7dcb56b6",
            "sourceColumn": "GL_AccurateJournalEntries",
            "summarizeBy": "none"
          },
          {
            "name": "GL_CostPerManualJournalEntries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c642562d-98c8-40d4-8ada-47690b8ae5c0",
            "sourceColumn": "GL_CostPerManualJournalEntries",
            "summarizeBy": "none"
          },
          {
            "name": "GL_ReconciliationsPrepared&Reviewed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0895a38-834e-4a74-a9ae-35b3600cce97",
            "sourceColumn": "GL_ReconciliationsPrepared&Reviewed",
            "summarizeBy": "none"
          },
          {
            "name": "PR_CostPerPayment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c14b77b5-0be9-46b5-92c2-ddd4e28e6ce1",
            "sourceColumn": "PR_CostPerPayment",
            "summarizeBy": "none"
          },
          {
            "name": "PR_eFormResolution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a829032-a7bf-4090-8177-7695ebf08422",
            "sourceColumn": "PR_eFormResolution",
            "summarizeBy": "none"
          },
          {
            "name": "PR_IncidentResolution-SLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fd23415-2184-4d5b-8e85-b22f2d06ce16",
            "sourceColumn": "PR_IncidentResolution-SLA",
            "summarizeBy": "none"
          },
          {
            "name": "BSS_CustomerSatisfaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2808b538-d4f1-4118-b879-c5f1797a00da",
            "sourceColumn": "BSS_CustomerSatisfaction",
            "summarizeBy": "none"
          },
          {
            "name": "BSS_SurveyParticipationRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f586ae2-9dd5-43f0-99f4-6e6fe6a36883",
            "sourceColumn": "BSS_SurveyParticipationRate",
            "summarizeBy": "none"
          },
          {
            "name": "BSS_AverageAnswerTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d3eb4b2-f4ae-46ff-86a7-fb4f39ef5413",
            "sourceColumn": "BSS_AverageAnswerTime",
            "summarizeBy": "none"
          },
          {
            "name": "BSS_AbandonmentRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8c37296-aa42-4666-a3de-2a5e81b4c54e",
            "sourceColumn": "BSS_AbandonmentRate",
            "summarizeBy": "none"
          },
          {
            "name": "BSS_CallsAnsweredWithinSLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbc87173-0c14-4cda-a20e-8a3285b08035",
            "sourceColumn": "BSS_CallsAnsweredWithinSLA",
            "summarizeBy": "none"
          },
          {
            "name": "BSS_Callbacks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09288c0e-3ac7-4397-b6a5-4e537eb1c277",
            "sourceColumn": "BSS_Callbacks",
            "summarizeBy": "none"
          },
          {
            "name": "BSS_EmailVolume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fb86928-9d0b-44b7-8b1e-f38f1544b19d",
            "sourceColumn": "BSS_EmailVolume",
            "summarizeBy": "none"
          },
          {
            "name": "PS_CustomerSatisfaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6255fa6d-1dd2-4b74-9caf-b18d16c1da05",
            "sourceColumn": "PS_CustomerSatisfaction",
            "summarizeBy": "none"
          },
          {
            "name": "PS_AverageAnswerTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c1081f4-6fad-4520-8a51-38a44b0a9de2",
            "sourceColumn": "PS_AverageAnswerTime",
            "summarizeBy": "none"
          },
          {
            "name": "PS_AbandonmentRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64c73c4b-c7f1-4bcd-ac59-d3764fdbff37",
            "sourceColumn": "PS_AbandonmentRate",
            "summarizeBy": "none"
          },
          {
            "name": "PS_InboundEmailEfficiency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e50393f6-8561-4d2a-a3d4-faafd23dbcd0",
            "sourceColumn": "PS_InboundEmailEfficiency",
            "summarizeBy": "none"
          },
          {
            "name": "Date-Submitted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c9b2f5d-68a4-4325-ba74-c1cdc91acd71",
            "sourceColumn": "Date-Submitted",
            "summarizeBy": "none"
          },
          {
            "name": "Created By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "542ddee8-32a9-4f77-a949-8be671299430",
            "sourceColumn": "Created By",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1e957053-d290-4c31-808e-41cb76470547",
        "partitions": [
          {
            "name": "fact_mor_Comments-GBS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"7901354777333636\" = #\"6501382963390340\"{[Key=\"7901354777333636\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"7901354777333636\",{{\"Period-ID\", type text}, {\"Fiscal-Period\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_ac_MetricList",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f7a6b0f-aa1a-46fb-bf2a-8eac0a3e7f53",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "AC-Metric-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c408d18f-274a-4fda-a655-6f2dab6ad1ec",
            "sourceColumn": "AC-Metric-ID",
            "summarizeBy": "count"
          },
          {
            "name": "AC-Metric-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05b756ac-7ef1-47a2-b2f9-8fd05b98fa00",
            "sourceColumn": "AC-Metric-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96e5b969-fcae-4ca0-a186-91dd6167c810",
            "sourceColumn": "Kpi-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Kpi-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c26ca38-5574-4a3f-8746-f0054f292448",
            "sortByColumn": "AC-Metric-ID",
            "sourceColumn": "Kpi-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4a75a2d-6f87-4439-8415-c8caa7261119",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16816b82-afab-418e-b476-6c5c958cc31e",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "AC-Metric-Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e54b8c16-6e81-4ff2-b856-6e6cce5cc6a8",
            "sourceColumn": "AC-Metric-Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "418afaab-b09f-4c80-ba4f-8cd6669a5a1c",
        "partitions": [
          {
            "name": "dim_ac_MetricList",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"5749115392577412\" = #\"6501382963390340\"{[Key=\"5749115392577412\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"5749115392577412\",{{\"AC-Metric-ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_ac_SortList",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a1858f0-c621-4a6b-a3d4-456cb5d4ff81",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Metric-Sort-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "40096804-b2ad-4f2f-b77f-8af09447a528",
            "sourceColumn": "Metric-Sort-ID",
            "summarizeBy": "none"
          },
          {
            "name": "AC-Metric-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "1848efcd-7885-4166-9728-fae2e395a9a3",
            "sortByColumn": "Metric-Sort-ID",
            "sourceColumn": "AC-Metric-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "702696e2-adc2-45cd-8617-4acc6d1970c1",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "aeb7898f-7893-4ed4-bfb6-655f85f384f7",
        "partitions": [
          {
            "name": "dim_ac_SortList",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"1070330491654020\" = #\"6501382963390340\"{[Key=\"1070330491654020\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"1070330491654020\",{{\"Metric-Sort-ID\", Int64.Type}, {\"RowNumber\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_ac_TeamSort",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2818c894-eafa-4c79-8a85-0dd3a8a542af",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "AC-Team-Sort-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "888362c1-7c4f-450a-b3d5-eba12492f607",
            "sourceColumn": "AC-Team-Sort-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6c8da5e-8568-4115-a4a9-9d8e656159f3",
            "sortByColumn": "AC-Team-Sort-ID",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5421a243-bb64-420e-a74f-a1fe0914fe66",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1709ee1b-1f9f-4a5a-9257-ebfca41f15a3",
        "partitions": [
          {
            "name": "dim_ac_TeamSort",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"1070871657533316\" = #\"6501382963390340\"{[Key=\"1070871657533316\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"1070871657533316\",{{\"AC-Team-Sort-ID\", Int64.Type}, {\"RowNumber\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_mor_ccTeams",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f6022c6-6f60-4f31-bd78-86065d064f32",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Team-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92a8d15c-b26f-427f-836d-6f2bfd5c7d08",
            "sourceColumn": "Team-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Department-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9ba186f-4598-4ccc-89d7-792aec3470f8",
            "sourceColumn": "Department-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Team-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8ea829d-66e0-4b22-8333-ea727e48ff46",
            "sourceColumn": "Team-Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6a94a9f5-5299-48f8-8185-7b5fc8668e42",
        "partitions": [
          {
            "name": "dim_mor_ccTeams",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"2853731708129156\" = #\"6501382963390340\"{[Key=\"2853731708129156\"]}[Data]",
                "in",
                "    #\"2853731708129156\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_mor_HeadcountPlan",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70cccc9e-812e-462c-b38e-cf68aa2b103d",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbac8e44-4309-4e45-93d6-c3b984ff8270",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a04c2c93-30e9-43b7-a5cb-123bf3219ed4",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "PFS-Team-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de4f41a1-3b67-40f1-abc7-4c184faa5c99",
            "sourceColumn": "PFS-Team-Name",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3461f26d-af3c-4d9c-b0be-7fc362d6c993",
            "sourceColumn": "ProfitCenter Code",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "281ff8c2-adc0-4c4d-8557-62c55e9ba9c8",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Plan-Headcount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7b986c94-22d4-439e-b611-28f95c449112",
            "sourceColumn": "Plan-Headcount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "70285e3e-2608-4309-b781-847d6dce07bf",
        "partitions": [
          {
            "name": "fact_mor_HeadcountPlan",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"6501382963390340\" = Source{[Key=\"6501382963390340\"]}[Data],",
                "    #\"305069123653508\" = #\"6501382963390340\"{[Key=\"305069123653508\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"305069123653508\",{{\"ProfitCenter Code\", type text}, {\"PeriodID\", type text}, {\"Plan-Headcount\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}