{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_date_fiscal_DateKey\",\"dim_date_fiscal_MonthKey\",\"dim_date_fiscal_TTMKey\",\"dim_gbs_ProfitCenter\",\"dim_gbs_Lockbox\",\"fact_Oracle_Export_US_AccountsReceivable\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.141.1451.0 (25.03)+5007b75f0f7edbed506e31fcb76584cd6d711788"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"CalcGroup\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "relationships": [
      {
        "name": "38e61474-9256-420a-b8af-b917163de6f4",
        "fromColumn": "DateID",
        "fromTable": "dim_date_fiscal_DateKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_85f61c1d-c101-4656-afa2-8b2ed3b11878"
      },
      {
        "name": "0a211ae5-32ad-4d51-bee1-6358fb55235f",
        "fromColumn": "DateID",
        "fromTable": "dim_date_fiscal_MonthKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_336abc93-57dc-46da-acaa-273f0a494a3a"
      },
      {
        "name": "ae769ad1-81d4-4e58-bbe0-51b8ee55cd03",
        "fromColumn": "DateID - Mmm",
        "fromTable": "dim_date_fiscal_MonthKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d7c77918-59e0-47ad-bc6e-76d5c4af2469"
      },
      {
        "name": "b1be2d67-588b-4b82-8b30-a2a33d486f49",
        "fromColumn": "DateID",
        "fromTable": "dim_date_fiscal_TTMKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_07d4074b-6db8-4afb-a27b-ef3a916e6b94"
      },
      {
        "name": "97a209d9-29b4-4ead-9b95-37131971c422",
        "fromColumn": "PeriodID",
        "fromTable": "dim_date_fiscal_DateKey",
        "toColumn": "PeriodID",
        "toTable": "dim_date_fiscal_MonthKey"
      },
      {
        "name": "0cba7a38-1d89-4876-8a50-57ba32484563",
        "fromColumn": "batch_date",
        "fromTable": "fact_Oracle_Export_US_AccountsReceivable",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4f36f013-85ec-46ae-b5cc-2de882cecbde"
      },
      {
        "name": "774910b3-8978-4e83-97b3-59f9457eb467",
        "fromColumn": "deposit_date",
        "fromTable": "fact_Oracle_Export_US_AccountsReceivable",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_547f1543-f30f-4b83-a32b-b45c0658ef64"
      },
      {
        "name": "73029d18-aaff-47ea-93fd-17dbb0d40f10",
        "fromColumn": "loaded_date",
        "fromTable": "fact_Oracle_Export_US_AccountsReceivable",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0442fb98-f7b4-4f40-8cd6-d52cd82da18a"
      },
      {
        "name": "6f77873e-e5b7-a215-20f0-7db3061b12bd",
        "fromColumn": "gl_date",
        "fromTable": "fact_Oracle_Export_US_AccountsReceivable",
        "toColumn": "DateID",
        "toTable": "dim_date_fiscal_DateKey"
      },
      {
        "name": "4c694d37-b1e1-97fa-b55d-113727fb1fbe",
        "fromColumn": "batch_source",
        "fromTable": "fact_Oracle_Export_US_AccountsReceivable",
        "toColumn": "Batch-Name",
        "toTable": "dim_gbs_Lockbox"
      },
      {
        "name": "2b3ede94-29ed-46d1-9ff4-0bfeda61fe93",
        "fromColumn": "Start of week",
        "fromTable": "dim_date_fiscal_MonthKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e062b3fa-97d5-48ca-bcc0-2eea9ab478b3"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_dca4052d-aff4-404f-874c-a1f4d0e63d60",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b9cbf0fe-e0c0-4bb8-895d-cefaf6e70b6e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "db879203-3de4-4ad5-ab30-5e56febccefe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5c707b52-fc4d-4ead-afa3-256439174284",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "60c70586-dc33-4a67-8e88-d867afd76452",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "87c486f0-ba38-445b-a22e-f76eac3dcbfb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1049da36-ba96-4705-9739-214fcd095d48",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "331f8aaa-26fe-4838-8655-2664d5f99396",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fa5d7f91-c94e-4faf-85b1-f822993deb91",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6aad10b9-8ef4-45c3-b658-e637511e977e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "17a3c838-b639-4c7d-a942-858ada4d1b3e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b03cf8a3-1d10-4f33-a2e0-635e4599b43d",
                "ordinal": 3
              }
            ],
            "lineageTag": "078f0a67-d305-4d64-819f-aa449cdce262"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "d0f6d403-e8ad-4cf5-a063-38427dba342a",
        "partitions": [
          {
            "name": "DateTableTemplate_dca4052d-aff4-404f-874c-a1f4d0e63d60",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": ".Measures",
        "calculationGroup": {},
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fa159de8-74ac-4579-b081-e3c0c50378e7",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "7942fe90-46a3-411e-bf53-8ac5477598f1",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4a13359a-294c-41ce-90aa-75afee8f7e30",
        "measures": [
          {
            "name": "Control Amount",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[control_amount] )",
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "8917e2b7-d207-4797-a8b0-3140375cf30d"
          },
          {
            "name": "Applied Amount",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[applied_amount] )",
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "9ebbfaf8-335e-4a7a-9763-9864e4c9a823"
          },
          {
            "name": "Unapplied Amount",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[unapplied_amount] )",
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "a9707cfa-f303-4966-8eb4-359e71b483f9"
          },
          {
            "name": "On Account Amount",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[on_account_amount] )",
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "db53f0a2-1723-42da-b8bb-4d64488ce23f"
          },
          {
            "name": "Unidentified Amount",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[unidentified_amount] )",
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "8aa07c31-ed2c-484b-8be6-a8d234db9491"
          },
          {
            "name": "Apply Rate (Amount)",
            "displayFolder": "Hit_Rates",
            "expression": "[Applied Amount] / [Control Amount]",
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "8d7c2972-eb5d-4c11-bd9d-4009deb88f15"
          },
          {
            "name": "Control Count",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[control_count] )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "f13f01f4-a64d-489a-b9f9-3edd1befe940"
          },
          {
            "name": "Applied Count",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[applied_count] )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "7068dbbe-b74a-4cf4-a50d-a3cfa6004f68"
          },
          {
            "name": "Unapplied Count",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[unapplied_count] )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "c035edfa-7be8-41a6-a59e-5bd993ae7937"
          },
          {
            "name": "On Account Count",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[on_account_count] )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "f8f20b8b-8f12-43c2-a785-0f59540bc863"
          },
          {
            "name": "Unidentified Count",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[unidentified_count] )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "77592922-15d6-4873-a2b7-93a8aa1e9166"
          },
          {
            "name": "Miscellaneous Count",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[miscellaneous_count] )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "fcdded14-a9c7-4c87-b2de-3de2e4b0f7f2"
          },
          {
            "name": "Miscellaneous Amount",
            "displayFolder": ".Oracle_Export_US",
            "expression": "SUM( fact_Oracle_Export_US_AccountsReceivable[miscellaneous_amount] )",
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "bb53cf62-56e7-43f0-b00d-6da4b38951c6"
          },
          {
            "name": "JPMC Control Amount",
            "displayFolder": ".base",
            "expression": [
              "\r",
              "    CALCULATE( \r",
              "        [Control Amount] , \r",
              "        FILTER( \r",
              "            dim_gbs_Lockbox , \r",
              "            dim_gbs_Lockbox[Type] = \"JPMC\" ) ) "
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "1aee8d2f-c6c7-46c7-bf26-e7ffd650fbc6"
          },
          {
            "name": "Lockbox Type",
            "displayFolder": ".base",
            "expression": "SELECTEDVALUE( dim_gbs_Lockbox[Type] )",
            "lineageTag": "9df8c3c1-a775-49e0-80ea-e237ff95c777"
          },
          {
            "name": "Variance - Bank to Oracle",
            "displayFolder": ".base",
            "expression": "[Control Amount] - [JPMC Control Amount]",
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "e44808ef-a629-49a7-8f16-cf93eb638203"
          },
          {
            "name": "Manually Applied Count",
            "displayFolder": ".base",
            "expression": "CALCULATE( [Unapplied Count] + [On Account Count] + [Unidentified Count] + [Miscellaneous Count] )",
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "78a437d3-40bc-4385-867f-b67e3fba0512"
          },
          {
            "name": "Control Amount - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Control Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "855a2069-2309-4669-9a77-f4872d051f8a"
          },
          {
            "name": "Payment Type",
            "displayFolder": ".base",
            "expression": [
              "\r",
              "CALCULATE( \r",
              "    IF( VALUES( fact_Oracle_Export_US_AccountsReceivable[transmission_batch] ) > 900 , \"Electronic\" , \r",
              "    \"Check\"\r",
              "    )\r",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e26f4ddc-2323-4218-8e50-c6790ccdec8b"
          },
          {
            "name": "Control Count - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Control Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "a89e72e5-3a02-4d07-9342-feeed8b6ff8d"
          },
          {
            "name": "Applied Amount - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Applied Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "ebbeb5b5-8646-4fff-8ffa-52e90754cbf8"
          },
          {
            "name": "Applied Count - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Applied Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "21bf021e-90e8-4694-a4ea-8303cd1c2a1e"
          },
          {
            "name": "Unapplied Amount - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Unapplied Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "a6ae6c62-bd5e-4c4e-ae4a-d1fec86902d1"
          },
          {
            "name": "Unidentified Count - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Unidentified Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "34819867-3055-4f0c-8597-96ae2a4d3e1a"
          },
          {
            "name": "Unidentified Amount - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Unidentified Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "bdfb873c-76f3-4f23-b1f0-4d1206a051db"
          },
          {
            "name": "On Account Amount - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [On Account Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "db88bb13-39e3-46bf-8a24-e6e536eace07"
          },
          {
            "name": "On Account Count - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [On Account Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "ea2b1910-a084-41fb-b799-b2d8b030c283"
          },
          {
            "name": "Unapplied Count - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Unapplied Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "3d7decc2-75ed-4951-b2b0-3b94361aae54"
          },
          {
            "name": "Control Amount - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Control Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "aa47f15a-34b4-41da-bcaf-abb20faf095b"
          },
          {
            "name": "Control Count - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Control Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "75cdf031-1358-4d21-9d5e-3bfde8eba1e6"
          },
          {
            "name": "Applied Count - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Applied Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "e410eb3f-a824-4e2f-900f-ee299dda1eab"
          },
          {
            "name": "Manually Applied Count - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Manually Applied Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "a1ef70ee-708d-4fd3-ae44-d3fce798a681"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Manually Applied Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "59a34c45-a7a4-4746-9cd8-2a05002e223a"
          },
          {
            "name": "Weeks in Fiscal Period",
            "displayFolder": ".base",
            "expression": "MAX( dim_date_fiscal_DateKey[WeekInFM] )",
            "formatString": "0",
            "lineageTag": "e2d5cff0-294b-46e4-aad9-3f916805cd40"
          },
          {
            "name": "Manual Count Avg Per Week",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".base",
            "expression": "[Manually Applied Count] / [Weeks in Fiscal Period]",
            "lineageTag": "e5eeb30e-2c82-422a-88d2-9951992d500a"
          },
          {
            "name": "Manual Avg Per Week - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Manual Count Avg Per Week] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "04b64dec-804c-4a23-95dc-7d5bca4153d3"
          },
          {
            "name": "Weeks in Period - 24 Month Rolling",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Weeks in Fiscal Period] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatString": "0",
            "lineageTag": "5373e86b-63a4-40b9-bf8a-9edc0047e3a0"
          },
          {
            "name": "Apply Rate - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Apply Rate (Amount)] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "38280cad-3538-43cf-9eaa-439e958ad534"
          },
          {
            "name": "Hit Rate (Count)",
            "displayFolder": "Hit_Rates",
            "expression": "[Applied Count] / [Control Count]",
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "7256d206-bd3e-44a0-910b-650b23124723"
          },
          {
            "name": "Hit Rate - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Hit Rate (Count)] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "dced6725-22a2-4618-a213-f019323977dc"
          },
          {
            "name": "Applied Amount - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Applied Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "a9b67c1f-ece2-4c3b-bdb7-29e747873f7e"
          },
          {
            "name": "On Account Count - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [On Account Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "6c98009a-8f98-4b33-855a-59e9205fa055"
          },
          {
            "name": "On Account Amount - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [On Account Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "b5292ad7-c96c-40ce-888a-247dd590feaa"
          },
          {
            "name": "Unapplied Count - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Unapplied Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "ac7fb7fb-00d4-48b2-bd76-0263aebce8d8"
          },
          {
            "name": "Unidentified Amount - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Unidentified Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "86940210-a4ba-49e2-a96a-06a027f0b8ae"
          },
          {
            "name": "Unidentified Count - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Unidentified Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "e63045f4-e0bc-49e2-9646-4195361ed23b"
          },
          {
            "name": "Unapplied Amount Rate",
            "displayFolder": ".base",
            "expression": "DIVIDE( [Unapplied Amount] , [Control Amount] ) ",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "ebf6bfb0-5e1c-4068-a541-d2cc76231bcf"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount % - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [AR Hit Rates Manually Applied Amount %] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "2d13e742-c516-4f1a-90ab-0075e2b87029"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount (Last Day)",
            "displayFolder": "Last_Day",
            "expression": [
              "",
              "",
              "VAR _lastDate = LASTDATE( dim_date_fiscal_DateKey[DateID] )",
              "",
              "VAR _result = ",
              "CALCULATE(",
              "    [Manually Applied Amount] ,",
              "    LASTDATE(dim_date_fiscal_DateKey[DateID])",
              ")",
              "",
              "RETURN ",
              "_result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "9ecc7a00-6687-424a-a793-573bdc38846a"
          },
          {
            "name": "Last Date of Fiscal Period",
            "displayFolder": ".base",
            "expression": "LASTDATE(dim_date_fiscal_DateKey[DateID])",
            "formatString": "General Date",
            "lineageTag": "b350979a-5110-4b1b-b7a9-35221e5b2ff9"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount (Last Day) - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [AR Hit Rates Manually Applied Amount (Last Day)] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "8e8e2a20-fae1-4812-87e0-e969a94e75bc"
          },
          {
            "name": "Control Amount (Last Day)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Last_Day",
            "expression": [
              "",
              "",
              "VAR _lastDate = LASTDATE( dim_date_fiscal_DateKey[DateID] )",
              "",
              "VAR _result = ",
              "CALCULATE(",
              "    [Control Amount] ,",
              "    LASTDATE(dim_date_fiscal_DateKey[DateID])",
              ")",
              "",
              "RETURN ",
              "_result"
            ],
            "lineageTag": "a1ff4f42-b90a-418d-ba7e-ce792e2cee1e"
          },
          {
            "name": "Control Amount (Last Day) - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Control Amount (Last Day)] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "77e881ac-1380-44f8-ac5b-6cf12f85bc15"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount % (Last Day)",
            "displayFolder": "Last_Day",
            "expression": "DIVIDE( [AR Hit Rates Manually Applied Amount (Last Day)] , [Control Amount (Last Day)] ) ",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "3bd750c7-98d1-4be8-9679-29ebb03bec9a"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount % (Last Day) - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [AR Hit Rates Manually Applied Amount % (Last Day)] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "fb09fbfd-004b-4d22-b770-144ec2502277"
          },
          {
            "name": "Received Amount % (Last Day)",
            "displayFolder": "Last_Day",
            "expression": "DIVIDE( [Control Amount (Last Day)] , [Control Amount] ) ",
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "19d3a772-fda3-48f3-b58e-4613f5ba09da"
          },
          {
            "name": "Received Amount % (Last Day) - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Received Amount % (Last Day)] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "18a6aa0c-a7db-41d6-9429-831842a41ad4"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount (Last Week)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Last_Week",
            "expression": [
              "",
              "CALCULATE(",
              "    [Manually Applied Amount] ,",
              "    DATESINPERIOD(dim_date_fiscal_DateKey[DateID], LASTDATE(dim_date_fiscal_DateKey[DateID]), -7, DAY)",
              ")",
              ""
            ],
            "lineageTag": "abce2b05-5825-486f-9b12-b17f5e5c202a"
          },
          {
            "name": "Control Amount (Last Week)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Last_Week",
            "expression": [
              "",
              "CALCULATE(",
              "    [Control Amount] ,",
              "    DATESINPERIOD(dim_date_fiscal_DateKey[DateID], LASTDATE(dim_date_fiscal_DateKey[DateID]), -7, DAY)",
              ")",
              ""
            ],
            "lineageTag": "be0d9dad-3a39-4066-8aa0-dae6ff0fac34"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount % (Last Week)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Last_Week",
            "expression": "DIVIDE( [AR Hit Rates Manually Applied Amount (Last Week)] , [Control Amount (Last Week)] ) ",
            "lineageTag": "f7957706-4abd-434b-86dc-ffabf95e93f6"
          },
          {
            "name": "Received Amount % (Last Week)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Last_Week",
            "expression": "DIVIDE( [Control Amount (Last Week)] , [Control Amount] ) ",
            "lineageTag": "e66168ec-f327-47e0-9749-a51b10ac6c28"
          },
          {
            "name": "Control Amount (Last Week) - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Control Amount (Last Week)] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "84752b6c-f62a-4045-8a36-8941cc7af6ef"
          },
          {
            "name": "Received Amount % (Last Week) - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Received Amount % (Last Week)] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "c9cf248e-bf9e-4e4e-9ad8-8c5f3cb884d4"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount % (Last Week) - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [AR Hit Rates Manually Applied Amount % (Last Week)] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"0.00%\""
            },
            "lineageTag": "e8e847e9-6050-49e7-82ef-30909c9a8930"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount (Last Week) - t24m",
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [AR Hit Rates Manually Applied Amount (Last Week)], ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0\""
            },
            "lineageTag": "3c83ad90-ba52-441c-9e6a-5fe968e4aa6f"
          },
          {
            "name": "Control Amount vs Prior Month (#)",
            "displayFolder": "time_comparison",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _CurrentMonth = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) , DAY ( _CurrentDate ) )",
              "",
              "VAR _PreviousMonth = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 1 , DAY ( _CurrentDate ) )",
              "",
              "VAR CurrentMonthControlAmount = ",
              "    CALCULATE(",
              "        [Control Amount] ,",
              "        dim_date_fiscal_MonthKey[DateID] = _CurrentDate ",
              "    )",
              "",
              "VAR PreviousMonthControlAmount = ",
              "    CALCULATE(",
              "        [Control Amount] ,",
              "        dim_date_fiscal_MonthKey[DateID] = _PreviousMonth",
              "    )",
              "    ",
              "RETURN",
              "    CurrentMonthControlAmount - PreviousMonthControlAmount"
            ],
            "formatStringDefinition": {
              "expression": "\"+$#,0; -$#,0\""
            },
            "lineageTag": "d12b7e39-dc40-4ec9-8d90-c4603c917ec5"
          },
          {
            "name": "Control Amount vs Prior Month (%)",
            "displayFolder": "time_comparison",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _CurrentMonth = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) , DAY ( _CurrentDate ) )",
              "",
              "VAR _PreviousMonth = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 1 , DAY ( _CurrentDate ) )",
              "",
              "VAR CurrentMonthControlAmount = ",
              "    CALCULATE(",
              "        [Control Amount] ,",
              "        dim_date_fiscal_MonthKey[DateID] = _CurrentDate ",
              "    )",
              "",
              "VAR PreviousMonthControlAmount = ",
              "    CALCULATE(",
              "        [Control Amount] ,",
              "        dim_date_fiscal_MonthKey[DateID] = _PreviousMonth",
              "    )",
              "    ",
              "RETURN",
              "( CurrentMonthControlAmount / PreviousMonthControlAmount ) - 1"
            ],
            "formatStringDefinition": {
              "expression": "\"+0.00%; -0.00%\""
            },
            "lineageTag": "106abb51-fc00-44b8-b0d2-221cd8de828f"
          },
          {
            "name": "AR Hit Rates Manually Applied Amount %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".base",
            "expression": "DIVIDE( [Manually Applied Amount] , [Control Amount] ) ",
            "lineageTag": "127a7d68-ed43-4285-960e-a100394c1b5d"
          },
          {
            "name": "Unapplied Amount Total - t24m",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "t24m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Unapplied Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "lineageTag": "e98983f7-fa59-4276-baed-e6b605bb3b2b"
          },
          {
            "name": "Manually Applied Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": ".base",
            "expression": "[Unapplied Amount] + [Unidentified Amount] + [On Account Amount] + [Miscellaneous Amount]",
            "lineageTag": "5867b8df-a114-48d4-9bfd-a2ff6a3e85c4"
          },
          {
            "name": "Manually Applied Amount vs Prior Month (#)",
            "displayFolder": "time_comparison",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _CurrentMonth = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) , DAY ( _CurrentDate ) )",
              "",
              "VAR _PreviousMonth = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 1 , DAY ( _CurrentDate ) )",
              "",
              "VAR CurrentMonthControlAmount = ",
              "    CALCULATE(",
              "        [Manually Applied Amount] ,",
              "        dim_date_fiscal_MonthKey[DateID] = _CurrentDate ",
              "    )",
              "",
              "VAR PreviousMonthControlAmount = ",
              "    CALCULATE(",
              "        [Manually Applied Amount] ,",
              "        dim_date_fiscal_MonthKey[DateID] = _PreviousMonth",
              "    )",
              "    ",
              "RETURN",
              "    CurrentMonthControlAmount - PreviousMonthControlAmount"
            ],
            "formatStringDefinition": {
              "expression": "\"+$#,0; -$#,0\""
            },
            "lineageTag": "2456074f-a30f-4e1a-b5a7-2190439e0fcb"
          },
          {
            "name": "Manually Applied Amount vs Prior Month (%)",
            "displayFolder": "time_comparison",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _CurrentMonth = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) , DAY ( _CurrentDate ) )",
              "",
              "VAR _PreviousMonth = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 1 , DAY ( _CurrentDate ) )",
              "",
              "VAR CurrentMonthControlAmount = ",
              "    CALCULATE(",
              "        [Manually Applied Amount] ,",
              "        dim_date_fiscal_MonthKey[DateID] = _CurrentDate ",
              "    )",
              "",
              "VAR PreviousMonthControlAmount = ",
              "    CALCULATE(",
              "        [Manually Applied Amount] ,",
              "        dim_date_fiscal_MonthKey[DateID] = _PreviousMonth",
              "    )",
              "    ",
              "RETURN",
              "( CurrentMonthControlAmount / PreviousMonthControlAmount ) - 1"
            ],
            "formatStringDefinition": {
              "expression": "\"+0.00%; -0.00%\""
            },
            "lineageTag": "0a86e19d-0b34-4aa2-b81f-388a7d648675"
          },
          {
            "name": "Miscellaneous Amount - t12m",
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Miscellaneous Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"$#,0.00\""
            },
            "lineageTag": "bf60bc08-68ee-41c2-860b-a26866ea0c12"
          },
          {
            "name": "Miscellaneous Count - t12m",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Miscellaneous Count] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "lineageTag": "7014e269-d696-4ad7-9581-214cf94ffca4"
          },
          {
            "name": "Manually Applied/Applied Count Hit Rate - t12m",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "t12m",
            "expression": [
              "\r",
              "\r",
              "VAR _CurrentDate = \r",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )\r",
              "\r",
              "VAR _PreviousDate = \r",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )\r",
              "\r",
              "VAR _Result =\r",
              "    CALCULATE ( \r",
              "        [Manually Applied Count] , \r",
              "        FILTER (\r",
              "            dim_date_fiscal_MonthKey ,\r",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate\r",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )\r",
              "\r",
              "RETURN\r",
              "    _Result"
            ],
            "lineageTag": "a6433ffe-7181-4869-8779-4932fb28b61b"
          },
          {
            "name": "Manual Count Per Week - t12m",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "t12m",
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Manual Count Avg Per Week] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "lineageTag": "df3cc692-93db-446a-ba4a-7211561f62b4"
          },
          {
            "name": "Manually Applied Count - t12m",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "t12m",
            "expression": [
              "\r",
              "\r",
              "VAR _CurrentDate = \r",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )\r",
              "\r",
              "VAR _PreviousDate = \r",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 12 , DAY ( _CurrentDate ) )\r",
              "\r",
              "VAR _Result =\r",
              "    CALCULATE ( \r",
              "        [Manually Applied Count] , \r",
              "        FILTER (\r",
              "            dim_date_fiscal_MonthKey ,\r",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate\r",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )\r",
              "\r",
              "RETURN\r",
              "    _Result"
            ],
            "lineageTag": "8c7224e0-a2fd-42a9-920d-a5dc97850637"
          },
          {
            "name": "Manually Applied Amount - t24m",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR _CurrentDate = ",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _PreviousDate = ",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )",
              "",
              "VAR _Result =",
              "    CALCULATE ( ",
              "        [Manually Applied Amount] , ",
              "        FILTER (",
              "            dim_date_fiscal_MonthKey ,",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )",
              "",
              "RETURN",
              "    _Result"
            ],
            "lineageTag": "a7bd61da-16a9-4c0f-b815-756f17efe2d2"
          },
          {
            "name": "Hit Rate - t24m",
            "displayFolder": "t24m",
            "expression": [
              "\r",
              "\r",
              "VAR _CurrentDate = \r",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )\r",
              "\r",
              "VAR _PreviousDate = \r",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )\r",
              "\r",
              "VAR _Result =\r",
              "    CALCULATE ( \r",
              "        [Hit Rate (Count)] , \r",
              "        FILTER (\r",
              "            dim_date_fiscal_MonthKey ,\r",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate\r",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )\r",
              "\r",
              "RETURN\r",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "b5b08bb0-133a-4f71-b466-2102fe2dec40"
          },
          {
            "name": "Apply Rate - t24m",
            "displayFolder": "t24m",
            "expression": [
              "\r",
              "\r",
              "VAR _CurrentDate = \r",
              "    MAX ( dim_date_fiscal_TTMKey[DateID] )\r",
              "\r",
              "VAR _PreviousDate = \r",
              "    DATE ( YEAR ( _CurrentDate ) , MONTH ( _CurrentDate ) - 24 , DAY ( _CurrentDate ) )\r",
              "\r",
              "VAR _Result =\r",
              "    CALCULATE ( \r",
              "        [Apply Rate (Amount)] , \r",
              "        FILTER (\r",
              "            dim_date_fiscal_MonthKey ,\r",
              "            dim_date_fiscal_MonthKey[DateID] >= _PreviousDate\r",
              "                && dim_date_fiscal_MonthKey[DateID] <= _CurrentDate ) )\r",
              "\r",
              "RETURN\r",
              "    _Result"
            ],
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "d3466459-761e-4e26-9cbf-5d225e3e33c0"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "dim_date_fiscal_DateKey",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DayIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "09f81d28-78b1-4bd4-bf8d-1d42a2e53fa7",
            "sourceColumn": "DayIndex",
            "summarizeBy": "sum"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f6146718-4bdf-41f9-874b-862c34261c0e",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_85f61c1d-c101-4656-afa2-8b2ed3b11878"
                },
                "isDefault": true,
                "relationship": "38e61474-9256-420a-b8af-b917163de6f4"
              }
            ]
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27aa782c-bd10-4e4b-8fe8-2142ba56da31",
            "sourceColumn": "Fiscal Period",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekInFM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f4aecb6-f017-4478-9e4b-5e3e4d76d2b0",
            "sourceColumn": "WeekInFM",
            "summarizeBy": "sum"
          },
          {
            "name": "FWeek_Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "55e6f43e-36b8-4019-9d55-843e2973bd2b",
            "sourceColumn": "FWeek_Index",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a693aa1-fd60-4346-92a5-cfe64ea664a8",
            "sourceColumn": "Fiscal-Year",
            "summarizeBy": "none"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3218cc33-731e-4fc3-b65a-8936a00f09f6",
            "sourceColumn": "FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal-Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61939cc3-eff8-45b8-8a4d-e953388fc011",
            "sourceColumn": "Fiscal-Period",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a2c8c85-4abe-4052-9686-cef2cbcd5422",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b098402e-684b-4b7e-aee7-0f880fe7d372",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "MMM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34a066d5-9fd3-4175-8960-94fde0904fde",
            "sourceColumn": "MMM",
            "summarizeBy": "none"
          },
          {
            "name": "MMM_FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "053f06bd-d150-45c1-9013-fe6de5336831",
            "sourceColumn": "MMM_FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e813c75c-fa76-4aa8-a218-e9a0f26389be",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "WeekDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "775174bc-78e9-48e1-a974-e090fde97e94",
            "sourceColumn": "WeekDay",
            "summarizeBy": "sum"
          },
          {
            "name": "Day name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a6d447c-210a-40bf-90ce-236ab032f473",
            "sourceColumn": "Day name",
            "summarizeBy": "none"
          },
          {
            "name": "IsWeekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "38759375-230f-43f9-8375-2f9eb8c79605",
            "sourceColumn": "IsWeekend",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8c566ff8-7d66-441f-a997-34273850b481",
        "partitions": [
          {
            "name": "dim_date_fiscal_DateKey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_fiscal_DateKey_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_fiscal_DateKey\",version=\"\"]}[Data]",
                "in",
                "    dim_date_fiscal_DateKey_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_85f61c1d-c101-4656-afa2-8b2ed3b11878",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "77466c81-0551-4ab3-98e8-a9be01e5724a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "82ee2f36-ba34-4538-be48-94c8615538f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5dfee182-b6cc-47bd-bc00-5571414a679a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9c9e0358-ac68-4e31-95c2-9e9d9461ca9a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "59e7a2b8-26d5-453a-8d26-824ca49c9f3e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "56694622-b8b2-4d44-bcf1-23ab022f0bae",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f8ffa950-8211-4870-a3bd-d47859119214",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "510b32c1-e189-4f0d-982e-3b366a9bbadc",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d0092733-9997-4b56-8431-6981600b8535",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ab1b9270-70ea-4ef9-93a1-fc1b90180eb3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3c6c992c-be1d-42d7-b6e2-ce22eb448e32",
                "ordinal": 3
              }
            ],
            "lineageTag": "0ca99b6e-e462-4060-bc24-b91f7d76dde9"
          }
        ],
        "isHidden": true,
        "lineageTag": "995feb1a-b8ca-4f52-bc86-8f6bbc830441",
        "partitions": [
          {
            "name": "LocalDateTable_85f61c1d-c101-4656-afa2-8b2ed3b11878",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_DateKey'[DateID])), 1, 1), Date(Year(MAX('dim_date_fiscal_DateKey'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_date_fiscal_MonthKey",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c7b485b0-97f9-4918-ba0c-5fd5ce4b0a46",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_336abc93-57dc-46da-acaa-273f0a494a3a"
                },
                "isDefault": true,
                "relationship": "0a211ae5-32ad-4d51-bee1-6358fb55235f"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d565a291-ccfd-4225-919a-aac7c7c8aa21",
            "sortByColumn": "DateID",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a5bcb79-2dae-4557-ba90-42cade595eff",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29e7a347-fb0d-4c47-8b45-f961f16ad565",
            "sourceColumn": "Fiscal Period",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a75efdca-2e1a-4ebc-8d24-f29416950c9f",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad473a79-71ef-459f-826a-9f02df1e7dc5",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cd7b832-54e8-4f91-b0ef-efa06cac412b",
            "sourceColumn": "FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3837db52-a6f7-4529-b058-3735cccec021",
            "sortByColumn": "DateID",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "MMM_FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5044b06-e1d5-4907-94ba-129db02dc96e",
            "sortByColumn": "DateID",
            "sourceColumn": "MMM_FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50df5129-52c3-4455-ab8b-118c49250963",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month YYYY - Calendar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cee996ad-22e2-486e-877b-ba88cd2fd127",
            "sourceColumn": "Month YYYY - Calendar",
            "summarizeBy": "none"
          },
          {
            "name": "DateID - Mmm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Mmm",
            "lineageTag": "3f8f7424-bafe-454e-a9b1-367fbd54ed3b",
            "sourceColumn": "DateID - Mmm",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d7c77918-59e0-47ad-bc6e-76d5c4af2469"
                },
                "isDefault": true,
                "relationship": "ae769ad1-81d4-4e58-bbe0-51b8ee55cd03"
              }
            ]
          },
          {
            "name": "Calendar-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea2c0fac-43d6-4a60-97db-55a9f2507fb0",
            "sourceColumn": "Calendar-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Start of week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2d16ae27-6d6d-4b75-8e9c-eed85ffc6443",
            "sourceColumn": "Start of week",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e062b3fa-97d5-48ca-bcc0-2eea9ab478b3"
                },
                "isDefault": true,
                "relationship": "2b3ede94-29ed-46d1-9ff4-0bfeda61fe93"
              }
            ]
          }
        ],
        "lineageTag": "7ec0e8e7-a81a-455d-b52f-ac5347932ea2",
        "partitions": [
          {
            "name": "dim_date_fiscal_MonthKey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_fiscal_MonthKey_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_fiscal_MonthKey\",version=\"\"]}[Data]",
                "in",
                "    dim_date_fiscal_MonthKey_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_336abc93-57dc-46da-acaa-273f0a494a3a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d9045f6e-2be9-45ea-9947-91524fc8e32f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9c4967c1-ba46-47a8-976e-9a982d7e9653",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "26cd980f-5db9-43b0-9819-aaa8a4b69d3f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "451948fa-9af1-4b1c-a2da-86f2f1868c38",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0ddcef0a-933e-4bf5-9843-0bd7e2182a13",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5bc7dd1f-03db-4de3-a8fe-7f2d1868890b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "38044c0a-60c4-446d-9336-cf38345e2ed9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f46f0ac6-c1c4-472f-9a76-760c2699c34f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4111ca61-0d11-4c89-9849-024b32897b13",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fa778180-6808-4139-b439-1de1faa5dc5e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d88a1e92-e6a7-4c67-8423-81516372bdc9",
                "ordinal": 3
              }
            ],
            "lineageTag": "7cdfb764-6375-4494-9326-2808a4a88e7d"
          }
        ],
        "isHidden": true,
        "lineageTag": "6bb69474-c412-40f2-9185-dba58f29475b",
        "partitions": [
          {
            "name": "LocalDateTable_336abc93-57dc-46da-acaa-273f0a494a3a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_MonthKey'[DateID])), 1, 1), Date(Year(MAX('dim_date_fiscal_MonthKey'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d7c77918-59e0-47ad-bc6e-76d5c4af2469",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "86b9deb2-9d02-40d2-83ac-13d224b4b893",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d1e4c04a-05dc-4191-b821-00d50332642b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b4b32ce3-0c31-4acc-aaec-2ff44da374b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3e6994bf-b9c0-4056-94c6-bb5aef334f8d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8dd6e35b-eea3-4fb6-a167-627208193e35",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1b0b5564-ad25-42e1-9e61-3d62131b54eb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8735a346-51c6-4875-a3ca-b71a9094985e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f67934b3-e5fb-4c59-b13f-3b57b31b2065",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "045c11fb-31e6-4b19-93ee-fb613177cf28",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d2510868-6992-47a6-96e7-3a7d9014df0b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7885d56c-bc08-4c2a-b24a-a11b49ee6cb7",
                "ordinal": 3
              }
            ],
            "lineageTag": "daad184f-c3c3-4d0a-b536-c2d8f767222f"
          }
        ],
        "isHidden": true,
        "lineageTag": "2a1ef0d6-147b-4258-9014-770d9487af15",
        "partitions": [
          {
            "name": "LocalDateTable_d7c77918-59e0-47ad-bc6e-76d5c4af2469",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_MonthKey'[DateID - Mmm])), 1, 1), Date(Year(MAX('dim_date_fiscal_MonthKey'[DateID - Mmm])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_date_fiscal_TTMKey",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5c0cba55-7a29-4ae7-ad3a-7736ac2ef799",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_07d4074b-6db8-4afb-a27b-ef3a916e6b94"
                },
                "isDefault": true,
                "relationship": "b1be2d67-588b-4b82-8b30-a2a33d486f49"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "87cd16f9-3bbd-417d-a701-372bd5beaa78",
            "sortByColumn": "DateID",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a97ff5d-6c5f-4e96-802f-5a0030b2ac7e",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "08e96709-395e-41a0-bc31-c7ffd6772c4c",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ffe26467-c987-45c6-a15e-5eec4b9ce88c",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e567abb-530f-40e7-b59e-a1e0ceacbeee",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a49da269-0841-4a6d-bfb6-aecf949ae08f",
            "sourceColumn": "YY",
            "summarizeBy": "none"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a70d43dc-d007-4320-9e7e-cfc4681b740f",
            "sortByColumn": "DateID",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "749b4862-992f-40f9-8fb3-d010c7bc9619",
            "sourceColumn": "FY-YY",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f09306d5-6901-415b-b6c4-ac7f6f4bbfc4",
        "partitions": [
          {
            "name": "dim_date_fiscal_TTMKey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_fiscal_TTMKey_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_fiscal_TTMKey\",version=\"\"]}[Data]",
                "in",
                "    dim_date_fiscal_TTMKey_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_07d4074b-6db8-4afb-a27b-ef3a916e6b94",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ae10b04e-db8d-4c67-8d59-c66ed00703b4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5f60e2dc-5ed1-479f-9a45-32cd09db8e5c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6772a882-a5a5-4d68-9468-d577b2a88f27",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8d065ffd-b182-4788-9883-e1682f9b0951",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "af9ffe01-efae-474d-98f8-b6d68d177254",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "25adc1d8-c738-4bee-8c0c-54406759880d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "2b463de9-1c81-4611-8ee3-45e5b502bc80",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "dfb47835-0cc2-4bd4-934d-3bad02524107",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a16f5c1b-f04a-49ff-974b-fc4ae137d3e2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "49318173-0bf1-486f-aac7-193892c17d80",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b1b5082d-c811-47c1-955b-10015ad0b63a",
                "ordinal": 3
              }
            ],
            "lineageTag": "4d75ae74-1eec-47e9-be55-f02ec82af357"
          }
        ],
        "isHidden": true,
        "lineageTag": "7d01126c-308b-4e08-8154-56acf11b4e68",
        "partitions": [
          {
            "name": "LocalDateTable_07d4074b-6db8-4afb-a27b-ef3a916e6b94",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_TTMKey'[DateID])), 1, 1), Date(Year(MAX('dim_date_fiscal_TTMKey'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_gbs_ProfitCenter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0af9a1d6-89de-483a-b549-9b331644f2e1",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter-Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61bc9e8c-a8ec-4a02-af6e-0cdb50945784",
            "sourceColumn": "ProfitCenter-Code",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter -ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e08426f6-ca8c-4614-a81a-8cad773e5ca7",
            "sourceColumn": "ProfitCenter -ID",
            "summarizeBy": "none"
          },
          {
            "name": "Department-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e9c73bf-045b-42d0-949c-8617e2c2bb15",
            "sourceColumn": "Department-Name",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f7864b1-94ef-4ef0-8c4d-c4490f4b91cb",
            "sourceColumn": "ProfitCenter-Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b61b8fd8-119c-4636-aa91-153e7196a353",
        "partitions": [
          {
            "name": "dim_gbs_ProfitCenter",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"2976903809263492\" = Source{[Key=\"2976903809263492\"]}[Data],",
                "    #\"7899457811074948\" = #\"2976903809263492\"{[Key=\"7899457811074948\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"7899457811074948\",{{\"ProfitCenter-Code\", type text}, {\"Department-Name\", type text}, {\"ProfitCenter-Name\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_gbs_Lockbox",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Sort-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b1a91c7e-68eb-48bf-821f-f47e3e99cbbb",
            "sourceColumn": "Sort-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Lockbox-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "242c3caf-575d-44f5-9221-e84729912d46",
            "sortByColumn": "Sort-ID",
            "sourceColumn": "Lockbox-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Lockbox-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2177c31-393a-4ecf-aad9-b69d050078d3",
            "sourceColumn": "Lockbox-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lockbox-Alt-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7deb6259-582d-4e5c-bedc-bf4d946a304b",
            "sourceColumn": "Lockbox-Alt-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a5e6f8a-696a-456c-935e-64baf8a0e49c",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccb06c83-5bf0-4252-a78f-4018568500c6",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Batch-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f3ae727-c69a-4fde-b824-88ef40852d2f",
            "sourceColumn": "Batch-Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9c080e5e-8f6a-44a7-9483-1ad266018292",
        "partitions": [
          {
            "name": "dim_gbs_Lockbox",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"2976903809263492\" = Source{[Key=\"2976903809263492\"]}[Data],",
                "    #\"313114822135684\" = #\"2976903809263492\"{[Key=\"313114822135684\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"313114822135684\",{\"RowNumber\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Sort-ID\", type number}, {\"Lockbox-ID\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_Oracle_Export_US_AccountsReceivable",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "transmission_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdf555a9-d3c9-4773-8727-2b89a59e6547",
            "sourceColumn": "transmission_name",
            "summarizeBy": "none"
          },
          {
            "name": "batch_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "884f0a71-9ef1-4d74-8eee-f9ac3fc515ee",
            "sourceColumn": "batch_number",
            "summarizeBy": "none"
          },
          {
            "name": "lockbox",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f01b16a-0a1d-4bac-9fd9-1592ed187b83",
            "sourceColumn": "lockbox",
            "summarizeBy": "sum"
          },
          {
            "name": "control_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5ce8770d-6fa8-4ce9-a251-fd4faa08e5a1",
            "sourceColumn": "control_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "control_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "53c8885f-b9a6-44b7-91ee-4650b14ba61c",
            "sourceColumn": "control_count",
            "summarizeBy": "sum"
          },
          {
            "name": "applied_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "54bc900e-0630-4509-84f7-18cfabd835fb",
            "sourceColumn": "applied_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "applied_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6ec11179-844e-4fcf-bc5c-fbd8f11112a1",
            "sourceColumn": "applied_count",
            "summarizeBy": "sum"
          },
          {
            "name": "unapplied_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "efb8beac-2af0-4758-8e97-d6306e5d48f3",
            "sourceColumn": "unapplied_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "unapplied_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "470613bd-58d1-4458-a86c-f1f38ee864b4",
            "sourceColumn": "unapplied_count",
            "summarizeBy": "sum"
          },
          {
            "name": "on_account_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0a979ca2-4330-4c98-bed2-1cc9e8b1c9c3",
            "sourceColumn": "on_account_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "on_account_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3094514-a9fa-48ed-9b07-bbdf5e81d215",
            "sourceColumn": "on_account_count",
            "summarizeBy": "sum"
          },
          {
            "name": "unidentified_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5719e9ac-c102-46ba-ab19-e5979c6e22ed",
            "sourceColumn": "unidentified_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "unidentified_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "18988a9c-14c3-43b4-a5c6-b172f5d5f802",
            "sourceColumn": "unidentified_count",
            "summarizeBy": "sum"
          },
          {
            "name": "reversed_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed1cc210-3ab9-4470-8f60-98d23eff5f49",
            "sourceColumn": "reversed_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "reversed_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2cefbfc4-46f0-4ea2-be37-6e97e7e6360d",
            "sourceColumn": "reversed_count",
            "summarizeBy": "sum"
          },
          {
            "name": "difference_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0d7699f3-2f2f-4da6-b01d-9258f18f7e62",
            "sourceColumn": "difference_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "difference_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec063789-ab7e-4798-b79e-ccb06957abbd",
            "sourceColumn": "difference_count",
            "summarizeBy": "sum"
          },
          {
            "name": "miscellaneous_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56f5a354-6b33-43de-b1c5-ec62cfd15db9",
            "sourceColumn": "miscellaneous_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "miscellaneous_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ef0c1bb5-761e-4d7e-a3d5-8f91d3ffd251",
            "sourceColumn": "miscellaneous_count",
            "summarizeBy": "sum"
          },
          {
            "name": "batch_source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d7e3532-0e17-4be7-b50d-cba2f83b04a2",
            "sourceColumn": "batch_source",
            "summarizeBy": "none"
          },
          {
            "name": "batch_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "cba52a33-9276-470e-a4fd-1384c3ca4bc9",
            "sourceColumn": "batch_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4f36f013-85ec-46ae-b5cc-2de882cecbde"
                },
                "isDefault": true,
                "relationship": "0cba7a38-1d89-4876-8a50-57ba32484563"
              }
            ]
          },
          {
            "name": "gl_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "36285ce4-37c6-4d6d-b5a8-4ca950b783c0",
            "sourceColumn": "gl_date",
            "summarizeBy": "none"
          },
          {
            "name": "deposit_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "be99e860-8f27-48df-a6a1-6283f0e4d64e",
            "sourceColumn": "deposit_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_547f1543-f30f-4b83-a32b-b45c0658ef64"
                },
                "isDefault": true,
                "relationship": "774910b3-8978-4e83-97b3-59f9457eb467"
              }
            ]
          },
          {
            "name": "batch_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1cb73a2-85b7-437a-815f-12fd8f7cc086",
            "sourceColumn": "batch_type",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d860a8d-8dc0-446e-8768-0a3fac485536",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "receipt_class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b14149d-dd9b-4f09-883a-33d34ecc23a8",
            "sourceColumn": "receipt_class",
            "summarizeBy": "none"
          },
          {
            "name": "receipt_method",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e9fc1c8-aade-4e02-80c2-2a49e8159b9b",
            "sourceColumn": "receipt_method",
            "summarizeBy": "none"
          },
          {
            "name": "transmission_batch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3e9bb8d-b9e3-4ad6-ac51-a1d9613e5126",
            "sourceColumn": "transmission_batch",
            "summarizeBy": "sum"
          },
          {
            "name": "operating_unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19f8f6f7-e1b7-4245-a583-1f960a7ddba5",
            "sourceColumn": "operating_unit",
            "summarizeBy": "none"
          },
          {
            "name": "media_reference",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4d8cb6c-5336-48dd-90f2-3e4078d1ecd7",
            "sourceColumn": "media_reference",
            "summarizeBy": "none"
          },
          {
            "name": "remittance_method",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0993f0cd-b512-4d9d-86e3-f1de1edf283a",
            "sourceColumn": "remittance_method",
            "summarizeBy": "none"
          },
          {
            "name": "remittance_bank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c88ed002-a01c-456b-8122-0383c3ad4c68",
            "sourceColumn": "remittance_bank",
            "summarizeBy": "none"
          },
          {
            "name": "remittance_branch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cc95be2-5e2f-4d1b-b94a-8a3b91eb3eea",
            "sourceColumn": "remittance_branch",
            "summarizeBy": "none"
          },
          {
            "name": "remittance_account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7156610f-98c5-44b6-b0ca-d5f37c00f57a",
            "sourceColumn": "remittance_account",
            "summarizeBy": "none"
          },
          {
            "name": "deposit_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9108774-f835-4892-9f10-5967dd1b5d8d",
            "sourceColumn": "deposit_number",
            "summarizeBy": "none"
          },
          {
            "name": "remittance_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66c7ffa5-53f0-49c1-a124-090c462591c2",
            "sourceColumn": "remittance_count",
            "summarizeBy": "none"
          },
          {
            "name": "remittance_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9251414-efb5-41e2-8223-6c53243c350b",
            "sourceColumn": "remittance_amount",
            "summarizeBy": "none"
          },
          {
            "name": "bank_currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdd2babe-42aa-4849-ba3a-a04cb87eb80d",
            "sourceColumn": "bank_currency",
            "summarizeBy": "none"
          },
          {
            "name": "comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea27c2d8-95a5-4e62-8d0d-bb6244f23557",
            "sourceColumn": "comments",
            "summarizeBy": "none"
          },
          {
            "name": "process_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f7cb611-ef78-4336-9b86-4b9cef171fbc",
            "sourceColumn": "process_status",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dd62c23-e070-4578-b14d-3516922beab4",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "request_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdacc632-f4ab-46ba-9953-b9f733ad0984",
            "sourceColumn": "request_id",
            "summarizeBy": "none"
          },
          {
            "name": "partially_purged",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c3aa30e-f53a-4dda-bf91-6776c406397a",
            "sourceColumn": "partially_purged",
            "summarizeBy": "none"
          },
          {
            "name": "loaded_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6d986187-32cc-415a-89c5-fa3257bff45f",
            "sourceColumn": "loaded_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0442fb98-f7b4-4f40-8cd6-d52cd82da18a"
                },
                "isDefault": true,
                "relationship": "73029d18-aaff-47ea-93fd-17dbb0d40f10"
              }
            ]
          },
          {
            "name": "report_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e70088f-dc84-4af6-986d-ddf3a28d6d80",
            "sourceColumn": "report_name",
            "summarizeBy": "none"
          },
          {
            "name": "payment_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61f804a1-bc7a-4e4f-bf38-25050a4ea928",
            "sourceColumn": "payment_type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "67494b33-c63c-4d0b-85fa-e74175ec4b34",
        "partitions": [
          {
            "name": "fact_Oracle_Export_US_AccountsReceivable",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"USPHL0PRPADBA1\", \"Graham_Workspace\"),",
                "    dbo_fact_Oracle_Export_US_AccountsReceivable = Source{[Schema=\"dbo\",Item=\"fact_Oracle_Export_US_AccountsReceivable\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_fact_Oracle_Export_US_AccountsReceivable,{{\"miscellaneous_count\", type number}, {\"miscellaneous_amount\", type number}, {\"difference_count\", type number}, {\"difference_amount\", type number}, {\"reversed_count\", type number}, {\"reversed_amount\", type number}, {\"unidentified_count\", type number}, {\"unidentified_amount\", type number}, {\"on_account_count\", type number}, {\"on_account_amount\", type number}, {\"unapplied_count\", type number}, {\"unapplied_amount\", type number}, {\"applied_count\", type number}, {\"applied_amount\", type number}, {\"control_count\", type number}, {\"control_amount\", type number}, {\"batch_date\", type date}, {\"gl_date\", type date}, {\"deposit_date\", type date}, {\"transmission_batch\", Int64.Type}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"payment_type\", each if [transmission_batch] = null then \"Manual Entry\" else if [transmission_batch] > 900 then \"Electronic\" else \"Check\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"lockbox\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4f36f013-85ec-46ae-b5cc-2de882cecbde",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8b6e3574-085d-4b16-9dc7-e2813f39d2e2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "33308d10-61dd-4751-a78d-7a63df5114e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a0dd6c99-0874-4475-979a-4b4f2a95c055",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b88677cf-8a61-48bb-b49d-fb669118c2db",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0cc702b9-e557-4f6c-92ca-6042dca3a6f7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c9f73081-4980-4fdd-9665-0a4beb517301",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b63d8655-58ee-4874-b7a3-f80a2100e390",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "660424ca-b47a-4aff-8bad-f74d8bec1103",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0c434902-8c46-4bd5-8ec6-635a4279df06",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ca8070ea-25bc-49d4-ab97-6988585523e1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6f2bc9b6-5826-4b16-8fce-91a11b7f7eef",
                "ordinal": 3
              }
            ],
            "lineageTag": "574bb984-f36c-4874-84ea-30f558ca7091"
          }
        ],
        "isHidden": true,
        "lineageTag": "873cd4fc-0f9e-441f-8166-de17224871dd",
        "partitions": [
          {
            "name": "LocalDateTable_4f36f013-85ec-46ae-b5cc-2de882cecbde",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_Oracle_Export_US_AccountsReceivable'[batch_date])), 1, 1), Date(Year(MAX('fact_Oracle_Export_US_AccountsReceivable'[batch_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_547f1543-f30f-4b83-a32b-b45c0658ef64",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "397f826a-6a18-4efb-b35a-15597ebd3a14",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7bd44193-8462-44d8-b0b2-4bcdbf4d9324",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3e707cfb-f2c7-4e49-b8f1-762886f7af6c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "330abad2-b3d5-4fd7-b1ec-17c4a9f831ed",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "ebd2f4b7-a946-4900-abd2-580e8019dd6d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d56f09f7-360c-47f3-adf0-3d2cc4a8a8c7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "64262945-5991-4010-b754-72836d2f1491",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a89d9dce-9fc1-4ea2-bf8a-3c72868eb80c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ee147f89-871d-442c-aacb-c9357158caaf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "585ca6ef-6cef-406b-8a27-a413af861e5c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "689fe9dc-7171-44e7-9e13-8ff76accee62",
                "ordinal": 3
              }
            ],
            "lineageTag": "0ee18fa6-95df-4886-ad20-9a3a79ffd078"
          }
        ],
        "isHidden": true,
        "lineageTag": "acfcc26e-b041-4718-a360-556f3e0deaf0",
        "partitions": [
          {
            "name": "LocalDateTable_547f1543-f30f-4b83-a32b-b45c0658ef64",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_Oracle_Export_US_AccountsReceivable'[deposit_date])), 1, 1), Date(Year(MAX('fact_Oracle_Export_US_AccountsReceivable'[deposit_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_0442fb98-f7b4-4f40-8cd6-d52cd82da18a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "35ab2984-20f7-4652-9863-9f621cd62e1b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9dc6ad55-15d5-413f-80d1-0f918bd45342",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "d03849e3-aaa1-4952-851e-c15603e07acb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "88845078-526b-40ab-ad39-1c6d0a1cc990",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0445d8b1-d461-477d-898b-0372fa7323e2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ead7cc12-a947-4dd3-932f-d36814e78d67",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "da2d6d26-d176-4990-96a9-37b81c2a3984",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "070bafbb-c1c2-4bbb-a962-d62ac8e38287",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "feb589fa-228d-4edd-8565-a526cdb11683",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "86eb26dc-8e67-4561-98ff-4802cafd0997",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7f248d0c-7c7b-4b2c-9e7c-e22439ab73c6",
                "ordinal": 3
              }
            ],
            "lineageTag": "ba8a339a-90bb-4e38-abdd-47e2f11cafca"
          }
        ],
        "isHidden": true,
        "lineageTag": "486eb7a9-3085-46ab-b8b2-80e15d89d745",
        "partitions": [
          {
            "name": "LocalDateTable_0442fb98-f7b4-4f40-8cd6-d52cd82da18a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_Oracle_Export_US_AccountsReceivable'[loaded_date])), 1, 1), Date(Year(MAX('fact_Oracle_Export_US_AccountsReceivable'[loaded_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e062b3fa-97d5-48ca-bcc0-2eea9ab478b3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0bd4543f-1719-49f4-9662-2b71c81c71e4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c428d38e-c46d-462d-a593-b9705ba97bd3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c3e0b89f-d1e3-40f2-bc1f-9559c2a36b32",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "404bb4aa-974b-4474-94d6-af422f356b3b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "1b9765a7-7a22-4b82-a2dc-f4d017447530",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "898d32af-2981-450c-98d3-c70cbf539d37",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "47287278-3cdb-4d71-899b-ff775aaa8954",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3f898951-7ba8-461c-9c1e-e9d56efb24ac",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0c9053b1-9d88-4aa6-8988-31220d66a4df",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7b78d5a0-557f-42fd-8bd5-4543718eca24",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "31ed7437-634a-4623-9f21-e68a7fa22423",
                "ordinal": 3
              }
            ],
            "lineageTag": "df93e6c3-58f3-48da-84d1-f98c1520e8b6"
          }
        ],
        "isHidden": true,
        "lineageTag": "ffaf6704-6bb1-4793-b649-35375fb2c909",
        "partitions": [
          {
            "name": "LocalDateTable_e062b3fa-97d5-48ca-bcc0-2eea9ab478b3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_MonthKey'[Start of week])), 1, 1), Date(Year(MAX('dim_date_fiscal_MonthKey'[Start of week])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}