{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fact_myPayRequestReport_Sharepoint\",\"dim_date_fiscal_TTMKey\",\"dim_date_fiscal_MonthKey\",\"dim_date_fiscal_DateKey\",\"dim_gbs_mor_Goals\",\"dim_date_Holiday\",\"dim_Employee_Payroll\",\"fact_ManualCheckRequest_Payroll\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "relationships": [
      {
        "name": "eb9a477c-004b-4134-9f3d-d090745aa3ea",
        "fromColumn": "DateID",
        "fromTable": "dim_date_fiscal_TTMKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c2489b95-dbda-4869-abe7-8404f9a57a68"
      },
      {
        "name": "d5f4880f-b8aa-401c-9cfb-70491ce57671",
        "fromColumn": "DateID",
        "fromTable": "dim_date_fiscal_MonthKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f44a0cd8-fd9f-492e-9f32-b12705b39cce"
      },
      {
        "name": "9789c8f3-75cc-4a26-be9a-fd750e0d2f59",
        "fromColumn": "PeriodID",
        "fromTable": "dim_date_fiscal_DateKey",
        "toColumn": "PeriodID",
        "toTable": "dim_date_fiscal_MonthKey"
      },
      {
        "name": "a30f67ef-006d-4db9-a584-ed9e74e1709e",
        "fromColumn": "Date Assigned",
        "fromTable": "fact_myPayRequestReport_Sharepoint",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_914b53b7-ff85-43e4-a732-dd0898818a8d"
      },
      {
        "name": "7f9a18cf-d69f-47b7-9835-b542bf288855",
        "fromColumn": "Date Completed - Finalized",
        "fromTable": "fact_myPayRequestReport_Sharepoint",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4a74c5f1-4f8e-49b8-bb29-6ebff532bee1"
      },
      {
        "name": "149038af-d3fe-4a34-a1b3-a8470bc61876",
        "fromColumn": "DateID",
        "fromTable": "dim_date_fiscal_DateKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6c8fa93c-f437-4be5-87c3-c593e4511d6f"
      },
      {
        "name": "6aca91e1-92c4-4027-a734-cc25549092a4",
        "fromColumn": "Date Completed - First Action MUST BE within 3 business days",
        "fromTable": "fact_myPayRequestReport_Sharepoint",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_eca1292c-ad7b-45fe-8205-88fa7351f813"
      },
      {
        "name": "44535829-2d88-464a-a9ea-ffab351fad34",
        "fromColumn": "DateID - Mmm",
        "fromTable": "dim_date_fiscal_MonthKey",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bdebe84b-ece2-4e5a-b795-61cdd67eb9aa"
      },
      {
        "name": "c93f99f0-9799-44dc-b9d8-ada4b560afd4",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Period-ID",
        "fromTable": "dim_gbs_mor_Goals",
        "toColumn": "PeriodID",
        "toTable": "dim_date_fiscal_MonthKey"
      },
      {
        "name": "845f0ee8-ceb8-41d4-951b-cd9ee3774ae4",
        "fromColumn": "Holiday-Date",
        "fromTable": "dim_date_Holiday",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_15b549a7-c9d6-4d04-9c88-727b41310491"
      },
      {
        "name": "26469b26-1d8a-4cca-a390-5747c12f7fd9",
        "fromColumn": "Completed By",
        "fromTable": "fact_myPayRequestReport_Sharepoint",
        "toColumn": "Employee-Initial",
        "toTable": "dim_Employee_Payroll"
      },
      {
        "name": "020420de-576f-4efe-baec-6fb8f36a253b",
        "fromColumn": "Submitted",
        "fromTable": "fact_myPayRequestReport_Sharepoint",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e865d21f-fb38-4543-b813-4036b2efc8d1"
      },
      {
        "name": "f7a95698-20ea-d3e8-1b0f-f41978a91e89",
        "fromColumn": "Opened",
        "fromTable": "fact_myPayRequestReport_Sharepoint",
        "toColumn": "DateID",
        "toTable": "dim_date_fiscal_DateKey"
      },
      {
        "name": "a5ffed66-ea56-4e54-9b17-0818629df40f",
        "fromColumn": "loaded_date",
        "fromTable": "fact_ManualCheckRequest_Payroll",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_95b4b8fc-862d-4f4c-9a5e-5ceecda8eea9"
      },
      {
        "name": "08bc3642-5541-65db-0193-dfa0649c71de",
        "fromColumn": "opened",
        "fromTable": "fact_ManualCheckRequest_Payroll",
        "toColumn": "DateID",
        "toTable": "dim_date_fiscal_DateKey"
      },
      {
        "name": "a2bfde29-5b94-4c43-ab4f-424ed915641d",
        "fromColumn": "submitted",
        "fromTable": "fact_ManualCheckRequest_Payroll",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f7135b25-71d1-471a-a34a-9502d5634eb8"
      },
      {
        "name": "860d5c73-6fc3-4ab1-a3e2-0332f7dd80fb",
        "fromColumn": "date_assigned",
        "fromTable": "fact_ManualCheckRequest_Payroll",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c901ae97-cd1c-4742-b3af-a35b16d9e232"
      },
      {
        "name": "48fd1933-8715-42c6-97c1-72ce2c7ee053",
        "fromColumn": "completed_first_action",
        "fromTable": "fact_ManualCheckRequest_Payroll",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_35818df4-99c6-4d25-b366-aab09cf21ebc"
      },
      {
        "name": "12889327-a481-32bb-c87d-ac77485ae25f",
        "fromColumn": "completed_by",
        "fromTable": "fact_ManualCheckRequest_Payroll",
        "toColumn": "Employee-Initial",
        "toTable": "dim_Employee_Payroll"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_b0089986-a12b-42d0-b042-0ce78b54dd4a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f3ef3c3c-eb7d-4574-8059-f271b2305102",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "942a62c1-f59a-4a0c-b587-da8e14795767",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "56ad1143-1311-415d-a4d2-9a22796f7d00",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "57a15010-c290-4f67-90c2-50d206b8c7fb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b0e77d82-a88b-401b-acc1-6740e76a1dfb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e545c970-cd89-4d1f-95ee-21dd7ffd9687",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "e29d45db-8338-4846-8908-6280400d27a9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "48ea03d0-afab-45f7-a229-a33c50799214",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "66309f11-c744-46f0-88c9-988109192898",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7e0f1291-e846-4f3f-850e-5e6c6d26dceb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "880e5f75-64e9-4a45-a222-020157eb2ee9",
                "ordinal": 3
              }
            ],
            "lineageTag": "cadbbd08-e376-4f57-8e7e-acd805072182"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "5b793128-8c16-4358-9b73-4261c33dbf21",
        "partitions": [
          {
            "name": "DateTableTemplate_b0089986-a12b-42d0-b042-0ce78b54dd4a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_date_fiscal_TTMKey",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8154f0b4-5292-4a3c-8780-eb3009cbbe51",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c2489b95-dbda-4869-abe7-8404f9a57a68"
                },
                "isDefault": true,
                "relationship": "eb9a477c-004b-4134-9f3d-d090745aa3ea"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1a8893e-989b-4f24-9028-994765b11314",
            "sortByColumn": "DateID",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e6ad874-c4d8-4cdc-9c2e-b1b337ddc34b",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f66f6412-8ad7-4ed4-b46b-f200d2c2faf2",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec8835d8-b871-4a55-90ab-d194f5fe6b65",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a419b41f-ba76-4a47-a27d-489066a1ab25",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a354f02-cddf-43dc-8880-0ce7ef3ecc2f",
            "sourceColumn": "YY",
            "summarizeBy": "none"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "804de0c9-2fdb-4309-a742-980ef206adfa",
            "sortByColumn": "DateID",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "688cf5f7-ded9-4474-8a63-e279ff1650b9",
        "partitions": [
          {
            "name": "dim_date_fiscal_TTMKey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_fiscal_TTMKey_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_fiscal_TTMKey\",version=\"\"]}[Data]",
                "in",
                "    dim_date_fiscal_TTMKey_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c2489b95-dbda-4869-abe7-8404f9a57a68",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "734fb8ec-9b8a-4a32-a82e-4c4599b90d87",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d5a107b2-7c9b-4010-a68f-31369872627d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "61840d5d-3a29-493a-83c3-d0b54e67ae33",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "32fa5b0c-52f5-4ac1-89c8-655b93be1b81",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a99b62ca-28d7-4113-ab82-910687014d06",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f5aaf08d-47c1-4baa-af62-7106428161ea",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b69418e9-8b44-47d5-89c4-4a7aace29b68",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5b978c17-2bf3-4f24-986c-5db039b9976c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "bac8c405-6c71-4cdb-8231-c62a63193d04",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6e42a61b-4114-471a-b824-f50497ac5ef1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4c1f95a9-3535-468f-b0fb-d7ae7663279a",
                "ordinal": 3
              }
            ],
            "lineageTag": "4a3b6563-77fd-4ad5-9451-9a7f48fd7bc3"
          }
        ],
        "isHidden": true,
        "lineageTag": "1d8f1995-6017-461d-af08-798e33da885b",
        "partitions": [
          {
            "name": "LocalDateTable_c2489b95-dbda-4869-abe7-8404f9a57a68",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_TTMKey'[DateID])), 1, 1), Date(Year(MAX('dim_date_fiscal_TTMKey'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_date_fiscal_MonthKey",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "692786f7-4cf7-4369-96dd-ceaaf23fac3e",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f44a0cd8-fd9f-492e-9f32-b12705b39cce"
                },
                "isDefault": true,
                "relationship": "d5f4880f-b8aa-401c-9cfb-70491ce57671"
              }
            ]
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1529c02-3d5f-498e-bbaa-c04a5ad03ffb",
            "sortByColumn": "DateID",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec334d19-29fd-4d5a-9a77-5c84611a25f4",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c15fd7f5-c9ad-4eb3-bd4c-3fd5da277c69",
            "sourceColumn": "Fiscal Period",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c0a8b6ad-6931-4208-8ccd-3d2f4561f12a",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c69aaf34-391d-43b1-94ea-f96e9d976e41",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c824769-39bb-4c68-b9f8-a401e9896051",
            "sourceColumn": "FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d383cd8c-f4ae-4c4e-bd0b-949f12d9d4bd",
            "sortByColumn": "DateID",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "MMM_FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "e67df255-44b5-440f-9f36-ab0fd43fc6b7",
            "sortByColumn": "DateID",
            "sourceColumn": "MMM_FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9a7b0b1-f492-4da1-8cef-983e143f4861",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month YYYY - Calendar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de9af99c-d9a7-4621-ad17-56c7d116aa88",
            "sourceColumn": "Month YYYY - Calendar",
            "summarizeBy": "none"
          },
          {
            "name": "DateID - Mmm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Mmm",
            "lineageTag": "88c6116c-17a9-4bab-a8ff-462193dda166",
            "sourceColumn": "DateID - Mmm",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bdebe84b-ece2-4e5a-b795-61cdd67eb9aa"
                },
                "isDefault": true,
                "relationship": "44535829-2d88-464a-a9ea-ffab351fad34"
              }
            ]
          },
          {
            "name": "Calendar-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aef908fa-2d5a-474d-be03-81797a7996f4",
            "sourceColumn": "Calendar-YY",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f85aa0b1-de4c-4ac4-a54e-d8cbac7e3a9f",
        "partitions": [
          {
            "name": "dim_date_fiscal_MonthKey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_fiscal_MonthKey_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_fiscal_MonthKey\",version=\"\"]}[Data]",
                "in",
                "    dim_date_fiscal_MonthKey_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f44a0cd8-fd9f-492e-9f32-b12705b39cce",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bcf36411-3e2b-4124-9ff2-ec4cfc05edcd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c936bcd4-943b-42b7-81ad-9e7f9eb1fa0e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "746b1134-642e-494f-8a2d-6fab7990e44f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f48e4c1b-658d-434c-b58c-5b1e143b89da",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "284cb5c9-b585-4d6e-83a6-2566a88d9168",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d45d4bdf-8aeb-4619-b50a-ef5e242f3a2b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a766804b-767a-436e-b819-656bc3937475",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ad7efd6a-ccd6-4114-8703-3ca87e2a2b52",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f0269494-8336-4e71-8b9b-c9554b49f49b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "754580f5-5924-40d3-925e-8531e23ae71f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fcbee4ea-c6a8-4406-b1c2-156a0fc55330",
                "ordinal": 3
              }
            ],
            "lineageTag": "d7794bcf-3e08-47d8-b031-e94ae925823d"
          }
        ],
        "isHidden": true,
        "lineageTag": "152d3bce-0786-45e4-8041-81a037964f4d",
        "partitions": [
          {
            "name": "LocalDateTable_f44a0cd8-fd9f-492e-9f32-b12705b39cce",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_MonthKey'[DateID])), 1, 1), Date(Year(MAX('dim_date_fiscal_MonthKey'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_date_fiscal_DateKey",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DayIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64f20332-2224-4333-94d5-967459fcbf5b",
            "sourceColumn": "DayIndex",
            "summarizeBy": "sum"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6d9aa2db-f344-480e-aa81-cf448f7c3ad3",
            "sourceColumn": "DateID",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6c8fa93c-f437-4be5-87c3-c593e4511d6f"
                },
                "isDefault": true,
                "relationship": "149038af-d3fe-4a34-a1b3-a8470bc61876"
              }
            ]
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2c8b7126-6a03-4ffb-91d2-9f8d105ecb34",
            "sourceColumn": "Fiscal Period",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekInFM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "263864ef-996c-43d8-a967-8b0038a336fb",
            "sourceColumn": "WeekInFM",
            "summarizeBy": "sum"
          },
          {
            "name": "FWeek_Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb91db2d-83fe-463d-9ab2-34a750379ea6",
            "sourceColumn": "FWeek_Index",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d49097c2-df23-43af-8764-8d4dea614107",
            "sourceColumn": "Fiscal-Year",
            "summarizeBy": "none"
          },
          {
            "name": "FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "440de7cb-dc6e-4d29-b30b-d677a2cbd243",
            "sourceColumn": "FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal-Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ea76fb4-830e-4e62-bd2b-9565249b53e2",
            "sourceColumn": "Fiscal-Period",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b15d3579-f2cd-47f2-b151-f880b401426b",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e98f38c5-620b-4653-96cf-e9d55a434cf9",
            "sourceColumn": "Month FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "MMM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95cc2819-ba0f-4dc2-93de-b11391cabe3f",
            "sourceColumn": "MMM",
            "summarizeBy": "none"
          },
          {
            "name": "MMM_FY-YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "260a72fd-2866-48e1-b12f-df33c84cb5e3",
            "sourceColumn": "MMM_FY-YY",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c99b586-5d78-426a-b550-b9c2d6f0986d",
            "sourceColumn": "PeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "WeekDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "053914dc-cf91-4598-a22d-14d991105ef2",
            "sourceColumn": "WeekDay",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6283fb61-df62-4f0a-b20b-b6080992292e",
        "partitions": [
          {
            "name": "dim_date_fiscal_DateKey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_fiscal_DateKey_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_fiscal_DateKey\",version=\"\"]}[Data]",
                "in",
                "    dim_date_fiscal_DateKey_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_myPayRequestReport_Sharepoint",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8977de12-8727-45e7-bdd4-df593880c37e",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fce5672-efdf-41e8-a283-8320938f18d9",
            "sourceColumn": "Request",
            "summarizeBy": "none"
          },
          {
            "name": "Opened",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "eaffc6a9-61a5-4db6-a183-a1cc6aa27a98",
            "sourceColumn": "Opened",
            "summarizeBy": "none"
          },
          {
            "name": "Submitted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "0d27c164-ebb6-48ee-9dc9-36ebbe510651",
            "sourceColumn": "Submitted",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e865d21f-fb38-4543-b813-4036b2efc8d1"
                },
                "isDefault": true,
                "relationship": "020420de-576f-4efe-baec-6fb8f36a253b"
              }
            ]
          },
          {
            "name": "Check/Cheque Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c59a864-12ea-4eb1-89a4-afa93bc95266",
            "sourceColumn": "Check/Cheque Reason",
            "summarizeBy": "none"
          },
          {
            "name": "State / Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63c241ed-2b8e-47ff-819a-8e19486f800b",
            "sourceColumn": "State / Province",
            "summarizeBy": "none"
          },
          {
            "name": "Pay Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7db36e8c-8894-45b7-87ee-11fa5b1d19ee",
            "sourceColumn": "Pay Group",
            "summarizeBy": "none"
          },
          {
            "name": "Opened By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c719edae-85a5-45e7-9442-435347c8a397",
            "sourceColumn": "Opened By",
            "summarizeBy": "none"
          },
          {
            "name": "Requested For",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac5b9fcc-3aa2-464c-bd80-05633cda802a",
            "sourceColumn": "Requested For",
            "summarizeBy": "none"
          },
          {
            "name": "Request State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1ec751b-346b-4c36-bdd0-dc33c2d1ac08",
            "sourceColumn": "Request State",
            "summarizeBy": "none"
          },
          {
            "name": "Date Assigned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0003d314-744d-445d-bce1-4a4a229f6958",
            "sourceColumn": "Date Assigned",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_914b53b7-ff85-43e4-a732-dd0898818a8d"
                },
                "isDefault": true,
                "relationship": "a30f67ef-006d-4db9-a584-ed9e74e1709e"
              }
            ]
          },
          {
            "name": "Assigned To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "274dc284-2510-4eb5-9497-65772f7bdffc",
            "sourceColumn": "Assigned To",
            "summarizeBy": "none"
          },
          {
            "name": "Completed By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0e673a0-9184-4c45-a0f1-7ef38c1ccc56",
            "sourceColumn": "Completed By",
            "summarizeBy": "none"
          },
          {
            "name": "Date Completed - First Action MUST BE within 3 business days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "d3fee14f-618d-4b5b-a499-a4a2644df438",
            "sourceColumn": "Date Completed - First Action MUST BE within 3 business days",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_eca1292c-ad7b-45fe-8205-88fa7351f813"
                },
                "isDefault": true,
                "relationship": "6aca91e1-92c4-4027-a734-cc25549092a4"
              }
            ]
          },
          {
            "name": "APPROVED/REJECTED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e0d5d0b-1dbb-4884-bbd1-740a069a0204",
            "sourceColumn": "APPROVED/REJECTED",
            "summarizeBy": "none"
          },
          {
            "name": "Check Fee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b962a87c-e87c-4996-814c-fe8d5e93d44b",
            "sourceColumn": "Check Fee",
            "summarizeBy": "none"
          },
          {
            "name": "Date Completed - Finalized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8e71d18c-1bd1-47a9-9e5b-42f92869274a",
            "sourceColumn": "Date Completed - Finalized",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4a74c5f1-4f8e-49b8-bb29-6ebff532bee1"
                },
                "isDefault": true,
                "relationship": "7f9a18cf-d69f-47b7-9835-b542bf288855"
              }
            ]
          },
          {
            "name": "Reassigned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cc214e9-0ea2-4c09-b99e-c034e78a4231",
            "sourceColumn": "Reassigned",
            "summarizeBy": "none"
          },
          {
            "name": "Reassigned from",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c34d9151-f676-4988-acc8-4077defc2371",
            "sourceColumn": "Reassigned from",
            "summarizeBy": "none"
          },
          {
            "name": "Elapsed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "243dace2-a254-4639-812b-2c5ac393b2bc",
            "sourceColumn": "Elapsed",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a77d6c7f-e35c-40de-aa09-f65615cc13af",
        "partitions": [
          {
            "name": "fact_myPayRequestReport_Sharepoint",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"91ffa50a-21b1-42ed-a2de-90f41f7212d0\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"91ffa50a-21b1-42ed-a2de-90f41f7212d0\"]}[Data],",
                "    fact_myPayRequestReport_Sharepoint_ = #\"91ffa50a-21b1-42ed-a2de-90f41f7212d0\"{[entity=\"fact_myPayRequestReport_Sharepoint\",version=\"\"]}[Data]",
                "in",
                "    fact_myPayRequestReport_Sharepoint_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": ".Measures",
        "calculationGroup": {},
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d59ead03-89bd-4ca7-a198-8b4dcc6f4820",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "f432398b-6bd3-4dfb-b9e7-86eddc513801",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "00ef07bf-7e7f-437a-887d-c83864fc2b65",
        "measures": [
          {
            "name": "Request Ticket Count - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "COUNTX( fact_myPayRequestReport_Sharepoint, [Request] )",
            "formatString": "0",
            "lineageTag": "57550193-0974-4b51-a628-9a1d0487b4e4"
          },
          {
            "name": "Opened Ticket Count - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "COUNTX( fact_myPayRequestReport_Sharepoint, [Opened - SP] )",
            "formatString": "0",
            "lineageTag": "56503eea-4c0f-47ad-a593-10050e7aab33"
          },
          {
            "name": "Total Days Elapsed - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] )",
              "",
              "RETURN",
              "    DATEDIFF( _openedDate, _firstActionDate, DAY )"
            ],
            "formatString": "0",
            "lineageTag": "c0a47a58-526f-4096-ba47-371745248591"
          },
          {
            "name": "SLA Check - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _workingDays = [Working Days Elapsed - SP]",
              "",
              "VAR _slaCheck = CALCULATE( ",
              "     IF( _workingDays <= 3.0, \"Passed SLA\", ",
              "    \"Failed SLA\" ) ) ",
              "",
              "RETURN",
              "    _slaCheck"
            ],
            "lineageTag": "27b3fa0d-f803-4575-b05d-b03aa6c74550"
          },
          {
            "name": "Submitted Date - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "SELECTEDVALUE ( fact_myPayRequestReport_Sharepoint[Submitted] )",
            "formatString": "General Date",
            "lineageTag": "9e9c389e-5599-47d8-9652-b56d7635a7c1"
          },
          {
            "name": "Date of First Action - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] )",
            "formatString": "General Date",
            "lineageTag": "3d92a8c4-eb22-4acb-8964-18c06adb2c55"
          },
          {
            "name": "Working Days Elapsed - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] )",
              "",
              "RETURN",
              "    NETWORKDAYS( _openedDate, _firstActionDate, 1, dim_date_Holiday )"
            ],
            "formatString": "0",
            "lineageTag": "efab3b75-8894-40b5-bf2c-5bd82d50a98e"
          },
          {
            "name": "Passed SLA - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _tickets = SUM( fact_myPayRequestReport_Sharepoint[Request] )",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _openedDate, _firstActionDate, 1, dim_date_Holiday )",
              "",
              "VAR _passed = ",
              "    COUNTROWS( ",
              "        FILTER( fact_myPayRequestReport_Sharepoint, ",
              "        [Working Days Elapsed - SP] <= 3.0 ) ) ",
              "",
              "RETURN",
              "    _passed"
            ],
            "formatString": "0",
            "lineageTag": "3ef6d14d-b6e0-4b88-a426-37ae5a4a27f8"
          },
          {
            "name": "SLA % - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "[Passed SLA - SP] / [Request Ticket Count - SP] "
            ],
            "formatStringDefinition": {
              "expression": "\"#.00%\""
            },
            "lineageTag": "da29f067-62f2-4d58-88fc-a46486e98343"
          },
          {
            "name": "TTM_Quantity - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Request Ticket Count - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "5f83f672-0ad6-478e-be06-c44ce5538ffd"
          },
          {
            "name": "TTM_KPI - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [SLA % - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"0.0#%\""
            },
            "lineageTag": "0abf8df6-5358-4926-a300-2ae3d6717c93"
          },
          {
            "name": "TTM_Goal",
            "displayFolder": "TTM - Goal",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _goal =",
              "CALCULATE( [Goal] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _goal"
            ],
            "formatStringDefinition": {
              "expression": "\"0%\""
            },
            "lineageTag": "d6ea4002-a7e3-471c-bad8-bc419cfa426b"
          },
          {
            "name": "TTM_PassedSLA - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Passed SLA - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "a80dbe86-7b60-4030-9cbc-ce546d90b0a1"
          },
          {
            "name": "Failed SLA - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _tickets = SUM( fact_myPayRequestReport_Sharepoint[Request] )",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _openedDate, _firstActionDate, 1, dim_date_Holiday )",
              "",
              "VAR _failed = ",
              "    COUNTROWS( ",
              "        FILTER( fact_myPayRequestReport_Sharepoint, ",
              "        [Working Days Elapsed - SP] > 3.0",
              "         ||",
              "         [Working Days Elapsed - SP] < 0 ) ) ",
              "",
              "RETURN",
              "    _failed"
            ],
            "formatString": "0",
            "lineageTag": "09a1765f-30e4-4954-801d-a7ac299270fd"
          },
          {
            "name": "TTM_FailedSLA - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Failed SLA - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "b0595a97-2bb5-44da-a5ee-341b966c70ab"
          },
          {
            "name": "TTM_PassedSLA-FinalPay - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [PassedSLA-FinalPay - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "3ef26dbd-1af9-403b-baa1-695050dc54b0"
          },
          {
            "name": "Check Reason - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "COUNTX( fact_myPayRequestReport_Sharepoint, [Check/Cheque Reason] )",
            "formatString": "0",
            "lineageTag": "af5b4818-f99b-4c99-aa6f-247df27413c9"
          },
          {
            "name": "PassedSLA-FinalPay - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Passed SLA - SP] , ",
              "    FILTER(",
              "        fact_myPayRequestReport_Sharepoint, ",
              "        fact_myPayRequestReport_Sharepoint[Check/Cheque Reason] = \"Final Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "0393a1aa-3ef4-42bd-94f3-ea9f204f2f43"
          },
          {
            "name": "PassedSLA-NotPay - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Passed SLA - SP] , ",
              "    FILTER(",
              "        fact_myPayRequestReport_Sharepoint, ",
              "        fact_myPayRequestReport_Sharepoint[Check/Cheque Reason] = \"Not Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "4358aae7-368a-415e-9592-d8492b4631a8"
          },
          {
            "name": "PassedSLA-ShortPay - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Passed SLA - SP] , ",
              "    FILTER(",
              "        fact_myPayRequestReport_Sharepoint, ",
              "        fact_myPayRequestReport_Sharepoint[Check/Cheque Reason] = \"Short Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "17b7d619-4edf-4f58-84ed-46763cd99603"
          },
          {
            "name": "TTM_PassedSLA-NotPay - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [PassedSLA-NotPay - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "c373aa10-581b-403b-8900-027c92ca082e"
          },
          {
            "name": "TTM_PassedSLA-ShortPay - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [PassedSLA-ShortPay - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "2a787764-cf10-4e54-bb11-2b72e5db29aa"
          },
          {
            "name": "FailedSLA-FinalPay - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Failed SLA - SP] , ",
              "    FILTER(",
              "        fact_myPayRequestReport_Sharepoint, ",
              "        fact_myPayRequestReport_Sharepoint[Check/Cheque Reason] = \"Final Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "31782d2d-62ce-4e3f-ad9e-3b4497518af4"
          },
          {
            "name": "FailedSLA-NotPay - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Failed SLA - SP] , ",
              "    FILTER(",
              "        fact_myPayRequestReport_Sharepoint, ",
              "        fact_myPayRequestReport_Sharepoint[Check/Cheque Reason] = \"Not Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "d1ba8d0c-2c9e-4a77-aeca-ec616d38e664"
          },
          {
            "name": "FailedSLA-ShortPay - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Failed SLA - SP] , ",
              "    FILTER(",
              "        fact_myPayRequestReport_Sharepoint, ",
              "        fact_myPayRequestReport_Sharepoint[Check/Cheque Reason] = \"Short Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "81eab37f-fd86-4310-b71f-6a33407141bf"
          },
          {
            "name": "TTM_FailedSLA-ShortPay - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [FailedSLA-ShortPay - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "892b8242-f642-42a9-8deb-8cf4803f6945"
          },
          {
            "name": "TTM_FailedSLA-NotPay - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [FailedSLA-NotPay - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "2567faa6-d6cf-4c1f-976f-92fd63f330c7"
          },
          {
            "name": "TTM_FailedSLA-FinalPay - SP",
            "displayFolder": "TTM - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [FailedSLA-FinalPay - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "c5837d5c-5990-4010-a29d-eba8bf82ff0b"
          },
          {
            "name": "Reviewer REQs - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( ",
              "    [Opened Ticket Count - SP] , ",
              "    FILTER(",
              "        dim_date_fiscal_DateKey, ",
              "        dim_date_fiscal_DateKey[DateID] >= _previousDate",
              "        &&",
              "        dim_date_fiscal_DateKey[DateID] <= _currentDate",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "0231e6c2-6e35-4521-8c26-4f32af4577d4"
          },
          {
            "name": "Completed By - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "DISTINCT( fact_myPayRequestReport_Sharepoint[Completed By] ) ",
            "lineageTag": "23c69b8b-b12e-40b5-95bb-effd755fb24a"
          },
          {
            "name": "Request Ticket Count2 - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "COUNTROWS( fact_myPayRequestReport_Sharepoint )",
            "formatString": "0",
            "lineageTag": "d953c462-69c9-4f58-89b7-3ae34af283b4"
          },
          {
            "name": "Goal",
            "displayFolder": "Base Measures - Goals",
            "expression": "SELECTEDVALUE(dim_gbs_mor_Goals[PR_eForm-Resolution] )",
            "lineageTag": "3f546c4e-211d-4f88-aed9-a540d4caa330"
          },
          {
            "name": "REQUEST Number",
            "displayFolder": ".noodles",
            "expression": "DISTINCT( fact_myPayRequestReport_Sharepoint[Request] )",
            "lineageTag": "85e0aa84-227c-4cc3-bac9-afedb39e9c7c"
          },
          {
            "name": "Elasped - Failed SLA (Table) - SP",
            "displayFolder": "Failed SLA Table - SharePoint",
            "expression": [
              "",
              "",
              "VAR _currentDate = SELECTEDVALUE( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR(_currentDate), MONTH(_currentDate) - 1, DAY(_currentDate) )",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] )",
              "",
              "VAR _submitted = DATE( YEAR(_openedDate), MONTH(_openedDate), DAY(_openedDate) )",
              "",
              "VAR _firstAction = DATE( YEAR(_firstActionDate), MONTH(_firstActionDate), DAY(_firstActionDate) )",
              "",
              "VAR _workingDays = NETWORKDAYS( _openedDate, _firstActionDate, 1, dim_date_Holiday )",
              "",
              "VAR _failed = ",
              "    CALCULATE( _workingDays, ",
              "        FILTER( dim_date_fiscal_DateKey, ",
              "        dim_date_fiscal_DateKey[DateID] == _currentDate ) ) ",
              "",
              "RETURN",
              "    _failed"
            ],
            "formatString": "0",
            "lineageTag": "ea4143ae-b507-46e0-89ea-646b95077cf6"
          },
          {
            "name": "Completed - First Action - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] )",
            "formatString": "Short Date",
            "lineageTag": "a18768a8-0728-4e59-a9b3-8a032699eb23"
          },
          {
            "name": "Submitted - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "DATEVALUE( SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Submitted] ))",
            "formatString": "Short Date",
            "lineageTag": "f04d58c2-91b4-460a-a558-cd61c9886dcd"
          },
          {
            "name": "Working Days - Failed SLA (Table)2",
            "displayFolder": ".noodles",
            "expression": [
              "",
              "",
              "VAR _tickets = SUM( fact_myPayRequestReport_Sharepoint[Request] )",
              "",
              "VAR _submittedDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Submitted] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _submittedDate, _firstActionDate, 1, dim_date_Holiday )",
              "",
              "VAR _failed = ",
              "    CALCULATE( _workingDays, ",
              "        FILTER( fact_myPayRequestReport_Sharepoint, ",
              "        [Working Days Elapsed - SP] > 3.0",
              "        ||",
              "        [Working Days Elapsed - SP] < 0 ) )",
              "",
              "RETURN",
              "    _failed"
            ],
            "formatString": "0",
            "lineageTag": "a73f5bd9-32c4-427f-beab-368d64eb2d4b"
          },
          {
            "name": "First Action Date - Failed SLA (Table)",
            "displayFolder": ".noodles",
            "expression": [
              "",
              "",
              "VAR _tickets = SUM( fact_myPayRequestReport_Sharepoint[Request] )",
              "",
              "VAR _submittedDate = DATEVALUE( SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Submitted] ) )",
              "",
              "VAR _firstActionDate = DATEVALUE( SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] ) )",
              "",
              "VAR _workingDays = NETWORKDAYS( _submittedDate, _firstActionDate, 1, dim_date_Holiday )",
              "",
              "VAR _failed = ",
              "    CALCULATE( _firstActionDate, ",
              "        FILTER( fact_myPayRequestReport_Sharepoint, ",
              "        [Working Days Elapsed - SP] > 3.0",
              "        ||",
              "        [Working Days Elapsed - SP] < 0 ) ) ",
              "",
              "RETURN",
              "    _failed"
            ],
            "formatString": "Short Date",
            "lineageTag": "3990c3e5-65d4-4675-b131-4073b42ecef5"
          },
          {
            "name": "NetWorkDays",
            "displayFolder": ".noodles",
            "expression": "NETWORKDAYS( [Submitted Date - SP], [Completed - First Action - SP], 1, dim_date_Holiday )",
            "formatString": "0",
            "lineageTag": "c696cc27-8b2b-4ad1-80cd-62c0d763573e"
          },
          {
            "name": "Failed SLA (Table)2",
            "displayFolder": ".noodles",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _submittedDate = SELECTEDVALUE(fact_myPayRequestReport_Sharepoint[Submitted] ) ",
              "",
              "VAR _request = CALCULATE(MIN(fact_myPayRequestReport_Sharepoint[Request] ) )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Date Completed - First Action MUST BE within 3 business days] )",
              "",
              "VAR _submitted = DATE( YEAR(_submittedDate), MONTH(_submittedDate), DAY(_submittedDate) )",
              "",
              "VAR _firstAction = DATE( YEAR(_firstActionDate), MONTH(_firstActionDate), DAY(_firstActionDate) )",
              "",
              "VAR _workingDays = NETWORKDAYS( _submitted, _firstAction, 1, dim_date_Holiday )",
              "",
              "RETURN",
              "    _request"
            ],
            "lineageTag": "1639bc33-c161-4896-8409-3e03331f56c0"
          },
          {
            "name": "Column Width",
            "displayFolder": "Formatting",
            "expression": "\"********\"",
            "lineageTag": "af2538ff-7f65-4f7f-8f99-53f99a2d45cd"
          },
          {
            "name": "SLA - Background (SP)",
            "displayFolder": "Formatting - SharePoint",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % - SP] >= [Goal], \"#009900\",",
              "        [SLA % - SP] < ( [Goal] * 0.9 ), \"#CC0000\", ",
              "        \"#FFFF00\" ) "
            ],
            "lineageTag": "216f61fc-bb21-4241-b08c-3c33d961ac01"
          },
          {
            "name": "SLA - Font (SP)",
            "displayFolder": "Formatting - SharePoint",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA % - SP] >= [Goal], \"#FFFFFF\",",
              "        [SLA % - SP] < ( [Goal] * 0.9 ), \"#FFFFFF\", ",
              "        \"#000000\" ) "
            ],
            "lineageTag": "382d42a2-ae2e-4357-a8e1-8e307a6f3cb3"
          },
          {
            "name": "Opened - SP",
            "displayFolder": "Base Measures - SharePoint",
            "expression": "DATEVALUE( SELECTEDVALUE( fact_myPayRequestReport_Sharepoint[Opened] ))",
            "formatString": "Short Date",
            "lineageTag": "ed94fa5c-13f8-4d22-a772-99c2f3cd188e"
          },
          {
            "name": "Check Reason",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "COUNTX( fact_ManualCheckRequest_Payroll, [check_reason] )",
            "formatString": "0",
            "lineageTag": "759b3176-094f-4e2a-96d0-c8bcc7d7ded2"
          },
          {
            "name": "TTM_FailedSLA",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Failed SLA] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "1c41d256-b935-4119-8f69-0af20d5e81c8"
          },
          {
            "name": "TTM_FailedSLA-FinalPay",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [FailedSLA-FinalPay] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "lineageTag": "4396eb24-53ba-40bb-bfac-4a970dbbc14f"
          },
          {
            "name": "TTM_FailedSLA-NotPay",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [FailedSLA-NotPay] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "lineageTag": "2039723e-acfb-4037-9064-e8a7b67e71fb"
          },
          {
            "name": "TTM_FailedSLA-ShortPay",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [FailedSLA-ShortPay] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "lineageTag": "2347f24c-3532-45e4-be2f-04616003b8f9"
          },
          {
            "name": "TTM_KPI",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [SLA %] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"0.##%\""
            },
            "lineageTag": "a601ecf7-8e4d-4aa5-8e29-f2e4f26cabaa"
          },
          {
            "name": "TTM_PassedSLA",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Passed SLA] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "e576a773-253e-42df-8a7a-7ac7430c9d00"
          },
          {
            "name": "TTM_PassedSLA-FinalPay",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [PassedSLA-FinalPay] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "lineageTag": "7102ed20-6182-489d-8726-0ef5353ae0cf"
          },
          {
            "name": "TTM_PassedSLA-NotPay",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [PassedSLA-NotPay] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "lineageTag": "d4712f7e-d10e-4319-b4a7-69a297a1daf8"
          },
          {
            "name": "TTM_PassedSLA-ShortPay",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [PassedSLA-ShortPay] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "lineageTag": "0d0db348-d071-4644-a189-9cbc59eaa014"
          },
          {
            "name": "TTM_Quantity",
            "displayFolder": "TTM - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Request Ticket Count] , ",
              "    FILTER(",
              "        dim_date_fiscal_MonthKey, ",
              "        dim_date_fiscal_MonthKey[DateID] >= _previousDate",
              "            && dim_date_fiscal_MonthKey[DateID] <= _currentDate",
              "    ) ) ",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatStringDefinition": {
              "expression": "\"#,0\""
            },
            "lineageTag": "8f302bd8-affe-4bed-9e73-bc574b338477"
          },
          {
            "name": "Completed - First Action",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "SELECTEDVALUE( fact_ManualCheckRequest_Payroll[completed_first_action] )",
            "formatString": "Short Date",
            "lineageTag": "4161ee8d-c591-403d-8118-59f38187a3f1"
          },
          {
            "name": "Completed By",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "DISTINCT( fact_ManualCheckRequest_Payroll[completed_by] ) ",
            "lineageTag": "f9edb750-a0ad-4186-ac9c-ab940ce2db55"
          },
          {
            "name": "Date of First Action",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "SELECTEDVALUE( fact_ManualCheckRequest_Payroll[completed_first_action] )",
            "formatString": "General Date",
            "lineageTag": "fcf07d12-c3c2-40e1-b966-133ef9531625"
          },
          {
            "name": "Failed SLA",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _tickets = SUM( fact_ManualCheckRequest_Payroll[request] )",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[completed_first_action] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _openedDate, _firstActionDate, 1, dim_date_Holiday )",
              "",
              "VAR _failed = ",
              "    COUNTROWS( ",
              "        FILTER( fact_ManualCheckRequest_Payroll , ",
              "        [Working Days Elapsed] > 3.0",
              "         ||",
              "         [Working Days Elapsed] < 0 ) ) ",
              "",
              "RETURN",
              "    _failed"
            ],
            "lineageTag": "e560d73d-68c4-484e-8a52-b87bd335d65c"
          },
          {
            "name": "FailedSLA-FinalPay",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Failed SLA] , ",
              "    FILTER(",
              "        fact_ManualCheckRequest_Payroll, ",
              "        fact_ManualCheckRequest_Payroll[check_reason] = \"Final Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "17f78dd9-099e-442f-b1c7-a74e4d1eab50"
          },
          {
            "name": "FailedSLA-NotPay",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Failed SLA] , ",
              "    FILTER(",
              "        fact_ManualCheckRequest_Payroll, ",
              "        fact_ManualCheckRequest_Payroll[check_reason] = \"Not Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "d43161c7-9e3f-4e31-97da-706cddb9d6ae"
          },
          {
            "name": "FailedSLA-ShortPay",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Failed SLA] , ",
              "    FILTER(",
              "        fact_ManualCheckRequest_Payroll, ",
              "        fact_ManualCheckRequest_Payroll[check_reason] = \"Short Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "72b8831e-fce6-4f1e-bd81-6b377ad3f8bc"
          },
          {
            "name": "Opened",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "DATEVALUE( SELECTEDVALUE( fact_ManualCheckRequest_Payroll[opened] ))",
            "formatString": "Short Date",
            "lineageTag": "7879d2b9-85ff-45c7-9941-e87b79d19eb7"
          },
          {
            "name": "Opened Ticket Count",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "COUNTX( fact_ManualCheckRequest_Payroll, [Opened] )",
            "formatString": "0",
            "lineageTag": "0120d05b-1a90-4bc2-af6b-6eeec462520d"
          },
          {
            "name": "Passed SLA",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _tickets = SUM( fact_ManualCheckRequest_Payroll[request] )",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[completed_first_action] )",
              "",
              "VAR _workingDays = NETWORKDAYS( _openedDate, _firstActionDate, 1, dim_date_Holiday )",
              "",
              "VAR _passed = ",
              "    COUNTROWS( ",
              "        FILTER( fact_ManualCheckRequest_Payroll, ",
              "        [Working Days Elapsed] <= 3.0 ) ) ",
              "",
              "RETURN",
              "    _passed"
            ],
            "lineageTag": "04f652a5-513b-4a8b-94b6-02ad02850ab5"
          },
          {
            "name": "PassedSLA-FinalPay",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Passed SLA] , ",
              "    FILTER(",
              "        fact_ManualCheckRequest_Payroll, ",
              "        fact_ManualCheckRequest_Payroll[check_reason] = \"Final Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty "
            ],
            "formatString": "0",
            "lineageTag": "46488377-e4a4-4634-8fa4-fcb6ed261952"
          },
          {
            "name": "PassedSLA-NotPay",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Passed SLA] , ",
              "    FILTER(",
              "        fact_ManualCheckRequest_Payroll, ",
              "        fact_ManualCheckRequest_Payroll[check_reason] = \"Not Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "8d2b5d8d-c264-4bff-8be3-ab4c01f7d2e6"
          },
          {
            "name": "PassedSLA-ShortPay",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( [Passed SLA] , ",
              "    FILTER(",
              "        fact_ManualCheckRequest_Payroll, ",
              "        fact_ManualCheckRequest_Payroll[check_reason] = \"Short Pay\"",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "934dd7a7-8e81-4f35-81f5-1efbb6d1fce0"
          },
          {
            "name": "Request Ticket Count",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "COUNTX( fact_ManualCheckRequest_Payroll, [request] )",
            "formatString": "0",
            "lineageTag": "a9e02091-451c-4f02-8440-0ba715411a64"
          },
          {
            "name": "Request Ticket Count2",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "COUNTROWS( fact_ManualCheckRequest_Payroll )",
            "formatString": "0",
            "lineageTag": "683240ba-e9f6-4a43-9e07-7f0be2f88b5d"
          },
          {
            "name": "Reviewer REQs",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _currentDate = MAX( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR( _currentDate ) , MONTH( _currentDate ) - 12 , DAY( _currentDate ) )",
              "",
              "VAR _qty = ",
              "CALCULATE( ",
              "    [Opened Ticket Count] , ",
              "    FILTER(",
              "        dim_date_fiscal_DateKey, ",
              "        dim_date_fiscal_DateKey[DateID] >= _previousDate",
              "        &&",
              "        dim_date_fiscal_DateKey[DateID] <= _currentDate",
              "    ) )",
              "",
              "RETURN",
              "    _qty"
            ],
            "formatString": "0",
            "lineageTag": "029cf08e-d454-4c4b-a734-c278d95e8fc7"
          },
          {
            "name": "SLA %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "ROUNDDOWN( DIVIDE( [Passed SLA] , [Request Ticket Count] ) , 4 ) "
            ],
            "lineageTag": "e6a0d45f-487f-47d6-92c0-cd61d0c69843"
          },
          {
            "name": "SLA Check",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _workingDays = [Working Days Elapsed]",
              "",
              "VAR _slaCheck = CALCULATE( ",
              "     IF( _workingDays <= 3.0, \"Passed SLA\", ",
              "    \"Failed SLA\" ) ) ",
              "",
              "RETURN",
              "    _slaCheck"
            ],
            "lineageTag": "ed0650c3-bb06-4fd5-8376-ffca92881218"
          },
          {
            "name": "Submitted",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "DATEVALUE( SELECTEDVALUE( fact_ManualCheckRequest_Payroll[submitted] ))",
            "formatString": "General Date",
            "lineageTag": "2a3a3d75-4f7d-4b32-a4c7-a95997614d07"
          },
          {
            "name": "Submitted Date",
            "displayFolder": "Base Measures - SQL Server",
            "expression": "SELECTEDVALUE ( fact_ManualCheckRequest_Payroll[submitted] )",
            "formatString": "General Date",
            "lineageTag": "1204b0be-17ee-49cb-803b-501e1572ccd7"
          },
          {
            "name": "Total Days Elapsed",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[completed_first_action] )",
              "",
              "RETURN",
              "    DATEDIFF( _openedDate, _firstActionDate, DAY )"
            ],
            "formatString": "0",
            "lineageTag": "dd94aa95-396d-4515-942a-a9525d539b0b"
          },
          {
            "name": "Working Days Elapsed",
            "displayFolder": "Base Measures - SQL Server",
            "expression": [
              "",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[completed_first_action] )",
              "",
              "RETURN",
              "    NETWORKDAYS( _openedDate, _firstActionDate, 1, dim_date_Holiday )"
            ],
            "formatString": "0",
            "lineageTag": "f630dd3e-b5ec-4948-8e7f-ee847c1ca62c"
          },
          {
            "name": "Elasped - Failed SLA (Table)",
            "displayFolder": "Failed SLA Table - SQL",
            "expression": [
              "",
              "",
              "VAR _currentDate = SELECTEDVALUE( dim_date_fiscal_TTMKey[DateID] )",
              "",
              "VAR _previousDate = DATE( YEAR(_currentDate), MONTH(_currentDate) - 1, DAY(_currentDate) )",
              "",
              "VAR _openedDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[opened] )",
              "",
              "VAR _firstActionDate = SELECTEDVALUE( fact_ManualCheckRequest_Payroll[completed_first_action] )",
              "",
              "VAR _submitted = DATE( YEAR(_openedDate), MONTH(_openedDate), DAY(_openedDate) )",
              "",
              "VAR _firstAction = DATE( YEAR(_firstActionDate), MONTH(_firstActionDate), DAY(_firstActionDate) )",
              "",
              "VAR _workingDays = NETWORKDAYS( _openedDate, _firstActionDate, 1, dim_date_Holiday )",
              "",
              "VAR _failed = ",
              "    CALCULATE( _workingDays, ",
              "        FILTER( dim_date_fiscal_DateKey, ",
              "        dim_date_fiscal_DateKey[DateID] == _currentDate ) ) ",
              "",
              "RETURN",
              "    _failed "
            ],
            "formatString": "0",
            "lineageTag": "8134bfb5-8496-41d9-9c18-79637b312d02"
          },
          {
            "name": "SLA - Background",
            "displayFolder": "Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA %] >= [Goal], \"#009900\",",
              "        [SLA %] < ( [Goal] * 0.9 ), \"#CC0000\", ",
              "        \"#FFFF00\" ) "
            ],
            "lineageTag": "1380e3f7-2631-46c7-a7ff-8de000a77c03"
          },
          {
            "name": "SLA - Font",
            "displayFolder": "Formatting",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(), ",
              "        [SLA %] >= [Goal], \"#FFFFFF\",",
              "        [SLA %] < ( [Goal] * 0.9 ), \"#FFFFFF\", ",
              "        \"#000000\" ) "
            ],
            "lineageTag": "ec31ccb6-4ddd-454e-9d6c-0004befbd188"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_914b53b7-ff85-43e4-a732-dd0898818a8d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1bc00d89-bbd5-46d2-bb40-d0bdb516d64b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "dcf5f9d5-4528-47be-9381-30207a96cc5a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b947903a-09e1-4ebe-9b9e-fd120b5625f3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6e2ae014-8820-420d-aa62-10c9a3548996",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "823c66fd-cdc8-4d39-b8cb-75ae1bdaca5f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5f87ab29-8afb-4ec1-a795-9855f7a454d9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5a849153-9d15-460d-8409-ce2532e8dde0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c0e6c7c8-e056-48da-8ce4-11a7df45b85f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0ae4614f-b353-44df-9383-b4bfcd39df2c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4e0289ff-6292-4e38-8cfc-93138bdc2c1f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "76d45637-1a55-4c05-957b-0ae6096e45f0",
                "ordinal": 3
              }
            ],
            "lineageTag": "3026dc5a-6e63-4c2f-a8da-22ee1cfb0829"
          }
        ],
        "isHidden": true,
        "lineageTag": "7bc1ab66-e80d-47e7-aec2-695f5a3b0415",
        "partitions": [
          {
            "name": "LocalDateTable_914b53b7-ff85-43e4-a732-dd0898818a8d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_myPayRequestReport_Sharepoint'[Date Assigned])), 1, 1), Date(Year(MAX('fact_myPayRequestReport_Sharepoint'[Date Assigned])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4a74c5f1-4f8e-49b8-bb29-6ebff532bee1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5b2c0c45-81f7-42d4-a465-be020e3be087",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5ef98914-373b-4e09-be91-c1676f0c6531",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6427024f-2f22-41a5-88de-18e37842bc47",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d9e9daf7-62fe-4f83-a6d5-a720c02193dd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c9b69bcf-7468-488d-a2ce-d30a3bcd9d83",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "871dea22-9b63-474d-b806-91b8fc2e27a4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7e4f1f6d-2b60-42bf-9853-df34abb4a4a5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "659819d1-0763-49ef-a05e-cf87e42542bd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c9e6d815-3c7a-4ea6-8b13-e27476d07e3b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2ce3ba7c-c83f-4b52-a2be-5a48a6cddd09",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1eef6b53-bae4-4547-b142-ec1ec7aba0b3",
                "ordinal": 3
              }
            ],
            "lineageTag": "c7e335da-8a65-4caf-9590-ef18a815a2dd"
          }
        ],
        "isHidden": true,
        "lineageTag": "d68cb64c-7935-44da-b73a-461081089499",
        "partitions": [
          {
            "name": "LocalDateTable_4a74c5f1-4f8e-49b8-bb29-6ebff532bee1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_myPayRequestReport_Sharepoint'[Date Completed - Finalized])), 1, 1), Date(Year(MAX('fact_myPayRequestReport_Sharepoint'[Date Completed - Finalized])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_6c8fa93c-f437-4be5-87c3-c593e4511d6f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "39371931-f44c-4b06-b18d-40ae58061ffe",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "36634d91-6ca8-4518-9579-228ff221f931",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "2dd24999-6ba0-4005-b55b-5b8935409b68",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "fa74e4bc-2c3d-4f53-addf-13c54084a6a9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c83d47c1-f89b-4d85-b2af-4eaba010b66c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2fe25650-7c7d-4e24-994f-f585c9cc1b92",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d6b01979-1659-4f0e-b69b-47f542bf592f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "68771887-9073-4004-b047-a78481429a50",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ae884611-d56f-4b18-9810-0362d9bb4f62",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "24598633-db8b-4cf7-a1bc-1c9f1453a995",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1e30ab6b-c264-4001-89f2-8fa9d99dbb25",
                "ordinal": 3
              }
            ],
            "lineageTag": "734becc2-dcce-48d9-9278-7a5ae896d484"
          }
        ],
        "isHidden": true,
        "lineageTag": "1cf945a0-551b-4c77-ad42-9a824c4f9246",
        "partitions": [
          {
            "name": "LocalDateTable_6c8fa93c-f437-4be5-87c3-c593e4511d6f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_DateKey'[DateID])), 1, 1), Date(Year(MAX('dim_date_fiscal_DateKey'[DateID])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_eca1292c-ad7b-45fe-8205-88fa7351f813",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ba11ca00-eb47-4e91-a932-ffd573f8c58a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "378cf19b-0883-42a7-b5dc-6327365727ee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e1573102-d399-4189-8fa4-0b881e8d3e93",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "16689d12-dd33-4887-962b-101c6c8a0043",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "378fffa9-3556-4d58-8375-11270bc3ebb4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "da0c2df7-915a-47ea-9817-d8aa2d192f98",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a10d15ce-a68d-47fc-b835-ffdad3bf9587",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "34cefd12-f7ab-4287-a794-0f4c3a156fbf",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a16ac3c7-c455-4bcf-884d-436dceda7b4e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d19d3f0a-68ab-4667-925e-0c81259a90f6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4ec29e52-725b-4cdd-aac4-baf3430a0969",
                "ordinal": 3
              }
            ],
            "lineageTag": "855c9cff-33e0-4c7d-ae11-898b121d4f16"
          }
        ],
        "isHidden": true,
        "lineageTag": "f87c8d53-f600-44a7-aeb9-48387b3e7ec6",
        "partitions": [
          {
            "name": "LocalDateTable_eca1292c-ad7b-45fe-8205-88fa7351f813",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_myPayRequestReport_Sharepoint'[Date Completed - First Action MUST BE within 3 business days])), 1, 1), Date(Year(MAX('fact_myPayRequestReport_Sharepoint'[Date Completed - First Action MUST BE within 3 business days])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_bdebe84b-ece2-4e5a-b795-61cdd67eb9aa",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "01514445-66e1-4765-b20b-3e7bfbcbae49",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b6c86418-bf8a-42de-a500-4b56133d7476",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "61ed32ae-85a3-464c-937f-a6beaacd87ee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d8eec049-e619-4305-913b-43cb1685a2f7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0a161000-122a-410a-91e8-264c0ba1e11d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2f27911c-5db6-4ace-bd2c-9db8c6a4b819",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "affca4ee-9a98-4ee5-a2ee-3a86c0f7c015",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "514868a3-4154-44f9-ac1e-a093f7502e0d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "68851b95-a212-4ca9-a02c-cced751af482",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "12eb9bd2-bd0f-4d8f-95b5-5346bc774c00",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b3801946-a0b8-4032-8ec6-deb00677bd6b",
                "ordinal": 3
              }
            ],
            "lineageTag": "8da45ff3-e991-400b-8b5c-944cf21d5ddf"
          }
        ],
        "isHidden": true,
        "lineageTag": "486da569-09b3-41fc-9c73-e0ad171c595d",
        "partitions": [
          {
            "name": "LocalDateTable_bdebe84b-ece2-4e5a-b795-61cdd67eb9aa",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_fiscal_MonthKey'[DateID - Mmm])), 1, 1), Date(Year(MAX('dim_date_fiscal_MonthKey'[DateID - Mmm])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_gbs_mor_Goals",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14c4e291-452c-4047-ab23-f7bc7261fb5b",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Period-ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc79524d-e2fa-4f29-b83c-390cb91a00e3",
            "sourceColumn": "Period-ID",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal-Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1815970b-4a35-44a4-910a-bd05a4276515",
            "sourceColumn": "Fiscal-Period",
            "summarizeBy": "none"
          },
          {
            "name": "AR_Incident-Resolution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44a7349b-1324-4c4c-8f7d-1f522cffeb42",
            "sourceColumn": "AR_Incident-Resolution",
            "summarizeBy": "none"
          },
          {
            "name": "AR_Unapplied-Cash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "926eb242-b684-4082-8fa4-3715cbac7018",
            "sourceColumn": "AR_Unapplied-Cash",
            "summarizeBy": "none"
          },
          {
            "name": "AR_Cost-Per-Manual-Receipt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "405badf2-789f-4374-bb4e-3f12535827cc",
            "sourceColumn": "AR_Cost-Per-Manual-Receipt",
            "summarizeBy": "none"
          },
          {
            "name": "AR_Cost-Per-SNow-Request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1768235-fb1a-449b-8316-af6d044c7ab6",
            "sourceColumn": "AR_Cost-Per-SNow-Request",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Debit-Pending-Items-US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83f1175b-9e35-4897-9cd3-ba428ca3900b",
            "sourceColumn": "CB_Debit-Pending-Items-US",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Bank-Account-Reconciliation-US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae40a50a-6088-40de-861f-7f119444a7a5",
            "sourceColumn": "CB_Bank-Account-Reconciliation-US",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Cost-Per-Manually-Reconcilied-Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0e8db3b-0813-4833-ba92-2558e34fd7e8",
            "sourceColumn": "CB_Cost-Per-Manually-Reconcilied-Item",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Debit-Pending-Items-CAN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3c2b0ef-409b-429b-82f9-fbcda850af08",
            "sourceColumn": "CB_Debit-Pending-Items-CAN",
            "summarizeBy": "none"
          },
          {
            "name": "CB_Bank-Account-Reconciliation-CAN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62f2c4da-1a08-476c-a5c1-85a541c3b37a",
            "sourceColumn": "CB_Bank-Account-Reconciliation-CAN",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CIP-Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4e49385-608b-4fe2-bac3-4fc1043ff4e9",
            "sourceColumn": "FA_CIP-Balance",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CIP-Balance-Stale",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2178641-afdb-48ad-8a1b-0a1b65144006",
            "sourceColumn": "FA_CIP-Balance-Stale",
            "summarizeBy": "none"
          },
          {
            "name": "FA_CERs-Closed-Timely",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6b71a42-60d2-4537-b110-e25553ee35fa",
            "sourceColumn": "FA_CERs-Closed-Timely",
            "summarizeBy": "none"
          },
          {
            "name": "FA_Cost-Per-Transaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef33968b-0342-4cad-8b3b-6599b4287f77",
            "sourceColumn": "FA_Cost-Per-Transaction",
            "summarizeBy": "none"
          },
          {
            "name": "FA_Reconciliations-Prepared-And-Reviewed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "660a330d-1616-4bba-9234-f5d8b18dd2b0",
            "sourceColumn": "FA_Reconciliations-Prepared-And-Reviewed",
            "summarizeBy": "none"
          },
          {
            "name": "GL_Accurate-Journal-Entries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f5738d7-8791-449d-962e-0e8e2e76437c",
            "sourceColumn": "GL_Accurate-Journal-Entries",
            "summarizeBy": "none"
          },
          {
            "name": "GL_Cost-Per-Manual-Journal-Entries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f14cc0cf-7595-4c16-994f-eb23898adcaa",
            "sourceColumn": "GL_Cost-Per-Manual-Journal-Entries",
            "summarizeBy": "none"
          },
          {
            "name": "GL_Reconciliations-Prepared-And-Reviewed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57c5a18e-3ac1-4a76-a622-253d767e4e82",
            "sourceColumn": "GL_Reconciliations-Prepared-And-Reviewed",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Cost-Per-Invoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f37718ac-4ef0-490f-a257-944a755b7fbf",
            "sourceColumn": "AP_Cost-Per-Invoice",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Incident-Resolution-Invoice-Entry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9de449ff-1266-4fc9-a4c6-71e212d33959",
            "sourceColumn": "AP_Incident-Resolution-Invoice-Entry",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Cost-Per-Payment-Processed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18cfba6b-f4a5-4e1c-a321-4fcba92e1f38",
            "sourceColumn": "AP_Cost-Per-Payment-Processed",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Incident-Resolution-Banking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1e8f388-c87b-4d93-87a9-450498f506f7",
            "sourceColumn": "AP_Incident-Resolution-Banking",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Cost-Per-Vendor-Setup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0332456-8fd1-4e11-9d20-65c90f55fe25",
            "sourceColumn": "AP_Cost-Per-Vendor-Setup",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Incident-Resolution-Vendor-Control",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3542405-0a27-42f9-a466-89ba5d5d1b3b",
            "sourceColumn": "AP_Incident-Resolution-Vendor-Control",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Audit-Recovery-Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b66b9246-c6e3-4e84-8cf9-1408f1a1004b",
            "sourceColumn": "AP_Audit-Recovery-Rate",
            "summarizeBy": "none"
          },
          {
            "name": "AP_Audit-Recovery-Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "145cd52f-8816-420d-823b-08b613621fde",
            "sourceColumn": "AP_Audit-Recovery-Volume",
            "summarizeBy": "none"
          },
          {
            "name": "PR_Cost-Per-Payment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70bab008-1c0c-431a-8a55-49f109bf5de7",
            "sourceColumn": "PR_Cost-Per-Payment",
            "summarizeBy": "none"
          },
          {
            "name": "PR_eForm-Resolution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9384f54a-a92c-4f1b-bd4b-4639d8eb4746",
            "sourceColumn": "PR_eForm-Resolution",
            "summarizeBy": "sum"
          },
          {
            "name": "PR_Incident-Resolution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "923db9d3-5603-49dd-b966-972aa70d2096",
            "sourceColumn": "PR_Incident-Resolution",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Customer-Satisfaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52296121-bec8-421c-9fdb-2e0db56bf66f",
            "sourceColumn": "CC_Customer-Satisfaction",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Survey-Participation-Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f560785-dc4a-4d46-bc68-f0833272535e",
            "sourceColumn": "CC_Survey-Participation-Rate",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Average-Answer-Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f96bf0d-4543-41f3-b93e-8227e0ce59c7",
            "sourceColumn": "CC_Average-Answer-Time",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Abandonment-Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4609e2f1-99e2-4a29-a577-0216074e1f8f",
            "sourceColumn": "CC_Abandonment-Rate",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Calls-Answered-Within-SLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f201d07-0404-4dd5-b4f4-6cadd017958e",
            "sourceColumn": "CC_Calls-Answered-Within-SLA",
            "summarizeBy": "none"
          },
          {
            "name": "CC_Callbacks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14e20def-d784-4b58-8c7e-16de8c46f871",
            "sourceColumn": "CC_Callbacks",
            "summarizeBy": "none"
          },
          {
            "name": "PS_Average-Answer-Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4075acb6-0f49-4ea9-a0e2-2a641b938835",
            "sourceColumn": "PS_Average-Answer-Time",
            "summarizeBy": "none"
          },
          {
            "name": "PS_Abandonment-Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad68dd01-9d75-484a-9d20-060df9a3fd7e",
            "sourceColumn": "PS_Abandonment-Rate",
            "summarizeBy": "none"
          },
          {
            "name": "PS_Inbound-Email-Efficiency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "377e040c-306a-467c-aeda-c6a5c86f691e",
            "sourceColumn": "PS_Inbound-Email-Efficiency",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4468c842-3c74-4e19-86a5-ede1f30f093b",
        "partitions": [
          {
            "name": "dim_gbs_mor_Goals",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"2976903809263492\" = Source{[Key=\"2976903809263492\"]}[Data],",
                "    #\"8860436996771716\" = #\"2976903809263492\"{[Key=\"8860436996771716\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"8860436996771716\",{{\"Period-ID\", type text}, {\"Fiscal-Period\", type text}, {\"PR_eForm-Resolution\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_date_Holiday",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Holiday-Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8c62baf1-555c-4b64-989d-6fa39907d088",
            "sourceColumn": "Holiday-Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_15b549a7-c9d6-4d04-9c88-727b41310491"
                },
                "isDefault": true,
                "relationship": "845f0ee8-ceb8-41d4-951b-cd9ee3774ae4"
              }
            ]
          }
        ],
        "lineageTag": "86c3c1c3-09db-4e77-9337-a11ea2060ae1",
        "partitions": [
          {
            "name": "dim_date_Holiday",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\" = Workspaces{[workspaceId=\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"]}[Data],",
                "    #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\" = #\"c52e4ff9-a75a-4ede-b43a-ee2e8b5aaae1\"{[dataflowId=\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"]}[Data],",
                "    dim_date_Holiday_ = #\"c4eefec3-54ff-4c2d-95b2-631d551349a7\"{[entity=\"dim_date_Holiday\",version=\"\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dim_date_Holiday_,{\"RowNumber\", \"Holiday-Name\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_15b549a7-c9d6-4d04-9c88-727b41310491",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "55358fde-3b68-4f98-9c37-f587914ff366",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "71ba0518-e6d2-48ca-bcd0-081142940431",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ae51f932-38cf-4608-8c5c-3855788c9235",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "af2a1fe8-9f0d-4a9d-b2b4-d9850be728df",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "1c6769a3-a5e3-46c0-9878-b29a1c480133",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5f24f9bd-3a67-467c-a199-2a4fcea4c7d8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "65dc0695-ab8f-49ac-ac8f-1c06ba8451de",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ce07d4f7-b2b9-498f-b1ad-8aac2c7c6d7d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "510af910-fadf-4961-9008-6319ada44faf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "eff03095-3e8b-484e-8fa6-9b4487138aae",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "493e0b62-2e10-44be-bc0b-334b49a5230d",
                "ordinal": 3
              }
            ],
            "lineageTag": "ca869bde-ce1f-4434-8e68-4d08e476cb3c"
          }
        ],
        "isHidden": true,
        "lineageTag": "2e9ee9fc-8be8-417f-b350-8faaf3142f7a",
        "partitions": [
          {
            "name": "LocalDateTable_15b549a7-c9d6-4d04-9c88-727b41310491",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_date_Holiday'[Holiday-Date])), 1, 1), Date(Year(MAX('dim_date_Holiday'[Holiday-Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_Employee_Payroll",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32ef9d4a-1c62-4336-a7e0-e49e0ae739bd",
            "sourceColumn": "RowNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1123d83c-9b87-4e85-93b1-416730cbaf1a",
            "sourceColumn": "Fiscal-Year",
            "summarizeBy": "none"
          },
          {
            "name": "Employee-Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df96667a-a607-4c69-94c8-7c8f1153dc1c",
            "sourceColumn": "Employee-Name",
            "summarizeBy": "none"
          },
          {
            "name": "Employee-Initial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eba69f27-19d7-4aed-9c86-933667541506",
            "sourceColumn": "Employee-Initial",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6540bac-6f56-4e0e-8001-3389175280f9",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bc2a88e-e9d7-4808-be20-9a2b95cfa1a1",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45205323-cd95-4a29-8fd5-cbdfa0fd9e35",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Maximum-%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c6394b7-feee-4630-aaf6-faf4fa5bcb78",
            "sourceColumn": "Maximum-%",
            "summarizeBy": "none"
          },
          {
            "name": "Employee-Salary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f18b9eb-14a6-4f01-90b7-77452e3bb137",
            "sourceColumn": "Employee-Salary",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "89f7e953-c2ef-4ee4-abea-bdc1fcd4ad0a",
        "partitions": [
          {
            "name": "dim_Employee_Payroll",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"2976903809263492\" = Source{[Key=\"2976903809263492\"]}[Data],",
                "    #\"6689296246695812\" = #\"2976903809263492\"{[Key=\"6689296246695812\"]}[Data],",
                "    #\"3595461470408580\" = #\"6689296246695812\"{[Key=\"3595461470408580\"]}[Data]",
                "in",
                "    #\"3595461470408580\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e865d21f-fb38-4543-b813-4036b2efc8d1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3e418356-be04-4011-a44e-ee421229af83",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "67913133-6f53-4585-8c0a-2824db9bd210",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c874cc54-2d28-4a4d-82b0-1936b3c9fe74",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "554daf53-e3fb-4ee5-a36a-145b7c240679",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "1f35505d-354b-4afa-be2b-40e8d80d56a9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "570b30f2-b852-40bd-a47c-51972e42b85b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "0e66dba0-3bd9-4bdb-afdc-578b4f2e864e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ead71653-0100-428b-97b8-06291053c823",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3920f35c-e0cf-4af7-82d2-ea5438d42710",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4173b830-c51e-4efa-ae64-a4f7fd32539e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ad6f7460-1462-41f1-9000-1f2d6516aa9d",
                "ordinal": 3
              }
            ],
            "lineageTag": "c1bb6e66-668d-435d-923b-48fdeb2559e0"
          }
        ],
        "isHidden": true,
        "lineageTag": "9ba75b20-a343-40b2-8086-93136387146a",
        "partitions": [
          {
            "name": "LocalDateTable_e865d21f-fb38-4543-b813-4036b2efc8d1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_myPayRequestReport_Sharepoint'[Submitted])), 1, 1), Date(Year(MAX('fact_myPayRequestReport_Sharepoint'[Submitted])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "fact_ManualCheckRequest_Payroll",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73ccf4f7-a315-49c2-b3b5-9f3797992eed",
            "sourceColumn": "request",
            "summarizeBy": "none"
          },
          {
            "name": "opened",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6bf65fcd-ecab-47ac-9beb-ac6181a07d2f",
            "sourceColumn": "opened",
            "summarizeBy": "none"
          },
          {
            "name": "submitted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4be3bfb0-a5c2-4a84-980c-8ff6805059f8",
            "sourceColumn": "submitted",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f7135b25-71d1-471a-a34a-9502d5634eb8"
                },
                "isDefault": true,
                "relationship": "a2bfde29-5b94-4c43-ab4f-424ed915641d"
              }
            ]
          },
          {
            "name": "check_reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "551f4332-be7a-424e-b8d1-698f7debf626",
            "sourceColumn": "check_reason",
            "summarizeBy": "none"
          },
          {
            "name": "state_province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "deab446f-d670-49fa-8325-99cd7576882a",
            "sourceColumn": "state_province",
            "summarizeBy": "none"
          },
          {
            "name": "pay_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "133125cc-6f98-4660-98b5-c9544998633e",
            "sourceColumn": "pay_group",
            "summarizeBy": "none"
          },
          {
            "name": "opened_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31bd6864-4dc3-43e8-9f37-35dac55b016f",
            "sourceColumn": "opened_by",
            "summarizeBy": "none"
          },
          {
            "name": "requested_for",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1626fed-11f0-4652-8c71-9e13899ec29b",
            "sourceColumn": "requested_for",
            "summarizeBy": "none"
          },
          {
            "name": "request_reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc5f4981-282e-451e-ab25-5551927753d2",
            "sourceColumn": "request_reason",
            "summarizeBy": "none"
          },
          {
            "name": "date_assigned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1fe32116-1e62-4a65-8490-da38a973f9f3",
            "sourceColumn": "date_assigned",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c901ae97-cd1c-4742-b3af-a35b16d9e232"
                },
                "isDefault": true,
                "relationship": "860d5c73-6fc3-4ab1-a3e2-0332f7dd80fb"
              }
            ]
          },
          {
            "name": "assigned_to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df60ec6e-adba-4e9d-8fac-6f4945031727",
            "sourceColumn": "assigned_to",
            "summarizeBy": "none"
          },
          {
            "name": "completed_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58ce4693-cd20-4b45-a409-14a4c69ec381",
            "sourceColumn": "completed_by",
            "summarizeBy": "none"
          },
          {
            "name": "completed_first_action",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "16d0c023-3c61-4322-a9f5-ff88f8a52d2a",
            "sourceColumn": "completed_first_action",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_35818df4-99c6-4d25-b366-aab09cf21ebc"
                },
                "isDefault": true,
                "relationship": "48fd1933-8715-42c6-97c1-72ce2c7ee053"
              }
            ]
          },
          {
            "name": "approved_rejected",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adecda49-a283-4aa7-b5be-78536696b7a6",
            "sourceColumn": "approved_rejected",
            "summarizeBy": "none"
          },
          {
            "name": "check_fee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00ec45b5-b921-4e28-bbbc-ed1826b05606",
            "sourceColumn": "check_fee",
            "summarizeBy": "none"
          },
          {
            "name": "notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e760737-dd0b-49e1-a384-9139251b8b9a",
            "sourceColumn": "notes",
            "summarizeBy": "none"
          },
          {
            "name": "completed_finalized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae23826a-dea8-4983-8219-67a3e997328e",
            "sourceColumn": "completed_finalized",
            "summarizeBy": "none"
          },
          {
            "name": "kronos_integration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f2f5c9e-9163-4dcd-8be1-4221d91f5f3c",
            "sourceColumn": "kronos_integration",
            "summarizeBy": "none"
          },
          {
            "name": "reassigned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eff27a40-5186-4924-9f3d-520d756b347b",
            "sourceColumn": "reassigned",
            "summarizeBy": "none"
          },
          {
            "name": "reassigned_from",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d81ada0-7525-4d46-b8ec-b61ad07532d2",
            "sourceColumn": "reassigned_from",
            "summarizeBy": "none"
          },
          {
            "name": "loaded_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "65d118e5-8c05-4656-9a60-68689c70f380",
            "sourceColumn": "loaded_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_95b4b8fc-862d-4f4c-9a5e-5ceecda8eea9"
                },
                "isDefault": true,
                "relationship": "a5ffed66-ea56-4e54-9b17-0818629df40f"
              }
            ]
          },
          {
            "name": "report_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09ac39ab-58e9-468c-bf5c-397f6a8d51a1",
            "sourceColumn": "report_name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "166fbd19-6174-4731-a686-4f6232f81fb7",
        "partitions": [
          {
            "name": "fact_ManualCheckRequest_Payroll",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"USPHL0PRPADBA1\", \"Graham_Workspace\"),",
                "    dbo_fact_ManualCheckRequest_Payroll = Source{[Schema=\"dbo\",Item=\"fact_ManualCheckRequest_Payroll\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_fact_ManualCheckRequest_Payroll,{{\"opened\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_95b4b8fc-862d-4f4c-9a5e-5ceecda8eea9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ded50db7-c736-454f-9348-6832c43b1bd6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "a8127306-c31d-442a-a8a3-14d6dbc2f96f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "71fa7410-e04e-49a4-a821-22bf7bfd6d91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2d65982c-3f9b-4a46-8ef7-26516285c8ec",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3734a07b-061e-4dc3-a901-78f0c554bae0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "61478eac-411d-4f1a-8321-97653cc7d373",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c49fef76-9930-4dbe-88f7-923ac646c25e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4d236878-5821-4d71-a8e9-64e95e6aa3fb",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7f105b14-725a-4606-b94c-66f99b350130",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0382ed57-6a5f-41fd-8967-1eb2dfd1520b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "47c997e8-446e-484d-9ae4-c0ca3b78cb59",
                "ordinal": 3
              }
            ],
            "lineageTag": "1508c512-b64f-4411-8ce0-c82c6f449e58"
          }
        ],
        "isHidden": true,
        "lineageTag": "6872598e-e193-4084-8513-bbe23e05b619",
        "partitions": [
          {
            "name": "LocalDateTable_95b4b8fc-862d-4f4c-9a5e-5ceecda8eea9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_ManualCheckRequest_Payroll'[loaded_date])), 1, 1), Date(Year(MAX('fact_ManualCheckRequest_Payroll'[loaded_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f7135b25-71d1-471a-a34a-9502d5634eb8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "34fab3f1-20e0-4c6e-8313-fab08e508f28",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f5aa9a5e-3fe6-4b55-bec8-411f549fd2c6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "27a8b592-fbc7-4737-b1a9-2786cd537b02",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4c381078-0622-4a61-baf4-7b319a0d2804",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2ad43e59-089b-48d7-8e1e-f7a27f90f61d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "759d377b-49e6-4236-aeea-409a8a49f747",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "add419c8-d149-48b7-9b8a-02c593b98019",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "20e630cd-e25e-4eae-835a-486e0c6d5788",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "07bfb72d-839b-43df-8417-bf78991274ec",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "17e5a8ee-5f41-4429-afbe-d3da9cc73fd0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6337f36c-7090-435a-87c8-747f09d1cac0",
                "ordinal": 3
              }
            ],
            "lineageTag": "9e8b6379-22bb-48b5-a9a3-818b117a6cd6"
          }
        ],
        "isHidden": true,
        "lineageTag": "3d253e5b-4d12-4d25-a813-288a3b842077",
        "partitions": [
          {
            "name": "LocalDateTable_f7135b25-71d1-471a-a34a-9502d5634eb8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_ManualCheckRequest_Payroll'[submitted])), 1, 1), Date(Year(MAX('fact_ManualCheckRequest_Payroll'[submitted])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c901ae97-cd1c-4742-b3af-a35b16d9e232",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "75fcaf81-d1f2-453e-91a4-888ce9ffb71a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ad857d01-7c08-49d8-9de5-d5da363bfa83",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "87a348e0-c7c7-429b-bf76-0e556d05d678",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1af2f0cc-2975-4581-a884-65b959acf342",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a18bc886-dbad-4d34-a17c-d9e02cd2dbd8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "80315596-965f-4481-b288-7d8038462a24",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d88b04e1-64c7-468f-9686-02b31ccfece9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ebbff31e-a7a0-4eff-9f14-ea52a58a5652",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "72b482ff-2bfa-47a7-b6be-da8100d86b44",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "557d298c-ee0f-4f71-b87f-9903d820a2ff",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b292b15a-77d6-46eb-b129-3b83609b0251",
                "ordinal": 3
              }
            ],
            "lineageTag": "432a51f4-8954-40ab-a3ba-92b3c5145413"
          }
        ],
        "isHidden": true,
        "lineageTag": "7aeac91c-4536-4d13-8090-2317e04955e2",
        "partitions": [
          {
            "name": "LocalDateTable_c901ae97-cd1c-4742-b3af-a35b16d9e232",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_ManualCheckRequest_Payroll'[date_assigned])), 1, 1), Date(Year(MAX('fact_ManualCheckRequest_Payroll'[date_assigned])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_35818df4-99c6-4d25-b366-aab09cf21ebc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "69a48a52-094a-46ee-ba16-b377522f6254",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4d397833-51f7-4908-8124-05def3767fda",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e009d4c3-49e1-45f6-a143-80919893c2a9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f9e4bd3e-61ed-41b2-820f-ff132e88aea1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "829896eb-b06c-406a-96e3-fa05a9ee436f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "68453a91-b3c5-4eea-95ed-132aa7a8a5bb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "eea9d77b-e55d-4a47-8cc9-8490918b9fba",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "41e3f46a-4589-443e-b4e6-ff0deee8a6ba",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8e947030-091d-46ee-b923-8da824a72f0d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f85b934a-bdae-4a04-9500-3854af71e9be",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e5af8ec3-93eb-4948-98db-08a8a07c1b30",
                "ordinal": 3
              }
            ],
            "lineageTag": "6b163ec1-7f01-42ed-aa2f-803757d6fdc2"
          }
        ],
        "isHidden": true,
        "lineageTag": "8b98db47-2ec6-43ae-a9f4-830d834a816c",
        "partitions": [
          {
            "name": "LocalDateTable_35818df4-99c6-4d25-b366-aab09cf21ebc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_ManualCheckRequest_Payroll'[completed_first_action])), 1, 1), Date(Year(MAX('fact_ManualCheckRequest_Payroll'[completed_first_action])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}